//! Module `locales`.
//!
//! PORT gohugoio/locales + gohugoio/localescompressed subset: Translator trait + generated en/th tables
//!
//! Owner: Wave B task T26 (common-thirdparty-ports).

//! Subset of `github.com/gohugoio/locales` (+ `localescompressed`): the `Translator` API used by
//! `htime.TimeFormatter` and `lang.FormatNumber*`, with generated data for the languages in use.
//! Generate the tables from the Go module (`localescompressed/locales.autogen.go`) with a small Go
//! program; do not hand-write them. Needed now: en, th (plus the fallback rules of GetTranslator).
//!
//! Upstream: `github.com/gohugoio/locales v0.14.0` (`rules.go`: `Translator`, `PluralRule`;
//! `currency/currency.go`) and `github.com/gohugoio/localescompressed v1.0.1` (`locales.go`:
//! `GetTranslator`, `GetCurrency`; `localen.go`: the `localen` translator; `locales.autogen.go`:
//! the per-locale data and the shared `fn*` implementations). neohugo reaches the translators only
//! through `localescompressed`, so that is what is ported (its `localen` methods differ from the
//! per-locale packages in places, e.g. `MonthsAbbreviated` keeps the leading empty entry).
//!
//! Layout:
//! - `locales/tables.rs`: generated by `tools/go-oracle/nh-common/locales/gen` (every locale
//!   name, the currency map, and the `translatorFuncs["en"]`/`["th"]` literals).
//! - `locales/localen.rs`: the `localen` struct and its `Translator` methods (localen.go).
//! - `locales/fns.rs`: the shared `fn*` functions that en and th use (locales.autogen.go).
//!
//! Only en and th are ported. [`get_translator`] returns an explicit "not supported" error for
//! any other locale that Go knows, and `Ok(None)` for locales Go does not know (Go's `nil`).
//!
//! Go panics reproduced: `FmtNumber`/`FmtCurrency`/`FmtAccounting` slice
//! `s[:len(s)-int(v)-1]`, which panics for NaN (precision ≥ 3) and ±Inf (precision ≥ 4); an
//! unknown currency indexes `currencies[-1]`. The `try_fmt_*` methods return these panics as
//! errors with Go's runtime message (what text/template's `safeCall` reports); the `fmt_*`
//! methods panic like Go.

mod fns;
mod localen;
#[rustfmt::skip]
mod tables;

use std::sync::{Arc, OnceLock};

use go_value::Time;

use crate::herrors::{Error, Result};

/// Go: `locales.PluralRule`.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum PluralRule {
    Unknown = 0,
    Zero = 1,
    One = 2,
    Two = 3,
    Few = 4,
    Many = 5,
    Other = 6,
}

impl PluralRule {
    // Go: locales rules.go:PluralRule.String
    /// String returns the string value of PluralRule.
    pub fn string(self) -> &'static str {
        const PLURALS_STRING: &str = "UnknownZeroOneTwoFewManyOther";
        match self {
            PluralRule::Zero => &PLURALS_STRING[7..11],
            PluralRule::One => &PLURALS_STRING[11..14],
            PluralRule::Two => &PLURALS_STRING[14..17],
            PluralRule::Few => &PLURALS_STRING[17..20],
            PluralRule::Many => &PLURALS_STRING[20..24],
            PluralRule::Other => &PLURALS_STRING[24..],
            PluralRule::Unknown => &PLURALS_STRING[..7],
        }
    }
}

/// Go: `locales.Translator`.
///
/// Months are Go `time.Month` values (1..=12) and weekdays Go `time.Weekday` values (0 = Sunday
/// ..= 6); other values index out of range and panic, as in Go. `currency` is an ISO 4217 code,
/// resolved like `localescompressed.GetCurrency` (see [`get_currency`]).
pub trait Translator: Send + Sync {
    fn locale(&self) -> &str;
    fn plurals_cardinal(&self) -> &[PluralRule];
    fn plurals_ordinal(&self) -> &[PluralRule];
    fn plurals_range(&self) -> &[PluralRule];
    fn cardinal_plural_rule(&self, num: f64, v: u64) -> PluralRule;
    fn ordinal_plural_rule(&self, num: f64, v: u64) -> PluralRule;
    fn range_plural_rule(&self, num1: f64, v1: u64, num2: f64, v2: u64) -> PluralRule;
    /// `m` is 1..=12.
    fn month_abbreviated(&self, m: u32) -> &str;
    fn months_abbreviated(&self) -> &[&str];
    fn month_narrow(&self, m: u32) -> &str;
    fn months_narrow(&self) -> &[&str];
    fn month_wide(&self, m: u32) -> &str;
    fn months_wide(&self) -> &[&str];
    /// `d` is 0 (Sunday)..=6.
    fn weekday_abbreviated(&self, d: u32) -> &str;
    fn weekdays_abbreviated(&self) -> &[&str];
    fn weekday_narrow(&self, d: u32) -> &str;
    fn weekdays_narrow(&self) -> &[&str];
    fn weekday_short(&self, d: u32) -> &str;
    fn weekdays_short(&self) -> &[&str];
    fn weekday_wide(&self, d: u32) -> &str;
    fn weekdays_wide(&self) -> &[&str];
    fn fmt_date_short(&self, t: &Time) -> String;
    fn fmt_date_medium(&self, t: &Time) -> String;
    fn fmt_date_long(&self, t: &Time) -> String;
    fn fmt_date_full(&self, t: &Time) -> String;
    fn fmt_time_short(&self, t: &Time) -> String;
    fn fmt_time_medium(&self, t: &Time) -> String;
    fn fmt_time_long(&self, t: &Time) -> String;
    fn fmt_time_full(&self, t: &Time) -> String;
    /// Panics where Go panics; see [`Translator::try_fmt_number`].
    fn fmt_number(&self, n: f64, v: u64) -> String {
        or_panic(self.try_fmt_number(n, v))
    }
    fn fmt_percent(&self, n: f64, v: u64) -> String;
    /// Panics where Go panics; see [`Translator::try_fmt_currency`].
    fn fmt_currency(&self, n: f64, v: u64, currency: &str) -> String {
        or_panic(self.try_fmt_currency(n, v, currency))
    }
    /// Panics where Go panics; see [`Translator::try_fmt_accounting`].
    fn fmt_accounting(&self, n: f64, v: u64, currency: &str) -> String {
        or_panic(self.try_fmt_accounting(n, v, currency))
    }
    /// `FmtNumber`, with Go's runtime panic returned as an error.
    fn try_fmt_number(&self, n: f64, v: u64) -> Result<String>;
    /// `FmtCurrency`, with Go's runtime panic returned as an error.
    fn try_fmt_currency(&self, n: f64, v: u64, currency: &str) -> Result<String>;
    /// `FmtAccounting`, with Go's runtime panic returned as an error.
    fn try_fmt_accounting(&self, n: f64, v: u64, currency: &str) -> Result<String>;
}

fn or_panic(r: Result<String>) -> String {
    match r {
        Ok(s) => s,
        Err(e) => panic!("{}", e.message()),
    }
}

/// The locales this port implements.
const PORTED: &[&str] = &["en", "th"];

/// Go: `localescompressed.GetTranslator(locale)`.
///
/// `Ok(None)` if Go does not know the locale (Go returns nil; callers fall back to the default
/// content language, then "en"). A locale Go knows but this port has no tables for is an explicit
/// `neohugo-rs: ... is not supported` error. Translators are created once and shared, like Go's
/// `translators` cache.
// Go: localescompressed locales.go:GetTranslator
pub fn get_translator(locale: &str) -> Result<Option<Arc<dyn Translator>>> {
    let locale = go_unicode::strings::to_lower(&go_unicode::strings::replace_all(
        locale.as_bytes(),
        b"-",
        b"_",
    ))
    .into_owned();

    if tables::LOCALE_NAMES
        .binary_search_by(|n| n.as_bytes().cmp(&locale))
        .is_err()
    {
        return Ok(None);
    }

    static EN: OnceLock<Arc<dyn Translator>> = OnceLock::new();
    static TH: OnceLock<Arc<dyn Translator>> = OnceLock::new();
    match &locale[..] {
        b"en" => Ok(Some(EN.get_or_init(|| Arc::new(tables::new_en())).clone())),
        b"th" => Ok(Some(TH.get_or_init(|| Arc::new(tables::new_th())).clone())),
        _ => Err(Error::new(format!(
            "neohugo-rs: locale {:?} is not supported (only {} are ported)",
            String::from_utf8_lossy(&locale),
            PORTED.join(", ")
        ))),
    }
}

/// Go: `localescompressed.GetCurrency(code)`: the `currency.Type` for the given ISO 4217 code
/// (case-insensitive), or -1 if not found.
// Go: localescompressed locales.go:GetCurrency
pub fn get_currency(code: &str) -> i64 {
    let code = go_unicode::strings::to_upper(code.as_bytes()).into_owned();
    match tables::CURRENCIES.binary_search_by(|(c, _)| c.as_bytes().cmp(&code)) {
        Ok(i) => tables::CURRENCIES[i].1,
        Err(_) => -1,
    }
}

// ---------------------------------------------------------------------------
// GO PORTING CHECKLIST (third-party; written by T26, not generated — the coverage run did not
// instrument third-party modules). `OK` = ported. Items without a prefix are not called by
// neohugo (or only through locales other than en/th, which return the explicit
// "neohugo-rs: locale ... is not supported" error from GetTranslator).
// Source: github.com/gohugoio/localescompressed@v1.0.1/locales.go
// OK L14-18: mu, translatorFuncs, translators (statics per ported locale)
// OK L22-44: GetTranslator(locale string) locales.Translator
// OK L48-54: GetCurrency(code string) currency.Type
// Source: localescompressed/localen.go — see locales/localen.rs (every method OK)
// Source: localescompressed/locales.autogen.go — data: locales/tables.rs (generated, en and th);
//   functions: locales/fns.rs (the 36 fn* functions en and th use, each OK); the other ~760
//   locales and their functions are not ported.
// Source: localescompressed/currencies.autogen.go
// OK L6-310: currencies (locales/tables.rs CURRENCIES)
// Source: github.com/gohugoio/locales@v0.14.0/rules.go
//   types: PluralRule, Translator
// OK L14-23: PluralRule constants
// OK L158-179: (p PluralRule) String() string
//    L227-250: W(n float64, v uint64) (w int64) — used only by plural rules of unported locales
//    L252-267: F(n float64, v uint64) (f int64) — used only by plural rules of unported locales
//    L269-293: T(n float64, v uint64) (t int64) — used only by plural rules of unported locales
// Source: locales/currency/currency.go
// OK L4-311: Type and its constants (as the i64 values of CURRENCIES)
// Source: locales/en/en.go, locales/th/th.go — not used by neohugo (localescompressed carries
//   its own copies of their data and functions)
// ---------------------------------------------------------------------------
