//! Module `object`.
//!
//! NEW: go_methods! macro, argument helpers, NamedTypeRegistry (replaces reflect method lookup)
//!
//! Owner: Wave B task T01 (common-values).

//!
//! Go templates reach Hugo objects through reflection (`reflect.Value.MethodByName`, struct fields,
//! map keys). The Rust port replaces that with explicit method tables:
//!
//! * Host types that Go passes as pointers/structs (Page, Site, Resource, Pager, Scratch, Language,
//!   OutputFormat, namespaces, hook contexts, ...) implement [`go_value::Object`]. Their exported
//!   method set is declared once with [`go_methods!`](crate::go_methods) and wired into the `Object`
//!   impl with [`object_basics!`](crate::object_basics).
//! * Methods declared on *named slice/map types* that are represented as `Value::List` /
//!   `Value::Map` (e.g. `page.Pages.Reverse`, `resource.Resources.Get`, `maps.Params.IsZero`,
//!   `page.Taxonomy.Alphabetical`) are registered in a [`NamedTypeRegistry`] keyed by the Go type
//!   string stored in [`go_value::SliceType::Named`] / [`go_value::MapType::Named`]. The template
//!   exec helper (nh-tplimpl `template_funcs`) consults it (Go: `hreflect.GetMethodByName`).
//! * Go interface assertions on host values (`compare.Eqer`, `types.Zeroer`, `fmt.Stringer`,
//!   `resource.Resource`, ...) become either an `Object` hook (`is_zero`, `go_string`, ...) or a
//!   `has_method("Eq")` + `call_method` pair: this mirrors Go, where the interface check *is* a
//!   method-set check.
//!
//! Method arguments arrive exactly as the template engine evaluated them (Go `evalArg` for
//! `any`/`...any` parameters: ideal constants become `int`/`float64`). Methods with typed Go
//! parameters convert with the [`args`] helpers (which mirror Go's assignability rules closely
//! enough for successful executions; error texts need not match).

use std::collections::HashMap;

pub use go_value::{HostCtx, Object, Value};

/// Result type of template-visible methods and functions.
pub type GoResult<T> = go_value::Result<T>;

/// Declares the exported Go method set of a host type.
///
/// ```ignore
/// nh_common::go_methods!(Scratch {
///     "Get" => |s, _ctx, args| Ok(s.get(&args::string(args, 0)?)),
///     "Set" => |s, _ctx, args| { s.set(args::string(args, 0)?, args::get(args, 1)?); Ok(Value::string("")) },
/// });
/// ```
///
/// Generates `GO_METHODS`, `go_has_method(name)` and `go_call_method(&self, ctx, name, args)`.
/// Names are exact-case Go method names. Each body is a non-capturing closure
/// `fn(&Self, HostCtx, &[Value]) -> GoResult<Value>`.
#[macro_export]
macro_rules! go_methods {
    ($ty:ty { $( $name:literal => $f:expr ),+ $(,)? }) => {
        impl $ty {
            /// Exported Go method names of this type (exact case).
            pub const GO_METHODS: &'static [&'static str] = &[$($name),+];

            /// Go: `reflect.Type.MethodByName(name)` for this type.
            pub fn go_has_method(name: &str) -> bool {
                matches!(name, $($name)|+)
            }

            /// Calls the Go method `name`; `None` if the type has no such method.
            pub fn go_call_method(
                &self,
                ctx: $crate::object::HostCtx<'_>,
                name: &str,
                args: &[$crate::object::Value],
            ) -> ::core::option::Option<$crate::object::GoResult<$crate::object::Value>> {
                match name {
                    $(
                        $name => {
                            let f: fn(&Self, $crate::object::HostCtx<'_>, &[$crate::object::Value])
                                -> $crate::object::GoResult<$crate::object::Value> = $f;
                            ::core::option::Option::Some(f(self, ctx, args))
                        }
                    )+
                    _ => ::core::option::Option::None,
                }
            }
        }
    };
}

/// Expands, inside an `impl go_value::Object for T` block, to `type_name`, `has_method`,
/// `call_method` and `as_any`, delegating to the table generated by [`go_methods!`].
///
/// ```ignore
/// impl Object for Scratch {
///     nh_common::object_basics!("*maps.Scratch");
/// }
/// ```
#[macro_export]
macro_rules! object_basics {
    ($go_type:expr) => {
        fn type_name(&self) -> ::std::borrow::Cow<'_, str> {
            ::std::borrow::Cow::Borrowed($go_type)
        }
        fn has_method(&self, name: &str) -> bool {
            Self::go_has_method(name)
        }
        fn call_method(
            &self,
            ctx: $crate::object::HostCtx<'_>,
            name: &str,
            args: &[$crate::object::Value],
        ) -> ::core::option::Option<$crate::object::GoResult<$crate::object::Value>> {
            self.go_call_method(ctx, name, args)
        }
        fn as_any(&self) -> &dyn ::std::any::Any {
            self
        }
    };
}

/// Argument helpers for method/function bodies (Go `evalArg` + the conversions Hugo's own
/// functions do with `cast`).
pub mod args {
    use super::*;
    use go_value::GoString;

    /// Errors unless exactly `n` arguments were passed (Go: `wrong number of args for %s: want %d got %d`).
    pub fn exactly(args: &[Value], n: usize, name: &str) -> GoResult<()> {
        if args.len() != n {
            return Err(go_value::Error::new(format!(
                "wrong number of args for {name}: want {n} got {}",
                args.len()
            )));
        }
        Ok(())
    }

    /// The i-th argument (cloned); error if missing.
    pub fn get(args: &[Value], i: usize) -> GoResult<Value> {
        args.get(i).cloned().ok_or_else(|| go_value::Error::new(format!("missing argument {i}")))
    }

    /// A Go `string` parameter: accepts `string` and (like Hugo's cast-based helpers) the
    /// html/template string types. Go: evalArg for a `string` param.
    pub fn string(args: &[Value], i: usize) -> GoResult<GoString> {
        match args.get(i) {
            Some(Value::String(s)) | Some(Value::Safe(_, s)) => Ok(s.clone()),
            Some(v) => Err(go_value::Error::new(format!(
                "wrong type for value; expected string; got {}",
                v.go_type_name()
            ))),
            None => Err(go_value::Error::new(format!("missing argument {i}"))),
        }
    }

    /// A Go `int` parameter (ideal integer constants and Go int kinds).
    pub fn int(args: &[Value], i: usize) -> GoResult<i64> {
        match args.get(i) {
            Some(Value::Int(n, _)) => Ok(*n),
            Some(Value::Uint(n, _)) => Ok(*n as i64),
            Some(v) => Err(go_value::Error::new(format!(
                "wrong type for value; expected int; got {}",
                v.go_type_name()
            ))),
            None => Err(go_value::Error::new(format!("missing argument {i}"))),
        }
    }

    /// Variadic tail `args[from..]` (Go `...any`).
    pub fn rest(args: &[Value], from: usize) -> &[Value] {
        if from >= args.len() { &[] } else { &args[from..] }
    }
}

/// A method dispatcher for a named Go type that is represented as `Value::List` or `Value::Map`.
#[derive(Clone, Copy)]
pub struct NamedMethods {
    /// Go: method-set membership (`reflect.Type.MethodByName`).
    pub has_method: fn(name: &str) -> bool,
    /// Calls method `name` on the receiver value; `None` if no such method.
    pub call: fn(ctx: HostCtx<'_>, recv: &Value, name: &str, args: &[Value]) -> Option<GoResult<Value>>,
}

/// Registry of methods declared on named slice/map Go types, keyed by the Go type string
/// (`"page.Pages"`, `"resource.Resources"`, `"maps.Params"`, `"page.Taxonomy"`, ...).
///
/// Built once per build by nh-hugolib (`tplapi::named_types::registry()`), from the
/// `register_named_types` function each owning crate exports, and handed to the template store.
#[derive(Default, Clone)]
pub struct NamedTypeRegistry {
    map: HashMap<&'static str, NamedMethods>,
}

impl NamedTypeRegistry {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn register(&mut self, go_type: &'static str, methods: NamedMethods) {
        self.map.insert(go_type, methods);
    }

    pub fn lookup(&self, go_type: &str) -> Option<&NamedMethods> {
        self.map.get(go_type)
    }

    /// Go type string of a `Value::List`/`Value::Map` receiver, if it is a named type.
    pub fn named_type_of(recv: &Value) -> Option<std::borrow::Cow<'_, str>> {
        match recv {
            Value::List(l) => match &l.ty {
                go_value::SliceType::Named(n) => Some(std::borrow::Cow::Borrowed(n)),
                _ => None,
            },
            Value::Map(m) => match &m.ty {
                go_value::MapType::Named(n) => Some(std::borrow::Cow::Borrowed(n)),
                go_value::MapType::Params => Some(std::borrow::Cow::Borrowed("maps.Params")),
                _ => None,
            },
            _ => None,
        }
    }

    /// Method lookup on a named slice/map receiver (the template engine's `GetMethod` for non-Object values).
    pub fn call(&self, ctx: HostCtx<'_>, recv: &Value, name: &str, args: &[Value]) -> Option<GoResult<Value>> {
        let tn = Self::named_type_of(recv)?;
        let m = self.lookup(&tn)?;
        if !(m.has_method)(name) {
            return None;
        }
        (m.call)(ctx, recv, name, args)
    }

    pub fn has_method(&self, recv: &Value, name: &str) -> bool {
        Self::named_type_of(recv)
            .and_then(|tn| self.lookup(&tn).copied())
            .map(|m| (m.has_method)(name))
            .unwrap_or(false)
    }
}

/// Conversion of a Rust host value into a template value.
pub trait ToValue {
    fn to_value(&self) -> Value;
}

impl ToValue for Value {
    fn to_value(&self) -> Value {
        self.clone()
    }
}

impl ToValue for str {
    fn to_value(&self) -> Value {
        Value::string(self)
    }
}

impl ToValue for String {
    fn to_value(&self) -> Value {
        Value::string(self.as_str())
    }
}

impl ToValue for bool {
    fn to_value(&self) -> Value {
        Value::Bool(*self)
    }
}

/// A Go `[]string` value from Rust strings.
pub fn string_slice<S: AsRef<str>>(items: &[S]) -> Value {
    Value::string_list(items.iter().map(|s| go_value::GoString::from(s.as_ref())))
}
