"""Extracts the test tables of the fork's html/template tests verbatim into
tools/go-oracle/gotemplate/htmlexec_tables.go (Go source, package main),
then gofmt's it. Run from anywhere:

    python3 tools/go-oracle/gotemplate/extract_tables.py
"""
import os
import re
import subprocess

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, '..', '..', '..', 'tpl', 'internal', 'go_templates', 'htmltemplate') + os.sep
OUT = os.path.join(HERE, 'htmlexec_tables.go')


def read(name):
    return open(SRC + name).read()


def balanced(s, start):
    """Returns the index just past the brace block starting at s[start] == '{'."""
    assert s[start] == '{', s[start:start + 20]
    depth = 0
    i = start
    while i < len(s):
        c = s[i]
        if c == '`':
            i = s.index('`', i + 1) + 1
            continue
        if c == '"':
            j = i + 1
            while s[j] != '"':
                j += 2 if s[j] == '\\' else 1
            i = j + 1
            continue
        if c == "'":
            j = i + 1
            while s[j] != "'":
                j += 2 if s[j] == '\\' else 1
            i = j + 1
            continue
        if s.startswith('//', i):
            i = s.index('\n', i)
            continue
        if s.startswith('/*', i):
            i = s.index('*/', i) + 2
            continue
        if c == '{':
            depth += 1
        elif c == '}':
            depth -= 1
            if depth == 0:
                return i + 1
        i += 1
    raise ValueError('unbalanced')


def literal_after(s, marker, typ_end_marker='}{'):
    """The composite literal body `{...}` that follows `marker` (a type
    whose own braces are skipped)."""
    i = s.index(marker)
    j = s.index('{', i)  # the struct type's brace (or the literal's)
    if marker.rstrip().endswith('struct {') or 'struct {' in s[i:j + 1]:
        j = balanced(s, j)  # skip the type
        assert s[j] == '{', s[j:j + 30]
    return s[j:balanced(s, j)]


out = ['//go:build gotemplate_oracle', '',
       '// Code generated by extract_tables.py from the fork\'s html/template',
       '// tests (tpl/internal/go_templates/htmltemplate/*_test.go). DO NOT EDIT.', '',
       'package main', '',
       'import (', '\t"bytes"', '\tstdhtml "html/template"', ')', '']

esc = read('escape_test.go')
exe = read('exec_test.go')
con = read('content_test.go')
mul = read('multi_test.go')

# TestEscape
body = literal_after(esc, 'tests := []struct {\n\t\tname   string\n\t\tinput  string\n\t\toutput string\n\t}')
out.append('var escapeTestsTable = []struct {\n\tname   string\n\tinput  string\n\toutput string\n}' + body + '\n')

# TestErrors
i = esc.index('func TestErrors(')
body = literal_after(esc[i:], 'tests := []struct {')
out.append('var errorsTestsTable = []struct {\n\tinput string\n\terr   string\n}' + body + '\n')

# TestEscapeText: inputs only (the expected contexts are the fork's own).
i = esc.index('func TestEscapeText(')
body = literal_after(esc[i:], 'tests := []struct {')
inputs = []
k = 1
while True:
    m = re.compile(r'\{\s*(`[^`]*`|"(?:[^"\\]|\\.)*")\s*,').search(body, k)
    if not m:
        break
    inputs.append(m.group(1))
    # skip this entry
    k = balanced(body, m.start())
out.append('var escapeTextInputs = []string{\n' + ''.join('\t' + x + ',\n' for x in inputs) + '}\n')

# TestEnsurePipelineContains
i = esc.index('func TestEnsurePipelineContains(')
body = literal_after(esc[i:], 'tests := []struct {')
out.append('var ensurePipelineTable = []struct {\n\tinput, output string\n\tids           []string\n}' + body + '\n')

# TestEscapeMap, TestEscapeSet tables are small and written by hand.

# TestTypedContent
i = con.index('func TestTypedContent(')
dbody = literal_after(con[i:], 'data := []any')
out.append('var typedContentData = []any' + dbody.replace('htmltemplate.', 'stdhtml.') + '\n')
body = literal_after(con[i:], 'tests := []struct {')
out.append('var typedContentTable = []struct {\n\tinput string\n\twant  []string\n}' + body + '\n')

# exec_test.go execTests and cmpTests
body = literal_after(exe, 'var execTests = []execTest')
out.append('var execTestsTable = []execTest' + body + '\n')
body = literal_after(exe, 'var cmpTests = []cmpTest')
out.append('var cmpTestsTable = []cmpTest' + body + '\n')

# multi_test.go multiExecTests
body = literal_after(mul, 'var multiExecTests = []execTest')
out.append('var multiExecTestsTable = []execTest' + body + '\n')

open(OUT, 'w').write('\n'.join(out))
subprocess.run(['gofmt', '-w', OUT], check=True)
print('wrote', OUT, len(inputs), 'escapeText inputs')
