//go:build gotemplate_oracle

// Code generated by extract_tables.py from the fork's html/template
// tests (tpl/internal/go_templates/htmltemplate/*_test.go). DO NOT EDIT.

package main

import (
	"bytes"
	stdhtml "html/template"
)

var escapeTestsTable = []struct {
	name   string
	input  string
	output string
}{
	{
		"if",
		"{{if .T}}Hello{{end}}, {{.C}}!",
		"Hello, &lt;Cincinnati&gt;!",
	},
	{
		"else",
		"{{if .F}}{{.H}}{{else}}{{.G}}{{end}}!",
		"&lt;Goodbye&gt;!",
	},
	{
		"overescaping1",
		"Hello, {{.C | html}}!",
		"Hello, &lt;Cincinnati&gt;!",
	},
	{
		"overescaping2",
		"Hello, {{html .C}}!",
		"Hello, &lt;Cincinnati&gt;!",
	},
	{
		"overescaping3",
		"{{with .C}}{{$msg := .}}Hello, {{$msg}}!{{end}}",
		"Hello, &lt;Cincinnati&gt;!",
	},
	{
		"assignment",
		"{{if $x := .H}}{{$x}}{{end}}",
		"&lt;Hello&gt;",
	},
	{
		"withBody",
		"{{with .H}}{{.}}{{end}}",
		"&lt;Hello&gt;",
	},
	{
		"withElse",
		"{{with .E}}{{.}}{{else}}{{.H}}{{end}}",
		"&lt;Hello&gt;",
	},
	{
		"rangeBody",
		"{{range .A}}{{.}}{{end}}",
		"&lt;a&gt;&lt;b&gt;",
	},
	{
		"rangeElse",
		"{{range .E}}{{.}}{{else}}{{.H}}{{end}}",
		"&lt;Hello&gt;",
	},
	{
		"nonStringValue",
		"{{.T}}",
		"true",
	},
	{
		"untypedNilValue",
		"{{.U}}",
		"",
	},
	{
		"typedNilValue",
		"{{.Z}}",
		"&lt;nil&gt;",
	},
	{
		"constant",
		`<a href="/search?q={{"'a<b'"}}">`,
		`<a href="/search?q=%27a%3cb%27">`,
	},
	{
		"multipleAttrs",
		"<a b=1 c={{.H}}>",
		"<a b=1 c=&lt;Hello&gt;>",
	},
	{
		"urlStartRel",
		`<a href='{{"/foo/bar?a=b&c=d"}}'>`,
		`<a href='/foo/bar?a=b&amp;c=d'>`,
	},
	{
		"urlStartAbsOk",
		`<a href='{{"http://example.com/foo/bar?a=b&c=d"}}'>`,
		`<a href='http://example.com/foo/bar?a=b&amp;c=d'>`,
	},
	{
		"protocolRelativeURLStart",
		`<a href='{{"//example.com:8000/foo/bar?a=b&c=d"}}'>`,
		`<a href='//example.com:8000/foo/bar?a=b&amp;c=d'>`,
	},
	{
		"pathRelativeURLStart",
		`<a href="{{"/javascript:80/foo/bar"}}">`,
		`<a href="/javascript:80/foo/bar">`,
	},
	{
		"dangerousURLStart",
		`<a href='{{"javascript:alert(%22pwned%22)"}}'>`,
		`<a href='#ZgotmplZ'>`,
	},
	{
		"dangerousURLStart2",
		`<a href='  {{"javascript:alert(%22pwned%22)"}}'>`,
		`<a href='  #ZgotmplZ'>`,
	},
	{
		"nonHierURL",
		`<a href={{"mailto:Muhammed \"The Greatest\" Ali <m.ali@example.com>"}}>`,
		`<a href=mailto:Muhammed%20%22The%20Greatest%22%20Ali%20%3cm.ali@example.com%3e>`,
	},
	{
		"urlPath",
		`<a href='http://{{"javascript:80"}}/foo'>`,
		`<a href='http://javascript:80/foo'>`,
	},
	{
		"urlQuery",
		`<a href='/search?q={{.H}}'>`,
		`<a href='/search?q=%3cHello%3e'>`,
	},
	{
		"urlFragment",
		`<a href='/faq#{{.H}}'>`,
		`<a href='/faq#%3cHello%3e'>`,
	},
	{
		"urlBranch",
		`<a href="{{if .F}}/foo?a=b{{else}}/bar{{end}}">`,
		`<a href="/bar">`,
	},
	{
		"urlBranchConflictMoot",
		`<a href="{{if .T}}/foo?a={{else}}/bar#{{end}}{{.C}}">`,
		`<a href="/foo?a=%3cCincinnati%3e">`,
	},
	{
		"jsStrValue",
		"<button onclick='alert({{.H}})'>",
		`<button onclick='alert(&#34;\u003cHello\u003e&#34;)'>`,
	},
	{
		"jsNumericValue",
		"<button onclick='alert({{.N}})'>",
		`<button onclick='alert( 42 )'>`,
	},
	{
		"jsBoolValue",
		"<button onclick='alert({{.T}})'>",
		`<button onclick='alert( true )'>`,
	},
	{
		"jsNilValueTyped",
		"<button onclick='alert(typeof{{.Z}})'>",
		`<button onclick='alert(typeof null )'>`,
	},
	{
		"jsNilValueUntyped",
		"<button onclick='alert(typeof{{.U}})'>",
		`<button onclick='alert(typeof null )'>`,
	},
	{
		"jsObjValue",
		"<button onclick='alert({{.A}})'>",
		`<button onclick='alert([&#34;\u003ca\u003e&#34;,&#34;\u003cb\u003e&#34;])'>`,
	},
	{
		"jsObjValueScript",
		"<script>alert({{.A}})</script>",
		`<script>alert(["\u003ca\u003e","\u003cb\u003e"])</script>`,
	},
	{
		"jsObjValueNotOverEscaped",
		"<button onclick='alert({{.A | html}})'>",
		`<button onclick='alert([&#34;\u003ca\u003e&#34;,&#34;\u003cb\u003e&#34;])'>`,
	},
	{
		"jsStr",
		"<button onclick='alert(&quot;{{.H}}&quot;)'>",
		`<button onclick='alert(&quot;\u003cHello\u003e&quot;)'>`,
	},
	{
		"badMarshaler",
		`<button onclick='alert(1/{{.B}}in numbers)'>`,
		`<button onclick='alert(1/ /* json: error calling MarshalJSON for type *template.badMarshaler: invalid character &#39;f&#39; looking for beginning of object key string */null in numbers)'>`,
	},
	{
		"jsMarshaler",
		`<button onclick='alert({{.M}})'>`,
		`<button onclick='alert({&#34;\u003cfoo\u003e&#34;:&#34;O&#39;Reilly&#34;})'>`,
	},
	{
		"jsStrNotUnderEscaped",
		"<button onclick='alert({{.C | urlquery}})'>",
		// URL escaped, then quoted for JS.
		`<button onclick='alert(&#34;%3CCincinnati%3E&#34;)'>`,
	},
	{
		"jsRe",
		`<button onclick='alert(/{{"foo+bar"}}/.test(""))'>`,
		`<button onclick='alert(/foo\u002bbar/.test(""))'>`,
	},
	{
		"jsReBlank",
		`<script>alert(/{{""}}/.test(""));</script>`,
		`<script>alert(/(?:)/.test(""));</script>`,
	},
	{
		"jsReAmbigOk",
		`<script>{{if true}}var x = 1{{end}}</script>`,
		// The {if} ends in an ambiguous jsCtx but there is
		// no slash following so we shouldn't care.
		`<script>var x = 1</script>`,
	},
	{
		"styleBidiKeywordPassed",
		`<p style="dir: {{"ltr"}}">`,
		`<p style="dir: ltr">`,
	},
	{
		"styleBidiPropNamePassed",
		`<p style="border-{{"left"}}: 0; border-{{"right"}}: 1in">`,
		`<p style="border-left: 0; border-right: 1in">`,
	},
	{
		"styleExpressionBlocked",
		`<p style="width: {{"expression(alert(1337))"}}">`,
		`<p style="width: ZgotmplZ">`,
	},
	{
		"styleTagSelectorPassed",
		`<style>{{"p"}} { color: pink }</style>`,
		`<style>p { color: pink }</style>`,
	},
	{
		"styleIDPassed",
		`<style>p{{"#my-ID"}} { font: Arial }</style>`,
		`<style>p#my-ID { font: Arial }</style>`,
	},
	{
		"styleClassPassed",
		`<style>p{{".my_class"}} { font: Arial }</style>`,
		`<style>p.my_class { font: Arial }</style>`,
	},
	{
		"styleQuantityPassed",
		`<a style="left: {{"2em"}}; top: {{0}}">`,
		`<a style="left: 2em; top: 0">`,
	},
	{
		"stylePctPassed",
		`<table style=width:{{"100%"}}>`,
		`<table style=width:100%>`,
	},
	{
		"styleColorPassed",
		`<p style="color: {{"#8ff"}}; background: {{"#000"}}">`,
		`<p style="color: #8ff; background: #000">`,
	},
	{
		"styleObfuscatedExpressionBlocked",
		`<p style="width: {{"  e\\78preS\x00Sio/**/n(alert(1337))"}}">`,
		`<p style="width: ZgotmplZ">`,
	},
	{
		"styleMozBindingBlocked",
		`<p style="{{"-moz-binding(alert(1337))"}}: ...">`,
		`<p style="ZgotmplZ: ...">`,
	},
	{
		"styleObfuscatedMozBindingBlocked",
		`<p style="{{"  -mo\\7a-B\x00I/**/nding(alert(1337))"}}: ...">`,
		`<p style="ZgotmplZ: ...">`,
	},
	{
		"styleFontNameString",
		`<p style='font-family: "{{"Times New Roman"}}"'>`,
		`<p style='font-family: "Times New Roman"'>`,
	},
	{
		"styleFontNameString",
		`<p style='font-family: "{{"Times New Roman"}}", "{{"sans-serif"}}"'>`,
		`<p style='font-family: "Times New Roman", "sans-serif"'>`,
	},
	{
		"styleFontNameUnquoted",
		`<p style='font-family: {{"Times New Roman"}}'>`,
		`<p style='font-family: Times New Roman'>`,
	},
	{
		"styleURLQueryEncoded",
		`<p style="background: url(/img?name={{"O'Reilly Animal(1)<2>.png"}})">`,
		`<p style="background: url(/img?name=O%27Reilly%20Animal%281%29%3c2%3e.png)">`,
	},
	{
		"styleQuotedURLQueryEncoded",
		`<p style="background: url('/img?name={{"O'Reilly Animal(1)<2>.png"}}')">`,
		`<p style="background: url('/img?name=O%27Reilly%20Animal%281%29%3c2%3e.png')">`,
	},
	{
		"styleStrQueryEncoded",
		`<p style="background: '/img?name={{"O'Reilly Animal(1)<2>.png"}}'">`,
		`<p style="background: '/img?name=O%27Reilly%20Animal%281%29%3c2%3e.png'">`,
	},
	{
		"styleURLBadProtocolBlocked",
		`<a style="background: url('{{"javascript:alert(1337)"}}')">`,
		`<a style="background: url('#ZgotmplZ')">`,
	},
	{
		"styleStrBadProtocolBlocked",
		`<a style="background: '{{"vbscript:alert(1337)"}}'">`,
		`<a style="background: '#ZgotmplZ'">`,
	},
	{
		"styleStrEncodedProtocolEncoded",
		`<a style="background: '{{"javascript\\3a alert(1337)"}}'">`,
		// The CSS string 'javascript\\3a alert(1337)' does not contain a colon.
		`<a style="background: 'javascript\\3a alert\28 1337\29 '">`,
	},
	{
		"styleURLGoodProtocolPassed",
		`<a style="background: url('{{"http://oreilly.com/O'Reilly Animals(1)<2>;{}.html"}}')">`,
		`<a style="background: url('http://oreilly.com/O%27Reilly%20Animals%281%29%3c2%3e;%7b%7d.html')">`,
	},
	{
		"styleStrGoodProtocolPassed",
		`<a style="background: '{{"http://oreilly.com/O'Reilly Animals(1)<2>;{}.html"}}'">`,
		`<a style="background: 'http\3a\2f\2foreilly.com\2fO\27Reilly Animals\28 1\29\3c 2\3e\3b\7b\7d.html'">`,
	},
	{
		"styleURLEncodedForHTMLInAttr",
		`<a style="background: url('{{"/search?img=foo&size=icon"}}')">`,
		`<a style="background: url('/search?img=foo&amp;size=icon')">`,
	},
	{
		"styleURLNotEncodedForHTMLInCdata",
		`<style>body { background: url('{{"/search?img=foo&size=icon"}}') }</style>`,
		`<style>body { background: url('/search?img=foo&size=icon') }</style>`,
	},
	{
		"styleURLMixedCase",
		`<p style="background: URL(#{{.H}})">`,
		`<p style="background: URL(#%3cHello%3e)">`,
	},
	{
		"stylePropertyPairPassed",
		`<a style='{{"color: red"}}'>`,
		`<a style='color: red'>`,
	},
	{
		"styleStrSpecialsEncoded",
		`<a style="font-family: '{{"/**/'\";:// \\"}}', &quot;{{"/**/'\";:// \\"}}&quot;">`,
		`<a style="font-family: '\2f**\2f\27\22\3b\3a\2f\2f  \\', &quot;\2f**\2f\27\22\3b\3a\2f\2f  \\&quot;">`,
	},
	{
		"styleURLSpecialsEncoded",
		`<a style="border-image: url({{"/**/'\";:// \\"}}), url(&quot;{{"/**/'\";:// \\"}}&quot;), url('{{"/**/'\";:// \\"}}'), 'http://www.example.com/?q={{"/**/'\";:// \\"}}''">`,
		`<a style="border-image: url(/**/%27%22;://%20%5c), url(&quot;/**/%27%22;://%20%5c&quot;), url('/**/%27%22;://%20%5c'), 'http://www.example.com/?q=%2f%2a%2a%2f%27%22%3b%3a%2f%2f%20%5c''">`,
	},
	{
		"HTML comment",
		"<b>Hello, <!-- name of world -->{{.C}}</b>",
		"<b>Hello, &lt;Cincinnati&gt;</b>",
	},
	{
		"HTML comment not first < in text node.",
		"<<!-- -->!--",
		"&lt;!--",
	},
	{
		"HTML normalization 1",
		"a < b",
		"a &lt; b",
	},
	{
		"HTML normalization 2",
		"a << b",
		"a &lt;&lt; b",
	},
	{
		"HTML normalization 3",
		"a<<!-- --><!-- -->b",
		"a&lt;b",
	},
	{
		"HTML doctype not normalized",
		"<!DOCTYPE html>Hello, World!",
		"<!DOCTYPE html>Hello, World!",
	},
	{
		"HTML doctype not case-insensitive",
		"<!doCtYPE htMl>Hello, World!",
		"<!doCtYPE htMl>Hello, World!",
	},
	{
		"No doctype injection",
		`<!{{"DOCTYPE"}}`,
		"&lt;!DOCTYPE",
	},
	{
		"Split HTML comment",
		"<b>Hello, <!-- name of {{if .T}}city -->{{.C}}{{else}}world -->{{.W}}{{end}}</b>",
		"<b>Hello, &lt;Cincinnati&gt;</b>",
	},
	{
		"JS line comment",
		"<script>for (;;) { if (c()) break// foo not a label\n" +
			"foo({{.T}});}</script>",
		"<script>for (;;) { if (c()) break\n" +
			"foo( true );}</script>",
	},
	{
		"JS multiline block comment",
		"<script>for (;;) { if (c()) break/* foo not a label\n" +
			" */foo({{.T}});}</script>",
		// Newline separates break from call. If newline
		// removed, then break will consume label leaving
		// code invalid.
		"<script>for (;;) { if (c()) break\n" +
			"foo( true );}</script>",
	},
	{
		"JS single-line block comment",
		"<script>for (;;) {\n" +
			"if (c()) break/* foo a label */foo;" +
			"x({{.T}});}</script>",
		// Newline separates break from call. If newline
		// removed, then break will consume label leaving
		// code invalid.
		"<script>for (;;) {\n" +
			"if (c()) break foo;" +
			"x( true );}</script>",
	},
	{
		"JS block comment flush with mathematical division",
		"<script>var a/*b*//c\nd</script>",
		"<script>var a /c\nd</script>",
	},
	{
		"JS mixed comments",
		"<script>var a/*b*///c\nd</script>",
		"<script>var a \nd</script>",
	},
	{
		"JS HTML-like comments",
		"<script>before <!-- beep\nbetween\nbefore-->boop\n</script>",
		"<script>before \nbetween\nbefore\n</script>",
	},
	{
		"JS hashbang comment",
		"<script>#! beep\n</script>",
		"<script>\n</script>",
	},
	{
		"Special tags in <script> string literals",
		`<script>var a = "asd < 123 <!-- 456 < fgh <script jkl < 789 </script"</script>`,
		`<script>var a = "asd < 123 \x3C!-- 456 < fgh \x3Cscript jkl < 789 \x3C/script"</script>`,
	},
	{
		"Special tags in <script> string literals (mixed case)",
		`<script>var a = "<!-- <ScripT </ScripT"</script>`,
		`<script>var a = "\x3C!-- \x3CScripT \x3C/ScripT"</script>`,
	},
	{
		"Special tags in <script> regex literals (mixed case)",
		`<script>var a = /<!-- <ScripT </ScripT/</script>`,
		`<script>var a = /\x3C!-- \x3CScripT \x3C/ScripT/</script>`,
	},
	{
		"CSS comments",
		"<style>p// paragraph\n" +
			`{border: 1px/* color */{{"#00f"}}}</style>`,
		"<style>p\n" +
			"{border: 1px #00f}</style>",
	},
	{
		"JS attr block comment",
		`<a onclick="f(&quot;&quot;); /* alert({{.H}}) */">`,
		// Attribute comment tests should pass if the comments
		// are successfully elided.
		`<a onclick="f(&quot;&quot;); /* alert() */">`,
	},
	{
		"JS attr line comment",
		`<a onclick="// alert({{.G}})">`,
		`<a onclick="// alert()">`,
	},
	{
		"CSS attr block comment",
		`<a style="/* color: {{.H}} */">`,
		`<a style="/* color:  */">`,
	},
	{
		"CSS attr line comment",
		`<a style="// color: {{.G}}">`,
		`<a style="// color: ">`,
	},
	{
		"HTML substitution commented out",
		"<p><!-- {{.H}} --></p>",
		"<p></p>",
	},
	{
		"Comment ends flush with start",
		"<!--{{.}}--><script>/*{{.}}*///{{.}}\n</script><style>/*{{.}}*///{{.}}\n</style><a onclick='/*{{.}}*///{{.}}' style='/*{{.}}*///{{.}}'>",
		"<script> \n</script><style> \n</style><a onclick='/**///' style='/**///'>",
	},
	{
		"typed HTML in text",
		`{{.W}}`,
		`&iexcl;<b class="foo">Hello</b>, <textarea>O'World</textarea>!`,
	},
	{
		"typed HTML in attribute",
		`<div title="{{.W}}">`,
		`<div title="&iexcl;Hello, O&#39;World!">`,
	},
	{
		"typed HTML in script",
		`<button onclick="alert({{.W}})">`,
		`<button onclick="alert(&#34;\u0026iexcl;\u003cb class=\&#34;foo\&#34;\u003eHello\u003c/b\u003e, \u003ctextarea\u003eO&#39;World\u003c/textarea\u003e!&#34;)">`,
	},
	{
		"typed HTML in RCDATA",
		`<textarea>{{.W}}</textarea>`,
		`<textarea>&iexcl;&lt;b class=&#34;foo&#34;&gt;Hello&lt;/b&gt;, &lt;textarea&gt;O&#39;World&lt;/textarea&gt;!</textarea>`,
	},
	{
		"range in textarea",
		"<textarea>{{range .A}}{{.}}{{end}}</textarea>",
		"<textarea>&lt;a&gt;&lt;b&gt;</textarea>",
	},
	{
		"No tag injection",
		`{{"10$"}}<{{"script src,evil.org/pwnd.js"}}...`,
		`10$&lt;script src,evil.org/pwnd.js...`,
	},
	{
		"No comment injection",
		`<{{"!--"}}`,
		`&lt;!--`,
	},
	{
		"No RCDATA end tag injection",
		`<textarea><{{"/textarea "}}...</textarea>`,
		`<textarea>&lt;/textarea ...</textarea>`,
	},
	{
		"optional attrs",
		`<img class="{{"iconClass"}}"` +
			`{{if .T}} id="{{"<iconId>"}}"{{end}}` +
			// Double quotes inside if/else.
			` src=` +
			`{{if .T}}"?{{"<iconPath>"}}"` +
			`{{else}}"images/cleardot.gif"{{end}}` +
			// Missing space before title, but it is not a
			// part of the src attribute.
			`{{if .T}}title="{{"<title>"}}"{{end}}` +
			// Quotes outside if/else.
			` alt="` +
			`{{if .T}}{{"<alt>"}}` +
			`{{else}}{{if .F}}{{"<title>"}}{{end}}` +
			`{{end}}"` +
			`>`,
		`<img class="iconClass" id="&lt;iconId&gt;" src="?%3ciconPath%3e"title="&lt;title&gt;" alt="&lt;alt&gt;">`,
	},
	{
		"conditional valueless attr name",
		`<input{{if .T}} checked{{end}} name=n>`,
		`<input checked name=n>`,
	},
	{
		"conditional dynamic valueless attr name 1",
		`<input{{if .T}} {{"checked"}}{{end}} name=n>`,
		`<input checked name=n>`,
	},
	{
		"conditional dynamic valueless attr name 2",
		`<input {{if .T}}{{"checked"}} {{end}}name=n>`,
		`<input checked name=n>`,
	},
	{
		"dynamic attribute name",
		`<img on{{"load"}}="alert({{"loaded"}})">`,
		// Treated as JS since quotes are inserted.
		`<img onload="alert(&#34;loaded&#34;)">`,
	},
	{
		"bad dynamic attribute name 1",
		// Allow checked, selected, disabled, but not JS or
		// CSS attributes.
		`<input {{"onchange"}}="{{"doEvil()"}}">`,
		`<input ZgotmplZ="doEvil()">`,
	},
	{
		"bad dynamic attribute name 2",
		`<div {{"sTyle"}}="{{"color: expression(alert(1337))"}}">`,
		`<div ZgotmplZ="color: expression(alert(1337))">`,
	},
	{
		"bad dynamic attribute name 3",
		// Allow title or alt, but not a URL.
		`<img {{"src"}}="{{"javascript:doEvil()"}}">`,
		`<img ZgotmplZ="javascript:doEvil()">`,
	},
	{
		"bad dynamic attribute name 4",
		// Structure preservation requires values to associate
		// with a consistent attribute.
		`<input checked {{""}}="Whose value am I?">`,
		`<input checked ZgotmplZ="Whose value am I?">`,
	},
	{
		"dynamic element name",
		`<h{{3}}><table><t{{"head"}}>...</h{{3}}>`,
		`<h3><table><thead>...</h3>`,
	},
	{
		"bad dynamic element name",
		// Dynamic element names are typically used to switch
		// between (thead, tfoot, tbody), (ul, ol), (th, td),
		// and other replaceable sets.
		// We do not currently easily support (ul, ol).
		// If we do change to support that, this test should
		// catch failures to filter out special tag names which
		// would violate the structure preservation property --
		// if any special tag name could be substituted, then
		// the content could be raw text/RCDATA for some inputs
		// and regular HTML content for others.
		`<{{"script"}}>{{"doEvil()"}}</{{"script"}}>`,
		`&lt;script>doEvil()&lt;/script>`,
	},
	{
		"srcset bad URL in second position",
		`<img srcset="{{"/not-an-image#,javascript:alert(1)"}}">`,
		// The second URL is also filtered.
		`<img srcset="/not-an-image#,#ZgotmplZ">`,
	},
	{
		"srcset buffer growth",
		`<img srcset={{",,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,"}}>`,
		`<img srcset=,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,>`,
	},
	{
		"unquoted empty attribute value (plaintext)",
		"<p name={{.U}}>",
		"<p name=ZgotmplZ>",
	},
	{
		"unquoted empty attribute value (url)",
		"<p href={{.U}}>",
		"<p href=ZgotmplZ>",
	},
	{
		"quoted empty attribute value",
		"<p name=\"{{.U}}\">",
		"<p name=\"\">",
	},
	{
		"JS template lit special characters",
		"<script>var a = `{{.I}}`</script>",
		"<script>var a = `\\u0024\\u007b asd \\u0060\\u0060 \\u007d`</script>",
	},
	{
		"JS template lit special characters, nested lit",
		"<script>var a = `${ `{{.I}}` }`</script>",
		"<script>var a = `${ `\\u0024\\u007b asd \\u0060\\u0060 \\u007d` }`</script>",
	},
	{
		"JS template lit, nested JS",
		"<script>var a = `${ var a = \"{{\"a \\\" d\"}}\" }`</script>",
		"<script>var a = `${ var a = \"a \\u0022 d\" }`</script>",
	},
}

var errorsTestsTable = []struct {
	input string
	err   string
}{
	// Non-error cases.
	{
		"{{if .Cond}}<a>{{else}}<b>{{end}}",
		"",
	},
	{
		"{{if .Cond}}<a>{{end}}",
		"",
	},
	{
		"{{if .Cond}}{{else}}<b>{{end}}",
		"",
	},
	{
		"{{with .Cond}}<div>{{end}}",
		"",
	},
	{
		"{{range .Items}}<a>{{end}}",
		"",
	},
	{
		"<a href='/foo?{{range .Items}}&{{.K}}={{.V}}{{end}}'>",
		"",
	},
	{
		"{{range .Items}}<a{{if .X}}{{end}}>{{end}}",
		"",
	},
	{
		"{{range .Items}}<a{{if .X}}{{end}}>{{continue}}{{end}}",
		"",
	},
	{
		"{{range .Items}}<a{{if .X}}{{end}}>{{break}}{{end}}",
		"",
	},
	{
		"{{range .Items}}<a{{if .X}}{{end}}>{{if .X}}{{break}}{{end}}{{end}}",
		"",
	},
	{
		"<script>var a = `${a+b}`</script>`",
		"",
	},
	{
		"<script>var tmpl = `asd`;</script>",
		``,
	},
	{
		"<script>var tmpl = `${1}`;</script>",
		``,
	},
	{
		"<script>var tmpl = `${return ``}`;</script>",
		``,
	},
	{
		"<script>var tmpl = `${return {{.}} }`;</script>",
		``,
	},
	{
		"<script>var tmpl = `${ let a = {1:1} {{.}} }`;</script>",
		``,
	},
	{
		"<script>var tmpl = `asd ${return \"{\"}`;</script>",
		``,
	},

	// Error cases.
	{
		"{{if .Cond}}<a{{end}}",
		"z:1:5: {{if}} branches",
	},
	{
		"{{if .Cond}}\n{{else}}\n<a{{end}}",
		"z:1:5: {{if}} branches",
	},
	{
		// Missing quote in the else branch.
		`{{if .Cond}}<a href="foo">{{else}}<a href="bar>{{end}}`,
		"z:1:5: {{if}} branches",
	},
	{
		// Different kind of attribute: href implies a URL.
		"<a {{if .Cond}}href='{{else}}title='{{end}}{{.X}}'>",
		"z:1:8: {{if}} branches",
	},
	{
		"\n{{with .X}}<a{{end}}",
		"z:2:7: {{with}} branches",
	},
	{
		"\n{{with .X}}<a>{{else}}<a{{end}}",
		"z:2:7: {{with}} branches",
	},
	{
		"{{range .Items}}<a{{end}}",
		`z:1: on range loop re-entry: "<" in attribute name: "<a"`,
	},
	{
		"\n{{range .Items}} x='<a{{end}}",
		"z:2:8: on range loop re-entry: {{range}} branches",
	},
	{
		"{{range .Items}}<a{{if .X}}{{break}}{{end}}>{{end}}",
		"z:1:29: at range loop break: {{range}} branches end in different contexts",
	},
	{
		"{{range .Items}}<a{{if .X}}{{continue}}{{end}}>{{end}}",
		"z:1:29: at range loop continue: {{range}} branches end in different contexts",
	},
	{
		"{{range .Items}}{{if .X}}{{break}}{{end}}<a{{if .Y}}{{continue}}{{end}}>{{if .Z}}{{continue}}{{end}}{{end}}",
		"z:1:54: at range loop continue: {{range}} branches end in different contexts",
	},
	{
		"<a b=1 c={{.H}}",
		"z: ends in a non-text context: {stateAttr delimSpaceOrTagEnd",
	},
	{
		"<script>foo();",
		"z: ends in a non-text context: {stateJS",
	},
	{
		`<a href="{{if .F}}/foo?a={{else}}/bar/{{end}}{{.H}}">`,
		"z:1:47: {{.H}} appears in an ambiguous context within a URL",
	},
	{
		`<a onclick="alert('Hello \`,
		`unfinished escape sequence in JS string: "Hello \\"`,
	},
	{
		`<a onclick='alert("Hello\, World\`,
		`unfinished escape sequence in JS string: "Hello\\, World\\"`,
	},
	{
		`<a onclick='alert(/x+\`,
		`unfinished escape sequence in JS string: "x+\\"`,
	},
	{
		`<a onclick="/foo[\]/`,
		`unfinished JS regexp charset: "foo[\\]/"`,
	},
	{
		// It is ambiguous whether 1.5 should be 1\.5 or 1.5.
		// Either `var x = 1/- 1.5 /i.test(x)`
		// where `i.test(x)` is a method call of reference i,
		// or `/-1\.5/i.test(x)` which is a method call on a
		// case insensitive regular expression.
		`<script>{{if false}}var x = 1{{end}}/-{{"1.5"}}/i.test(x)</script>`,
		`'/' could start a division or regexp: "/-"`,
	},
	{
		`{{template "foo"}}`,
		"z:1:11: no such template \"foo\"",
	},
	{
		`<div{{template "y"}}>` +
			// Illegal starting in stateTag but not in stateText.
			`{{define "y"}} foo<b{{end}}`,
		`"<" in attribute name: " foo<b"`,
	},
	{
		`<script>reverseList = [{{template "t"}}]</script>` +
			// Missing " after recursive call.
			`{{define "t"}}{{if .Tail}}{{template "t" .Tail}}{{end}}{{.Head}}",{{end}}`,
		`: cannot compute output context for template t$htmltemplate_stateJS_elementScript`,
	},
	{
		`<input type=button value=onclick=>`,
		`html/template:z: "=" in unquoted attr: "onclick="`,
	},
	{
		`<input type=button value= onclick=>`,
		`html/template:z: "=" in unquoted attr: "onclick="`,
	},
	{
		`<input type=button value= 1+1=2>`,
		`html/template:z: "=" in unquoted attr: "1+1=2"`,
	},
	{
		"<a class=`foo>",
		"html/template:z: \"`\" in unquoted attr: \"`foo\"",
	},
	{
		`<a style=font:'Arial'>`,
		`html/template:z: "'" in unquoted attr: "font:'Arial'"`,
	},
	{
		`<a=foo>`,
		`: expected space, attr name, or end of tag, but got "=foo>"`,
	},
	{
		`Hello, {{. | urlquery | print}}!`,
		// urlquery is disallowed if it is not the last command in the pipeline.
		`predefined escaper "urlquery" disallowed in template`,
	},
	{
		`Hello, {{. | html | print}}!`,
		// html is disallowed if it is not the last command in the pipeline.
		`predefined escaper "html" disallowed in template`,
	},
	{
		`Hello, {{html . | print}}!`,
		// A direct call to html is disallowed if it is not the last command in the pipeline.
		`predefined escaper "html" disallowed in template`,
	},
	{
		`<div class={{. | html}}>Hello<div>`,
		// html is disallowed in a pipeline that is in an unquoted attribute context,
		// even if it is the last command in the pipeline.
		`predefined escaper "html" disallowed in template`,
	},
	{
		`Hello, {{. | urlquery | html}}!`,
		// html is allowed since it is the last command in the pipeline, but urlquery is not.
		`predefined escaper "urlquery" disallowed in template`,
	},
}

var escapeTextInputs = []string{
	``,
	`Hello, World!`,
	`<a`,
	`<a `,
	`<a>`,
	`<a href`,
	`<a on`,
	`<a href `,
	`<a style  =  `,
	`<a href=`,
	`<a href=x`,
	`<a href=x `,
	`<a href=>`,
	`<a href=x>`,
	`<a href ='`,
	`<a href=''`,
	`<a href= "`,
	`<a href=""`,
	`<a title="`,
	`<a HREF='http:`,
	`<a Href='/`,
	`<a href='"`,
	`<a href="'`,
	`<a href='&apos;`,
	`<a href="&quot;`,
	`<a href="&#34;`,
	`<a href=&quot;`,
	`<img alt="1">`,
	`<img alt="1>"`,
	`<img alt="1>">`,
	`<input checked type="checkbox"`,
	`<a onclick="`,
	`<a onclick="//foo`,
	"<a onclick='//\n",
	"<a onclick='//\r\n",
	"<a onclick='//\u2028",
	`<a onclick="/*`,
	`<a onclick="/*/`,
	`<a onclick="/**/`,
	`<a onkeypress="&quot;`,
	`<a onclick='&quot;foo&quot;`,
	`<a onclick=&#39;foo&#39;`,
	`<a onclick=&#39;foo`,
	`<a onclick="&quot;foo'`,
	`<a onclick="'foo&quot;`,
	"<a onclick=\"`foo",
	`<A ONCLICK="'`,
	`<a onclick="/`,
	`<a onclick="'foo'`,
	`<a onclick="'foo\'`,
	`<a onclick="'foo\'`,
	`<a onclick="/foo/`,
	`<script>/foo/ /=`,
	`<a onclick="1 /foo`,
	`<a onclick="1 /*c*/ /foo`,
	`<a onclick="/foo[/]`,
	`<a onclick="/foo\/`,
	`<a onclick="/foo/`,
	`<input checked style="`,
	`<a style="//`,
	`<a style="//</script>`,
	"<a style='//\n",
	"<a style='//\r",
	`<a style="/*`,
	`<a style="/*/`,
	`<a style="/**/`,
	`<a style="background: '`,
	`<a style="background: &quot;`,
	`<a style="background: '/foo?img=`,
	`<a style="background: '/`,
	`<a style="background: url(&#x22;/`,
	`<a style="background: url('/`,
	`<a style="background: url('/)`,
	`<a style="background: url('/ `,
	`<a style="background: url(/`,
	`<a style="background: url( `,
	`<a style="background: url( /image?name=`,
	`<a style="background: url(x)`,
	`<a style="background: url('x'`,
	`<a style="background: url( x `,
	`<!-- foo`,
	`<!-->`,
	`<!--->`,
	`<!-- foo -->`,
	`<script`,
	`<script `,
	`<script src="foo.js" `,
	`<script src='foo.js' `,
	`<script type=text/javascript `,
	`<script>`,
	`<script>foo`,
	`<script>foo</script>`,
	`<script>foo</script><!--`,
	`<script>document.write("<p>foo</p>");`,
	`<script>document.write("<p>foo<\/script>");`,
	`<script>document.write("<script>`,
	`<script>document.write("<script>alert(1)</script>`,
	`<script>document.write("<script>alert(1)<!--`,
	`<script>document.write("<script>alert(1)</Script>");`,
	`<script>document.write("<!--");`,
	`<script>let a = /</script`,
	`<script>let a = /</script/`,
	`<script type="text/template">`,
	`<script type="TEXT/JAVASCRIPT">`,
	`<script TYPE="text/template">`,
	`<script type="notjs">`,
	`<Script>`,
	`<SCRIPT>foo`,
	`<textarea>value`,
	`<textarea>value</TEXTAREA>`,
	`<textarea name=html><b`,
	`<title>value`,
	`<style>value`,
	`<a xlink:href`,
	`<a xmlns`,
	`<a xmlns:foo`,
	`<a xmlnsxyz`,
	`<a data-url`,
	`<a data-iconUri`,
	`<a data-urlItem`,
	`<a g:`,
	`<a g:url`,
	`<a g:iconUri`,
	`<a g:urlItem`,
	`<a g:value`,
	`<a svg:style='`,
	`<svg:font-face`,
	`<svg:a svg:onclick="`,
	`<svg:a svg:onclick="x()">`,
	"<script>var a = `",
	"<script>var a = `${",
	"<script>var a = `${}",
	"<script>var a = `${`",
	"<script>var a = `${var a = \"",
	"<script>var a = `${var a = \"`",
	"<script>var a = `${var a = \"}",
	"<script>var a = `${``",
	"<script>var a = `${`}",
	"<script>`${ {} } asd`</script><script>`${ {} }",
	"<script>var foo = `${ (_ => { return \"x\" })() + \"${",
	"<script>var a = `${ {</script><script>var b = `${ x }",
	"<script>var foo = `x` + \"${",
	"<script>function f() { var a = `${}`; }",
	"<script>{`${}`}",
	"<script>`${ function f() { return `${1}` }() }`",
	"<script>function f() {`${ function f() { `${1}` } }`}",
	"<script>`${ { `` }",
	"<script>`${ { }`",
	"<script>var foo = `${ foo({ a: { c: `${",
	"<script>var foo = `${ foo({ a: { c: `${ {{.}} }` }, b: ",
	"<script>`${ `}",
}

var ensurePipelineTable = []struct {
	input, output string
	ids           []string
}{
	{
		"{{.X}}",
		".X",
		[]string{},
	},
	{
		"{{.X | html}}",
		".X | html",
		[]string{},
	},
	{
		"{{.X}}",
		".X | html",
		[]string{"html"},
	},
	{
		"{{html .X}}",
		"_eval_args_ .X | html | urlquery",
		[]string{"html", "urlquery"},
	},
	{
		"{{html .X .Y .Z}}",
		"_eval_args_ .X .Y .Z | html | urlquery",
		[]string{"html", "urlquery"},
	},
	{
		"{{.X | print}}",
		".X | print | urlquery",
		[]string{"urlquery"},
	},
	{
		"{{.X | print | urlquery}}",
		".X | print | urlquery",
		[]string{"urlquery"},
	},
	{
		"{{.X | urlquery}}",
		".X | html | urlquery",
		[]string{"html", "urlquery"},
	},
	{
		"{{.X | print 2 | .f 3}}",
		".X | print 2 | .f 3 | urlquery | html",
		[]string{"urlquery", "html"},
	},
	{
		// covering issue 10801
		"{{.X | println.x }}",
		".X | println.x | urlquery | html",
		[]string{"urlquery", "html"},
	},
	{
		// covering issue 10801
		"{{.X | (print 12 | println).x }}",
		".X | (print 12 | println).x | urlquery | html",
		[]string{"urlquery", "html"},
	},
	// The following test cases ensure that the merging of internal escapers
	// with the predefined "html" and "urlquery" escapers is correct.
	{
		"{{.X | urlquery}}",
		".X | _html_template_urlfilter | urlquery",
		[]string{"_html_template_urlfilter", "_html_template_urlnormalizer"},
	},
	{
		"{{.X | urlquery}}",
		".X | urlquery | _html_template_urlfilter | _html_template_cssescaper",
		[]string{"_html_template_urlfilter", "_html_template_cssescaper"},
	},
	{
		"{{.X | urlquery}}",
		".X | urlquery",
		[]string{"_html_template_urlnormalizer"},
	},
	{
		"{{.X | urlquery}}",
		".X | urlquery",
		[]string{"_html_template_urlescaper"},
	},
	{
		"{{.X | html}}",
		".X | html",
		[]string{"_html_template_htmlescaper"},
	},
	{
		"{{.X | html}}",
		".X | html",
		[]string{"_html_template_rcdataescaper"},
	},
}

var typedContentData = []any{
	`<b> "foo%" O'Reilly &bar;`,
	stdhtml.CSS(`a[href =~ "//example.com"]#foo`),
	stdhtml.HTML(`Hello, <b>World</b> &amp;tc!`),
	stdhtml.HTMLAttr(` dir="ltr"`),
	stdhtml.JS(`c && alert("Hello, World!");`),
	stdhtml.JSStr(`Hello, World & O'Reilly\u0021`),
	stdhtml.URL(`greeting=H%69,&addressee=(World)`),
	stdhtml.Srcset(`greeting=H%69,&addressee=(World) 2x, https://golang.org/favicon.ico 500.5w`),
	stdhtml.URL(`,foo/,`),
}

var typedContentTable = []struct {
	input string
	want  []string
}{
	{
		`<style>{{.}} { color: blue }</style>`,
		[]string{
			`ZgotmplZ`,
			// Allowed but not escaped.
			`a[href =~ "//example.com"]#foo`,
			`ZgotmplZ`,
			`ZgotmplZ`,
			`ZgotmplZ`,
			`ZgotmplZ`,
			`ZgotmplZ`,
			`ZgotmplZ`,
			`ZgotmplZ`,
		},
	},
	{
		`<div style="{{.}}">`,
		[]string{
			`ZgotmplZ`,
			// Allowed and HTML escaped.
			`a[href =~ &#34;//example.com&#34;]#foo`,
			`ZgotmplZ`,
			`ZgotmplZ`,
			`ZgotmplZ`,
			`ZgotmplZ`,
			`ZgotmplZ`,
			`ZgotmplZ`,
			`ZgotmplZ`,
		},
	},
	{
		`{{.}}`,
		[]string{
			`&lt;b&gt; &#34;foo%&#34; O&#39;Reilly &amp;bar;`,
			`a[href =~ &#34;//example.com&#34;]#foo`,
			// Not escaped.
			`Hello, <b>World</b> &amp;tc!`,
			` dir=&#34;ltr&#34;`,
			`c &amp;&amp; alert(&#34;Hello, World!&#34;);`,
			`Hello, World &amp; O&#39;Reilly\u0021`,
			`greeting=H%69,&amp;addressee=(World)`,
			`greeting=H%69,&amp;addressee=(World) 2x, https://golang.org/favicon.ico 500.5w`,
			`,foo/,`,
		},
	},
	{
		`<a{{.}}>`,
		[]string{
			`ZgotmplZ`,
			`ZgotmplZ`,
			`ZgotmplZ`,
			// Allowed and HTML escaped.
			` dir="ltr"`,
			`ZgotmplZ`,
			`ZgotmplZ`,
			`ZgotmplZ`,
			`ZgotmplZ`,
			`ZgotmplZ`,
		},
	},
	{
		`<a title={{.}}>`,
		[]string{
			`&lt;b&gt;&#32;&#34;foo%&#34;&#32;O&#39;Reilly&#32;&amp;bar;`,
			`a[href&#32;&#61;~&#32;&#34;//example.com&#34;]#foo`,
			// Tags stripped, spaces escaped, entity not re-escaped.
			`Hello,&#32;World&#32;&amp;tc!`,
			`&#32;dir&#61;&#34;ltr&#34;`,
			`c&#32;&amp;&amp;&#32;alert(&#34;Hello,&#32;World!&#34;);`,
			`Hello,&#32;World&#32;&amp;&#32;O&#39;Reilly\u0021`,
			`greeting&#61;H%69,&amp;addressee&#61;(World)`,
			`greeting&#61;H%69,&amp;addressee&#61;(World)&#32;2x,&#32;https://golang.org/favicon.ico&#32;500.5w`,
			`,foo/,`,
		},
	},
	{
		`<a title='{{.}}'>`,
		[]string{
			`&lt;b&gt; &#34;foo%&#34; O&#39;Reilly &amp;bar;`,
			`a[href =~ &#34;//example.com&#34;]#foo`,
			// Tags stripped, entity not re-escaped.
			`Hello, World &amp;tc!`,
			` dir=&#34;ltr&#34;`,
			`c &amp;&amp; alert(&#34;Hello, World!&#34;);`,
			`Hello, World &amp; O&#39;Reilly\u0021`,
			`greeting=H%69,&amp;addressee=(World)`,
			`greeting=H%69,&amp;addressee=(World) 2x, https://golang.org/favicon.ico 500.5w`,
			`,foo/,`,
		},
	},
	{
		`<textarea>{{.}}</textarea>`,
		[]string{
			`&lt;b&gt; &#34;foo%&#34; O&#39;Reilly &amp;bar;`,
			`a[href =~ &#34;//example.com&#34;]#foo`,
			// Angle brackets escaped to prevent injection of close tags, entity not re-escaped.
			`Hello, &lt;b&gt;World&lt;/b&gt; &amp;tc!`,
			` dir=&#34;ltr&#34;`,
			`c &amp;&amp; alert(&#34;Hello, World!&#34;);`,
			`Hello, World &amp; O&#39;Reilly\u0021`,
			`greeting=H%69,&amp;addressee=(World)`,
			`greeting=H%69,&amp;addressee=(World) 2x, https://golang.org/favicon.ico 500.5w`,
			`,foo/,`,
		},
	},
	{
		`<script>alert({{.}})</script>`,
		[]string{
			`"\u003cb\u003e \"foo%\" O'Reilly \u0026bar;"`,
			`"a[href =~ \"//example.com\"]#foo"`,
			`"Hello, \u003cb\u003eWorld\u003c/b\u003e \u0026amp;tc!"`,
			`" dir=\"ltr\""`,
			// Not escaped.
			`c && alert("Hello, World!");`,
			// Escape sequence not over-escaped.
			`"Hello, World & O'Reilly\u0021"`,
			`"greeting=H%69,\u0026addressee=(World)"`,
			`"greeting=H%69,\u0026addressee=(World) 2x, https://golang.org/favicon.ico 500.5w"`,
			`",foo/,"`,
		},
	},
	{
		`<button onclick="alert({{.}})">`,
		[]string{
			`&#34;\u003cb\u003e \&#34;foo%\&#34; O&#39;Reilly \u0026bar;&#34;`,
			`&#34;a[href =~ \&#34;//example.com\&#34;]#foo&#34;`,
			`&#34;Hello, \u003cb\u003eWorld\u003c/b\u003e \u0026amp;tc!&#34;`,
			`&#34; dir=\&#34;ltr\&#34;&#34;`,
			// Not JS escaped but HTML escaped.
			`c &amp;&amp; alert(&#34;Hello, World!&#34;);`,
			// Escape sequence not over-escaped.
			`&#34;Hello, World &amp; O&#39;Reilly\u0021&#34;`,
			`&#34;greeting=H%69,\u0026addressee=(World)&#34;`,
			`&#34;greeting=H%69,\u0026addressee=(World) 2x, https://golang.org/favicon.ico 500.5w&#34;`,
			`&#34;,foo/,&#34;`,
		},
	},
	{
		`<script>alert("{{.}}")</script>`,
		[]string{
			`\u003cb\u003e \u0022foo%\u0022 O\u0027Reilly \u0026bar;`,
			`a[href =~ \u0022\/\/example.com\u0022]#foo`,
			`Hello, \u003cb\u003eWorld\u003c\/b\u003e \u0026amp;tc!`,
			` dir=\u0022ltr\u0022`,
			`c \u0026\u0026 alert(\u0022Hello, World!\u0022);`,
			// Escape sequence not over-escaped.
			`Hello, World \u0026 O\u0027Reilly\u0021`,
			`greeting=H%69,\u0026addressee=(World)`,
			`greeting=H%69,\u0026addressee=(World) 2x, https:\/\/golang.org\/favicon.ico 500.5w`,
			`,foo\/,`,
		},
	},
	{
		`<script type="text/javascript">alert("{{.}}")</script>`,
		[]string{
			`\u003cb\u003e \u0022foo%\u0022 O\u0027Reilly \u0026bar;`,
			`a[href =~ \u0022\/\/example.com\u0022]#foo`,
			`Hello, \u003cb\u003eWorld\u003c\/b\u003e \u0026amp;tc!`,
			` dir=\u0022ltr\u0022`,
			`c \u0026\u0026 alert(\u0022Hello, World!\u0022);`,
			// Escape sequence not over-escaped.
			`Hello, World \u0026 O\u0027Reilly\u0021`,
			`greeting=H%69,\u0026addressee=(World)`,
			`greeting=H%69,\u0026addressee=(World) 2x, https:\/\/golang.org\/favicon.ico 500.5w`,
			`,foo\/,`,
		},
	},
	{
		`<script type="text/javascript">alert({{.}})</script>`,
		[]string{
			`"\u003cb\u003e \"foo%\" O'Reilly \u0026bar;"`,
			`"a[href =~ \"//example.com\"]#foo"`,
			`"Hello, \u003cb\u003eWorld\u003c/b\u003e \u0026amp;tc!"`,
			`" dir=\"ltr\""`,
			// Not escaped.
			`c && alert("Hello, World!");`,
			// Escape sequence not over-escaped.
			`"Hello, World & O'Reilly\u0021"`,
			`"greeting=H%69,\u0026addressee=(World)"`,
			`"greeting=H%69,\u0026addressee=(World) 2x, https://golang.org/favicon.ico 500.5w"`,
			`",foo/,"`,
		},
	},
	{
		// Not treated as JS. The output is same as for <div>{{.}}</div>
		`<script type="text/template">{{.}}</script>`,
		[]string{
			`&lt;b&gt; &#34;foo%&#34; O&#39;Reilly &amp;bar;`,
			`a[href =~ &#34;//example.com&#34;]#foo`,
			// Not escaped.
			`Hello, <b>World</b> &amp;tc!`,
			` dir=&#34;ltr&#34;`,
			`c &amp;&amp; alert(&#34;Hello, World!&#34;);`,
			`Hello, World &amp; O&#39;Reilly\u0021`,
			`greeting=H%69,&amp;addressee=(World)`,
			`greeting=H%69,&amp;addressee=(World) 2x, https://golang.org/favicon.ico 500.5w`,
			`,foo/,`,
		},
	},
	{
		`<button onclick='alert("{{.}}")'>`,
		[]string{
			`\u003cb\u003e \u0022foo%\u0022 O\u0027Reilly \u0026bar;`,
			`a[href =~ \u0022\/\/example.com\u0022]#foo`,
			`Hello, \u003cb\u003eWorld\u003c\/b\u003e \u0026amp;tc!`,
			` dir=\u0022ltr\u0022`,
			`c \u0026\u0026 alert(\u0022Hello, World!\u0022);`,
			// Escape sequence not over-escaped.
			`Hello, World \u0026 O\u0027Reilly\u0021`,
			`greeting=H%69,\u0026addressee=(World)`,
			`greeting=H%69,\u0026addressee=(World) 2x, https:\/\/golang.org\/favicon.ico 500.5w`,
			`,foo\/,`,
		},
	},
	{
		`<a href="?q={{.}}">`,
		[]string{
			`%3cb%3e%20%22foo%25%22%20O%27Reilly%20%26bar%3b`,
			`a%5bhref%20%3d~%20%22%2f%2fexample.com%22%5d%23foo`,
			`Hello%2c%20%3cb%3eWorld%3c%2fb%3e%20%26amp%3btc%21`,
			`%20dir%3d%22ltr%22`,
			`c%20%26%26%20alert%28%22Hello%2c%20World%21%22%29%3b`,
			`Hello%2c%20World%20%26%20O%27Reilly%5cu0021`,
			// Quotes and parens are escaped but %69 is not over-escaped. HTML escaping is done.
			`greeting=H%69,&amp;addressee=%28World%29`,
			`greeting%3dH%2569%2c%26addressee%3d%28World%29%202x%2c%20https%3a%2f%2fgolang.org%2ffavicon.ico%20500.5w`,
			`,foo/,`,
		},
	},
	{
		`<style>body { background: url('?img={{.}}') }</style>`,
		[]string{
			`%3cb%3e%20%22foo%25%22%20O%27Reilly%20%26bar%3b`,
			`a%5bhref%20%3d~%20%22%2f%2fexample.com%22%5d%23foo`,
			`Hello%2c%20%3cb%3eWorld%3c%2fb%3e%20%26amp%3btc%21`,
			`%20dir%3d%22ltr%22`,
			`c%20%26%26%20alert%28%22Hello%2c%20World%21%22%29%3b`,
			`Hello%2c%20World%20%26%20O%27Reilly%5cu0021`,
			// Quotes and parens are escaped but %69 is not over-escaped. HTML escaping is not done.
			`greeting=H%69,&addressee=%28World%29`,
			`greeting%3dH%2569%2c%26addressee%3d%28World%29%202x%2c%20https%3a%2f%2fgolang.org%2ffavicon.ico%20500.5w`,
			`,foo/,`,
		},
	},
	{
		`<img srcset="{{.}}">`,
		[]string{
			`#ZgotmplZ`,
			`#ZgotmplZ`,
			// Commas are not escaped.
			`Hello,#ZgotmplZ`,
			// Leading spaces are not percent escapes.
			` dir=%22ltr%22`,
			// Spaces after commas are not percent escaped.
			`#ZgotmplZ, World!%22%29;`,
			`Hello,#ZgotmplZ`,
			`greeting=H%69%2c&amp;addressee=%28World%29`,
			// Metadata is not escaped.
			`greeting=H%69,&amp;addressee=(World) 2x, https://golang.org/favicon.ico 500.5w`,
			`%2cfoo/%2c`,
		},
	},
	{
		`<img srcset={{.}}>`,
		[]string{
			`#ZgotmplZ`,
			`#ZgotmplZ`,
			`Hello,#ZgotmplZ`,
			// Spaces are HTML escaped not %-escaped
			`&#32;dir&#61;%22ltr%22`,
			`#ZgotmplZ,&#32;World!%22%29;`,
			`Hello,#ZgotmplZ`,
			`greeting&#61;H%69%2c&amp;addressee&#61;%28World%29`,
			`greeting&#61;H%69,&amp;addressee&#61;(World)&#32;2x,&#32;https://golang.org/favicon.ico&#32;500.5w`,
			// Commas are escaped.
			`%2cfoo/%2c`,
		},
	},
	{
		`<img srcset="{{.}} 2x, https://golang.org/ 500.5w">`,
		[]string{
			`#ZgotmplZ`,
			`#ZgotmplZ`,
			`Hello,#ZgotmplZ`,
			` dir=%22ltr%22`,
			`#ZgotmplZ, World!%22%29;`,
			`Hello,#ZgotmplZ`,
			`greeting=H%69%2c&amp;addressee=%28World%29`,
			`greeting=H%69,&amp;addressee=(World) 2x, https://golang.org/favicon.ico 500.5w`,
			`%2cfoo/%2c`,
		},
	},
	{
		`<img srcset="http://godoc.org/ {{.}}, https://golang.org/ 500.5w">`,
		[]string{
			`#ZgotmplZ`,
			`#ZgotmplZ`,
			`Hello,#ZgotmplZ`,
			` dir=%22ltr%22`,
			`#ZgotmplZ, World!%22%29;`,
			`Hello,#ZgotmplZ`,
			`greeting=H%69%2c&amp;addressee=%28World%29`,
			`greeting=H%69,&amp;addressee=(World) 2x, https://golang.org/favicon.ico 500.5w`,
			`%2cfoo/%2c`,
		},
	},
	{
		`<img srcset="http://godoc.org/?q={{.}} 2x, https://golang.org/ 500.5w">`,
		[]string{
			`#ZgotmplZ`,
			`#ZgotmplZ`,
			`Hello,#ZgotmplZ`,
			` dir=%22ltr%22`,
			`#ZgotmplZ, World!%22%29;`,
			`Hello,#ZgotmplZ`,
			`greeting=H%69%2c&amp;addressee=%28World%29`,
			`greeting=H%69,&amp;addressee=(World) 2x, https://golang.org/favicon.ico 500.5w`,
			`%2cfoo/%2c`,
		},
	},
	{
		`<img srcset="http://godoc.org/ 2x, {{.}} 500.5w">`,
		[]string{
			`#ZgotmplZ`,
			`#ZgotmplZ`,
			`Hello,#ZgotmplZ`,
			` dir=%22ltr%22`,
			`#ZgotmplZ, World!%22%29;`,
			`Hello,#ZgotmplZ`,
			`greeting=H%69%2c&amp;addressee=%28World%29`,
			`greeting=H%69,&amp;addressee=(World) 2x, https://golang.org/favicon.ico 500.5w`,
			`%2cfoo/%2c`,
		},
	},
	{
		`<img srcset="http://godoc.org/ 2x, https://golang.org/ {{.}}">`,
		[]string{
			`#ZgotmplZ`,
			`#ZgotmplZ`,
			`Hello,#ZgotmplZ`,
			` dir=%22ltr%22`,
			`#ZgotmplZ, World!%22%29;`,
			`Hello,#ZgotmplZ`,
			`greeting=H%69%2c&amp;addressee=%28World%29`,
			`greeting=H%69,&amp;addressee=(World) 2x, https://golang.org/favicon.ico 500.5w`,
			`%2cfoo/%2c`,
		},
	},
}

var execTestsTable = []execTest{
	// Trivial cases.
	{"empty", "", "", nil, true},
	{"text", "some text", "some text", nil, true},
	{"nil action", "{{nil}}", "", nil, false},

	// Ideal constants.
	{"ideal int", "{{typeOf 3}}", "int", 0, true},
	{"ideal float", "{{typeOf 1.0}}", "float64", 0, true},
	{"ideal exp float", "{{typeOf 1e1}}", "float64", 0, true},
	{"ideal complex", "{{typeOf 1i}}", "complex128", 0, true},
	{"ideal int", "{{typeOf " + bigInt + "}}", "int", 0, true},
	{"ideal too big", "{{typeOf " + bigUint + "}}", "", 0, false},
	{"ideal nil without type", "{{nil}}", "", 0, false},

	// Fields of structs.
	{".X", "-{{.X}}-", "-x-", tVal, true},
	{".U.V", "-{{.U.V}}-", "-v-", tVal, true},
	{".unexported", "{{.unexported}}", "", tVal, false},

	// Fields on maps.
	{"map .one", "{{.MSI.one}}", "1", tVal, true},
	{"map .two", "{{.MSI.two}}", "2", tVal, true},
	{"map .NO", "{{.MSI.NO}}", "", tVal, true}, // NOTE: <no value> in text/template
	{"map .one interface", "{{.MXI.one}}", "1", tVal, true},
	{"map .WRONG args", "{{.MSI.one 1}}", "", tVal, false},
	{"map .WRONG type", "{{.MII.one}}", "", tVal, false},

	// Dots of all kinds to test basic evaluation.
	{"dot int", "<{{.}}>", "&lt;13>", 13, true},
	{"dot uint", "<{{.}}>", "&lt;14>", uint(14), true},
	{"dot float", "<{{.}}>", "&lt;15.1>", 15.1, true},
	{"dot bool", "<{{.}}>", "&lt;true>", true, true},
	{"dot complex", "<{{.}}>", "&lt;(16.2-17i)>", 16.2 - 17i, true},
	{"dot string", "<{{.}}>", "&lt;hello>", "hello", true},
	{"dot slice", "<{{.}}>", "&lt;[-1 -2 -3]>", []int{-1, -2, -3}, true},
	{"dot map", "<{{.}}>", "&lt;map[two:22]>", map[string]int{"two": 22}, true},
	{"dot struct", "<{{.}}>", "&lt;{7 seven}>", struct {
		a int
		b string
	}{7, "seven"}, true},

	// Variables.
	{"$ int", "{{$}}", "123", 123, true},
	{"$.I", "{{$.I}}", "17", tVal, true},
	{"$.U.V", "{{$.U.V}}", "v", tVal, true},
	{"declare in action", "{{$x := $.U.V}}{{$x}}", "v", tVal, true},
	{"simple assignment", "{{$x := 2}}{{$x = 3}}{{$x}}", "3", tVal, true},
	{
		"nested assignment",
		"{{$x := 2}}{{if true}}{{$x = 3}}{{end}}{{$x}}",
		"3", tVal, true,
	},
	{
		"nested assignment changes the last declaration",
		"{{$x := 1}}{{if true}}{{$x := 2}}{{if true}}{{$x = 3}}{{end}}{{end}}{{$x}}",
		"1", tVal, true,
	},

	// Type with String method.
	{"V{6666}.String()", "-{{.V0}}-", "-{6666}-", tVal, true}, //  NOTE: -<6666>- in text/template
	{"&V{7777}.String()", "-{{.V1}}-", "-&lt;7777&gt;-", tVal, true},
	{"(*V)(nil).String()", "-{{.V2}}-", "-nilV-", tVal, true},

	// Type with Error method.
	{"W{888}.Error()", "-{{.W0}}-", "-{888}-", tVal, true}, // NOTE: -[888] in text/template
	{"&W{999}.Error()", "-{{.W1}}-", "-[999]-", tVal, true},
	{"(*W)(nil).Error()", "-{{.W2}}-", "-nilW-", tVal, true},

	// Pointers.
	{"*int", "{{.PI}}", "23", tVal, true},
	{"*string", "{{.PS}}", "a string", tVal, true},
	{"*[]int", "{{.PSI}}", "[21 22 23]", tVal, true},
	{"*[]int[1]", "{{index .PSI 1}}", "22", tVal, true},
	{"NIL", "{{.NIL}}", "&lt;nil&gt;", tVal, true},

	// Empty interfaces holding values.
	{"empty nil", "{{.Empty0}}", "", tVal, true}, // NOTE: <no value> in text/template
	{"empty with int", "{{.Empty1}}", "3", tVal, true},
	{"empty with string", "{{.Empty2}}", "empty2", tVal, true},
	{"empty with slice", "{{.Empty3}}", "[7 8]", tVal, true},
	{"empty with struct", "{{.Empty4}}", "{UinEmpty}", tVal, true},
	{"empty with struct, field", "{{.Empty4.V}}", "UinEmpty", tVal, true},

	// Edge cases with <no value> with an interface value
	{"field on interface", "{{.foo}}", "", nil, true},                  // NOTE: <no value> in text/template
	{"field on parenthesized interface", "{{(.).foo}}", "", nil, true}, // NOTE: <no value> in text/template

	// Issue 31810: Parenthesized first element of pipeline with arguments.
	// See also TestIssue31810.
	{"unparenthesized non-function", "{{1 2}}", "", nil, false},
	{"parenthesized non-function", "{{(1) 2}}", "", nil, false},
	{"parenthesized non-function with no args", "{{(1)}}", "1", nil, true}, // This is fine.

	// Method calls.
	{".Method0", "-{{.Method0}}-", "-M0-", tVal, true},
	{".Method1(1234)", "-{{.Method1 1234}}-", "-1234-", tVal, true},
	{".Method1(.I)", "-{{.Method1 .I}}-", "-17-", tVal, true},
	{".Method2(3, .X)", "-{{.Method2 3 .X}}-", "-Method2: 3 x-", tVal, true},
	{".Method2(.U16, `str`)", "-{{.Method2 .U16 `str`}}-", "-Method2: 16 str-", tVal, true},
	{".Method2(.U16, $x)", "{{if $x := .X}}-{{.Method2 .U16 $x}}{{end}}-", "-Method2: 16 x-", tVal, true},
	{".Method3(nil constant)", "-{{.Method3 nil}}-", "-Method3: &lt;nil&gt;-", tVal, true},
	{".Method3(nil value)", "-{{.Method3 .MXI.unset}}-", "-Method3: &lt;nil&gt;-", tVal, true},
	{"method on var", "{{if $x := .}}-{{$x.Method2 .U16 $x.X}}{{end}}-", "-Method2: 16 x-", tVal, true},
	{
		"method on chained var",
		"{{range .MSIone}}{{if $.U.TrueFalse $.True}}{{$.U.TrueFalse $.True}}{{else}}WRONG{{end}}{{end}}",
		"true", tVal, true,
	},
	{
		"chained method",
		"{{range .MSIone}}{{if $.GetU.TrueFalse $.True}}{{$.U.TrueFalse $.True}}{{else}}WRONG{{end}}{{end}}",
		"true", tVal, true,
	},
	{
		"chained method on variable",
		"{{with $x := .}}{{with .SI}}{{$.GetU.TrueFalse $.True}}{{end}}{{end}}",
		"true", tVal, true,
	},
	{".NilOKFunc not nil", "{{call .NilOKFunc .PI}}", "false", tVal, true},
	{".NilOKFunc nil", "{{call .NilOKFunc nil}}", "true", tVal, true},
	{"method on nil value from slice", "-{{range .}}{{.Method1 1234}}{{end}}-", "-1234-", tSliceOfNil, true},
	{"method on typed nil interface value", "{{.NonEmptyInterfaceTypedNil.Method0}}", "M0", tVal, true},

	// Function call builtin.
	{".BinaryFunc", "{{call .BinaryFunc `1` `2`}}", "[1=2]", tVal, true},
	{".VariadicFunc0", "{{call .VariadicFunc}}", "&lt;&gt;", tVal, true},
	{".VariadicFunc2", "{{call .VariadicFunc `he` `llo`}}", "&lt;he&#43;llo&gt;", tVal, true},
	{".VariadicFuncInt", "{{call .VariadicFuncInt 33 `he` `llo`}}", "33=&lt;he&#43;llo&gt;", tVal, true},
	{"if .BinaryFunc call", "{{ if .BinaryFunc}}{{call .BinaryFunc `1` `2`}}{{end}}", "[1=2]", tVal, true},
	{"if not .BinaryFunc call", "{{ if not .BinaryFunc}}{{call .BinaryFunc `1` `2`}}{{else}}No{{end}}", "No", tVal, true},
	{"Interface Call", `{{stringer .S}}`, "foozle", map[string]any{"S": bytes.NewBufferString("foozle")}, true},
	{".ErrFunc", "{{call .ErrFunc}}", "bla", tVal, true},
	{"call nil", "{{call nil}}", "", tVal, false},

	// Erroneous function calls (check args).
	{".BinaryFuncTooFew", "{{call .BinaryFunc `1`}}", "", tVal, false},
	{".BinaryFuncTooMany", "{{call .BinaryFunc `1` `2` `3`}}", "", tVal, false},
	{".BinaryFuncBad0", "{{call .BinaryFunc 1 3}}", "", tVal, false},
	{".BinaryFuncBad1", "{{call .BinaryFunc `1` 3}}", "", tVal, false},
	{".VariadicFuncBad0", "{{call .VariadicFunc 3}}", "", tVal, false},
	{".VariadicFuncIntBad0", "{{call .VariadicFuncInt}}", "", tVal, false},
	{".VariadicFuncIntBad`", "{{call .VariadicFuncInt `x`}}", "", tVal, false},
	{".VariadicFuncNilBad", "{{call .VariadicFunc nil}}", "", tVal, false},

	// Pipelines.
	{"pipeline", "-{{.Method0 | .Method2 .U16}}-", "-Method2: 16 M0-", tVal, true},
	{"pipeline func", "-{{call .VariadicFunc `llo` | call .VariadicFunc `he` }}-", "-&lt;he&#43;&lt;llo&gt;&gt;-", tVal, true},

	// Nil values aren't missing arguments.
	{"nil pipeline", "{{ .Empty0 | call .NilOKFunc }}", "true", tVal, true},
	{"nil call arg", "{{ call .NilOKFunc .Empty0 }}", "true", tVal, true},
	{"bad nil pipeline", "{{ .Empty0 | .VariadicFunc }}", "", tVal, false},

	// Parenthesized expressions
	{"parens in pipeline", "{{printf `%d %d %d` (1) (2 | add 3) (add 4 (add 5 6))}}", "1 5 15", tVal, true},

	// Parenthesized expressions with field accesses
	{"parens: $ in paren", "{{($).X}}", "x", tVal, true},
	{"parens: $.GetU in paren", "{{($.GetU).V}}", "v", tVal, true},
	{"parens: $ in paren in pipe", "{{($ | echo).X}}", "x", tVal, true},
	{"parens: spaces and args", `{{(makemap "up" "down" "left" "right").left}}`, "right", tVal, true},

	// If.
	{"if true", "{{if true}}TRUE{{end}}", "TRUE", tVal, true},
	{"if false", "{{if false}}TRUE{{else}}FALSE{{end}}", "FALSE", tVal, true},
	{"if nil", "{{if nil}}TRUE{{end}}", "", tVal, false},
	{"if on typed nil interface value", "{{if .NonEmptyInterfaceTypedNil}}TRUE{{ end }}", "", tVal, true},
	{"if 1", "{{if 1}}NON-ZERO{{else}}ZERO{{end}}", "NON-ZERO", tVal, true},
	{"if 0", "{{if 0}}NON-ZERO{{else}}ZERO{{end}}", "ZERO", tVal, true},
	{"if 1.5", "{{if 1.5}}NON-ZERO{{else}}ZERO{{end}}", "NON-ZERO", tVal, true},
	{"if 0.0", "{{if .FloatZero}}NON-ZERO{{else}}ZERO{{end}}", "ZERO", tVal, true},
	{"if 1.5i", "{{if 1.5i}}NON-ZERO{{else}}ZERO{{end}}", "NON-ZERO", tVal, true},
	{"if 0.0i", "{{if .ComplexZero}}NON-ZERO{{else}}ZERO{{end}}", "ZERO", tVal, true},
	{"if emptystring", "{{if ``}}NON-EMPTY{{else}}EMPTY{{end}}", "EMPTY", tVal, true},
	{"if string", "{{if `notempty`}}NON-EMPTY{{else}}EMPTY{{end}}", "NON-EMPTY", tVal, true},
	{"if emptyslice", "{{if .SIEmpty}}NON-EMPTY{{else}}EMPTY{{end}}", "EMPTY", tVal, true},
	{"if slice", "{{if .SI}}NON-EMPTY{{else}}EMPTY{{end}}", "NON-EMPTY", tVal, true},
	{"if emptymap", "{{if .MSIEmpty}}NON-EMPTY{{else}}EMPTY{{end}}", "EMPTY", tVal, true},
	{"if map", "{{if .MSI}}NON-EMPTY{{else}}EMPTY{{end}}", "NON-EMPTY", tVal, true},
	{"if map unset", "{{if .MXI.none}}NON-ZERO{{else}}ZERO{{end}}", "ZERO", tVal, true},
	{"if map not unset", "{{if not .MXI.none}}ZERO{{else}}NON-ZERO{{end}}", "ZERO", tVal, true},
	{"if $x with $y int", "{{if $x := true}}{{with $y := .I}}{{$x}},{{$y}}{{end}}{{end}}", "true,17", tVal, true},
	{"if $x with $x int", "{{if $x := true}}{{with $x := .I}}{{$x}},{{end}}{{$x}}{{end}}", "17,true", tVal, true},
	{"if else if", "{{if false}}FALSE{{else if true}}TRUE{{end}}", "TRUE", tVal, true},
	{"if else chain", "{{if eq 1 3}}1{{else if eq 2 3}}2{{else if eq 3 3}}3{{end}}", "3", tVal, true},

	// Print etc.
	{"print", `{{print "hello, print"}}`, "hello, print", tVal, true},
	{"print 123", `{{print 1 2 3}}`, "1 2 3", tVal, true},
	{"print nil", `{{print nil}}`, "&lt;nil&gt;", tVal, true},
	{"println", `{{println 1 2 3}}`, "1 2 3\n", tVal, true},
	{"printf int", `{{printf "%04x" 127}}`, "007f", tVal, true},
	{"printf float", `{{printf "%g" 3.5}}`, "3.5", tVal, true},
	{"printf complex", `{{printf "%g" 1+7i}}`, "(1&#43;7i)", tVal, true},
	{"printf string", `{{printf "%s" "hello"}}`, "hello", tVal, true},
	{"printf function", `{{printf "%#q" zeroArgs}}`, "`zeroArgs`", tVal, true},
	{"printf field", `{{printf "%s" .U.V}}`, "v", tVal, true},
	{"printf method", `{{printf "%s" .Method0}}`, "M0", tVal, true},
	{"printf dot", `{{with .I}}{{printf "%d" .}}{{end}}`, "17", tVal, true},
	{"printf var", `{{with $x := .I}}{{printf "%d" $x}}{{end}}`, "17", tVal, true},
	{"printf lots", `{{printf "%d %s %g %s" 127 "hello" 7-3i .Method0}}`, "127 hello (7-3i) M0", tVal, true},

	// HTML.
	{
		"html", `{{html "<script>alert(\"XSS\");</script>"}}`,
		"&lt;script&gt;alert(&#34;XSS&#34;);&lt;/script&gt;", nil, true,
	},
	{
		"html pipeline", `{{printf "<script>alert(\"XSS\");</script>" | html}}`,
		"&lt;script&gt;alert(&#34;XSS&#34;);&lt;/script&gt;", nil, true,
	},
	{"html", `{{html .PS}}`, "a string", tVal, true},
	{"html typed nil", `{{html .NIL}}`, "&lt;nil&gt;", tVal, true},
	{"html untyped nil", `{{html .Empty0}}`, "&lt;nil&gt;", tVal, true}, // NOTE: "&lt;no value&gt;" in text/template

	// JavaScript.
	{"js", `{{js .}}`, `It\&#39;d be nice.`, `It'd be nice.`, true},

	// URL query.
	{"urlquery", `{{"http://www.example.org/"|urlquery}}`, "http%3A%2F%2Fwww.example.org%2F", nil, true},

	// Booleans
	{"not", "{{not true}} {{not false}}", "false true", nil, true},
	{"and", "{{and false 0}} {{and 1 0}} {{and 0 true}} {{and 1 1}}", "false 0 0 1", nil, true},
	{"or", "{{or 0 0}} {{or 1 0}} {{or 0 true}} {{or 1 1}}", "0 1 true 1", nil, true},
	{"boolean if", "{{if and true 1 `hi`}}TRUE{{else}}FALSE{{end}}", "TRUE", tVal, true},
	{"boolean if not", "{{if and true 1 `hi` | not}}TRUE{{else}}FALSE{{end}}", "FALSE", nil, true},

	// Indexing.
	{"slice[0]", "{{index .SI 0}}", "3", tVal, true},
	{"slice[1]", "{{index .SI 1}}", "4", tVal, true},
	{"slice[HUGE]", "{{index .SI 10}}", "", tVal, false},
	{"slice[WRONG]", "{{index .SI `hello`}}", "", tVal, false},
	{"slice[nil]", "{{index .SI nil}}", "", tVal, false},
	{"map[one]", "{{index .MSI `one`}}", "1", tVal, true},
	{"map[two]", "{{index .MSI `two`}}", "2", tVal, true},
	{"map[NO]", "{{index .MSI `XXX`}}", "0", tVal, true},
	{"map[nil]", "{{index .MSI nil}}", "", tVal, false},
	{"map[``]", "{{index .MSI ``}}", "0", tVal, true},
	{"map[WRONG]", "{{index .MSI 10}}", "", tVal, false},
	{"double index", "{{index .SMSI 1 `eleven`}}", "11", tVal, true},
	{"nil[1]", "{{index nil 1}}", "", tVal, false},
	{"map MI64S", "{{index .MI64S 2}}", "i642", tVal, true},
	{"map MI32S", "{{index .MI32S 2}}", "two", tVal, true},
	{"map MUI64S", "{{index .MUI64S 3}}", "ui643", tVal, true},
	{"map MI8S", "{{index .MI8S 3}}", "i83", tVal, true},
	{"map MUI8S", "{{index .MUI8S 2}}", "u82", tVal, true},
	{"index of an interface field", "{{index .Empty3 0}}", "7", tVal, true},

	// Slicing.
	{"slice[:]", "{{slice .SI}}", "[3 4 5]", tVal, true},
	{"slice[1:]", "{{slice .SI 1}}", "[4 5]", tVal, true},
	{"slice[1:2]", "{{slice .SI 1 2}}", "[4]", tVal, true},
	{"slice[-1:]", "{{slice .SI -1}}", "", tVal, false},
	{"slice[1:-2]", "{{slice .SI 1 -2}}", "", tVal, false},
	{"slice[1:2:-1]", "{{slice .SI 1 2 -1}}", "", tVal, false},
	{"slice[2:1]", "{{slice .SI 2 1}}", "", tVal, false},
	{"slice[2:2:1]", "{{slice .SI 2 2 1}}", "", tVal, false},
	{"out of range", "{{slice .SI 4 5}}", "", tVal, false},
	{"out of range", "{{slice .SI 2 2 5}}", "", tVal, false},
	{"len(s) < indexes < cap(s)", "{{slice .SICap 6 10}}", "[0 0 0 0]", tVal, true},
	{"len(s) < indexes < cap(s)", "{{slice .SICap 6 10 10}}", "[0 0 0 0]", tVal, true},
	{"indexes > cap(s)", "{{slice .SICap 10 11}}", "", tVal, false},
	{"indexes > cap(s)", "{{slice .SICap 6 10 11}}", "", tVal, false},
	{"array[:]", "{{slice .AI}}", "[3 4 5]", tVal, true},
	{"array[1:]", "{{slice .AI 1}}", "[4 5]", tVal, true},
	{"array[1:2]", "{{slice .AI 1 2}}", "[4]", tVal, true},
	{"string[:]", "{{slice .S}}", "xyz", tVal, true},
	{"string[0:1]", "{{slice .S 0 1}}", "x", tVal, true},
	{"string[1:]", "{{slice .S 1}}", "yz", tVal, true},
	{"string[1:2]", "{{slice .S 1 2}}", "y", tVal, true},
	{"out of range", "{{slice .S 1 5}}", "", tVal, false},
	{"3-index slice of string", "{{slice .S 1 2 2}}", "", tVal, false},
	{"slice of an interface field", "{{slice .Empty3 0 1}}", "[7]", tVal, true},

	// Len.
	{"slice", "{{len .SI}}", "3", tVal, true},
	{"map", "{{len .MSI }}", "3", tVal, true},
	{"len of int", "{{len 3}}", "", tVal, false},
	{"len of nothing", "{{len .Empty0}}", "", tVal, false},
	{"len of an interface field", "{{len .Empty3}}", "2", tVal, true},

	// With.
	{"with true", "{{with true}}{{.}}{{end}}", "true", tVal, true},
	{"with false", "{{with false}}{{.}}{{else}}FALSE{{end}}", "FALSE", tVal, true},
	{"with 1", "{{with 1}}{{.}}{{else}}ZERO{{end}}", "1", tVal, true},
	{"with 0", "{{with 0}}{{.}}{{else}}ZERO{{end}}", "ZERO", tVal, true},
	{"with 1.5", "{{with 1.5}}{{.}}{{else}}ZERO{{end}}", "1.5", tVal, true},
	{"with 0.0", "{{with .FloatZero}}{{.}}{{else}}ZERO{{end}}", "ZERO", tVal, true},
	{"with 1.5i", "{{with 1.5i}}{{.}}{{else}}ZERO{{end}}", "(0&#43;1.5i)", tVal, true},
	{"with 0.0i", "{{with .ComplexZero}}{{.}}{{else}}ZERO{{end}}", "ZERO", tVal, true},
	{"with emptystring", "{{with ``}}{{.}}{{else}}EMPTY{{end}}", "EMPTY", tVal, true},
	{"with string", "{{with `notempty`}}{{.}}{{else}}EMPTY{{end}}", "notempty", tVal, true},
	{"with emptyslice", "{{with .SIEmpty}}{{.}}{{else}}EMPTY{{end}}", "EMPTY", tVal, true},
	{"with slice", "{{with .SI}}{{.}}{{else}}EMPTY{{end}}", "[3 4 5]", tVal, true},
	{"with emptymap", "{{with .MSIEmpty}}{{.}}{{else}}EMPTY{{end}}", "EMPTY", tVal, true},
	{"with map", "{{with .MSIone}}{{.}}{{else}}EMPTY{{end}}", "map[one:1]", tVal, true},
	{"with empty interface, struct field", "{{with .Empty4}}{{.V}}{{end}}", "UinEmpty", tVal, true},
	{"with $x int", "{{with $x := .I}}{{$x}}{{end}}", "17", tVal, true},
	{"with $x struct.U.V", "{{with $x := $}}{{$x.U.V}}{{end}}", "v", tVal, true},
	{"with variable and action", "{{with $x := $}}{{$y := $.U.V}}{{$y}}{{end}}", "v", tVal, true},
	{"with on typed nil interface value", "{{with .NonEmptyInterfaceTypedNil}}TRUE{{ end }}", "", tVal, true},
	{"with else with", "{{with 0}}{{.}}{{else with true}}{{.}}{{end}}", "true", tVal, true},
	{"with else with chain", "{{with 0}}{{.}}{{else with false}}{{.}}{{else with `notempty`}}{{.}}{{end}}", "notempty", tVal, true},

	// Range.
	{"range []int", "{{range .SI}}-{{.}}-{{end}}", "-3--4--5-", tVal, true},
	{"range empty no else", "{{range .SIEmpty}}-{{.}}-{{end}}", "", tVal, true},
	{"range []int else", "{{range .SI}}-{{.}}-{{else}}EMPTY{{end}}", "-3--4--5-", tVal, true},
	{"range empty else", "{{range .SIEmpty}}-{{.}}-{{else}}EMPTY{{end}}", "EMPTY", tVal, true},
	{"range []int break else", "{{range .SI}}-{{.}}-{{break}}NOTREACHED{{else}}EMPTY{{end}}", "-3-", tVal, true},
	{"range []int continue else", "{{range .SI}}-{{.}}-{{continue}}NOTREACHED{{else}}EMPTY{{end}}", "-3--4--5-", tVal, true},
	{"range []bool", "{{range .SB}}-{{.}}-{{end}}", "-true--false-", tVal, true},
	{"range []int method", "{{range .SI | .MAdd .I}}-{{.}}-{{end}}", "-20--21--22-", tVal, true},
	{"range map", "{{range .MSI}}-{{.}}-{{end}}", "-1--3--2-", tVal, true},
	{"range empty map no else", "{{range .MSIEmpty}}-{{.}}-{{end}}", "", tVal, true},
	{"range map else", "{{range .MSI}}-{{.}}-{{else}}EMPTY{{end}}", "-1--3--2-", tVal, true},
	{"range empty map else", "{{range .MSIEmpty}}-{{.}}-{{else}}EMPTY{{end}}", "EMPTY", tVal, true},
	{"range empty interface", "{{range .Empty3}}-{{.}}-{{else}}EMPTY{{end}}", "-7--8-", tVal, true},
	{"range empty nil", "{{range .Empty0}}-{{.}}-{{end}}", "", tVal, true},
	{"range $x SI", "{{range $x := .SI}}<{{$x}}>{{end}}", "&lt;3>&lt;4>&lt;5>", tVal, true},
	{"range $x $y SI", "{{range $x, $y := .SI}}<{{$x}}={{$y}}>{{end}}", "&lt;0=3>&lt;1=4>&lt;2=5>", tVal, true},
	{"range $x MSIone", "{{range $x := .MSIone}}<{{$x}}>{{end}}", "&lt;1>", tVal, true},
	{"range $x $y MSIone", "{{range $x, $y := .MSIone}}<{{$x}}={{$y}}>{{end}}", "&lt;one=1>", tVal, true},
	{"range $x PSI", "{{range $x := .PSI}}<{{$x}}>{{end}}", "&lt;21>&lt;22>&lt;23>", tVal, true},
	{"declare in range", "{{range $x := .PSI}}<{{$foo:=$x}}{{$x}}>{{end}}", "&lt;21>&lt;22>&lt;23>", tVal, true},
	{"range count", `{{range $i, $x := count 5}}[{{$i}}]{{$x}}{{end}}`, "[0]a[1]b[2]c[3]d[4]e", tVal, true},
	{"range nil count", `{{range $i, $x := count 0}}{{else}}empty{{end}}`, "empty", tVal, true},

	// Cute examples.
	{"or as if true", `{{or .SI "slice is empty"}}`, "[3 4 5]", tVal, true},
	{"or as if false", `{{or .SIEmpty "slice is empty"}}`, "slice is empty", tVal, true},

	// Error handling.
	{"error method, error", "{{.MyError true}}", "", tVal, false},
	{"error method, no error", "{{.MyError false}}", "false", tVal, true},

	// Numbers
	{"decimal", "{{print 1234}}", "1234", tVal, true},
	{"decimal _", "{{print 12_34}}", "1234", tVal, true},
	{"binary", "{{print 0b101}}", "5", tVal, true},
	{"binary _", "{{print 0b_1_0_1}}", "5", tVal, true},
	{"BINARY", "{{print 0B101}}", "5", tVal, true},
	{"octal0", "{{print 0377}}", "255", tVal, true},
	{"octal", "{{print 0o377}}", "255", tVal, true},
	{"octal _", "{{print 0o_3_7_7}}", "255", tVal, true},
	{"OCTAL", "{{print 0O377}}", "255", tVal, true},
	{"hex", "{{print 0x123}}", "291", tVal, true},
	{"hex _", "{{print 0x1_23}}", "291", tVal, true},
	{"HEX", "{{print 0X123ABC}}", "1194684", tVal, true},
	{"float", "{{print 123.4}}", "123.4", tVal, true},
	{"float _", "{{print 0_0_1_2_3.4}}", "123.4", tVal, true},
	{"hex float", "{{print +0x1.ep+2}}", "7.5", tVal, true},
	{"hex float _", "{{print +0x_1.e_0p+0_2}}", "7.5", tVal, true},
	{"HEX float", "{{print +0X1.EP+2}}", "7.5", tVal, true},
	{"print multi", "{{print 1_2_3_4 7.5_00_00_00}}", "1234 7.5", tVal, true},
	{"print multi2", "{{print 1234 0x0_1.e_0p+02}}", "1234 7.5", tVal, true},

	// Fixed bugs.
	// Must separate dot and receiver; otherwise args are evaluated with dot set to variable.
	{"bug0", "{{range .MSIone}}{{if $.Method1 .}}X{{end}}{{end}}", "X", tVal, true},
	// Do not loop endlessly in indirect for non-empty interfaces.
	// The bug appears with *interface only; looped forever.
	{"bug1", "{{.Method0}}", "M0", &iVal, true},
	// Was taking address of interface field, so method set was empty.
	{"bug2", "{{$.NonEmptyInterface.Method0}}", "M0", tVal, true},
	// Struct values were not legal in with - mere oversight.
	{"bug3", "{{with $}}{{.Method0}}{{end}}", "M0", tVal, true},
	// Nil interface values in if.
	{"bug4", "{{if .Empty0}}non-nil{{else}}nil{{end}}", "nil", tVal, true},
	// Stringer.
	{"bug5", "{{.Str}}", "foozle", tVal, true},
	{"bug5a", "{{.Err}}", "erroozle", tVal, true},
	// Args need to be indirected and dereferenced sometimes.
	{"bug6a", "{{vfunc .V0 .V1}}", "vfunc", tVal, true},
	{"bug6b", "{{vfunc .V0 .V0}}", "vfunc", tVal, true},
	{"bug6c", "{{vfunc .V1 .V0}}", "vfunc", tVal, true},
	{"bug6d", "{{vfunc .V1 .V1}}", "vfunc", tVal, true},
	// Legal parse but illegal execution: non-function should have no arguments.
	{"bug7a", "{{3 2}}", "", tVal, false},
	{"bug7b", "{{$x := 1}}{{$x 2}}", "", tVal, false},
	{"bug7c", "{{$x := 1}}{{3 | $x}}", "", tVal, false},
	// Pipelined arg was not being type-checked.
	{"bug8a", "{{3|oneArg}}", "", tVal, false},
	{"bug8b", "{{4|dddArg 3}}", "", tVal, false},
	// A bug was introduced that broke map lookups for lower-case names.
	{"bug9", "{{.cause}}", "neglect", map[string]string{"cause": "neglect"}, true},
	// Field chain starting with function did not work.
	{"bug10", "{{mapOfThree.three}}-{{(mapOfThree).three}}", "3-3", 0, true},
	// Dereferencing nil pointer while evaluating function arguments should not panic. Issue 7333.
	{"bug11", "{{valueString .PS}}", "", T{}, false},
	// 0xef gave constant type float64. Issue 8622.
	{"bug12xe", "{{printf `%T` 0xef}}", "int", T{}, true},
	{"bug12xE", "{{printf `%T` 0xEE}}", "int", T{}, true},
	{"bug12Xe", "{{printf `%T` 0Xef}}", "int", T{}, true},
	{"bug12XE", "{{printf `%T` 0XEE}}", "int", T{}, true},
	// Chained nodes did not work as arguments. Issue 8473.
	{"bug13", "{{print (.Copy).I}}", "17", tVal, true},
	// Didn't protect against nil or literal values in field chains.
	{"bug14a", "{{(nil).True}}", "", tVal, false},
	{"bug14b", "{{$x := nil}}{{$x.anything}}", "", tVal, false},
	{"bug14c", `{{$x := (1.0)}}{{$y := ("hello")}}{{$x.anything}}{{$y.true}}`, "", tVal, false},
	// Didn't call validateType on function results. Issue 10800.
	{"bug15", "{{valueString returnInt}}", "", tVal, false},
	// Variadic function corner cases. Issue 10946.
	{"bug16a", "{{true|printf}}", "", tVal, false},
	{"bug16b", "{{1|printf}}", "", tVal, false},
	{"bug16c", "{{1.1|printf}}", "", tVal, false},
	{"bug16d", "{{'x'|printf}}", "", tVal, false},
	{"bug16e", "{{0i|printf}}", "", tVal, false},
	{"bug16f", "{{true|twoArgs \"xxx\"}}", "", tVal, false},
	{"bug16g", "{{\"aaa\" |twoArgs \"bbb\"}}", "twoArgs=bbbaaa", tVal, true},
	{"bug16h", "{{1|oneArg}}", "", tVal, false},
	{"bug16i", "{{\"aaa\"|oneArg}}", "oneArg=aaa", tVal, true},
	{"bug16j", "{{1+2i|printf \"%v\"}}", "(1&#43;2i)", tVal, true},
	{"bug16k", "{{\"aaa\"|printf }}", "aaa", tVal, true},
	{"bug17a", "{{.NonEmptyInterface.X}}", "x", tVal, true},
	{"bug17b", "-{{.NonEmptyInterface.Method1 1234}}-", "-1234-", tVal, true},
	{"bug17c", "{{len .NonEmptyInterfacePtS}}", "2", tVal, true},
	{"bug17d", "{{index .NonEmptyInterfacePtS 0}}", "a", tVal, true},
	{"bug17e", "{{range .NonEmptyInterfacePtS}}-{{.}}-{{end}}", "-a--b-", tVal, true},

	// More variadic function corner cases. Some runes would get evaluated
	// as constant floats instead of ints. Issue 34483.
	{"bug18a", "{{eq . '.'}}", "true", '.', true},
	{"bug18b", "{{eq . 'e'}}", "true", 'e', true},
	{"bug18c", "{{eq . 'P'}}", "true", 'P', true},
}

var cmpTestsTable = []cmpTest{
	{"eq true true", "true", true},
	{"eq true false", "false", true},
	{"eq 1+2i 1+2i", "true", true},
	{"eq 1+2i 1+3i", "false", true},
	{"eq 1.5 1.5", "true", true},
	{"eq 1.5 2.5", "false", true},
	{"eq 1 1", "true", true},
	{"eq 1 2", "false", true},
	{"eq `xy` `xy`", "true", true},
	{"eq `xy` `xyz`", "false", true},
	{"eq .Uthree .Uthree", "true", true},
	{"eq .Uthree .Ufour", "false", true},
	{"eq 3 4 5 6 3", "true", true},
	{"eq 3 4 5 6 7", "false", true},
	{"ne true true", "false", true},
	{"ne true false", "true", true},
	{"ne 1+2i 1+2i", "false", true},
	{"ne 1+2i 1+3i", "true", true},
	{"ne 1.5 1.5", "false", true},
	{"ne 1.5 2.5", "true", true},
	{"ne 1 1", "false", true},
	{"ne 1 2", "true", true},
	{"ne `xy` `xy`", "false", true},
	{"ne `xy` `xyz`", "true", true},
	{"ne .Uthree .Uthree", "false", true},
	{"ne .Uthree .Ufour", "true", true},
	{"lt 1.5 1.5", "false", true},
	{"lt 1.5 2.5", "true", true},
	{"lt 1 1", "false", true},
	{"lt 1 2", "true", true},
	{"lt `xy` `xy`", "false", true},
	{"lt `xy` `xyz`", "true", true},
	{"lt .Uthree .Uthree", "false", true},
	{"lt .Uthree .Ufour", "true", true},
	{"le 1.5 1.5", "true", true},
	{"le 1.5 2.5", "true", true},
	{"le 2.5 1.5", "false", true},
	{"le 1 1", "true", true},
	{"le 1 2", "true", true},
	{"le 2 1", "false", true},
	{"le `xy` `xy`", "true", true},
	{"le `xy` `xyz`", "true", true},
	{"le `xyz` `xy`", "false", true},
	{"le .Uthree .Uthree", "true", true},
	{"le .Uthree .Ufour", "true", true},
	{"le .Ufour .Uthree", "false", true},
	{"gt 1.5 1.5", "false", true},
	{"gt 1.5 2.5", "false", true},
	{"gt 1 1", "false", true},
	{"gt 2 1", "true", true},
	{"gt 1 2", "false", true},
	{"gt `xy` `xy`", "false", true},
	{"gt `xy` `xyz`", "false", true},
	{"gt .Uthree .Uthree", "false", true},
	{"gt .Uthree .Ufour", "false", true},
	{"gt .Ufour .Uthree", "true", true},
	{"ge 1.5 1.5", "true", true},
	{"ge 1.5 2.5", "false", true},
	{"ge 2.5 1.5", "true", true},
	{"ge 1 1", "true", true},
	{"ge 1 2", "false", true},
	{"ge 2 1", "true", true},
	{"ge `xy` `xy`", "true", true},
	{"ge `xy` `xyz`", "false", true},
	{"ge `xyz` `xy`", "true", true},
	{"ge .Uthree .Uthree", "true", true},
	{"ge .Uthree .Ufour", "false", true},
	{"ge .Ufour .Uthree", "true", true},
	// Mixing signed and unsigned integers.
	{"eq .Uthree .Three", "true", true},
	{"eq .Three .Uthree", "true", true},
	{"le .Uthree .Three", "true", true},
	{"le .Three .Uthree", "true", true},
	{"ge .Uthree .Three", "true", true},
	{"ge .Three .Uthree", "true", true},
	{"lt .Uthree .Three", "false", true},
	{"lt .Three .Uthree", "false", true},
	{"gt .Uthree .Three", "false", true},
	{"gt .Three .Uthree", "false", true},
	{"eq .Ufour .Three", "false", true},
	{"lt .Ufour .Three", "false", true},
	{"gt .Ufour .Three", "true", true},
	{"eq .NegOne .Uthree", "false", true},
	{"eq .Uthree .NegOne", "false", true},
	{"ne .NegOne .Uthree", "true", true},
	{"ne .Uthree .NegOne", "true", true},
	{"lt .NegOne .Uthree", "true", true},
	{"lt .Uthree .NegOne", "false", true},
	{"le .NegOne .Uthree", "true", true},
	{"le .Uthree .NegOne", "false", true},
	{"gt .NegOne .Uthree", "false", true},
	{"gt .Uthree .NegOne", "true", true},
	{"ge .NegOne .Uthree", "false", true},
	{"ge .Uthree .NegOne", "true", true},
	{"eq (index `x` 0) 'x'", "true", true}, // The example that triggered this rule.
	{"eq (index `x` 0) 'y'", "false", true},
	{"eq .V1 .V2", "true", true},
	{"eq .Ptr .Ptr", "true", true},
	{"eq .Ptr .NilPtr", "false", true},
	{"eq .NilPtr .NilPtr", "true", true},
	{"eq .Iface1 .Iface1", "true", true},
	{"eq .Iface1 .Iface2", "false", true},
	{"eq .Iface2 .Iface2", "true", true},
	{"eq .Map .Map", "true", true},        // Uncomparable types but nil is OK.
	{"eq .Map nil", "true", true},         // Uncomparable types but nil is OK.
	{"eq nil .Map", "true", true},         // Uncomparable types but nil is OK.
	{"eq .Map .NonNilMap", "false", true}, // Uncomparable types but nil is OK.
	// Errors
	{"eq `xy` 1", "", false},                // Different types.
	{"eq 2 2.0", "", false},                 // Different types.
	{"lt true true", "", false},             // Unordered types.
	{"lt 1+0i 1+0i", "", false},             // Unordered types.
	{"eq .Ptr 1", "", false},                // Incompatible types.
	{"eq .Ptr .NegOne", "", false},          // Incompatible types.
	{"eq .Map .V1", "", false},              // Uncomparable types.
	{"eq .NonNilMap .NonNilMap", "", false}, // Uncomparable types.
}

var multiExecTestsTable = []execTest{
	{"empty", "", "", nil, true},
	{"text", "some text", "some text", nil, true},
	{"invoke x", `{{template "x" .SI}}`, "TEXT", tVal, true},
	{"invoke x no args", `{{template "x"}}`, "TEXT", tVal, true},
	{"invoke dot int", `{{template "dot" .I}}`, "17", tVal, true},
	{"invoke dot []int", `{{template "dot" .SI}}`, "[3 4 5]", tVal, true},
	{"invoke dotV", `{{template "dotV" .U}}`, "v", tVal, true},
	{"invoke nested int", `{{template "nested" .I}}`, "17", tVal, true},
	{"variable declared by template", `{{template "nested" $x:=.SI}},{{index $x 1}}`, "[3 4 5],4", tVal, true},

	// User-defined function: test argument evaluator.
	{"testFunc literal", `{{oneArg "joe"}}`, "oneArg=joe", tVal, true},
	{"testFunc .", `{{oneArg .}}`, "oneArg=joe", "joe", true},
}
