# Number of days of inactivity before an issue becomes stale
daysUntilStale: 120
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 30
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
# Label to use when marking an issue as stale
staleLabel: 'status: stale'
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity.

  If this is a **bug** and you can still reproduce this error on the <code>main</code> branch, please reply with all of the information you have about it in order to keep the issue open.

  If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us.

  This issue will automatically be closed if no further activity occurs. Thank you for your contributions.

# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
