//! Chroma's `base16-snazzy.xml` style, converted to Rust (crate README, "Lexer and style files").

use crate::style::StyleDef;
use crate::token::TokenType as T;

#[rustfmt::skip]
pub(crate) static STYLE: StyleDef = StyleDef {
    name: "base16-snazzy",
    entries: &[
        (T::Other, "#e2e4e5"),
        (T::Error, "#ff5c57"),
        (T::Background, "bg:#282a36"),
        (T::Keyword, "#ff6ac1"),
        (T::KeywordConstant, "#ff6ac1"),
        (T::KeywordDeclaration, "#ff5c57"),
        (T::KeywordNamespace, "#ff6ac1"),
        (T::KeywordPseudo, "#ff6ac1"),
        (T::KeywordReserved, "#ff6ac1"),
        (T::KeywordType, "#9aedfe"),
        (T::Name, "#e2e4e5"),
        (T::NameAttribute, "#57c7ff"),
        (T::NameBuiltin, "#ff5c57"),
        (T::NameBuiltinPseudo, "#e2e4e5"),
        (T::NameClass, "#f3f99d"),
        (T::NameConstant, "#ff9f43"),
        (T::NameDecorator, "#ff9f43"),
        (T::NameEntity, "#e2e4e5"),
        (T::NameException, "#e2e4e5"),
        (T::NameFunction, "#57c7ff"),
        (T::NameLabel, "#ff5c57"),
        (T::NameNamespace, "#e2e4e5"),
        (T::NameOther, "#e2e4e5"),
        (T::NameTag, "#ff6ac1"),
        (T::NameVariable, "#ff5c57"),
        (T::NameVariableClass, "#ff5c57"),
        (T::NameVariableGlobal, "#ff5c57"),
        (T::NameVariableInstance, "#ff5c57"),
        (T::Literal, "#e2e4e5"),
        (T::LiteralDate, "#e2e4e5"),
        (T::LiteralString, "#5af78e"),
        (T::LiteralStringBacktick, "#5af78e"),
        (T::LiteralStringChar, "#5af78e"),
        (T::LiteralStringDoc, "#5af78e"),
        (T::LiteralStringDouble, "#5af78e"),
        (T::LiteralStringEscape, "#5af78e"),
        (T::LiteralStringHeredoc, "#5af78e"),
        (T::LiteralStringInterpol, "#5af78e"),
        (T::LiteralStringOther, "#5af78e"),
        (T::LiteralStringRegex, "#5af78e"),
        (T::LiteralStringSingle, "#5af78e"),
        (T::LiteralStringSymbol, "#5af78e"),
        (T::LiteralNumber, "#ff9f43"),
        (T::LiteralNumberBin, "#ff9f43"),
        (T::LiteralNumberFloat, "#ff9f43"),
        (T::LiteralNumberHex, "#ff9f43"),
        (T::LiteralNumberInteger, "#ff9f43"),
        (T::LiteralNumberIntegerLong, "#ff9f43"),
        (T::LiteralNumberOct, "#ff9f43"),
        (T::Operator, "#ff6ac1"),
        (T::OperatorWord, "#ff6ac1"),
        (T::Punctuation, "#e2e4e5"),
        (T::Comment, "#78787e"),
        (T::CommentHashbang, "#78787e"),
        (T::CommentMultiline, "#78787e"),
        (T::CommentSingle, "#78787e"),
        (T::CommentSpecial, "#78787e"),
        (T::CommentPreproc, "#78787e"),
        (T::Generic, "#e2e4e5"),
        (T::GenericDeleted, "#ff5c57"),
        (T::GenericEmph, "underline #e2e4e5"),
        (T::GenericError, "#ff5c57"),
        (T::GenericHeading, "bold #e2e4e5"),
        (T::GenericInserted, "bold #e2e4e5"),
        (T::GenericOutput, "#43454f"),
        (T::GenericPrompt, "#e2e4e5"),
        (T::GenericStrong, "italic #e2e4e5"),
        (T::GenericSubheading, "bold #e2e4e5"),
        (T::GenericTraceback, "#e2e4e5"),
        (T::GenericUnderline, "underline"),
        (T::Text, "#e2e4e5"),
        (T::TextWhitespace, "#e2e4e5"),
    ],
};
