//! Chroma's `catppuccin-macchiato.xml` style, converted to Rust
//! (crate README, "Lexer and style files").

use crate::style::StyleDef;
use crate::token::TokenType as T;

#[rustfmt::skip]
pub(crate) static STYLE: StyleDef = StyleDef {
    name: "catppuccin-macchiato",
    entries: &[
        (T::Background, "bg:#24273a #cad3f5"),
        (T::CodeLine, "#cad3f5"),
        (T::Error, "#ed8796"),
        (T::Other, "#cad3f5"),
        (T::LineTableTd, ""),
        (T::LineTable, ""),
        (T::LineHighlight, "bg:#494d64"),
        (T::LineNumbersTable, "#8087a2"),
        (T::LineNumbers, "#8087a2"),
        (T::Keyword, "#c6a0f6"),
        (T::KeywordReserved, "#c6a0f6"),
        (T::KeywordPseudo, "#c6a0f6"),
        (T::KeywordConstant, "#f5a97f"),
        (T::KeywordDeclaration, "#ed8796"),
        (T::KeywordNamespace, "#8bd5ca"),
        (T::KeywordType, "#ed8796"),
        (T::Name, "#cad3f5"),
        (T::NameClass, "#eed49f"),
        (T::NameConstant, "#eed49f"),
        (T::NameDecorator, "bold #8aadf4"),
        (T::NameEntity, "#8bd5ca"),
        (T::NameException, "#f5a97f"),
        (T::NameFunction, "#8aadf4"),
        (T::NameFunctionMagic, "#8aadf4"),
        (T::NameLabel, "#91d7e3"),
        (T::NameNamespace, "#f5a97f"),
        (T::NameProperty, "#f5a97f"),
        (T::NameTag, "#c6a0f6"),
        (T::NameVariable, "#f4dbd6"),
        (T::NameVariableClass, "#f4dbd6"),
        (T::NameVariableGlobal, "#f4dbd6"),
        (T::NameVariableInstance, "#f4dbd6"),
        (T::NameVariableMagic, "#f4dbd6"),
        (T::NameAttribute, "#8aadf4"),
        (T::NameBuiltin, "#91d7e3"),
        (T::NameBuiltinPseudo, "#91d7e3"),
        (T::NameOther, "#cad3f5"),
        (T::Literal, "#cad3f5"),
        (T::LiteralDate, "#cad3f5"),
        (T::LiteralString, "#a6da95"),
        (T::LiteralStringChar, "#a6da95"),
        (T::LiteralStringSingle, "#a6da95"),
        (T::LiteralStringDouble, "#a6da95"),
        (T::LiteralStringBacktick, "#a6da95"),
        (T::LiteralStringOther, "#a6da95"),
        (T::LiteralStringSymbol, "#a6da95"),
        (T::LiteralStringInterpol, "#a6da95"),
        (T::LiteralStringAffix, "#ed8796"),
        (T::LiteralStringDelimiter, "#8aadf4"),
        (T::LiteralStringEscape, "#8aadf4"),
        (T::LiteralStringRegex, "#8bd5ca"),
        (T::LiteralStringDoc, "#6e738d"),
        (T::LiteralStringHeredoc, "#6e738d"),
        (T::LiteralNumber, "#f5a97f"),
        (T::LiteralNumberBin, "#f5a97f"),
        (T::LiteralNumberHex, "#f5a97f"),
        (T::LiteralNumberInteger, "#f5a97f"),
        (T::LiteralNumberFloat, "#f5a97f"),
        (T::LiteralNumberIntegerLong, "#f5a97f"),
        (T::LiteralNumberOct, "#f5a97f"),
        (T::Operator, "bold #91d7e3"),
        (T::OperatorWord, "bold #91d7e3"),
        (T::Comment, "italic #6e738d"),
        (T::CommentSingle, "italic #6e738d"),
        (T::CommentMultiline, "italic #6e738d"),
        (T::CommentSpecial, "italic #6e738d"),
        (T::CommentHashbang, "italic #6e738d"),
        (T::CommentPreproc, "italic #6e738d"),
        (T::CommentPreprocFile, "bold #6e738d"),
        (T::Generic, "#cad3f5"),
        (T::GenericInserted, "bg:#363a4f #a6da95"),
        (T::GenericDeleted, "#ed8796 bg:#363a4f"),
        (T::GenericEmph, "italic #cad3f5"),
        (T::GenericStrong, "bold #cad3f5"),
        (T::GenericUnderline, "underline #cad3f5"),
        (T::GenericHeading, "bold #f5a97f"),
        (T::GenericSubheading, "bold #f5a97f"),
        (T::GenericOutput, "#cad3f5"),
        (T::GenericPrompt, "#cad3f5"),
        (T::GenericError, "#ed8796"),
        (T::GenericTraceback, "#ed8796"),
    ],
};
