//! Chroma's `catppuccin-latte.xml` style, converted to Rust
//! (crate README, "Lexer and style files").

use crate::style::StyleDef;
use crate::token::TokenType as T;

#[rustfmt::skip]
pub(crate) static STYLE: StyleDef = StyleDef {
    name: "catppuccin-latte",
    entries: &[
        (T::Background, "bg:#eff1f5 #4c4f69"),
        (T::CodeLine, "#4c4f69"),
        (T::Error, "#d20f39"),
        (T::Other, "#4c4f69"),
        (T::LineTableTd, ""),
        (T::LineTable, ""),
        (T::LineHighlight, "bg:#bcc0cc"),
        (T::LineNumbersTable, "#8c8fa1"),
        (T::LineNumbers, "#8c8fa1"),
        (T::Keyword, "#8839ef"),
        (T::KeywordReserved, "#8839ef"),
        (T::KeywordPseudo, "#8839ef"),
        (T::KeywordConstant, "#fe640b"),
        (T::KeywordDeclaration, "#d20f39"),
        (T::KeywordNamespace, "#179299"),
        (T::KeywordType, "#d20f39"),
        (T::Name, "#4c4f69"),
        (T::NameClass, "#df8e1d"),
        (T::NameConstant, "#df8e1d"),
        (T::NameDecorator, "bold #1e66f5"),
        (T::NameEntity, "#179299"),
        (T::NameException, "#fe640b"),
        (T::NameFunction, "#1e66f5"),
        (T::NameFunctionMagic, "#1e66f5"),
        (T::NameLabel, "#04a5e5"),
        (T::NameNamespace, "#fe640b"),
        (T::NameProperty, "#fe640b"),
        (T::NameTag, "#8839ef"),
        (T::NameVariable, "#dc8a78"),
        (T::NameVariableClass, "#dc8a78"),
        (T::NameVariableGlobal, "#dc8a78"),
        (T::NameVariableInstance, "#dc8a78"),
        (T::NameVariableMagic, "#dc8a78"),
        (T::NameAttribute, "#1e66f5"),
        (T::NameBuiltin, "#04a5e5"),
        (T::NameBuiltinPseudo, "#04a5e5"),
        (T::NameOther, "#4c4f69"),
        (T::Literal, "#4c4f69"),
        (T::LiteralDate, "#4c4f69"),
        (T::LiteralString, "#40a02b"),
        (T::LiteralStringChar, "#40a02b"),
        (T::LiteralStringSingle, "#40a02b"),
        (T::LiteralStringDouble, "#40a02b"),
        (T::LiteralStringBacktick, "#40a02b"),
        (T::LiteralStringOther, "#40a02b"),
        (T::LiteralStringSymbol, "#40a02b"),
        (T::LiteralStringInterpol, "#40a02b"),
        (T::LiteralStringAffix, "#d20f39"),
        (T::LiteralStringDelimiter, "#1e66f5"),
        (T::LiteralStringEscape, "#1e66f5"),
        (T::LiteralStringRegex, "#179299"),
        (T::LiteralStringDoc, "#9ca0b0"),
        (T::LiteralStringHeredoc, "#9ca0b0"),
        (T::LiteralNumber, "#fe640b"),
        (T::LiteralNumberBin, "#fe640b"),
        (T::LiteralNumberHex, "#fe640b"),
        (T::LiteralNumberInteger, "#fe640b"),
        (T::LiteralNumberFloat, "#fe640b"),
        (T::LiteralNumberIntegerLong, "#fe640b"),
        (T::LiteralNumberOct, "#fe640b"),
        (T::Operator, "bold #04a5e5"),
        (T::OperatorWord, "bold #04a5e5"),
        (T::Comment, "italic #9ca0b0"),
        (T::CommentSingle, "italic #9ca0b0"),
        (T::CommentMultiline, "italic #9ca0b0"),
        (T::CommentSpecial, "italic #9ca0b0"),
        (T::CommentHashbang, "italic #9ca0b0"),
        (T::CommentPreproc, "italic #9ca0b0"),
        (T::CommentPreprocFile, "bold #9ca0b0"),
        (T::Generic, "#4c4f69"),
        (T::GenericInserted, "bg:#ccd0da #40a02b"),
        (T::GenericDeleted, "#d20f39 bg:#ccd0da"),
        (T::GenericEmph, "italic #4c4f69"),
        (T::GenericStrong, "bold #4c4f69"),
        (T::GenericUnderline, "underline #4c4f69"),
        (T::GenericHeading, "bold #fe640b"),
        (T::GenericSubheading, "bold #fe640b"),
        (T::GenericOutput, "#4c4f69"),
        (T::GenericPrompt, "#4c4f69"),
        (T::GenericError, "#d20f39"),
        (T::GenericTraceback, "#d20f39"),
    ],
};
