//! Chroma's `catppuccin-mocha.xml` style, converted to Rust
//! (crate README, "Lexer and style files").

use crate::style::StyleDef;
use crate::token::TokenType as T;

#[rustfmt::skip]
pub(crate) static STYLE: StyleDef = StyleDef {
    name: "catppuccin-mocha",
    entries: &[
        (T::Background, "bg:#1e1e2e #cdd6f4"),
        (T::CodeLine, "#cdd6f4"),
        (T::Error, "#f38ba8"),
        (T::Other, "#cdd6f4"),
        (T::LineTableTd, ""),
        (T::LineTable, ""),
        (T::LineHighlight, "bg:#45475a"),
        (T::LineNumbersTable, "#7f849c"),
        (T::LineNumbers, "#7f849c"),
        (T::Keyword, "#cba6f7"),
        (T::KeywordReserved, "#cba6f7"),
        (T::KeywordPseudo, "#cba6f7"),
        (T::KeywordConstant, "#fab387"),
        (T::KeywordDeclaration, "#f38ba8"),
        (T::KeywordNamespace, "#94e2d5"),
        (T::KeywordType, "#f38ba8"),
        (T::Name, "#cdd6f4"),
        (T::NameClass, "#f9e2af"),
        (T::NameConstant, "#f9e2af"),
        (T::NameDecorator, "bold #89b4fa"),
        (T::NameEntity, "#94e2d5"),
        (T::NameException, "#fab387"),
        (T::NameFunction, "#89b4fa"),
        (T::NameFunctionMagic, "#89b4fa"),
        (T::NameLabel, "#89dceb"),
        (T::NameNamespace, "#fab387"),
        (T::NameProperty, "#fab387"),
        (T::NameTag, "#cba6f7"),
        (T::NameVariable, "#f5e0dc"),
        (T::NameVariableClass, "#f5e0dc"),
        (T::NameVariableGlobal, "#f5e0dc"),
        (T::NameVariableInstance, "#f5e0dc"),
        (T::NameVariableMagic, "#f5e0dc"),
        (T::NameAttribute, "#89b4fa"),
        (T::NameBuiltin, "#89dceb"),
        (T::NameBuiltinPseudo, "#89dceb"),
        (T::NameOther, "#cdd6f4"),
        (T::Literal, "#cdd6f4"),
        (T::LiteralDate, "#cdd6f4"),
        (T::LiteralString, "#a6e3a1"),
        (T::LiteralStringChar, "#a6e3a1"),
        (T::LiteralStringSingle, "#a6e3a1"),
        (T::LiteralStringDouble, "#a6e3a1"),
        (T::LiteralStringBacktick, "#a6e3a1"),
        (T::LiteralStringOther, "#a6e3a1"),
        (T::LiteralStringSymbol, "#a6e3a1"),
        (T::LiteralStringInterpol, "#a6e3a1"),
        (T::LiteralStringAffix, "#f38ba8"),
        (T::LiteralStringDelimiter, "#89b4fa"),
        (T::LiteralStringEscape, "#89b4fa"),
        (T::LiteralStringRegex, "#94e2d5"),
        (T::LiteralStringDoc, "#6c7086"),
        (T::LiteralStringHeredoc, "#6c7086"),
        (T::LiteralNumber, "#fab387"),
        (T::LiteralNumberBin, "#fab387"),
        (T::LiteralNumberHex, "#fab387"),
        (T::LiteralNumberInteger, "#fab387"),
        (T::LiteralNumberFloat, "#fab387"),
        (T::LiteralNumberIntegerLong, "#fab387"),
        (T::LiteralNumberOct, "#fab387"),
        (T::Operator, "bold #89dceb"),
        (T::OperatorWord, "bold #89dceb"),
        (T::Comment, "italic #6c7086"),
        (T::CommentSingle, "italic #6c7086"),
        (T::CommentMultiline, "italic #6c7086"),
        (T::CommentSpecial, "italic #6c7086"),
        (T::CommentHashbang, "italic #6c7086"),
        (T::CommentPreproc, "italic #6c7086"),
        (T::CommentPreprocFile, "bold #6c7086"),
        (T::Generic, "#cdd6f4"),
        (T::GenericInserted, "bg:#313244 #a6e3a1"),
        (T::GenericDeleted, "#f38ba8 bg:#313244"),
        (T::GenericEmph, "italic #cdd6f4"),
        (T::GenericStrong, "bold #cdd6f4"),
        (T::GenericUnderline, "underline #cdd6f4"),
        (T::GenericHeading, "bold #fab387"),
        (T::GenericSubheading, "bold #fab387"),
        (T::GenericOutput, "#cdd6f4"),
        (T::GenericPrompt, "#cdd6f4"),
        (T::GenericError, "#f38ba8"),
        (T::GenericTraceback, "#f38ba8"),
    ],
};
