//! Chroma's `catppuccin-frappe.xml` style, converted to Rust
//! (crate README, "Lexer and style files").

use crate::style::StyleDef;
use crate::token::TokenType as T;

#[rustfmt::skip]
pub(crate) static STYLE: StyleDef = StyleDef {
    name: "catppuccin-frappe",
    entries: &[
        (T::Background, "bg:#303446 #c6d0f5"),
        (T::CodeLine, "#c6d0f5"),
        (T::Error, "#e78284"),
        (T::Other, "#c6d0f5"),
        (T::LineTableTd, ""),
        (T::LineTable, ""),
        (T::LineHighlight, "bg:#51576d"),
        (T::LineNumbersTable, "#838ba7"),
        (T::LineNumbers, "#838ba7"),
        (T::Keyword, "#ca9ee6"),
        (T::KeywordReserved, "#ca9ee6"),
        (T::KeywordPseudo, "#ca9ee6"),
        (T::KeywordConstant, "#ef9f76"),
        (T::KeywordDeclaration, "#e78284"),
        (T::KeywordNamespace, "#81c8be"),
        (T::KeywordType, "#e78284"),
        (T::Name, "#c6d0f5"),
        (T::NameClass, "#e5c890"),
        (T::NameConstant, "#e5c890"),
        (T::NameDecorator, "bold #8caaee"),
        (T::NameEntity, "#81c8be"),
        (T::NameException, "#ef9f76"),
        (T::NameFunction, "#8caaee"),
        (T::NameFunctionMagic, "#8caaee"),
        (T::NameLabel, "#99d1db"),
        (T::NameNamespace, "#ef9f76"),
        (T::NameProperty, "#ef9f76"),
        (T::NameTag, "#ca9ee6"),
        (T::NameVariable, "#f2d5cf"),
        (T::NameVariableClass, "#f2d5cf"),
        (T::NameVariableGlobal, "#f2d5cf"),
        (T::NameVariableInstance, "#f2d5cf"),
        (T::NameVariableMagic, "#f2d5cf"),
        (T::NameAttribute, "#8caaee"),
        (T::NameBuiltin, "#99d1db"),
        (T::NameBuiltinPseudo, "#99d1db"),
        (T::NameOther, "#c6d0f5"),
        (T::Literal, "#c6d0f5"),
        (T::LiteralDate, "#c6d0f5"),
        (T::LiteralString, "#a6d189"),
        (T::LiteralStringChar, "#a6d189"),
        (T::LiteralStringSingle, "#a6d189"),
        (T::LiteralStringDouble, "#a6d189"),
        (T::LiteralStringBacktick, "#a6d189"),
        (T::LiteralStringOther, "#a6d189"),
        (T::LiteralStringSymbol, "#a6d189"),
        (T::LiteralStringInterpol, "#a6d189"),
        (T::LiteralStringAffix, "#e78284"),
        (T::LiteralStringDelimiter, "#8caaee"),
        (T::LiteralStringEscape, "#8caaee"),
        (T::LiteralStringRegex, "#81c8be"),
        (T::LiteralStringDoc, "#737994"),
        (T::LiteralStringHeredoc, "#737994"),
        (T::LiteralNumber, "#ef9f76"),
        (T::LiteralNumberBin, "#ef9f76"),
        (T::LiteralNumberHex, "#ef9f76"),
        (T::LiteralNumberInteger, "#ef9f76"),
        (T::LiteralNumberFloat, "#ef9f76"),
        (T::LiteralNumberIntegerLong, "#ef9f76"),
        (T::LiteralNumberOct, "#ef9f76"),
        (T::Operator, "bold #99d1db"),
        (T::OperatorWord, "bold #99d1db"),
        (T::Comment, "italic #737994"),
        (T::CommentSingle, "italic #737994"),
        (T::CommentMultiline, "italic #737994"),
        (T::CommentSpecial, "italic #737994"),
        (T::CommentHashbang, "italic #737994"),
        (T::CommentPreproc, "italic #737994"),
        (T::CommentPreprocFile, "bold #737994"),
        (T::Generic, "#c6d0f5"),
        (T::GenericInserted, "bg:#414559 #a6d189"),
        (T::GenericDeleted, "#e78284 bg:#414559"),
        (T::GenericEmph, "italic #c6d0f5"),
        (T::GenericStrong, "bold #c6d0f5"),
        (T::GenericUnderline, "underline #c6d0f5"),
        (T::GenericHeading, "bold #ef9f76"),
        (T::GenericSubheading, "bold #ef9f76"),
        (T::GenericOutput, "#c6d0f5"),
        (T::GenericPrompt, "#c6d0f5"),
        (T::GenericError, "#e78284"),
        (T::GenericTraceback, "#e78284"),
    ],
};
