//! Chroma's `colorful.xml` style, converted to Rust (crate README, "Lexer and style files").

use crate::style::StyleDef;
use crate::token::TokenType as T;

#[rustfmt::skip]
pub(crate) static STYLE: StyleDef = StyleDef {
    name: "colorful",
    entries: &[
        (T::Error, "#ff0000 bg:#ffaaaa"),
        (T::Background, "bg:#ffffff"),
        (T::Keyword, "bold #008800"),
        (T::KeywordPseudo, "#003388"),
        (T::KeywordType, "#333399"),
        (T::NameAttribute, "#0000cc"),
        (T::NameBuiltin, "#007020"),
        (T::NameClass, "bold #bb0066"),
        (T::NameConstant, "bold #003366"),
        (T::NameDecorator, "bold #555555"),
        (T::NameEntity, "bold #880000"),
        (T::NameException, "bold #ff0000"),
        (T::NameFunction, "bold #0066bb"),
        (T::NameLabel, "bold #997700"),
        (T::NameNamespace, "bold #0e84b5"),
        (T::NameTag, "#007700"),
        (T::NameVariable, "#996633"),
        (T::NameVariableClass, "#336699"),
        (T::NameVariableGlobal, "bold #dd7700"),
        (T::NameVariableInstance, "#3333bb"),
        (T::LiteralString, "bg:#fff0f0"),
        (T::LiteralStringChar, "#0044dd"),
        (T::LiteralStringDoc, "#dd4422"),
        (T::LiteralStringEscape, "bold #666666"),
        (T::LiteralStringInterpol, "bg:#eeeeee"),
        (T::LiteralStringOther, "#dd2200"),
        (T::LiteralStringRegex, "#000000 bg:#fff0ff"),
        (T::LiteralStringSymbol, "#aa6600"),
        (T::LiteralNumber, "bold #6600ee"),
        (T::LiteralNumberFloat, "bold #6600ee"),
        (T::LiteralNumberHex, "bold #005588"),
        (T::LiteralNumberInteger, "bold #0000dd"),
        (T::LiteralNumberOct, "bold #4400ee"),
        (T::Operator, "#333333"),
        (T::OperatorWord, "bold #000000"),
        (T::Comment, "#888888"),
        (T::CommentSpecial, "bold #cc0000"),
        (T::CommentPreproc, "#557799"),
        (T::GenericDeleted, "#a00000"),
        (T::GenericEmph, "italic"),
        (T::GenericError, "#ff0000"),
        (T::GenericHeading, "bold #000080"),
        (T::GenericInserted, "#00a000"),
        (T::GenericOutput, "#888888"),
        (T::GenericPrompt, "bold #c65d09"),
        (T::GenericStrong, "bold"),
        (T::GenericSubheading, "bold #800080"),
        (T::GenericTraceback, "#0044dd"),
        (T::GenericUnderline, "underline"),
        (T::TextWhitespace, "#bbbbbb"),
    ],
};
