//! Chroma's `doom-one.xml` style, converted to Rust (crate README, "Lexer and style files").

use crate::style::StyleDef;
use crate::token::TokenType as T;

#[rustfmt::skip]
pub(crate) static STYLE: StyleDef = StyleDef {
    name: "doom-one",
    entries: &[
        (T::Error, "#b0c4de"),
        (T::Background, "#b0c4de bg:#282c34"),
        (T::Keyword, "#c678dd"),
        (T::KeywordConstant, "bold #b756ff"),
        (T::KeywordType, "#ef8383"),
        (T::Name, "#c1abea"),
        (T::NameAttribute, "#b3d23c"),
        (T::NameBuiltin, "#ef8383"),
        (T::NameClass, "#76a9f9"),
        (T::NameConstant, "bold #b756ff"),
        (T::NameDecorator, "#e5c07b"),
        (T::NameEntity, "#bda26f"),
        (T::NameException, "bold #fd7474"),
        (T::NameFunction, "#00b1f7"),
        (T::NameLabel, "#f5a40d"),
        (T::NameNamespace, "#76a9f9"),
        (T::NameProperty, "#cebc3a"),
        (T::NameTag, "#e06c75"),
        (T::NameVariable, "#dcaeea"),
        (T::NameVariableGlobal, "bold #dcaeea"),
        (T::NameVariableInstance, "#e06c75"),
        (T::Literal, "#98c379"),
        (T::LiteralString, "#98c379"),
        (T::LiteralStringDoc, "#7e97c3"),
        (T::LiteralStringDouble, "#63c381"),
        (T::LiteralStringEscape, "bold #d26464"),
        (T::LiteralStringHeredoc, "#98c379"),
        (T::LiteralStringInterpol, "#98c379"),
        (T::LiteralStringOther, "#70b33f"),
        (T::LiteralStringRegex, "#56b6c2"),
        (T::LiteralStringSingle, "#98c379"),
        (T::LiteralStringSymbol, "#56b6c2"),
        (T::LiteralNumber, "#d19a66"),
        (T::Operator, "#c7bf54"),
        (T::OperatorWord, "bold #b756ff"),
        (T::Punctuation, "#b0c4de"),
        (T::Comment, "italic #8a93a5"),
        (T::CommentHashbang, "bold"),
        (T::Generic, "#b0c4de"),
        (T::GenericEmph, "italic"),
        (T::GenericHeading, "bold #a2cbff"),
        (T::GenericInserted, "#a6e22e"),
        (T::GenericOutput, "#a6e22e"),
        (T::GenericPrompt, "#a6e22e"),
        (T::GenericStrong, "bold"),
        (T::GenericSubheading, "#a2cbff"),
        (T::GenericTraceback, "#a2cbff"),
        (T::GenericUnderline, "underline"),
        (T::Text, "#b0c4de"),
    ],
};
