//! Chroma's `dracula.xml` style, converted to Rust (crate README, "Lexer and style files").

use crate::style::StyleDef;
use crate::token::TokenType as T;

#[rustfmt::skip]
pub(crate) static STYLE: StyleDef = StyleDef {
    name: "dracula",
    entries: &[
        (T::Other, "#f8f8f2"),
        (T::Error, "#f8f8f2"),
        (T::Background, "bg:#282a36"),
        (T::Keyword, "#ff79c6"),
        (T::KeywordConstant, "#ff79c6"),
        (T::KeywordDeclaration, "italic #8be9fd"),
        (T::KeywordNamespace, "#ff79c6"),
        (T::KeywordPseudo, "#ff79c6"),
        (T::KeywordReserved, "#ff79c6"),
        (T::KeywordType, "#8be9fd"),
        (T::Name, "#f8f8f2"),
        (T::NameAttribute, "#50fa7b"),
        (T::NameBuiltin, "italic #8be9fd"),
        (T::NameBuiltinPseudo, "#f8f8f2"),
        (T::NameClass, "#50fa7b"),
        (T::NameConstant, "#f8f8f2"),
        (T::NameDecorator, "#f8f8f2"),
        (T::NameEntity, "#f8f8f2"),
        (T::NameException, "#f8f8f2"),
        (T::NameFunction, "#50fa7b"),
        (T::NameLabel, "italic #8be9fd"),
        (T::NameNamespace, "#f8f8f2"),
        (T::NameOther, "#f8f8f2"),
        (T::NameTag, "#ff79c6"),
        (T::NameVariable, "italic #8be9fd"),
        (T::NameVariableClass, "italic #8be9fd"),
        (T::NameVariableGlobal, "italic #8be9fd"),
        (T::NameVariableInstance, "italic #8be9fd"),
        (T::Literal, "#f8f8f2"),
        (T::LiteralDate, "#f8f8f2"),
        (T::LiteralString, "#f1fa8c"),
        (T::LiteralStringBacktick, "#f1fa8c"),
        (T::LiteralStringChar, "#f1fa8c"),
        (T::LiteralStringDoc, "#f1fa8c"),
        (T::LiteralStringDouble, "#f1fa8c"),
        (T::LiteralStringEscape, "#f1fa8c"),
        (T::LiteralStringHeredoc, "#f1fa8c"),
        (T::LiteralStringInterpol, "#f1fa8c"),
        (T::LiteralStringOther, "#f1fa8c"),
        (T::LiteralStringRegex, "#f1fa8c"),
        (T::LiteralStringSingle, "#f1fa8c"),
        (T::LiteralStringSymbol, "#f1fa8c"),
        (T::LiteralNumber, "#bd93f9"),
        (T::LiteralNumberBin, "#bd93f9"),
        (T::LiteralNumberFloat, "#bd93f9"),
        (T::LiteralNumberHex, "#bd93f9"),
        (T::LiteralNumberInteger, "#bd93f9"),
        (T::LiteralNumberIntegerLong, "#bd93f9"),
        (T::LiteralNumberOct, "#bd93f9"),
        (T::Operator, "#ff79c6"),
        (T::OperatorWord, "#ff79c6"),
        (T::Punctuation, "#f8f8f2"),
        (T::Comment, "#6272a4"),
        (T::CommentHashbang, "#6272a4"),
        (T::CommentMultiline, "#6272a4"),
        (T::CommentSingle, "#6272a4"),
        (T::CommentSpecial, "#6272a4"),
        (T::CommentPreproc, "#ff79c6"),
        (T::Generic, "#f8f8f2"),
        (T::GenericDeleted, "#ff5555"),
        (T::GenericEmph, "underline #f8f8f2"),
        (T::GenericError, "#f8f8f2"),
        (T::GenericHeading, "bold #f8f8f2"),
        (T::GenericInserted, "bold #50fa7b"),
        (T::GenericOutput, "#44475a"),
        (T::GenericPrompt, "#f8f8f2"),
        (T::GenericStrong, "#f8f8f2"),
        (T::GenericSubheading, "bold #f8f8f2"),
        (T::GenericTraceback, "#f8f8f2"),
        (T::GenericUnderline, "underline"),
        (T::Text, "#f8f8f2"),
        (T::TextWhitespace, "#f8f8f2"),
    ],
};
