//! Chroma's `github-dark.xml` style, converted to Rust (crate README, "Lexer and style files").

use crate::style::StyleDef;
use crate::token::TokenType as T;

#[rustfmt::skip]
pub(crate) static STYLE: StyleDef = StyleDef {
    name: "github-dark",
    entries: &[
        (T::Error, "#f85149"),
        (T::LineHighlight, "bg:#6e7681"),
        (T::LineNumbers, "#6e7681"),
        (T::Background, "#e6edf3 bg:#0d1117"),
        (T::Keyword, "#ff7b72"),
        (T::KeywordConstant, "#79c0ff"),
        (T::KeywordPseudo, "#79c0ff"),
        (T::Name, "#e6edf3"),
        (T::NameClass, "bold #f0883e"),
        (T::NameConstant, "bold #79c0ff"),
        (T::NameDecorator, "bold #d2a8ff"),
        (T::NameEntity, "#ffa657"),
        (T::NameException, "bold #f0883e"),
        (T::NameFunction, "bold #d2a8ff"),
        (T::NameLabel, "bold #79c0ff"),
        (T::NameNamespace, "#ff7b72"),
        (T::NameProperty, "#79c0ff"),
        (T::NameTag, "#7ee787"),
        (T::NameVariable, "#79c0ff"),
        (T::Literal, "#a5d6ff"),
        (T::LiteralDate, "#79c0ff"),
        (T::LiteralStringAffix, "#79c0ff"),
        (T::LiteralStringDelimiter, "#79c0ff"),
        (T::LiteralStringEscape, "#79c0ff"),
        (T::LiteralStringHeredoc, "#79c0ff"),
        (T::LiteralStringRegex, "#79c0ff"),
        (T::Operator, "bold #ff7b72"),
        (T::Comment, "italic #8b949e"),
        (T::CommentSpecial, "bold italic #8b949e"),
        (T::CommentPreproc, "bold #8b949e"),
        (T::Generic, "#e6edf3"),
        (T::GenericDeleted, "#ffa198 bg:#490202"),
        (T::GenericEmph, "italic"),
        (T::GenericError, "#ffa198"),
        (T::GenericHeading, "bold #79c0ff"),
        (T::GenericInserted, "#56d364 bg:#0f5323"),
        (T::GenericOutput, "#8b949e"),
        (T::GenericPrompt, "#8b949e"),
        (T::GenericStrong, "bold"),
        (T::GenericSubheading, "#79c0ff"),
        (T::GenericTraceback, "#ff7b72"),
        (T::GenericUnderline, "underline"),
        (T::TextWhitespace, "#6e7681"),
    ],
};
