//! Chroma's `murphy.xml` style, converted to Rust (crate README, "Lexer and style files").

use crate::style::StyleDef;
use crate::token::TokenType as T;

#[rustfmt::skip]
pub(crate) static STYLE: StyleDef = StyleDef {
    name: "murphy",
    entries: &[
        (T::Error, "#ff0000 bg:#ffaaaa"),
        (T::Background, "bg:#ffffff"),
        (T::Keyword, "bold #228899"),
        (T::KeywordPseudo, "#0088ff"),
        (T::KeywordType, "#6666ff"),
        (T::NameAttribute, "#000077"),
        (T::NameBuiltin, "#007722"),
        (T::NameClass, "bold #ee99ee"),
        (T::NameConstant, "bold #55eedd"),
        (T::NameDecorator, "bold #555555"),
        (T::NameEntity, "#880000"),
        (T::NameException, "bold #ff0000"),
        (T::NameFunction, "bold #55eedd"),
        (T::NameLabel, "bold #997700"),
        (T::NameNamespace, "bold #0e84b5"),
        (T::NameTag, "#007700"),
        (T::NameVariable, "#003366"),
        (T::NameVariableClass, "#ccccff"),
        (T::NameVariableGlobal, "#ff8844"),
        (T::NameVariableInstance, "#aaaaff"),
        (T::LiteralString, "bg:#e0e0ff"),
        (T::LiteralStringChar, "#8888ff"),
        (T::LiteralStringDoc, "#dd4422"),
        (T::LiteralStringEscape, "bold #666666"),
        (T::LiteralStringInterpol, "bg:#eeeeee"),
        (T::LiteralStringOther, "#ff8888"),
        (T::LiteralStringRegex, "#000000 bg:#e0e0ff"),
        (T::LiteralStringSymbol, "#ffcc88"),
        (T::LiteralNumber, "bold #6600ee"),
        (T::LiteralNumberFloat, "bold #6600ee"),
        (T::LiteralNumberHex, "bold #005588"),
        (T::LiteralNumberInteger, "bold #6666ff"),
        (T::LiteralNumberOct, "bold #4400ee"),
        (T::Operator, "#333333"),
        (T::OperatorWord, "bold #000000"),
        (T::Comment, "italic #666666"),
        (T::CommentSpecial, "bold #cc0000"),
        (T::CommentPreproc, "noitalic #557799"),
        (T::GenericDeleted, "#a00000"),
        (T::GenericEmph, "italic"),
        (T::GenericError, "#ff0000"),
        (T::GenericHeading, "bold #000080"),
        (T::GenericInserted, "#00a000"),
        (T::GenericOutput, "#888888"),
        (T::GenericPrompt, "bold #c65d09"),
        (T::GenericStrong, "bold"),
        (T::GenericSubheading, "bold #800080"),
        (T::GenericTraceback, "#0044dd"),
        (T::GenericUnderline, "underline"),
        (T::TextWhitespace, "#bbbbbb"),
    ],
};
