//! Chroma's `nord.xml` style, converted to Rust (crate README, "Lexer and style files").

use crate::style::StyleDef;
use crate::token::TokenType as T;

#[rustfmt::skip]
pub(crate) static STYLE: StyleDef = StyleDef {
    name: "nord",
    entries: &[
        (T::Error, "#bf616a"),
        (T::Background, "#d8dee9 bg:#2e3440"),
        (T::Keyword, "bold #81a1c1"),
        (T::KeywordPseudo, "nobold #81a1c1"),
        (T::KeywordType, "nobold #81a1c1"),
        (T::Name, "#d8dee9"),
        (T::NameAttribute, "#8fbcbb"),
        (T::NameBuiltin, "#81a1c1"),
        (T::NameClass, "#8fbcbb"),
        (T::NameConstant, "#8fbcbb"),
        (T::NameDecorator, "#d08770"),
        (T::NameEntity, "#d08770"),
        (T::NameException, "#bf616a"),
        (T::NameFunction, "#88c0d0"),
        (T::NameLabel, "#8fbcbb"),
        (T::NameNamespace, "#8fbcbb"),
        (T::NameOther, "#d8dee9"),
        (T::NameTag, "#81a1c1"),
        (T::NameVariable, "#d8dee9"),
        (T::NameProperty, "#8fbcbb"),
        (T::LiteralString, "#a3be8c"),
        (T::LiteralStringDoc, "#616e87"),
        (T::LiteralStringEscape, "#ebcb8b"),
        (T::LiteralStringInterpol, "#a3be8c"),
        (T::LiteralStringOther, "#a3be8c"),
        (T::LiteralStringRegex, "#ebcb8b"),
        (T::LiteralStringSymbol, "#a3be8c"),
        (T::LiteralNumber, "#b48ead"),
        (T::Operator, "#81a1c1"),
        (T::OperatorWord, "bold #81a1c1"),
        (T::Punctuation, "#eceff4"),
        (T::Comment, "italic #616e87"),
        (T::CommentPreproc, "#5e81ac"),
        (T::GenericDeleted, "#bf616a"),
        (T::GenericEmph, "italic"),
        (T::GenericError, "#bf616a"),
        (T::GenericHeading, "bold #88c0d0"),
        (T::GenericInserted, "#a3be8c"),
        (T::GenericOutput, "#d8dee9"),
        (T::GenericPrompt, "bold #4c566a"),
        (T::GenericStrong, "bold"),
        (T::GenericSubheading, "bold #88c0d0"),
        (T::GenericTraceback, "#bf616a"),
        (T::TextWhitespace, "#d8dee9"),
    ],
};
