//! Chroma's `nordic.xml` style, converted to Rust (crate README, "Lexer and style files").

use crate::style::StyleDef;
use crate::token::TokenType as T;

#[rustfmt::skip]
pub(crate) static STYLE: StyleDef = StyleDef {
    name: "nordic",
    entries: &[
        (T::Error, "#C5727A"),
        (T::Background, "#BBC3D4 bg:#242933"),
        (T::Keyword, "bold #D08770"),
        (T::KeywordPseudo, "nobold #D08770"),
        (T::KeywordType, "nobold #D08770"),
        (T::Name, "#BBC3D4"),
        (T::NameAttribute, "#8FBCBB"),
        (T::NameBuiltin, "#5E81AC"),
        (T::NameClass, "#8FBCBB"),
        (T::NameConstant, "#8FBCBB"),
        (T::NameDecorator, "#D08770"),
        (T::NameEntity, "#D08770"),
        (T::NameException, "#C5727A"),
        (T::NameFunction, "#88C0D0"),
        (T::NameLabel, "#8FBCBB"),
        (T::NameNamespace, "#8FBCBB"),
        (T::NameOther, "#BBC3D4"),
        (T::NameTag, "#5E81AC"),
        (T::NameVariable, "#BBC3D4"),
        (T::NameProperty, "#8FBCBB"),
        (T::LiteralString, "#A3BE8C"),
        (T::LiteralStringDoc, "#4C566A"),
        (T::LiteralStringEscape, "#EBCB8B"),
        (T::LiteralStringInterpol, "#A3BE8C"),
        (T::LiteralStringOther, "#A3BE8C"),
        (T::LiteralStringRegex, "#EBCB8B"),
        (T::LiteralStringSymbol, "#A3BE8C"),
        (T::LiteralNumber, "#B48EAD"),
        (T::Operator, "#5E81AC"),
        (T::OperatorWord, "bold #5E81AC"),
        (T::Punctuation, "#ECEFF4"),
        (T::Comment, "italic #4C566A"),
        (T::CommentPreproc, "#5E81AC"),
        (T::GenericDeleted, "#C5727A"),
        (T::GenericEmph, "italic"),
        (T::GenericError, "#C5727A"),
        (T::GenericHeading, "bold #88C0D0"),
        (T::GenericInserted, "#A3BE8C"),
        (T::GenericOutput, "#BBC3D4"),
        (T::GenericPrompt, "bold #1E222A"),
        (T::GenericStrong, "bold"),
        (T::GenericSubheading, "bold #88C0D0"),
        (T::GenericTraceback, "#C5727A"),
        (T::TextWhitespace, "#BBC3D4"),
    ],
};
