//! Chroma's `pastie.xml` style, converted to Rust (crate README, "Lexer and style files").

use crate::style::StyleDef;
use crate::token::TokenType as T;

#[rustfmt::skip]
pub(crate) static STYLE: StyleDef = StyleDef {
    name: "pastie",
    entries: &[
        (T::Error, "#a61717 bg:#e3d2d2"),
        (T::Background, "bg:#ffffff"),
        (T::Keyword, "bold #008800"),
        (T::KeywordPseudo, "nobold"),
        (T::KeywordType, "#888888"),
        (T::NameAttribute, "#336699"),
        (T::NameBuiltin, "#003388"),
        (T::NameClass, "bold #bb0066"),
        (T::NameConstant, "bold #003366"),
        (T::NameDecorator, "#555555"),
        (T::NameException, "bold #bb0066"),
        (T::NameFunction, "bold #0066bb"),
        (T::NameLabel, "italic #336699"),
        (T::NameNamespace, "bold #bb0066"),
        (T::NameProperty, "bold #336699"),
        (T::NameTag, "bold #bb0066"),
        (T::NameVariable, "#336699"),
        (T::NameVariableClass, "#336699"),
        (T::NameVariableGlobal, "#dd7700"),
        (T::NameVariableInstance, "#3333bb"),
        (T::LiteralString, "#dd2200 bg:#fff0f0"),
        (T::LiteralStringEscape, "#0044dd"),
        (T::LiteralStringInterpol, "#3333bb"),
        (T::LiteralStringOther, "#22bb22 bg:#f0fff0"),
        (T::LiteralStringRegex, "#008800 bg:#fff0ff"),
        (T::LiteralStringSymbol, "#aa6600"),
        (T::LiteralNumber, "bold #0000dd"),
        (T::OperatorWord, "#008800"),
        (T::Comment, "#888888"),
        (T::CommentSpecial, "bold #cc0000 bg:#fff0f0"),
        (T::CommentPreproc, "bold #cc0000"),
        (T::GenericDeleted, "#000000 bg:#ffdddd"),
        (T::GenericEmph, "italic"),
        (T::GenericError, "#aa0000"),
        (T::GenericHeading, "#333333"),
        (T::GenericInserted, "#000000 bg:#ddffdd"),
        (T::GenericOutput, "#888888"),
        (T::GenericPrompt, "#555555"),
        (T::GenericStrong, "bold"),
        (T::GenericSubheading, "#666666"),
        (T::GenericTraceback, "#aa0000"),
        (T::GenericUnderline, "underline"),
        (T::TextWhitespace, "#bbbbbb"),
    ],
};
