//! Chroma's `tokyonight-night.xml` style, converted to Rust
//! (crate README, "Lexer and style files").

use crate::style::StyleDef;
use crate::token::TokenType as T;

#[rustfmt::skip]
pub(crate) static STYLE: StyleDef = StyleDef {
    name: "tokyonight-night",
    entries: &[
        (T::Background, "bg:#1a1b26 #c0caf5"),
        (T::CodeLine, "#c0caf5"),
        (T::Error, "#db4b4b"),
        (T::Other, "#c0caf5"),
        (T::LineTableTd, ""),
        (T::LineTable, ""),
        (T::LineHighlight, "bg:#414868"),
        (T::LineNumbersTable, "#a9b1d6"),
        (T::LineNumbers, "#a9b1d6"),
        (T::Keyword, "#bb9af7"),
        (T::KeywordReserved, "#bb9af7"),
        (T::KeywordPseudo, "#bb9af7"),
        (T::KeywordConstant, "#e0af68"),
        (T::KeywordDeclaration, "#9d7cd8"),
        (T::KeywordNamespace, "#7dcfff"),
        (T::KeywordType, "#41a6b5"),
        (T::Name, "#c0caf5"),
        (T::NameClass, "#ff9e64"),
        (T::NameConstant, "#ff9e64"),
        (T::NameDecorator, "bold #7aa2f7"),
        (T::NameEntity, "#7dcfff"),
        (T::NameException, "#e0af68"),
        (T::NameFunction, "#7aa2f7"),
        (T::NameFunctionMagic, "#7aa2f7"),
        (T::NameLabel, "#9ece6a"),
        (T::NameNamespace, "#e0af68"),
        (T::NameProperty, "#e0af68"),
        (T::NameTag, "#bb9af7"),
        (T::NameVariable, "#c0caf5"),
        (T::NameVariableClass, "#c0caf5"),
        (T::NameVariableGlobal, "#c0caf5"),
        (T::NameVariableInstance, "#c0caf5"),
        (T::NameVariableMagic, "#c0caf5"),
        (T::NameAttribute, "#7aa2f7"),
        (T::NameBuiltin, "#9ece6a"),
        (T::NameBuiltinPseudo, "#9ece6a"),
        (T::NameOther, "#c0caf5"),
        (T::Literal, "#c0caf5"),
        (T::LiteralDate, "#c0caf5"),
        (T::LiteralString, "#9ece6a"),
        (T::LiteralStringChar, "#9ece6a"),
        (T::LiteralStringSingle, "#9ece6a"),
        (T::LiteralStringDouble, "#9ece6a"),
        (T::LiteralStringBacktick, "#9ece6a"),
        (T::LiteralStringOther, "#9ece6a"),
        (T::LiteralStringSymbol, "#9ece6a"),
        (T::LiteralStringInterpol, "#9ece6a"),
        (T::LiteralStringAffix, "#9d7cd8"),
        (T::LiteralStringDelimiter, "#7aa2f7"),
        (T::LiteralStringEscape, "#7aa2f7"),
        (T::LiteralStringRegex, "#7dcfff"),
        (T::LiteralStringDoc, "#414868"),
        (T::LiteralStringHeredoc, "#414868"),
        (T::LiteralNumber, "#e0af68"),
        (T::LiteralNumberBin, "#e0af68"),
        (T::LiteralNumberHex, "#e0af68"),
        (T::LiteralNumberInteger, "#e0af68"),
        (T::LiteralNumberFloat, "#e0af68"),
        (T::LiteralNumberIntegerLong, "#e0af68"),
        (T::LiteralNumberOct, "#e0af68"),
        (T::Operator, "bold #9ece6a"),
        (T::OperatorWord, "bold #9ece6a"),
        (T::Comment, "italic #414868"),
        (T::CommentSingle, "italic #414868"),
        (T::CommentMultiline, "italic #414868"),
        (T::CommentSpecial, "italic #414868"),
        (T::CommentHashbang, "italic #414868"),
        (T::CommentPreproc, "italic #414868"),
        (T::CommentPreprocFile, "bold #414868"),
        (T::Generic, "#c0caf5"),
        (T::GenericInserted, "bg:#15161e #9ece6a"),
        (T::GenericDeleted, "#db4b4b bg:#15161e"),
        (T::GenericEmph, "italic #c0caf5"),
        (T::GenericStrong, "bold #c0caf5"),
        (T::GenericUnderline, "underline #c0caf5"),
        (T::GenericHeading, "bold #e0af68"),
        (T::GenericSubheading, "bold #e0af68"),
        (T::GenericOutput, "#c0caf5"),
        (T::GenericPrompt, "#c0caf5"),
        (T::GenericError, "#db4b4b"),
        (T::GenericTraceback, "#db4b4b"),
    ],
};
