//! Chroma's `tokyonight-day.xml` style, converted to Rust (crate README, "Lexer and style files").

use crate::style::StyleDef;
use crate::token::TokenType as T;

#[rustfmt::skip]
pub(crate) static STYLE: StyleDef = StyleDef {
    name: "tokyonight-day",
    entries: &[
        (T::Background, "bg:#e1e2e7 #3760bf"),
        (T::CodeLine, "#3760bf"),
        (T::Error, "#c64343"),
        (T::Other, "#3760bf"),
        (T::LineTableTd, ""),
        (T::LineTable, ""),
        (T::LineHighlight, "bg:#a1a6c5"),
        (T::LineNumbersTable, "#6172b0"),
        (T::LineNumbers, "#6172b0"),
        (T::Keyword, "#9854f1"),
        (T::KeywordReserved, "#9854f1"),
        (T::KeywordPseudo, "#9854f1"),
        (T::KeywordConstant, "#8c6c3e"),
        (T::KeywordDeclaration, "#9d7cd8"),
        (T::KeywordNamespace, "#007197"),
        (T::KeywordType, "#0db9d7"),
        (T::Name, "#3760bf"),
        (T::NameClass, "#b15c00"),
        (T::NameConstant, "#b15c00"),
        (T::NameDecorator, "bold #2e7de9"),
        (T::NameEntity, "#007197"),
        (T::NameException, "#8c6c3e"),
        (T::NameFunction, "#2e7de9"),
        (T::NameFunctionMagic, "#2e7de9"),
        (T::NameLabel, "#587539"),
        (T::NameNamespace, "#8c6c3e"),
        (T::NameProperty, "#8c6c3e"),
        (T::NameTag, "#9854f1"),
        (T::NameVariable, "#3760bf"),
        (T::NameVariableClass, "#3760bf"),
        (T::NameVariableGlobal, "#3760bf"),
        (T::NameVariableInstance, "#3760bf"),
        (T::NameVariableMagic, "#3760bf"),
        (T::NameAttribute, "#2e7de9"),
        (T::NameBuiltin, "#587539"),
        (T::NameBuiltinPseudo, "#587539"),
        (T::NameOther, "#3760bf"),
        (T::Literal, "#3760bf"),
        (T::LiteralDate, "#3760bf"),
        (T::LiteralString, "#587539"),
        (T::LiteralStringChar, "#587539"),
        (T::LiteralStringSingle, "#587539"),
        (T::LiteralStringDouble, "#587539"),
        (T::LiteralStringBacktick, "#587539"),
        (T::LiteralStringOther, "#587539"),
        (T::LiteralStringSymbol, "#587539"),
        (T::LiteralStringInterpol, "#587539"),
        (T::LiteralStringAffix, "#9d7cd8"),
        (T::LiteralStringDelimiter, "#2e7de9"),
        (T::LiteralStringEscape, "#2e7de9"),
        (T::LiteralStringRegex, "#007197"),
        (T::LiteralStringDoc, "#a1a6c5"),
        (T::LiteralStringHeredoc, "#a1a6c5"),
        (T::LiteralNumber, "#8c6c3e"),
        (T::LiteralNumberBin, "#8c6c3e"),
        (T::LiteralNumberHex, "#8c6c3e"),
        (T::LiteralNumberInteger, "#8c6c3e"),
        (T::LiteralNumberFloat, "#8c6c3e"),
        (T::LiteralNumberIntegerLong, "#8c6c3e"),
        (T::LiteralNumberOct, "#8c6c3e"),
        (T::Operator, "bold #587539"),
        (T::OperatorWord, "bold #587539"),
        (T::Comment, "italic #a1a6c5"),
        (T::CommentSingle, "italic #a1a6c5"),
        (T::CommentMultiline, "italic #a1a6c5"),
        (T::CommentSpecial, "italic #a1a6c5"),
        (T::CommentHashbang, "italic #a1a6c5"),
        (T::CommentPreproc, "italic #a1a6c5"),
        (T::CommentPreprocFile, "bold #a1a6c5"),
        (T::Generic, "#3760bf"),
        (T::GenericInserted, "bg:#e9e9ed #587539"),
        (T::GenericDeleted, "#c64343 bg:#e9e9ed"),
        (T::GenericEmph, "italic #3760bf"),
        (T::GenericStrong, "bold #3760bf"),
        (T::GenericUnderline, "underline #3760bf"),
        (T::GenericHeading, "bold #8c6c3e"),
        (T::GenericSubheading, "bold #8c6c3e"),
        (T::GenericOutput, "#3760bf"),
        (T::GenericPrompt, "#3760bf"),
        (T::GenericError, "#c64343"),
        (T::GenericTraceback, "#c64343"),
    ],
};
