//! Chroma's `tokyonight-moon.xml` style, converted to Rust (crate README, "Lexer and style files").

use crate::style::StyleDef;
use crate::token::TokenType as T;

#[rustfmt::skip]
pub(crate) static STYLE: StyleDef = StyleDef {
    name: "tokyonight-moon",
    entries: &[
        (T::Background, "bg:#222436 #c8d3f5"),
        (T::CodeLine, "#c8d3f5"),
        (T::Error, "#c53b53"),
        (T::Other, "#c8d3f5"),
        (T::LineTableTd, ""),
        (T::LineTable, ""),
        (T::LineHighlight, "bg:#444a73"),
        (T::LineNumbersTable, "#828bb8"),
        (T::LineNumbers, "#828bb8"),
        (T::Keyword, "#c099ff"),
        (T::KeywordReserved, "#c099ff"),
        (T::KeywordPseudo, "#c099ff"),
        (T::KeywordConstant, "#ffc777"),
        (T::KeywordDeclaration, "#c099ff"),
        (T::KeywordNamespace, "#86e1fc"),
        (T::KeywordType, "#4fd6be"),
        (T::Name, "#c8d3f5"),
        (T::NameClass, "#ff966c"),
        (T::NameConstant, "#ff966c"),
        (T::NameDecorator, "bold #82aaff"),
        (T::NameEntity, "#86e1fc"),
        (T::NameException, "#ffc777"),
        (T::NameFunction, "#82aaff"),
        (T::NameFunctionMagic, "#82aaff"),
        (T::NameLabel, "#c3e88d"),
        (T::NameNamespace, "#ffc777"),
        (T::NameProperty, "#ffc777"),
        (T::NameTag, "#c099ff"),
        (T::NameVariable, "#c8d3f5"),
        (T::NameVariableClass, "#c8d3f5"),
        (T::NameVariableGlobal, "#c8d3f5"),
        (T::NameVariableInstance, "#c8d3f5"),
        (T::NameVariableMagic, "#c8d3f5"),
        (T::NameAttribute, "#82aaff"),
        (T::NameBuiltin, "#c3e88d"),
        (T::NameBuiltinPseudo, "#c3e88d"),
        (T::NameOther, "#c8d3f5"),
        (T::Literal, "#c8d3f5"),
        (T::LiteralDate, "#c8d3f5"),
        (T::LiteralString, "#c3e88d"),
        (T::LiteralStringChar, "#c3e88d"),
        (T::LiteralStringSingle, "#c3e88d"),
        (T::LiteralStringDouble, "#c3e88d"),
        (T::LiteralStringBacktick, "#c3e88d"),
        (T::LiteralStringOther, "#c3e88d"),
        (T::LiteralStringSymbol, "#c3e88d"),
        (T::LiteralStringInterpol, "#c3e88d"),
        (T::LiteralStringAffix, "#c099ff"),
        (T::LiteralStringDelimiter, "#82aaff"),
        (T::LiteralStringEscape, "#82aaff"),
        (T::LiteralStringRegex, "#86e1fc"),
        (T::LiteralStringDoc, "#444a73"),
        (T::LiteralStringHeredoc, "#444a73"),
        (T::LiteralNumber, "#ffc777"),
        (T::LiteralNumberBin, "#ffc777"),
        (T::LiteralNumberHex, "#ffc777"),
        (T::LiteralNumberInteger, "#ffc777"),
        (T::LiteralNumberFloat, "#ffc777"),
        (T::LiteralNumberIntegerLong, "#ffc777"),
        (T::LiteralNumberOct, "#ffc777"),
        (T::Operator, "bold #c3e88d"),
        (T::OperatorWord, "bold #c3e88d"),
        (T::Comment, "italic #444a73"),
        (T::CommentSingle, "italic #444a73"),
        (T::CommentMultiline, "italic #444a73"),
        (T::CommentSpecial, "italic #444a73"),
        (T::CommentHashbang, "italic #444a73"),
        (T::CommentPreproc, "italic #444a73"),
        (T::CommentPreprocFile, "bold #444a73"),
        (T::Generic, "#c8d3f5"),
        (T::GenericInserted, "bg:#1b1d2b #c3e88d"),
        (T::GenericDeleted, "#c53b53 bg:#1b1d2b"),
        (T::GenericEmph, "italic #c8d3f5"),
        (T::GenericStrong, "bold #c8d3f5"),
        (T::GenericUnderline, "underline #c8d3f5"),
        (T::GenericHeading, "bold #ffc777"),
        (T::GenericSubheading, "bold #ffc777"),
        (T::GenericOutput, "#c8d3f5"),
        (T::GenericPrompt, "#c8d3f5"),
        (T::GenericError, "#c53b53"),
        (T::GenericTraceback, "#c53b53"),
    ],
};
