//! Chroma's `vulcan.xml` style, converted to Rust (crate README, "Lexer and style files").

use crate::style::StyleDef;
use crate::token::TokenType as T;

#[rustfmt::skip]
pub(crate) static STYLE: StyleDef = StyleDef {
    name: "vulcan",
    entries: &[
        (T::Other, "#c9c9c9"),
        (T::Error, "#cf5967"),
        (T::Background, "bg:#282c34"),
        (T::Keyword, "#7fbaf5"),
        (T::KeywordConstant, "#cf5967 bg:#43454f"),
        (T::KeywordDeclaration, "#7fbaf5"),
        (T::KeywordNamespace, "#bc74c4"),
        (T::KeywordPseudo, "#bc74c4"),
        (T::KeywordReserved, "#7fbaf5"),
        (T::KeywordType, "bold #57c7ff"),
        (T::Name, "#c9c9c9"),
        (T::NameAttribute, "#bc74c4"),
        (T::NameBuiltin, "#7fbaf5"),
        (T::NameBuiltinPseudo, "#7fbaf5"),
        (T::NameClass, "#ecbe7b"),
        (T::NameConstant, "#ecbe7b"),
        (T::NameDecorator, "#ecbe7b"),
        (T::NameEntity, "#c9c9c9"),
        (T::NameException, "#cf5967"),
        (T::NameFunction, "#57c7ff"),
        (T::NameLabel, "#cf5967"),
        (T::NameNamespace, "#c9c9c9"),
        (T::NameOther, "#c9c9c9"),
        (T::NameTag, "#bc74c4"),
        (T::NameVariable, "italic #bc74c4"),
        (T::NameVariableClass, "bold #57c7ff"),
        (T::NameVariableGlobal, "#ecbe7b"),
        (T::NameVariableInstance, "#57c7ff"),
        (T::Literal, "#c9c9c9"),
        (T::LiteralDate, "#57c7ff"),
        (T::LiteralString, "#82cc6a"),
        (T::LiteralStringBacktick, "#57c7ff"),
        (T::LiteralStringChar, "#57c7ff"),
        (T::LiteralStringDoc, "#82cc6a"),
        (T::LiteralStringDouble, "#82cc6a"),
        (T::LiteralStringEscape, "#56b6c2"),
        (T::LiteralStringHeredoc, "#56b6c2"),
        (T::LiteralStringInterpol, "#82cc6a"),
        (T::LiteralStringOther, "#82cc6a"),
        (T::LiteralStringRegex, "#57c7ff"),
        (T::LiteralStringSingle, "#82cc6a"),
        (T::LiteralStringSymbol, "#82cc6a"),
        (T::LiteralNumber, "#56b6c2"),
        (T::LiteralNumberBin, "#57c7ff"),
        (T::LiteralNumberFloat, "#56b6c2"),
        (T::LiteralNumberHex, "#57c7ff"),
        (T::LiteralNumberInteger, "#56b6c2"),
        (T::LiteralNumberIntegerLong, "#56b6c2"),
        (T::LiteralNumberOct, "#57c7ff"),
        (T::Operator, "#bc74c4"),
        (T::OperatorWord, "#bc74c4"),
        (T::Punctuation, "#56b6c2"),
        (T::Comment, "#3e4460"),
        (T::CommentHashbang, "italic #3e4460"),
        (T::CommentMultiline, "#3e4460"),
        (T::CommentSingle, "#3e4460"),
        (T::CommentSpecial, "italic #bc74c4"),
        (T::CommentPreproc, "#7fbaf5"),
        (T::Generic, "#c9c9c9"),
        (T::GenericDeleted, "#cf5967"),
        (T::GenericEmph, "underline #c9c9c9"),
        (T::GenericError, "bold #cf5967"),
        (T::GenericHeading, "bold #ecbe7b"),
        (T::GenericInserted, "#ecbe7b"),
        (T::GenericOutput, "#43454f"),
        (T::GenericPrompt, "#c9c9c9"),
        (T::GenericStrong, "bold #cf5967"),
        (T::GenericSubheading, "italic #cf5967"),
        (T::GenericTraceback, "#c9c9c9"),
        (T::GenericUnderline, "underline"),
        (T::Text, "#c9c9c9"),
        (T::TextWhitespace, "#c9c9c9"),
    ],
};
