project_name: neohugo
env:
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org
before:
  hooks:
    - go mod download
builds:
  -
    binary: neohugo
    id: neohugo
    ldflags: -s -w -X github.com/neohugo/neohugo/common/neohugo.buildDate={{.Date}} -X github.com/neohugo/neohugo/common/neohugo.commitHash={{ .ShortCommit }}
    env:
      - CGO_ENABLED=0
    flags:
      - -buildmode
      - exe
    goos:
      - darwin
      - linux
      - windows
      - freebsd
      - netbsd
      - openbsd
      - dragonfly
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 7
    ignore:
      - goos: darwin
        goarch: 386

  -
    binary: neohugo
    id: neohugo_extended_windows
    ldflags:
      - -s -w -X github.com/neohugo/neohugo/common/neohugo.buildDate={{.Date}} -X github.com/neohugo/neohugo/common/neohugo.commitHash={{ .ShortCommit }}
      - "-extldflags '-static'"
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    flags:
      - -buildmode
      - exe
      - -tags
      - extended
    goos:
      - windows
    goarch:
      - amd64
  - binary: neohugo
    id: neohugo_extended_darwin
    ldflags: -s -w -X github.com/neohugo/neohugo/common/neohugo.buildDate={{.Date}} -X github.com/neohugo/neohugo/common/neohugo.commitHash={{ .ShortCommit }}
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    flags:
      - -buildmode
      - exe
      - -tags
      - extended
    goos:
      - darwin
    goarch:
      - amd64
  - binary: neohugo
    id: neohugo_extended_linux
    ldflags: -s -w -X github.com/neohugo/neohugo/common/neohugo.buildDate={{.Date}} -X github.com/neohugo/neohugo/common/neohugo.commitHash={{ .ShortCommit }}
    env:
      - CGO_ENABLED=1
    flags:
      - -buildmode
      - exe
      - -tags
      - extended
    goos:
      - linux
    goarch:
      - amd64
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
checksum:
  name_template: 'checksums.txt'
release:
  prerelease: auto
snapshot:
  name_template: "{{ .Tag }}-next"
archives:
  -
    id: "neohugo"
    builds: ['neohugo']
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
    replacements:
      amd64: 64bit
      386: 32bit
      arm: ARM
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows
      openbsd: OpenBSD
      netbsd: NetBSD
      freebsd: FreeBSD
      dragonfly: DragonFlyBSD
    files:
      - README.md
      - LICENSE
  -
    id: "neohugo_extended"
    builds: ['neohugo_extended_windows', 'neohugo_extended_linux', 'neohugo_extended_darwin']
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{.ProjectName}}_extended_{{.Version}}_{{.Os}}-{{.Arch}}"
    replacements:
      amd64: 64bit
      386: 32bit
      arm: ARM
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows
      openbsd: OpenBSD
      netbsd: NetBSD
      freebsd: FreeBSD
      dragonfly: DragonFlyBSD
    files:
      - README.md
      - LICENSE

nfpms:
  -
    id: "neohugo"
    builds: ['neohugo']
    formats:
        - deb
    vendor: "neohugo"
    homepage: "https://neohugo.github.io/"
    maintainer: "Prachya Saechua <blackb1rd@blackb1rd.dev>"
    description: "hugo-fork focused on multilingual and bug fixes/refactor/cleanup."
    license: "Apache 2.0"
    file_name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
    replacements:
      amd64: 64bit
      386: 32bit
      arm: ARM
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows
      openbsd: OpenBSD
      netbsd: NetBSD
      freebsd: FreeBSD
      dragonfly: DragonFlyBSD
  -
    id: "neohugo_extended"
    builds: ['neohugo_extended_linux']
    formats:
        - deb
    vendor: "neohugo"
    homepage: "https://neohugo.github.io/"
    maintainer: "Prachya Saechua <blackb1rd@blackb1rd.dev>"
    description: "hugo-fork focused on multilingual and bug fixes/refactor/cleanup."
    license: "Apache 2.0"
    file_name_template: "{{.ProjectName}}_extended_{{.Version}}_{{.Os}}-{{.Arch}}"
    replacements:
      amd64: 64bit
      386: 32bit
      arm: ARM
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows
      openbsd: OpenBSD
      netbsd: NetBSD
      freebsd: FreeBSD
      dragonfly: DragonFlyBSD
