# GitHub:       https://github.com/neohugo/neohugo
# Website:      https://neohugo.github.io/

FROM golang:1.25 AS build

# Optionally set HUGO_BUILD_TAGS to "extended" or "nodeploy" when building like so:
#   docker build --build-arg HUGO_BUILD_TAGS=extended .
ENV HUGO_BUILD_TAGS=extended,withdeploy

ARG CGO=1
ENV CGO_ENABLED=${CGO}
ENV GOOS=linux
ENV GO111MODULE=on

WORKDIR /go/src/github.com/neohugo/neohugo

COPY . /go/src/github.com/neohugo/neohugo/

# gcc/g++ are required to build SASS libraries for extended version
RUN apt-get update && \
  apt-get install -y gcc g++ libc6-dev && \
  go install github.com/magefile/mage@latest

RUN mage neohugo && mage install

# ---

FROM node:lts

ENV MOZJPEG_VERSION="4.1.1"

LABEL description="Docker container for building static sites with the neohugo static site generator with extended."
LABEL maintainer="Prachya Saechua<blackb1rd@blackb1rd.dev>"

COPY --from=build /go/bin/neohugo /usr/bin/neohugo

# libc6-compat & libstdc++ are required for extended SASS libraries
# ca-certificates are required to fetch outside resources (like Twitter oEmbeds)
RUN DEBIAN_FRONTEND=noninteractive \
  && BUILD_PACKAGES="autoconf automake binutils build-essential cmake curl g++ gcc git gnupg gzip libtool make nasm pkg-config tar xz-utils" \
  && apt-get update \
  && apt-get install -y --no-install-recommends \
  bash \
  ca-certificates \
  exiftool \
  libpng-dev \
  libstdc++6 \
  libwebp-dev \
  webp \
  openssh-client \
  pngquant \
  rsync \
  zlib1g-dev \
  $BUILD_PACKAGES \
  && deluser --remove-home node \
  && addgroup --system --gid 1000 neohugo \
  && adduser --system --uid 1000 --ingroup neohugo --home /src neohugo \
  && curl -L https://github.com/mozilla/mozjpeg/archive/v${MOZJPEG_VERSION}.tar.gz | tar -xz \
  && cd mozjpeg-${MOZJPEG_VERSION} \
  && cmake -DCMAKE_BUILD_TYPE=Release . \
  && make install && cd .. \
  && rm -rf mozjpeg-${MOZJPEG_VERSION} \
  && apt-get purge -y --auto-remove $BUILD_PACKAGES \
  && rm -rf /var/lib/apt/lists/* \
  && /opt/mozjpeg/bin/cjpeg -version \
  && cwebp \
  && neohugo version

ENV PATH="${PATH}:/opt/mozjpeg/bin"

WORKDIR /src
# Expose port for live server
EXPOSE 1313
