//! Chroma's `haxe.xml` lexer, converted to Rust (crate README, "Lexer and style files").

use crate::chroma::defs::prelude::*;

#[rustfmt::skip]
pub(crate) static LEXER: LexerDef = LexerDef {
    file: "haxe",
    config: ConfigDef {
        name: "Haxe",
        aliases: &["hx", "haxe", "hxsl"],
        filenames: &["*.hx", "*.hxsl"],
        mime_types: &["text/haxe", "text/x-haxe", "text/x-hx"],
        dot_all: true,
        ..ConfigDef::EMPTY
    },
    states: &[
        ("abstract", &[
            include("spaces"),
            rule("").mutators(&[M::Pop(1), M::Push(&["abstract-body"]), M::Push(&["abstract-relation"]), M::Push(&["abstract-opaque"]), M::Push(&["type-param-constraint"]), M::Push(&["type-name"])]),
        ]),
        ("abstract-body", &[
            include("spaces"),
            rule(r"\{").token(T::Punctuation).push(&["#pop", "class-body"]),
        ]),
        ("abstract-opaque", &[
            include("spaces"),
            rule(r"\(").token(T::Punctuation).push(&["#pop", "parenthesis-close", "type"]),
            rule("").mutators(&[M::Pop(1)]),
        ]),
        ("abstract-relation", &[
            include("spaces"),
            rule(r"(?:to|from)").token(T::KeywordDeclaration).push(&["type"]),
            rule(r",").token(T::Punctuation),
            rule("").mutators(&[M::Pop(1)]),
        ]),
        ("array-access", &[
            include("spaces"),
            rule("").mutators(&[M::Pop(1), M::Push(&["array-access-close"]), M::Push(&["expr"])]),
        ]),
        ("array-access-close", &[
            include("spaces"),
            rule(r"\]").token(T::Punctuation).pop(1),
        ]),
        ("array-decl", &[
            include("spaces"),
            rule(r"\]").token(T::Punctuation).pop(1),
            rule("").mutators(&[M::Pop(1), M::Push(&["array-decl-sep"]), M::Push(&["expr"])]),
        ]),
        ("array-decl-sep", &[
            include("spaces"),
            rule(r"\]").token(T::Punctuation).pop(1),
            rule(r",").token(T::Punctuation).push(&["#pop", "array-decl"]),
        ]),
        ("assign", &[
            include("spaces"),
            rule(r"=").token(T::Operator).push(&["#pop", "expr"]),
            rule("").mutators(&[M::Pop(1)]),
        ]),
        ("block", &[
            include("spaces"),
            rule(r"\}").token(T::Punctuation).pop(1),
            rule("").mutators(&[M::Push(&["expr-statement"])]),
        ]),
        ("bracket", &[
            include("spaces"),
            rule(r"(?!(?:\$\s*[a-z]\b|\$(?!(?:_*[a-z]\w*|_+[0-9]\w*|_*[A-Z]\w*|_+|\$\w+))))(?!(?:function|class|static|var|if|else|while|do|for|break|return|continue|extends|implements|import|switch|case|default|public|private|try|untyped|catch|new|this|throw|extern|enum|in|interface|cast|override|dynamic|typedef|package|inline|using|null|true|false|abstract)\b)(?:_*[a-z]\w*|_+[0-9]\w*|_*[A-Z]\w*|_+|\$\w+)").token(T::Name).push(&["#pop", "bracket-check"]),
            rule(r"'").token(T::LiteralStringSingle).push(&["#pop", "bracket-check", "string-single"]),
            rule(r#"""#).token(T::LiteralStringDouble).push(&["#pop", "bracket-check", "string-double"]),
            rule("").mutators(&[M::Pop(1), M::Push(&["block"])]),
        ]),
        ("bracket-check", &[
            include("spaces"),
            rule(r":").token(T::Punctuation).push(&["#pop", "object-sep", "expr"]),
            rule("").mutators(&[M::Pop(1), M::Push(&["block"]), M::Push(&["optional-semicolon"]), M::Push(&["expr-chain"])]),
        ]),
        ("bracket-close", &[
            include("spaces"),
            rule(r"\}").token(T::Punctuation).pop(1),
        ]),
        ("bracket-open", &[
            include("spaces"),
            rule(r"\{").token(T::Punctuation).pop(1),
        ]),
        ("call", &[
            include("spaces"),
            rule(r"\)").token(T::Punctuation).pop(1),
            rule("").mutators(&[M::Pop(1), M::Push(&["call-sep"]), M::Push(&["expr"])]),
        ]),
        ("call-sep", &[
            include("spaces"),
            rule(r"\)").token(T::Punctuation).pop(1),
            rule(r",").token(T::Punctuation).push(&["#pop", "call"]),
        ]),
        ("case", &[
            include("spaces"),
            rule(r":").token(T::Punctuation).pop(1),
            rule("").mutators(&[M::Pop(1), M::Push(&["case-sep"]), M::Push(&["case-guard"]), M::Push(&["expr"])]),
        ]),
        ("case-block", &[
            include("spaces"),
            rule(r"(?!(?:case|default)\b|\})").token(T::Keyword).push(&["expr-statement"]),
            rule("").mutators(&[M::Pop(1)]),
        ]),
        ("case-guard", &[
            include("spaces"),
            rule(r"(?:if)\b").token(T::Keyword).push(&["#pop", "parenthesis", "parenthesis-open"]),
            rule("").mutators(&[M::Pop(1)]),
        ]),
        ("case-sep", &[
            include("spaces"),
            rule(r":").token(T::Punctuation).pop(1),
            rule(r",").token(T::Punctuation).push(&["#pop", "case"]),
        ]),
        ("cast", &[
            include("spaces"),
            rule(r"\(").token(T::Punctuation).push(&["#pop", "parenthesis-close", "cast-type", "expr"]),
            rule("").mutators(&[M::Pop(1), M::Push(&["expr"])]),
        ]),
        ("cast-type", &[
            include("spaces"),
            rule(r",").token(T::Punctuation).push(&["#pop", "type"]),
            rule("").mutators(&[M::Pop(1)]),
        ]),
        ("catch", &[
            include("spaces"),
            rule(r"(?:catch)\b").token(T::Keyword).push(&["expr", "function-param", "parenthesis-open"]),
            rule("").mutators(&[M::Pop(1)]),
        ]),
        ("class", &[
            include("spaces"),
            rule("").mutators(&[M::Pop(1), M::Push(&["class-body"]), M::Push(&["bracket-open"]), M::Push(&["extends"]), M::Push(&["type-param-constraint"]), M::Push(&["type-name"])]),
        ]),
        ("class-body", &[
            include("spaces"),
            include("meta"),
            rule(r"\}").token(T::Punctuation).pop(1),
            rule(r"(?:static|public|private|override|dynamic|inline|macro)\b").token(T::KeywordDeclaration),
            rule("").mutators(&[M::Push(&["class-member"])]),
        ]),
        ("class-member", &[
            include("spaces"),
            rule(r"(var)\b").token(T::KeywordDeclaration).push(&["#pop", "optional-semicolon", "var"]),
            rule(r"(function)\b").token(T::KeywordDeclaration).push(&["#pop", "optional-semicolon", "class-method"]),
        ]),
        ("class-method", &[
            include("spaces"),
            rule(r"(?:_*[a-z]\w*|_+[0-9]\w*|_*[A-Z]\w*|_+|\$\w+)").token(T::NameFunction).push(&["#pop", "optional-expr", "flag", "function-param", "parenthesis-open", "type-param-constraint"]),
        ]),
        ("colon", &[
            include("spaces"),
            rule(r":").token(T::Punctuation).pop(1),
        ]),
        ("comma", &[
            include("spaces"),
            rule(r",").token(T::Punctuation).pop(1),
        ]),
        ("do", &[
            include("spaces"),
            rule("").mutators(&[M::Pop(1), M::Push(&["do-while"]), M::Push(&["expr"])]),
        ]),
        ("do-while", &[
            include("spaces"),
            rule(r"(?:while)\b").token(T::Keyword).push(&["#pop", "parenthesis", "parenthesis-open"]),
        ]),
        ("dollar", &[
            include("spaces"),
            rule(r"\{").token(T::Punctuation).push(&["#pop", "expr-chain", "bracket-close", "expr"]),
            rule("").mutators(&[M::Pop(1), M::Push(&["expr-chain"])]),
        ]),
        ("else", &[
            include("spaces"),
            rule(r"(?:else)\b").token(T::Keyword).push(&["#pop", "expr"]),
            rule("").mutators(&[M::Pop(1)]),
        ]),
        ("enum", &[
            include("spaces"),
            rule("").mutators(&[M::Pop(1), M::Push(&["enum-body"]), M::Push(&["bracket-open"]), M::Push(&["type-param-constraint"]), M::Push(&["type-name"])]),
        ]),
        ("enum-body", &[
            include("spaces"),
            include("meta"),
            rule(r"\}").token(T::Punctuation).pop(1),
            rule(r"(?!(?:function|class|static|var|if|else|while|do|for|break|return|continue|extends|implements|import|switch|case|default|public|private|try|untyped|catch|new|this|throw|extern|enum|in|interface|cast|override|dynamic|typedef|package|inline|using|null|true|false|abstract)\b)(?:_*[a-z]\w*|_+[0-9]\w*|_*[A-Z]\w*|_+|\$\w+)").token(T::Name).push(&["enum-member", "type-param-constraint"]),
        ]),
        ("enum-member", &[
            include("spaces"),
            rule(r"\(").token(T::Punctuation).push(&["#pop", "semicolon", "flag", "function-param"]),
            rule("").mutators(&[M::Pop(1), M::Push(&["semicolon"]), M::Push(&["flag"])]),
        ]),
        ("expr", &[
            include("spaces"),
            rule(r"@").token(T::NameDecorator).push(&["#pop", "optional-expr", "meta-body", "meta-ident", "meta-colon"]),
            rule(r"(?:\+\+|\-\-|~(?!/)|!|\-)").token(T::Operator),
            rule(r"\(").token(T::Punctuation).push(&["#pop", "expr-chain", "parenthesis"]),
            rule(r"(?:static|public|private|override|dynamic|inline)\b").token(T::KeywordDeclaration),
            rule(r"(?:function)\b").token(T::KeywordDeclaration).push(&["#pop", "expr-chain", "function-local"]),
            rule(r"\{").token(T::Punctuation).push(&["#pop", "expr-chain", "bracket"]),
            rule(r"(?:true|false|null)\b").token(T::KeywordConstant).push(&["#pop", "expr-chain"]),
            rule(r"(?:this)\b").token(T::Keyword).push(&["#pop", "expr-chain"]),
            rule(r"(?:cast)\b").token(T::Keyword).push(&["#pop", "expr-chain", "cast"]),
            rule(r"(?:try)\b").token(T::Keyword).push(&["#pop", "catch", "expr"]),
            rule(r"(?:var)\b").token(T::KeywordDeclaration).push(&["#pop", "var"]),
            rule(r"(?:new)\b").token(T::Keyword).push(&["#pop", "expr-chain", "new"]),
            rule(r"(?:switch)\b").token(T::Keyword).push(&["#pop", "switch"]),
            rule(r"(?:if)\b").token(T::Keyword).push(&["#pop", "if"]),
            rule(r"(?:do)\b").token(T::Keyword).push(&["#pop", "do"]),
            rule(r"(?:while)\b").token(T::Keyword).push(&["#pop", "while"]),
            rule(r"(?:for)\b").token(T::Keyword).push(&["#pop", "for"]),
            rule(r"(?:untyped|throw)\b").token(T::Keyword),
            rule(r"(?:return)\b").token(T::Keyword).push(&["#pop", "optional-expr"]),
            rule(r"(?:macro)\b").token(T::Keyword).push(&["#pop", "macro"]),
            rule(r"(?:continue|break)\b").token(T::Keyword).pop(1),
            rule(r"(?:\$\s*[a-z]\b|\$(?!(?:_*[a-z]\w*|_+[0-9]\w*|_*[A-Z]\w*|_+|\$\w+)))").token(T::Name).push(&["#pop", "dollar"]),
            rule(r"(?!(?:function|class|static|var|if|else|while|do|for|break|return|continue|extends|implements|import|switch|case|default|public|private|try|untyped|catch|new|this|throw|extern|enum|in|interface|cast|override|dynamic|typedef|package|inline|using|null|true|false|abstract)\b)(?:_*[a-z]\w*|_+[0-9]\w*|_*[A-Z]\w*|_+|\$\w+)").token(T::Name).push(&["#pop", "expr-chain"]),
            rule(r"\.[0-9]+").token(T::LiteralNumberFloat).push(&["#pop", "expr-chain"]),
            rule(r"[0-9]+[eE][+\-]?[0-9]+").token(T::LiteralNumberFloat).push(&["#pop", "expr-chain"]),
            rule(r"[0-9]+\.[0-9]*[eE][+\-]?[0-9]+").token(T::LiteralNumberFloat).push(&["#pop", "expr-chain"]),
            rule(r"[0-9]+\.[0-9]+").token(T::LiteralNumberFloat).push(&["#pop", "expr-chain"]),
            rule(r"[0-9]+\.(?!(?:_*[a-z]\w*|_+[0-9]\w*|_*[A-Z]\w*|_+|\$\w+)|\.\.)").token(T::LiteralNumberFloat).push(&["#pop", "expr-chain"]),
            rule(r"0x[0-9a-fA-F]+").token(T::LiteralNumberHex).push(&["#pop", "expr-chain"]),
            rule(r"[0-9]+").token(T::LiteralNumberInteger).push(&["#pop", "expr-chain"]),
            rule(r"'").token(T::LiteralStringSingle).push(&["#pop", "expr-chain", "string-single-interpol"]),
            rule(r#"""#).token(T::LiteralStringDouble).push(&["#pop", "expr-chain", "string-double"]),
            rule(r"~/(\\\\|\\/|[^/\n])*/[gimsu]*").token(T::LiteralStringRegex).push(&["#pop", "expr-chain"]),
            rule(r"\[").token(T::Punctuation).push(&["#pop", "expr-chain", "array-decl"]),
        ]),
        ("expr-chain", &[
            include("spaces"),
            rule(r"(?:\+\+|\-\-)").token(T::Operator),
            rule(r"(?:%=|&=|\|=|\^=|\+=|\-=|\*=|/=|<<=|>\s*>\s*=|>\s*>\s*>\s*=|==|!=|<=|>\s*=|&&|\|\||<<|>>>|>\s*>|\.\.\.|<|>|%|&|\||\^|\+|\*|/|\-|=>|=)").token(T::Operator).push(&["#pop", "expr"]),
            rule(r"(?:in)\b").token(T::Keyword).push(&["#pop", "expr"]),
            rule(r"\?").token(T::Operator).push(&["#pop", "expr", "ternary", "expr"]),
            rule(r"(\.)((?!(?:function|class|static|var|if|else|while|do|for|break|return|continue|extends|implements|import|switch|case|default|public|private|try|untyped|catch|new|this|throw|extern|enum|in|interface|cast|override|dynamic|typedef|package|inline|using|null|true|false|abstract)\b)(?:_*[a-z]\w*|_+[0-9]\w*|_*[A-Z]\w*|_+|\$\w+))").groups(&[T::Punctuation, T::Name]),
            rule(r"\[").token(T::Punctuation).push(&["array-access"]),
            rule(r"\(").token(T::Punctuation).push(&["call"]),
            rule("").mutators(&[M::Pop(1)]),
        ]),
        ("expr-statement", &[
            include("spaces"),
            rule("").mutators(&[M::Pop(1), M::Push(&["optional-semicolon"]), M::Push(&["expr"])]),
        ]),
        ("extends", &[
            include("spaces"),
            rule(r"(?:extends|implements)\b").token(T::KeywordDeclaration).push(&["type"]),
            rule(r",").token(T::Punctuation),
            rule("").mutators(&[M::Pop(1)]),
        ]),
        ("flag", &[
            include("spaces"),
            rule(r":").token(T::Punctuation).push(&["#pop", "type"]),
            rule("").mutators(&[M::Pop(1)]),
        ]),
        ("for", &[
            include("spaces"),
            rule(r"\(").token(T::Punctuation).push(&["#pop", "expr", "parenthesis"]),
        ]),
        ("function-local", &[
            include("spaces"),
            rule(r"(?!(?:function|class|static|var|if|else|while|do|for|break|return|continue|extends|implements|import|switch|case|default|public|private|try|untyped|catch|new|this|throw|extern|enum|in|interface|cast|override|dynamic|typedef|package|inline|using|null|true|false|abstract)\b)(?:_*[a-z]\w*|_+[0-9]\w*|_*[A-Z]\w*|_+|\$\w+)").token(T::NameFunction).push(&["#pop", "optional-expr", "flag", "function-param", "parenthesis-open", "type-param-constraint"]),
            rule("").mutators(&[M::Pop(1), M::Push(&["optional-expr"]), M::Push(&["flag"]), M::Push(&["function-param"]), M::Push(&["parenthesis-open"]), M::Push(&["type-param-constraint"])]),
        ]),
        ("function-param", &[
            include("spaces"),
            rule(r"\)").token(T::Punctuation).pop(1),
            rule(r"\?").token(T::Punctuation),
            rule(r"(?!(?:function|class|static|var|if|else|while|do|for|break|return|continue|extends|implements|import|switch|case|default|public|private|try|untyped|catch|new|this|throw|extern|enum|in|interface|cast|override|dynamic|typedef|package|inline|using|null|true|false|abstract)\b)(?:_*[a-z]\w*|_+[0-9]\w*|_*[A-Z]\w*|_+|\$\w+)").token(T::Name).push(&["#pop", "function-param-sep", "assign", "flag"]),
        ]),
        ("function-param-sep", &[
            include("spaces"),
            rule(r"\)").token(T::Punctuation).pop(1),
            rule(r",").token(T::Punctuation).push(&["#pop", "function-param"]),
        ]),
        ("ident", &[
            include("spaces"),
            rule(r"(?:_*[a-z]\w*|_+[0-9]\w*|_*[A-Z]\w*|_+|\$\w+)").token(T::Name).pop(1),
        ]),
        ("ident-or-string", &[
            include("spaces"),
            rule(r"(?!(?:function|class|static|var|if|else|while|do|for|break|return|continue|extends|implements|import|switch|case|default|public|private|try|untyped|catch|new|this|throw|extern|enum|in|interface|cast|override|dynamic|typedef|package|inline|using|null|true|false|abstract)\b)(?:_*[a-z]\w*|_+[0-9]\w*|_*[A-Z]\w*|_+|\$\w+)").token(T::Name).pop(1),
            rule(r"'").token(T::LiteralStringSingle).push(&["#pop", "string-single"]),
            rule(r#"""#).token(T::LiteralStringDouble).push(&["#pop", "string-double"]),
        ]),
        ("if", &[
            include("spaces"),
            rule(r"\(").token(T::Punctuation).push(&["#pop", "else", "optional-semicolon", "expr", "parenthesis"]),
        ]),
        ("import", &[
            include("spaces"),
            rule(r"(?:_*[a-z]\w*|_+[0-9]\w*|_*[A-Z]\w*|_+|\$\w+)").token(T::NameNamespace),
            rule(r"\*").token(T::Keyword),
            rule(r"\.").token(T::Punctuation).push(&["import-ident"]),
            rule(r"in").token(T::KeywordNamespace).push(&["ident"]),
            rule("").mutators(&[M::Pop(1)]),
        ]),
        ("import-ident", &[
            include("spaces"),
            rule(r"\*").token(T::Keyword).pop(1),
            rule(r"(?:_*[a-z]\w*|_+[0-9]\w*|_*[A-Z]\w*|_+|\$\w+)").token(T::NameNamespace).pop(1),
        ]),
        ("macro", &[
            include("spaces"),
            include("meta"),
            rule(r":").token(T::Punctuation).push(&["#pop", "type"]),
            rule(r"(?:extern|private)\b").token(T::KeywordDeclaration),
            rule(r"(?:abstract)\b").token(T::KeywordDeclaration).push(&["#pop", "optional-semicolon", "abstract"]),
            rule(r"(?:class|interface)\b").token(T::KeywordDeclaration).push(&["#pop", "optional-semicolon", "macro-class"]),
            rule(r"(?:enum)\b").token(T::KeywordDeclaration).push(&["#pop", "optional-semicolon", "enum"]),
            rule(r"(?:typedef)\b").token(T::KeywordDeclaration).push(&["#pop", "optional-semicolon", "typedef"]),
            rule("").mutators(&[M::Pop(1), M::Push(&["expr"])]),
        ]),
        ("macro-class", &[
            rule(r"\{").token(T::Punctuation).push(&["#pop", "class-body"]),
            include("class"),
        ]),
        ("meta", &[
            include("spaces"),
            rule(r"@").token(T::NameDecorator).push(&["meta-body", "meta-ident", "meta-colon"]),
        ]),
        ("meta-body", &[
            include("spaces"),
            rule(r"\(").token(T::NameDecorator).push(&["#pop", "meta-call"]),
            rule("").mutators(&[M::Pop(1)]),
        ]),
        ("meta-call", &[
            include("spaces"),
            rule(r"\)").token(T::NameDecorator).pop(1),
            rule("").mutators(&[M::Pop(1), M::Push(&["meta-call-sep"]), M::Push(&["expr"])]),
        ]),
        ("meta-call-sep", &[
            include("spaces"),
            rule(r"\)").token(T::NameDecorator).pop(1),
            rule(r",").token(T::Punctuation).push(&["#pop", "meta-call"]),
        ]),
        ("meta-colon", &[
            include("spaces"),
            rule(r":").token(T::NameDecorator).pop(1),
            rule("").mutators(&[M::Pop(1)]),
        ]),
        ("meta-ident", &[
            include("spaces"),
            rule(r"(?:_*[a-z]\w*|_+[0-9]\w*|_*[A-Z]\w*|_+|\$\w+)").token(T::NameDecorator).pop(1),
        ]),
        ("new", &[
            include("spaces"),
            rule("").mutators(&[M::Pop(1), M::Push(&["call"]), M::Push(&["parenthesis-open"]), M::Push(&["type"])]),
        ]),
        ("object", &[
            include("spaces"),
            rule(r"\}").token(T::Punctuation).pop(1),
            rule("").mutators(&[M::Pop(1), M::Push(&["object-sep"]), M::Push(&["expr"]), M::Push(&["colon"]), M::Push(&["ident-or-string"])]),
        ]),
        ("object-sep", &[
            include("spaces"),
            rule(r"\}").token(T::Punctuation).pop(1),
            rule(r",").token(T::Punctuation).push(&["#pop", "object"]),
        ]),
        ("optional-expr", &[
            include("spaces"),
            include("expr"),
            rule("").mutators(&[M::Pop(1)]),
        ]),
        ("optional-semicolon", &[
            include("spaces"),
            rule(r";").token(T::Punctuation).pop(1),
            rule("").mutators(&[M::Pop(1)]),
        ]),
        ("package", &[
            include("spaces"),
            rule(r"(?:_*[a-z]\w*|_+[0-9]\w*|_*[A-Z]\w*|_+|\$\w+)").token(T::NameNamespace),
            rule(r"\.").token(T::Punctuation).push(&["import-ident"]),
            rule("").mutators(&[M::Pop(1)]),
        ]),
        ("parenthesis", &[
            include("spaces"),
            rule("").mutators(&[M::Pop(1), M::Push(&["parenthesis-close"]), M::Push(&["flag"]), M::Push(&["expr"])]),
        ]),
        ("parenthesis-close", &[
            include("spaces"),
            rule(r"\)").token(T::Punctuation).pop(1),
        ]),
        ("parenthesis-open", &[
            include("spaces"),
            rule(r"\(").token(T::Punctuation).pop(1),
        ]),
        ("preproc-error", &[
            rule(r"\s+").token(T::CommentPreproc),
            rule(r"'").token(T::LiteralStringSingle).push(&["#pop", "string-single"]),
            rule(r#"""#).token(T::LiteralStringDouble).push(&["#pop", "string-double"]),
            rule("").mutators(&[M::Pop(1)]),
        ]),
        ("preproc-expr", &[
            rule(r"\s+").token(T::CommentPreproc),
            rule(r"\!").token(T::CommentPreproc),
            rule(r"\(").token(T::CommentPreproc).push(&["#pop", "preproc-parenthesis"]),
            rule(r"(?:_*[a-z]\w*|_+[0-9]\w*|_*[A-Z]\w*|_+|\$\w+)").token(T::CommentPreproc).pop(1),
            rule(r"\.[0-9]+").token(T::LiteralNumberFloat),
            rule(r"[0-9]+[eE][+\-]?[0-9]+").token(T::LiteralNumberFloat),
            rule(r"[0-9]+\.[0-9]*[eE][+\-]?[0-9]+").token(T::LiteralNumberFloat),
            rule(r"[0-9]+\.[0-9]+").token(T::LiteralNumberFloat),
            rule(r"[0-9]+\.(?!(?:_*[a-z]\w*|_+[0-9]\w*|_*[A-Z]\w*|_+|\$\w+)|\.\.)").token(T::LiteralNumberFloat),
            rule(r"0x[0-9a-fA-F]+").token(T::LiteralNumberHex),
            rule(r"[0-9]+").token(T::LiteralNumberInteger),
            rule(r"'").token(T::LiteralStringSingle).push(&["#pop", "string-single"]),
            rule(r#"""#).token(T::LiteralStringDouble).push(&["#pop", "string-double"]),
        ]),
        ("preproc-expr-chain", &[
            rule(r"\s+").token(T::CommentPreproc),
            rule(r"(?:%=|&=|\|=|\^=|\+=|\-=|\*=|/=|<<=|>\s*>\s*=|>\s*>\s*>\s*=|==|!=|<=|>\s*=|&&|\|\||<<|>>>|>\s*>|\.\.\.|<|>|%|&|\||\^|\+|\*|/|\-|=>|=)").token(T::CommentPreproc).push(&["#pop", "preproc-expr-in-parenthesis"]),
            rule("").mutators(&[M::Pop(1)]),
        ]),
        ("preproc-expr-in-parenthesis", &[
            rule(r"\s+").token(T::CommentPreproc),
            rule(r"\!").token(T::CommentPreproc),
            rule(r"\(").token(T::CommentPreproc).push(&["#pop", "preproc-expr-chain", "preproc-parenthesis"]),
            rule(r"(?:_*[a-z]\w*|_+[0-9]\w*|_*[A-Z]\w*|_+|\$\w+)").token(T::CommentPreproc).push(&["#pop", "preproc-expr-chain"]),
            rule(r"\.[0-9]+").token(T::LiteralNumberFloat).push(&["#pop", "preproc-expr-chain"]),
            rule(r"[0-9]+[eE][+\-]?[0-9]+").token(T::LiteralNumberFloat).push(&["#pop", "preproc-expr-chain"]),
            rule(r"[0-9]+\.[0-9]*[eE][+\-]?[0-9]+").token(T::LiteralNumberFloat).push(&["#pop", "preproc-expr-chain"]),
            rule(r"[0-9]+\.[0-9]+").token(T::LiteralNumberFloat).push(&["#pop", "preproc-expr-chain"]),
            rule(r"[0-9]+\.(?!(?:_*[a-z]\w*|_+[0-9]\w*|_*[A-Z]\w*|_+|\$\w+)|\.\.)").token(T::LiteralNumberFloat).push(&["#pop", "preproc-expr-chain"]),
            rule(r"0x[0-9a-fA-F]+").token(T::LiteralNumberHex).push(&["#pop", "preproc-expr-chain"]),
            rule(r"[0-9]+").token(T::LiteralNumberInteger).push(&["#pop", "preproc-expr-chain"]),
            rule(r"'").token(T::LiteralStringSingle).push(&["#pop", "preproc-expr-chain", "string-single"]),
            rule(r#"""#).token(T::LiteralStringDouble).push(&["#pop", "preproc-expr-chain", "string-double"]),
        ]),
        ("preproc-parenthesis", &[
            rule(r"\s+").token(T::CommentPreproc),
            rule(r"\)").token(T::CommentPreproc).pop(1),
            rule("").mutators(&[M::Push(&["preproc-expr-in-parenthesis"])]),
        ]),
        ("prop-get-set", &[
            include("spaces"),
            rule(r"\(").token(T::Punctuation).push(&["#pop", "parenthesis-close", "prop-get-set-opt", "comma", "prop-get-set-opt"]),
            rule("").mutators(&[M::Pop(1)]),
        ]),
        ("prop-get-set-opt", &[
            include("spaces"),
            rule(r"(?:default|null|never|dynamic|get|set)\b").token(T::Keyword).pop(1),
            rule(r"(?!(?:function|class|static|var|if|else|while|do|for|break|return|continue|extends|implements|import|switch|case|default|public|private|try|untyped|catch|new|this|throw|extern|enum|in|interface|cast|override|dynamic|typedef|package|inline|using|null|true|false|abstract)\b)(?:_*[a-z]\w*|_+[0-9]\w*|_*[A-Z]\w*|_+|\$\w+)").token(T::Text).pop(1),
        ]),
        ("root", &[
            include("spaces"),
            include("meta"),
            rule(r"(?:package)\b").token(T::KeywordNamespace).push(&["semicolon", "package"]),
            rule(r"(?:import)\b").token(T::KeywordNamespace).push(&["semicolon", "import"]),
            rule(r"(?:using)\b").token(T::KeywordNamespace).push(&["semicolon", "using"]),
            rule(r"(?:extern|private)\b").token(T::KeywordDeclaration),
            rule(r"(?:abstract)\b").token(T::KeywordDeclaration).push(&["abstract"]),
            rule(r"(?:class|interface)\b").token(T::KeywordDeclaration).push(&["class"]),
            rule(r"(?:enum)\b").token(T::KeywordDeclaration).push(&["enum"]),
            rule(r"(?:typedef)\b").token(T::KeywordDeclaration).push(&["typedef"]),
            rule(r"(?=.)").token(T::Text).push(&["expr-statement"]),
        ]),
        ("semicolon", &[
            include("spaces"),
            rule(r";").token(T::Punctuation).pop(1),
        ]),
        ("spaces", &[
            rule(r"\s+").token(T::Text),
            rule(r"//[^\n\r]*").token(T::CommentSingle),
            rule(r"/\*.*?\*/").token(T::CommentMultiline),
            rule(r"(#)(if|elseif|else|end|error)\b").token(T::CommentPreproc).mutator_func("haxePreProcMutator"),
        ]),
        ("string-double", &[
            rule(r#"""#).token(T::LiteralStringDouble).pop(1),
            rule(r"\\.").token(T::LiteralStringEscape),
            rule(r".").token(T::LiteralStringDouble),
        ]),
        ("string-interpol-close", &[
            rule(r"\$(?:_*[a-z]\w*|_+[0-9]\w*|_*[A-Z]\w*|_+|\$\w+)").token(T::LiteralStringInterpol),
            rule(r"\}").token(T::LiteralStringInterpol).pop(1),
        ]),
        ("string-single", &[
            rule(r"'").token(T::LiteralStringSingle).pop(1),
            rule(r"\\.").token(T::LiteralStringEscape),
            rule(r".").token(T::LiteralStringSingle),
        ]),
        ("string-single-interpol", &[
            rule(r"\$\{").token(T::LiteralStringInterpol).push(&["string-interpol-close", "expr"]),
            rule(r"\$\$").token(T::LiteralStringEscape),
            rule(r"\$(?=(?:_*[a-z]\w*|_+[0-9]\w*|_*[A-Z]\w*|_+|\$\w+))").token(T::LiteralStringInterpol).push(&["ident"]),
            include("string-single"),
        ]),
        ("switch", &[
            include("spaces"),
            rule("").mutators(&[M::Pop(1), M::Push(&["switch-body"]), M::Push(&["bracket-open"]), M::Push(&["expr"])]),
        ]),
        ("switch-body", &[
            include("spaces"),
            rule(r"(?:case|default)\b").token(T::Keyword).push(&["case-block", "case"]),
            rule(r"\}").token(T::Punctuation).pop(1),
        ]),
        ("ternary", &[
            include("spaces"),
            rule(r":").token(T::Operator).pop(1),
        ]),
        ("type", &[
            include("spaces"),
            rule(r"\?").token(T::Punctuation),
            rule(r"(?:_*[a-z]\w*|_+[0-9]\w*|_*[A-Z]\w*|_+|\$\w+)").token(T::Name).push(&["#pop", "type-check", "type-full-name"]),
            rule(r"\{").token(T::Punctuation).push(&["#pop", "type-check", "type-struct"]),
            rule(r"\(").token(T::Punctuation).push(&["#pop", "type-check", "type-parenthesis"]),
        ]),
        ("type-check", &[
            include("spaces"),
            rule(r"->").token(T::Punctuation).push(&["#pop", "type"]),
            rule(r"<(?!=)").token(T::Punctuation).push(&["type-param"]),
            rule("").mutators(&[M::Pop(1)]),
        ]),
        ("type-full-name", &[
            include("spaces"),
            rule(r"\.").token(T::Punctuation).push(&["ident"]),
            rule("").mutators(&[M::Pop(1)]),
        ]),
        ("type-name", &[
            include("spaces"),
            rule(r"_*[A-Z]\w*").token(T::Name).pop(1),
        ]),
        ("type-param", &[
            include("spaces"),
            rule("").mutators(&[M::Pop(1), M::Push(&["type-param-sep"]), M::Push(&["type-param-type"])]),
        ]),
        ("type-param-constraint", &[
            include("spaces"),
            rule(r"<(?!=)").token(T::Punctuation).push(&["#pop", "type-param-constraint-sep", "type-param-constraint-flag", "type-name"]),
            rule("").mutators(&[M::Pop(1)]),
        ]),
        ("type-param-constraint-flag", &[
            include("spaces"),
            rule(r":").token(T::Punctuation).push(&["#pop", "type-param-constraint-flag-type"]),
            rule("").mutators(&[M::Pop(1)]),
        ]),
        ("type-param-constraint-flag-type", &[
            include("spaces"),
            rule(r"\(").token(T::Punctuation).push(&["#pop", "type-param-constraint-flag-type-sep", "type"]),
            rule("").mutators(&[M::Pop(1), M::Push(&["type"])]),
        ]),
        ("type-param-constraint-flag-type-sep", &[
            include("spaces"),
            rule(r"\)").token(T::Punctuation).pop(1),
            rule(r",").token(T::Punctuation).push(&["type"]),
        ]),
        ("type-param-constraint-sep", &[
            include("spaces"),
            rule(r">").token(T::Punctuation).pop(1),
            rule(r",").token(T::Punctuation).push(&["#pop", "type-param-constraint-sep", "type-param-constraint-flag", "type-name"]),
        ]),
        ("type-param-sep", &[
            include("spaces"),
            rule(r">").token(T::Punctuation).pop(1),
            rule(r",").token(T::Punctuation).push(&["#pop", "type-param"]),
        ]),
        ("type-param-type", &[
            rule(r"\.[0-9]+").token(T::LiteralNumberFloat).pop(1),
            rule(r"[0-9]+[eE][+\-]?[0-9]+").token(T::LiteralNumberFloat).pop(1),
            rule(r"[0-9]+\.[0-9]*[eE][+\-]?[0-9]+").token(T::LiteralNumberFloat).pop(1),
            rule(r"[0-9]+\.[0-9]+").token(T::LiteralNumberFloat).pop(1),
            rule(r"[0-9]+\.(?!(?:_*[a-z]\w*|_+[0-9]\w*|_*[A-Z]\w*|_+|\$\w+)|\.\.)").token(T::LiteralNumberFloat).pop(1),
            rule(r"0x[0-9a-fA-F]+").token(T::LiteralNumberHex).pop(1),
            rule(r"[0-9]+").token(T::LiteralNumberInteger).pop(1),
            rule(r"'").token(T::LiteralStringSingle).push(&["#pop", "string-single"]),
            rule(r#"""#).token(T::LiteralStringDouble).push(&["#pop", "string-double"]),
            rule(r"~/(\\\\|\\/|[^/\n])*/[gim]*").token(T::LiteralStringRegex).pop(1),
            rule(r"\[").token(T::Operator).push(&["#pop", "array-decl"]),
            include("type"),
        ]),
        ("type-parenthesis", &[
            include("spaces"),
            rule("").mutators(&[M::Pop(1), M::Push(&["parenthesis-close"]), M::Push(&["type"])]),
        ]),
        ("type-struct", &[
            include("spaces"),
            rule(r"\}").token(T::Punctuation).pop(1),
            rule(r"\?").token(T::Punctuation),
            rule(r">").token(T::Punctuation).push(&["comma", "type"]),
            rule(r"(?!(?:function|class|static|var|if|else|while|do|for|break|return|continue|extends|implements|import|switch|case|default|public|private|try|untyped|catch|new|this|throw|extern|enum|in|interface|cast|override|dynamic|typedef|package|inline|using|null|true|false|abstract)\b)(?:_*[a-z]\w*|_+[0-9]\w*|_*[A-Z]\w*|_+|\$\w+)").token(T::Name).push(&["#pop", "type-struct-sep", "type", "colon"]),
            include("class-body"),
        ]),
        ("type-struct-sep", &[
            include("spaces"),
            rule(r"\}").token(T::Punctuation).pop(1),
            rule(r",").token(T::Punctuation).push(&["#pop", "type-struct"]),
        ]),
        ("typedef", &[
            include("spaces"),
            rule("").mutators(&[M::Pop(1), M::Push(&["typedef-body"]), M::Push(&["type-param-constraint"]), M::Push(&["type-name"])]),
        ]),
        ("typedef-body", &[
            include("spaces"),
            rule(r"=").token(T::Operator).push(&["#pop", "optional-semicolon", "type"]),
        ]),
        ("using", &[
            include("spaces"),
            rule(r"(?:_*[a-z]\w*|_+[0-9]\w*|_*[A-Z]\w*|_+|\$\w+)").token(T::NameNamespace),
            rule(r"\.").token(T::Punctuation).push(&["import-ident"]),
            rule("").mutators(&[M::Pop(1)]),
        ]),
        ("var", &[
            include("spaces"),
            rule(r"(?!(?:function|class|static|var|if|else|while|do|for|break|return|continue|extends|implements|import|switch|case|default|public|private|try|untyped|catch|new|this|throw|extern|enum|in|interface|cast|override|dynamic|typedef|package|inline|using|null|true|false|abstract)\b)(?:_*[a-z]\w*|_+[0-9]\w*|_*[A-Z]\w*|_+|\$\w+)").token(T::Text).push(&["#pop", "var-sep", "assign", "flag", "prop-get-set"]),
        ]),
        ("var-sep", &[
            include("spaces"),
            rule(r",").token(T::Punctuation).push(&["#pop", "var"]),
            rule("").mutators(&[M::Pop(1)]),
        ]),
        ("while", &[
            include("spaces"),
            rule(r"\(").token(T::Punctuation).push(&["#pop", "expr", "parenthesis"]),
        ]),
    ],
};
