[package]
name = "neohugo-minify"
description = "Output minification"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true
autotests = false

[lib]
doctest = false

[[test]]
name = "it"
path = "tests/it/main.rs"

[lints]
workspace = true

[dependencies]
neohugo-workspace-hack.workspace = true
neohugo-base.workspace = true
neohugo-config.workspace = true
minify-html.workspace = true
lightningcss.workspace = true
oxc_allocator.workspace = true
oxc_codegen.workspace = true
oxc_minifier.workspace = true
oxc_parser.workspace = true
oxc_span.workspace = true
quick-xml.workspace = true
thiserror.workspace = true

[dev-dependencies]
neohugo-testkit.workspace = true
serde.workspace = true
serde_json.workspace = true
html5gum.workspace = true
roxmltree.workspace = true
