//! Go: parse/html/hash.go (generated by tdewolff/hasher; tables ported
//! literally).

use crate::gobytes::ByteView;

/// Go: html.Hash — perfect hashes for a predefined list of strings.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
pub struct Hash(pub u32);

// Unique hash definitions to be used instead of strings
pub const Iframe: Hash = Hash(0x6); // iframe
pub const Math: Hash = Hash(0x604); // math
pub const Plaintext: Hash = Hash(0x1e09); // plaintext
pub const Script: Hash = Hash(0xa06); // script
pub const Style: Hash = Hash(0x1405); // style
pub const Svg: Hash = Hash(0x1903); // svg
pub const Textarea: Hash = Hash(0x2308); // textarea
pub const Title: Hash = Hash(0xf05); // title
pub const Xmp: Hash = Hash(0x1c03); // xmp

const HASH_HASH0: u32 = 0x9acb0442;
const HASH_MAX_LEN: usize = 9;
const HASH_TEXT: &[u8] = b"iframemathscriptitlestylesvgxmplaintextarea";

static HASH_TABLE: [Hash; 1 << 4] = {
    let mut t = [Hash(0); 1 << 4];
    t[0x0] = Hash(0x2308); // textarea
    t[0x2] = Hash(0x6); // iframe
    t[0x4] = Hash(0xf05); // title
    t[0x5] = Hash(0x1e09); // plaintext
    t[0x7] = Hash(0x1405); // style
    t[0x8] = Hash(0x604); // math
    t[0x9] = Hash(0xa06); // script
    t[0xa] = Hash(0x1903); // svg
    t[0xb] = Hash(0x1c03); // xmp
    t
};

impl Hash {
    // Go: parse/html/hash.go:Hash.String
    /// Returns the hash' name.
    pub fn string(self) -> &'static [u8] {
        let start = (self.0 >> 8) as usize;
        let n = (self.0 & 0xff) as usize;
        if start + n > HASH_TEXT.len() {
            return b"";
        }
        &HASH_TEXT[start..start + n]
    }
}

// Go: parse/html/hash.go:ToHash
/// Returns the hash whose name is s. It returns zero if there is no such
/// hash. It is case sensitive.
pub fn to_hash<B: ByteView + ?Sized>(s: &B) -> Hash {
    if s.len() == 0 || s.len() > HASH_MAX_LEN {
        return Hash(0);
    }
    let mut h: u32 = HASH_HASH0;
    for i in 0..s.len() {
        h ^= s.at(i) as u32;
        h = h.wrapping_mul(16777619);
    }
    let i = HASH_TABLE[(h & (HASH_TABLE.len() as u32 - 1)) as usize];
    if (i.0 & 0xff) as usize == s.len() {
        let t = &HASH_TEXT[(i.0 >> 8) as usize..(i.0 >> 8) as usize + (i.0 & 0xff) as usize];
        let mut ok = true;
        for k in 0..s.len() {
            if t[k] != s.at(k) {
                ok = false; // goto NEXT
                break;
            }
        }
        if ok {
            return i;
        }
    }
    // NEXT:
    let i = HASH_TABLE[((h >> 16) & (HASH_TABLE.len() as u32 - 1)) as usize];
    if (i.0 & 0xff) as usize == s.len() {
        let t = &HASH_TEXT[(i.0 >> 8) as usize..(i.0 >> 8) as usize + (i.0 & 0xff) as usize];
        for k in 0..s.len() {
            if t[k] != s.at(k) {
                return Hash(0);
            }
        }
        return i;
    }
    Hash(0)
}
