#!/usr/bin/env python3
"""Generates crates/nh-images/src/exif_fields.rs from bep/imagemeta v0.12.0's
metadecoder_exif_fields.go: the `exifFieldsAll` table that metadecoder_exif.go's init builds
(`exifFields`, then `exifFieldsGPS` copied over it, so the GPS names win for the shared ids).

    python3 tools/go-oracle/nh-images/exiffields.py   # from the repository root

The output is identical to the checked-in file (it only depends on the module source).
"""
import os
import re
import subprocess

env = dict(os.environ, GOTOOLCHAIN="go1.27.1")
modcache = subprocess.check_output(["go", "env", "GOMODCACHE"], env=env, text=True).strip()
src = open(os.path.join(modcache, "github.com/bep/imagemeta@v0.12.0/metadecoder_exif_fields.go")).read()


def parse(name):
    m = re.search(r"var " + name + r" = map\[uint16\]string\{(.*?)\n\}", src, re.S)
    out = []
    for line in m.group(1).splitlines():
        line = line.strip()
        if not line or line.startswith("//"):
            continue
        mm = re.match(r'(0x[0-9a-fA-F]+):\s*"((?:[^"\\]|\\.)*)",?$', line)
        assert mm, line
        out.append((int(mm.group(1), 16), mm.group(2)))
    return out


allf = {}
for k, v in parse("exifFields"):
    allf[k] = v
for k, v in parse("exifFieldsGPS"):
    allf[k] = v  # maps.Copy: GPS overrides

lines = [
    "//! Tag names of `github.com/bep/imagemeta@v0.12.0/metadecoder_exif_fields.go`:",
    "//! `exifFieldsAll` = `exifFields` then `exifFieldsGPS` copied over it (GPS names win for",
    "//! the shared ids 0x0000-0x001f), as built by `metadecoder_exif.go:init`.",
    "//!",
    "//! Generated by `tools/go-oracle/nh-images/exiffields.py`; do not edit.",
    "",
    "/// Go: `exifFieldsAll[tagID]` (`\"\"` when missing).",
    "pub(crate) fn exif_field_name(tag_id: u16) -> &'static str {",
    "    match tag_id {",
]
for k in sorted(allf):
    v = allf[k]
    assert "\\" not in v
    lines.append('        0x%04x => "%s",' % (k, v))
lines += [
    '        _ => "",',
    "    }",
    "}",
    "",
    "/// Go: `maxEXIFField` (computed by `init`; not used by the decoder).",
    "#[allow(dead_code)]",
    "pub(crate) const MAX_EXIF_FIELD: u16 = 0x%04x;" % max(allf),
]
out = "crates/nh-images/src/exif_fields.rs"
with open(out, "w") as f:
    f.write("\n".join(lines) + "\n")
subprocess.check_call(["rustfmt", "--edition", "2024", out])
