package main

import (
	"bufio"
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/tdewolff/parse/v2"
	"github.com/tdewolff/parse/v2/html"
)

// listFiles returns the regular files under root with one of the extensions
// (all files if exts is empty), sorted.
func listFiles(root string, exts []string) []string {
	var files []string
	err := filepath.Walk(root, func(p string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() {
			return nil
		}
		if len(exts) == 0 {
			files = append(files, p)
			return nil
		}
		for _, e := range exts {
			if strings.HasSuffix(p, e) {
				files = append(files, p)
				break
			}
		}
		return nil
	})
	if err != nil {
		panic(err)
	}
	sort.Strings(files)
	return files
}

// corpusDigests writes "relpath\tsize\tfnv64\n" for every file of the corpus,
// where fnv64 is the FNV-1a hash of the serialized stream for kind.
func corpusDigests(kind, root, out string, exts []string) {
	f, err := os.Create(out)
	if err != nil {
		panic(err)
	}
	w := bufio.NewWriter(f)
	fmt.Fprintf(w, "# kind=%s generated by tools/go-oracle/tdewolff-parse corpus (%s)\n", kind, goVersion())
	files := listFiles(root, exts)
	for _, p := range files {
		in, err := os.ReadFile(p)
		if err != nil {
			panic(err)
		}
		rel, _ := filepath.Rel(root, p)
		s := streamFor(kind, in)
		fmt.Fprintf(w, "%s\t%d\t%016x\n", rel, len(in), fnv64a(s))
	}
	w.Flush()
	f.Close()
	fmt.Fprintf(os.Stderr, "%s: %d files\n", out, len(files))
}

// extractEmbedded lexes every HTML file under root and writes the embedded
// <style> contents, style="" attribute values, <svg>/<math> tokens, <script>
// contents and JSON-LD scripts as separate deduplicated files under outDir.
func extractEmbedded(root, outDir string) {
	kinds := []string{"css", "cssinline", "svg", "js", "json"}
	for _, k := range kinds {
		if err := os.MkdirAll(filepath.Join(outDir, k), 0o755); err != nil {
			panic(err)
		}
	}
	seen := map[string]bool{}
	counts := map[string]int{}
	write := func(kind string, data []byte) {
		name := fmt.Sprintf("%016x", fnv64a(data))
		key := kind + "/" + name
		if seen[key] {
			return
		}
		seen[key] = true
		counts[kind]++
		if err := os.WriteFile(filepath.Join(outDir, kind, name), data, 0o644); err != nil {
			panic(err)
		}
	}
	for _, p := range listFiles(root, []string{".html"}) {
		in, err := os.ReadFile(p)
		if err != nil {
			panic(err)
		}
		l := html.NewLexer(parse.NewInputBytes(cp(in)))
		var rawTag string
		var scriptType []byte
		for {
			tt, data := l.Next()
			switch tt {
			case html.ErrorToken:
				goto DONE
			case html.StartTagToken:
				rawTag = string(l.Text())
				scriptType = nil
			case html.AttributeToken:
				key := string(l.AttrKey())
				val := l.AttrVal()
				if 1 < len(val) && (val[0] == '"' || val[0] == '\'') {
					val = val[1 : len(val)-1]
				}
				if key == "style" {
					write("cssinline", parse.Copy(val))
				} else if key == "type" && rawTag == "script" {
					scriptType = parse.Copy(val)
				}
			case html.TextToken:
				if rawTag == "style" {
					write("css", parse.Copy(data))
				} else if rawTag == "script" {
					if bytes.Contains(scriptType, []byte("json")) {
						write("json", parse.Copy(data))
					} else {
						write("js", parse.Copy(data))
					}
				}
				rawTag = ""
			case html.SvgToken, html.MathToken:
				write("svg", parse.Copy(data))
			case html.EndTagToken:
				rawTag = ""
			}
		}
	DONE:
	}
	fmt.Fprintf(os.Stderr, "extracted: %v\n", counts)
}
