#!/usr/bin/env python3
"""Converts the table-driven tests of parse/v2@v2.8.1/js/*_test.go into Rust
data (crates/tdewolff-parse-js/tests/upstream_tables.rs). Go string literals
are decoded to bytes and re-emitted as Rust byte strings.

Usage: gen_upstream_tables.py GO_JS_DIR OUT.rs
"""
import re
import sys


def go_unquote(s, i):
    """Parses a Go string literal starting at s[i]; returns (bytes, next i)."""
    q = s[i]
    if q == '`':
        j = s.index('`', i + 1)
        return s[i + 1:j].replace('\r', '').encode('utf-8'), j + 1
    assert q == '"', s[i:i + 20]
    out = bytearray()
    j = i + 1
    while True:
        c = s[j]
        if c == '"':
            return bytes(out), j + 1
        if c != '\\':
            out += c.encode('utf-8')
            j += 1
            continue
        e = s[j + 1]
        simple = {'n': 10, 't': 9, 'v': 11, 'f': 12, 'r': 13, 'a': 7, 'b': 8,
                  '\\': 92, '"': 34, "'": 39}
        if e in simple:
            out.append(simple[e])
            j += 2
        elif e == 'x':
            out.append(int(s[j + 2:j + 4], 16))
            j += 4
        elif e == 'u':
            out += chr(int(s[j + 2:j + 6], 16)).encode('utf-8', 'surrogatepass')
            j += 6
        elif e == 'U':
            out += chr(int(s[j + 2:j + 10], 16)).encode('utf-8')
            j += 10
        elif e in '01234567':
            out.append(int(s[j + 1:j + 4], 8))
            j += 4
        else:
            raise ValueError('bad escape ' + e)


def parse_values(line):
    """Parses the values of a table entry line `{...},`."""
    vals = []
    i = line.index('{') + 1
    while i < len(line):
        c = line[i]
        if c in ' \t,':
            i += 1
        elif c in '"`':
            b, i = go_unquote(line, i)
            vals.append(b)
        elif line.startswith('TTs{', i):
            j = line.index('}', i)
            items = [t.strip() for t in line[i + 4:j].split(',') if t.strip()]
            vals.append(items)
            i = j + 1
        elif c == '}':
            break
        else:
            raise ValueError('unexpected %r in %s' % (line[i:i + 20], line))
    return vals


def table(src, func, start_marker):
    """Returns the entries of the first table after `func` and `start_marker`."""
    i = src.index('func ' + func + '(')
    i = src.index(start_marker, i)
    i = src.index('}{', i) + 2
    rows = []
    for line in src[i:].split('\n'):
        t = line.strip()
        if t.startswith('}') and not t.startswith('},'):
            break
        if not t.startswith('{'):
            continue
        rows.append(parse_values(t))
    return rows


def rs_bytes(b):
    out = []
    for c in b:
        if 0x20 <= c < 0x7f and c not in (0x22, 0x5c):
            out.append(chr(c))
        else:
            out.append('\\x%02x' % c)
    return 'b"' + ''.join(out) + '"'


def main():
    d, out = sys.argv[1], sys.argv[2]
    lex = open(d + '/lex_test.go').read()
    par = open(d + '/parse_test.go').read()
    astt = open(d + '/ast_test.go').read()
    w = []
    w.append('// Generated by tools/go-oracle/tdewolff-parse-js/gen_upstream_tables.py from')
    w.append('// github.com/tdewolff/parse/v2@v2.8.1/js/{lex,parse,ast}_test.go. Do not edit.')
    w.append('')
    w.append('use tdewolff_parse_js::*;')
    w.append('')

    def tok_table(name, rows):
        w.append('pub static %s: &[(&[u8], &[TokenType])] = &[' % name)
        for js, tts in rows:
            w.append('    (%s, &[%s]),' % (rs_bytes(js), ', '.join(tts)))
        w.append('];')
        w.append('')

    def str_table(name, rows, n):
        w.append('pub static %s: &[(%s)] = &[' % (name, ', '.join(['&[u8]'] * n)))
        for r in rows:
            assert len(r) == n, r
            w.append('    (%s),' % ', '.join(rs_bytes(x) for x in r))
        w.append('];')
        w.append('')

    tok_table('TOKEN_TESTS', table(lex, 'TestTokens', 'tokenTests'))
    tok_table('REGEXP_TESTS', table(lex, 'TestRegExp', 'tokenTests'))
    str_table('LEXER_ERROR_TESTS', table(lex, 'TestLexerErrors', 'tests'), 2)
    str_table('PARSE_TESTS', table(par, 'TestParse', 'tests'), 2)
    str_table('PARSE_ERROR_TESTS', table(par, 'TestParseError', 'tests'), 2)
    str_table('PARSE_SCOPE_TESTS', table(par, 'TestParseScope', 'tests'), 3)
    str_table('JS_TESTS', table(astt, 'TestJS', 'tests'), 2)
    open(out, 'w').write('\n'.join(w))


main()
