//! Ports of Go 1.27.1's own compress/flate and compress/zlib `_test.go`
//! tables that check exact output bytes (their testdata goldens were
//! generated by the same Go encoder).

use std::path::{Path, PathBuf};

use go_flate::flate::internal::{BitWriter, TokenList};
use go_flate::{Error, flate, zlib};

fn testdata(name: &str) -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/go_testdata")
        .join(name)
}

fn read(name: &str) -> Vec<u8> {
    std::fs::read(testdata(name)).unwrap_or_else(|e| panic!("{name}: {e}"))
}

// Go: compress/flate/deflate_test.go:deflateTests / TestDeflate
#[test]
fn test_deflate() {
    let tests: &[(&[u8], i32, &[u8])] = &[
        (&[], 0, &[0x3, 0x0]),
        (&[0x11], flate::BEST_COMPRESSION, &[0x12, 0x4, 0xc, 0x0]),
        (&[0x11], flate::BEST_COMPRESSION, &[0x12, 0x4, 0xc, 0x0]),
        (&[0x11], flate::BEST_COMPRESSION, &[0x12, 0x4, 0xc, 0x0]),
        (&[0x11], 0, &[0x0, 0x1, 0x0, 0xfe, 0xff, 0x11, 0x3, 0x0]),
        (
            &[0x11, 0x12],
            0,
            &[0x0, 0x2, 0x0, 0xfd, 0xff, 0x11, 0x12, 0x3, 0x0],
        ),
        (
            &[0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11],
            0,
            &[
                0x0, 0x8, 0x0, 0xf7, 0xff, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x3, 0x0,
            ],
        ),
        (&[], 1, &[0x3, 0x0]),
        (&[0x11], flate::BEST_COMPRESSION, &[0x12, 0x4, 0xc, 0x0]),
        (
            &[0x11, 0x12],
            flate::BEST_COMPRESSION,
            &[0x12, 0x14, 0x2, 0xc, 0x0],
        ),
        (
            &[0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11],
            flate::BEST_COMPRESSION,
            &[0x12, 0x84, 0x1, 0xc0, 0x0],
        ),
        (&[], 9, &[0x3, 0x0]),
        (&[0x11], 9, &[0x12, 0x4, 0xc, 0x0]),
        (&[0x11, 0x12], 9, &[0x12, 0x14, 0x2, 0xc, 0x0]),
        (
            &[0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11],
            9,
            &[0x12, 0x84, 0x1, 0xc0, 0x0],
        ),
    ];
    for (i, (input, level, out)) in tests.iter().enumerate() {
        let mut w = flate::new_writer(Vec::new(), *level).unwrap();
        w.write(input).unwrap();
        w.close().unwrap();
        assert_eq!(&w.into_inner()[..], *out, "{i}: level {level}");
    }
}

// Go: compress/flate/deflate_test.go:TestWriterClose (closed-writer errors)
#[test]
fn test_writer_close() {
    let mut zw = flate::new_writer(Vec::new(), 6).unwrap();
    assert_eq!(zw.write(b"Test").unwrap(), 4);
    zw.close().unwrap();
    let after_close = zw.get_ref().len();
    assert!(matches!(zw.write(b"Test"), Err(Error::WriterClosed)));
    assert!(matches!(zw.flush(), Err(Error::WriterClosed)));
    assert!(zw.close().is_ok());
    assert_eq!(zw.get_ref().len(), after_close, "writer wrote after close");
    assert_eq!(Error::WriterClosed.to_string(), "flate: closed writer");
}

#[test]
fn test_invalid_levels() {
    for level in [-3, 10, 100] {
        let e = flate::new_writer(Vec::new(), level).err().unwrap();
        assert_eq!(
            e.to_string(),
            format!("flate: invalid compression level {level}: want value in range [-2, 9]")
        );
        let e = zlib::new_writer_level(Vec::new(), level).err().unwrap();
        assert_eq!(
            e.to_string(),
            format!("zlib: invalid compression level: {level}")
        );
    }
}

// Go: compress/flate/huffman_bit_writer_test.go:TestBlockHuff
#[test]
fn test_block_huff() {
    let mut names: Vec<String> = std::fs::read_dir(testdata(""))
        .unwrap()
        .map(|e| e.unwrap().file_name().to_string_lossy().into_owned())
        .filter(|n| n.starts_with("huffman-") && n.ends_with(".in"))
        .collect();
    names.sort();
    assert_eq!(names.len(), 9);
    for input in names {
        let out = format!("{}.golden", input.trim_end_matches(".in"));
        let all = read(&input);
        let want = read(&out);
        let mut bw = BitWriter::new(Vec::new());
        bw.set_log_new_table_penalty(8);
        bw.write_block_huff(false, &all, false);
        bw.flush();
        assert_eq!(bw.get_ref(), &want, "{input}");

        // Test if the writer produces the same output after reset.
        bw.reset(Vec::new());
        bw.write_block_huff(false, &all, false);
        bw.flush();
        assert_eq!(bw.get_ref(), &want, "{input} after reset");

        // testWriterEOF(t, "huff", ...)
        let mut bw = BitWriter::new(Vec::new());
        bw.write_block_huff(true, &all, true);
        bw.flush();
        let b = bw.get_ref();
        assert!(
            !b.is_empty() && b[0] & 1 == 1,
            "{input}: block not marked with EOF"
        );
    }
}

struct HuffTest {
    input: String,
    want: String,
    want_no_input: String,
    tokens: Vec<u32>,
}

fn write_block_tests() -> Vec<HuffTest> {
    let text = std::fs::read_to_string(testdata("writeblock_tokens.txt")).unwrap();
    text.lines()
        .map(|l| {
            let f: Vec<&str> = l.split(' ').collect();
            let dash = |s: &str| {
                if s == "-" {
                    String::new()
                } else {
                    s.to_string()
                }
            };
            HuffTest {
                input: dash(f[0]),
                want: dash(f[1]),
                want_no_input: f[2].to_string(),
                tokens: f[3]
                    .split(',')
                    .map(|t| u32::from_str_radix(t, 16).unwrap())
                    .collect(),
            }
        })
        .collect()
}

/// Go passes `tok tokens` by value, so every call gets a fresh copy of the
/// indexed tokens.
fn write_to_type(ttype: &str, bw: &mut BitWriter<Vec<u8>>, raw: &[u32], input: Option<&[u8]>) {
    let mut tok = TokenList::index(raw);
    let tok = &mut tok;
    match ttype {
        "wb" => bw.write_block(tok, false, input),
        "dyn" => bw.write_block_dynamic(tok, false, input, false),
        "sync" => bw.write_block_dynamic(tok, false, input, true),
        _ => panic!("unknown test type"),
    }
    assert!(bw.err().is_none());
    bw.flush();
    assert!(bw.err().is_none());
}

// Go: compress/flate/huffman_bit_writer_test.go:testWriterEOF
fn test_writer_eof(ttype: &str, test: &HuffTest, use_input: bool) {
    if use_input && test.input.is_empty() {
        return;
    }
    let input = if use_input {
        Some(read(&test.input))
    } else {
        None
    };
    let mut bw = BitWriter::new(Vec::new());
    let mut tokens = TokenList::index(&test.tokens);
    match ttype {
        "wb" => bw.write_block(&mut tokens, true, input.as_deref()),
        "dyn" => bw.write_block_dynamic(&mut tokens, true, input.as_deref(), true),
        "huff" => bw.write_block_huff(true, input.as_deref().unwrap_or(&[]), true),
        _ => panic!("unknown test type"),
    }
    assert!(bw.err().is_none());
    bw.flush();
    let b = bw.get_ref();
    assert!(!b.is_empty(), "no output received");
    assert_eq!(
        b[0] & 1,
        1,
        "block not marked with EOF for input {:?}",
        test.input
    );
}

// Go: compress/flate/huffman_bit_writer_test.go:testBlock
fn test_block(test: &HuffTest, ttype: &str) {
    let want_path = test.want.replace("%s", ttype);
    let want_ni_path = test.want_no_input.replace("%s", ttype);
    if !test.input.is_empty() {
        let input = read(&test.input);
        let want = read(&want_path);
        let mut bw = BitWriter::new(Vec::new());
        write_to_type(ttype, &mut bw, &test.tokens, Some(&input));
        assert_eq!(bw.get_ref(), &want, "{want_path}");

        // Test if the writer produces the same output after reset.
        bw.reset(Vec::new());
        write_to_type(ttype, &mut bw, &test.tokens, Some(&input));
        bw.flush();
        assert_eq!(bw.get_ref(), &want, "{want_path} after reset");
        test_writer_eof("wb", test, true);
    }
    let want_ni = read(&want_ni_path);
    let mut bw = BitWriter::new(Vec::new());
    write_to_type(ttype, &mut bw, &test.tokens, None);
    assert_eq!(bw.get_ref(), &want_ni, "{want_ni_path}");
    assert_ne!(bw.get_ref()[0] & 1, 1, "got unexpected EOF");

    bw.reset(Vec::new());
    write_to_type(ttype, &mut bw, &test.tokens, None);
    bw.flush();
    assert_eq!(bw.get_ref(), &want_ni, "{want_ni_path} after reset");
    test_writer_eof("wb", test, false);
}

// Go: TestWriteBlock
#[test]
fn test_write_block() {
    for t in write_block_tests() {
        test_block(&t, "wb");
    }
}

// Go: TestWriteBlockDynamic
#[test]
fn test_write_block_dynamic() {
    for t in write_block_tests() {
        test_block(&t, "dyn");
    }
}

// Go: TestWriteBlockDynamicSync
#[test]
fn test_write_block_dynamic_sync() {
    for t in write_block_tests() {
        test_block(&t, "sync");
    }
}

// Go: compress/zlib/writer_test.go:TestWriterDictIsUsed (FDICT / dict id)
#[test]
fn test_zlib_header_bytes() {
    // Header bytes per level, as written by Go's zlib.Writer.
    let want: &[(i32, [u8; 2])] = &[
        (-2, [0x78, 0x01]),
        (-1, [0x78, 0x9c]),
        (0, [0x78, 0x01]),
        (1, [0x78, 0x01]),
        (2, [0x78, 0x5e]),
        (5, [0x78, 0x5e]),
        (6, [0x78, 0x9c]),
        (7, [0x78, 0xda]),
        (9, [0x78, 0xda]),
    ];
    for (level, hdr) in want {
        let mut z = zlib::new_writer_level(Vec::new(), *level).unwrap();
        z.close().unwrap();
        let out = z.into_inner();
        assert_eq!(&out[..2], hdr, "level {level}");
        assert_eq!(&out[out.len() - 4..], &[0, 0, 0, 1], "adler32 of empty");
    }
    // FDICT with an empty (non-nil) dictionary.
    let mut z = zlib::new_writer_level_dict(Vec::new(), 6, Some(&[])).unwrap();
    z.close().unwrap();
    let out = z.into_inner();
    assert_eq!(&out[..6], &[0x78, 0xbb, 0, 0, 0, 1]);
}

/// Go's failWriter: the (n+1)-th call to Write fails with errIO, the others
/// succeed (and discard).
struct FailWriter {
    n: i64,
}

impl std::io::Write for FailWriter {
    fn write(&mut self, b: &[u8]) -> std::io::Result<usize> {
        self.n -= 1;
        if self.n == -1 {
            return Err(std::io::Error::other("IO error"));
        }
        Ok(b.len())
    }
    fn flush(&mut self) -> std::io::Result<()> {
        Ok(())
    }
}

fn is_err_io(e: &Result<(), Error>) -> bool {
    matches!(e, Err(Error::Io(io)) if io.to_string() == "IO error")
}

// Go: compress/flate/deflate_test.go:TestWriterPersistentWriteError
#[test]
fn test_writer_persistent_write_error() {
    let d = std::fs::read(
        Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/files/Isaac.Newton-Opticks.txt"),
    )
    .unwrap();
    let d = &d[..10000]; // Keep this test short
    let mut zw = flate::new_writer(FailWriter { n: 0 }, flate::DEFAULT_COMPRESSION).unwrap();
    // Sweep over the threshold at which an error is returned.
    for i in 0..1000 {
        zw.reset(FailWriter { n: i });
        let werr = zw.write(d).map(|_| ());
        let cerr = zw.close();
        let ferr = zw.flush();
        let n = zw.get_ref().n;
        assert!(
            werr.is_ok() || is_err_io(&werr),
            "test {i}: Write error {werr:?}"
        );
        if n < 0 {
            assert!(is_err_io(&cerr), "test {i}: Close error {cerr:?}");
            assert!(is_err_io(&ferr), "test {i}: Flush error {ferr:?}");
        } else {
            // The failure threshold was high enough to write the whole stream.
            return;
        }
    }
    panic!("never wrote the whole stream");
}

// Go: compress/flate/deflate_test.go:TestWriterPersistentFlushError
#[test]
fn test_writer_persistent_flush_error() {
    let mut zw = flate::new_writer(FailWriter { n: 0 }, flate::DEFAULT_COMPRESSION).unwrap();
    let flush_err = zw.flush();
    let close_err = zw.close();
    let write_err = zw.write(b"Test").map(|_| ());
    for e in [&close_err, &flush_err, &write_err] {
        assert!(is_err_io(e), "{e:?}");
    }
}

// Go: compress/flate/deflate_test.go:TestWriterPersistentCloseError
#[test]
fn test_writer_persistent_close_error() {
    // If underlying writer return error on closing stream we should persistent this error across all writer calls.
    let mut zw = flate::new_writer(FailWriter { n: 0 }, flate::DEFAULT_COMPRESSION).unwrap();
    let close_err = zw.close();
    let flush_err = zw.flush();
    let write_err = zw.write(b"Test").map(|_| ());
    for e in [&close_err, &flush_err, &write_err] {
        assert!(is_err_io(e), "{e:?}");
    }
    // After closing writer we should persistent "write after close" error across Flush and Write calls, but return nil
    // on next Close calls.
    zw.reset(FailWriter { n: i64::MAX });
    zw.close().expect("First call to close returned error");
    zw.close().expect("Second call to close returned error");
    assert!(matches!(zw.flush(), Err(Error::WriterClosed)));
    assert!(matches!(zw.write(b"Test"), Err(Error::WriterClosed)));
}

// Go: compress/flate/writer_test.go:TestWriteError (error propagation and
// recovery after Reset; the byte-exact variant is in fixtures/gotests.txt).
#[test]
fn test_write_error() {
    struct ErrorWriter {
        n: i64,
    }
    impl std::io::Write for ErrorWriter {
        fn write(&mut self, b: &[u8]) -> std::io::Result<usize> {
            if self.n <= 0 {
                return Err(std::io::Error::from(std::io::ErrorKind::BrokenPipe));
            }
            self.n -= 1;
            Ok(b.len())
        }
        fn flush(&mut self) -> std::io::Result<()> {
            Ok(())
        }
    }
    let mut input = Vec::new();
    for i in 0..65536 * 4 {
        input.extend_from_slice(format!("asdasfasf{i}{i}fghfgujyut{i}yutyu\n").as_bytes());
    }
    for l in 0..10 {
        let mut fail = 1;
        while fail <= 256 {
            let mut w = flate::new_writer(ErrorWriter { n: fail }, l).unwrap();
            let mut err = None;
            for chunk in input.chunks(128) {
                if let Err(e) = w.write(chunk) {
                    err = Some(e);
                    break;
                }
            }
            assert!(err.is_some(), "Level {l}: Expected an error");
            assert!(
                w.write(&[1, 2, 2, 3, 4, 5]).is_err(),
                "Level {l}: Expected an error"
            );
            assert!(w.flush().is_err(), "Level {l}: Expected an error on flush");
            assert!(w.close().is_err(), "Level {l}: Expected an error on close");
            w.reset(ErrorWriter { n: i64::MAX });
            let n2 = w
                .write(&[1, 2, 3, 4, 5, 6])
                .expect("Got unexpected error after reset");
            assert!(n2 > 0, "Level {l}: Got 0 length write, expected > 0");
            fail *= 2;
        }
    }
}
