package main

import (
	"bufio"
	"bytes"
	"compress/gzip"
	"encoding/hex"
	stdjson "encoding/json"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"math/rand"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/tdewolff/minify/v2"
	"github.com/tdewolff/minify/v2/svg"
	"github.com/tdewolff/parse/v2/buffer"
)

// scale multiplies the number of generated random cases.
var scale = 1

// fixWriter writes one gzip-compressed, tab-separated fixture file.
type fixWriter struct {
	f  *os.File
	gz *gzip.Writer
	bw *bufio.Writer
	n  int
}

func newFix(dir, name string) *fixWriter {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		panic(err)
	}
	f, err := os.Create(filepath.Join(dir, name+".txt.gz"))
	if err != nil {
		panic(err)
	}
	gz, _ := gzip.NewWriterLevel(f, gzip.BestCompression)
	gz.ModTime = gz.ModTime.UTC() // zero time: reproducible output
	bw := bufio.NewWriter(gz)
	_, _ = fmt.Fprintf(bw, "# generated by tools/go-oracle/tdewolff-minify fixtures (%s); DO NOT EDIT\n", goVersion())
	return &fixWriter{f, gz, bw, 0}
}

func (w *fixWriter) rec(fields ...string) {
	_, _ = w.bw.WriteString(strings.Join(fields, "\t"))
	_ = w.bw.WriteByte('\n')
	w.n++
}

func (w *fixWriter) close() {
	if err := w.bw.Flush(); err != nil {
		panic(err)
	}
	if err := w.gz.Close(); err != nil {
		panic(err)
	}
	if err := w.f.Close(); err != nil {
		panic(err)
	}
	fmt.Fprintf(os.Stderr, "%s: %d records\n", w.f.Name(), w.n)
}

func hx(b []byte) string { return hex.EncodeToString(b) }

func errStr(err error) string {
	if err == nil {
		return "-"
	}
	return hx([]byte(err.Error()))
}

// cp is append([]byte(nil), s...) (Go size-class capacity).
func cp(s []byte) []byte { return append([]byte(nil), s...) }

// runM minifies a private copy of in through m.Minify and returns the
// output, the (possibly rewritten in place) input copy and the error.
func runM(m *minify.M, mediatype string, in []byte) ([]byte, []byte, error) {
	buf := cp(in)
	var w bytes.Buffer
	err := m.Minify(mediatype, &w, buffer.NewReader(buf))
	return w.Bytes(), buf, err
}

// sameOr returns "=" when b equals ref, else hex(b).
func sameOr(b, ref []byte) string {
	if bytes.Equal(b, ref) {
		return "="
	}
	return hx(b)
}

// minRec writes `min CONFIG MEDIATYPE INPUT OUTPUT ERR AFTER`.
func minRec(w *fixWriter, cfg string, m *minify.M, mediatype string, in []byte) {
	out, after, err := runM(m, mediatype, in)
	w.rec("min", cfg, hx([]byte(mediatype)), hx(in), sameOr(out, in), errStr(err), sameOr(after, in))
}

// testLiterals returns every string literal inside a Test* function of the
// _test.go files of the given minify package (sorted, deduplicated).
func testLiterals(pkg string) [][]byte {
	dir := filepath.Join(minifyModuleDir(), pkg)
	fset := token.NewFileSet()
	matches, err := filepath.Glob(filepath.Join(dir, "*_test.go"))
	if err != nil {
		panic(err)
	}
	seen := map[string]bool{}
	var lits []string
	for _, fn := range matches {
		f, err := parser.ParseFile(fset, fn, nil, 0)
		if err != nil {
			panic(err)
		}
		for _, decl := range f.Decls {
			fd, ok := decl.(*ast.FuncDecl)
			if !ok || !strings.HasPrefix(fd.Name.Name, "Test") {
				continue
			}
			ast.Inspect(fd, func(n ast.Node) bool {
				if bl, ok := n.(*ast.BasicLit); ok && bl.Kind == token.STRING {
					s, err := strconv.Unquote(bl.Value)
					if err == nil && !seen[s] {
						seen[s] = true
						lits = append(lits, s)
					}
				}
				return true
			})
		}
	}
	sort.Strings(lits)
	out := make([][]byte, len(lits))
	for i, s := range lits {
		out[i] = []byte(s)
	}
	return out
}

type kind struct {
	name       string
	pkg        string
	mediatypes []string
	configs    []string
	dict       []string
}

var allConfigNames = func() []string {
	var n []string
	for _, c := range configs {
		n = append(n, c.name)
	}
	return n
}()

var kinds = []kind{
	{"html", "html", []string{"text/html"},
		append(append([]string{}, allConfigNames...), "t-copycssjs", "t-htmlcsssvg", "errplain", "dummyjs", "errjs", "xml-json-rx"), htmlDict},
	{"css", "css", []string{"text/css", "text/css;inline=1"}, []string{"default", "seeksnack", "css2-prec3", "prec1-inline", "t-empty"}, cssDict},
	{"svg", "svg", []string{"image/svg+xml", "image/svg+xml;inline=1"}, []string{"default", "seeksnack", "css2-prec3", "prec1-inline", "svgerr"}, svgDict},
	{"xml", "xml", []string{"application/xml", "application/rss+xml"}, []string{"default", "seeksnack", "css2-prec3"}, xmlDict},
	{"json", "json", []string{"application/json", "application/ld+json"}, []string{"default", "seeksnack", "css2-prec3", "prec1-inline"}, jsonDict},
}

func genFixtures(dir string) {
	// upstream tables
	w := newFix(dir, "upstream")
	genUpstream(w)
	w.close()

	// every upstream test literal through the relevant configs
	w = newFix(dir, "literals")
	for _, k := range kinds {
		lits := testLiterals(k.pkg)
		for _, cfg := range k.configs {
			m := configByName(cfg)
			for _, mt := range k.mediatypes {
				for _, in := range lits {
					minRec(w, cfg, m, mt, in)
				}
			}
		}
	}
	w.close()

	// random mutations
	w = newFix(dir, "fuzz")
	genFuzzRecords(w, 1500*scale, 1)
	w.close()

	// grammar-shaped css / svg path / html
	w = newFix(dir, "structured")
	genStructured(w, 1500*scale, 3)
	w.close()

	// unit functions
	w = newFix(dir, "units")
	genUnits(w)
	w.close()
}

// seedsFor returns the fuzz seeds of a kind: upstream literals plus
// snippets of the site corpora when available (SEEKSNACK_GOLDEN, CORPUS2).
func seedsFor(k kind) [][]byte {
	seeds := testLiterals(k.pkg)
	add := func(root string, exts ...string) {
		if root == "" {
			return
		}
		var files []string
		_ = filepath.Walk(root, func(p string, info os.FileInfo, err error) error {
			if err != nil || info.IsDir() {
				return nil
			}
			for _, e := range exts {
				if strings.HasSuffix(p, e) {
					files = append(files, p)
				}
			}
			return nil
		})
		sort.Strings(files)
		// take up to 40 files spread over the corpus
		step := 1
		if len(files) > 40 {
			step = len(files) / 40
		}
		for i := 0; i < len(files); i += step {
			b, err := os.ReadFile(files[i])
			if err == nil && len(b) > 0 {
				seeds = append(seeds, b)
			}
		}
	}
	g := os.Getenv("SEEKSNACK_GOLDEN")
	c2 := os.Getenv("CORPUS2")
	switch k.name {
	case "html":
		add(g, ".html")
	case "xml":
		add(g, ".xml")
	case "css":
		if c2 != "" {
			add(filepath.Join(c2, "css"), ".in")
			add(filepath.Join(c2, "css-resource"), ".in")
		}
	case "svg":
		if c2 != "" {
			add(filepath.Join(c2, "svg"), ".in")
		}
	case "json":
		if c2 != "" {
			add(filepath.Join(c2, "json"), ".in")
		}
	}
	return seeds
}

// mutate returns a random mutation of one or two seeds (at most 700 bytes).
func mutate(r *rand.Rand, seeds [][]byte, dict []string) []byte {
	window := func(b []byte, max int) []byte {
		if len(b) <= max {
			return cp(b)
		}
		n := 1 + r.Intn(max)
		i := r.Intn(len(b) - n + 1)
		return cp(b[i : i+n])
	}
	b := window(seeds[r.Intn(len(seeds))], 400)
	ops := 1 + r.Intn(5)
	for k := 0; k < ops; k++ {
		pos := 0
		if len(b) > 0 {
			pos = r.Intn(len(b) + 1)
		}
		switch r.Intn(8) {
		case 0, 1, 2: // insert dictionary token
			t := dict[r.Intn(len(dict))]
			b = append(b[:pos], append([]byte(t), b[pos:]...)...)
		case 3: // delete a range
			if len(b) > 0 {
				n := 1 + r.Intn(8)
				if pos+n > len(b) {
					n = len(b) - pos
				}
				b = append(b[:pos], b[pos+n:]...)
			}
		case 4: // splice another seed window
			o := window(seeds[r.Intn(len(seeds))], 80)
			b = append(b[:pos], append(o, b[pos:]...)...)
		case 5: // replace a byte
			if pos < len(b) {
				const special = " \t\n\r\f\"'<>=&;:,./\\#%+-!?*()[]{}0123456789eE"
				b[pos] = special[r.Intn(len(special))]
			}
		case 6: // duplicate a range
			if len(b) > 0 {
				i := r.Intn(len(b))
				n := 1 + r.Intn(16)
				if i+n > len(b) {
					n = len(b) - i
				}
				d := cp(b[i : i+n])
				b = append(b[:pos], append(d, b[pos:]...)...)
			}
		case 7: // insert a random byte (NUL, high bytes included)
			c := byte(r.Intn(256))
			b = append(b[:pos], append([]byte{c}, b[pos:]...)...)
		}
	}
	if len(b) > 700 {
		b = b[:700]
	}
	return b
}

// genFuzzRecords writes n random cases per kind, each through every config
// and mediatype of the kind (cycled).
func genFuzzRecords(w *fixWriter, n int, seed int64) {
	r := rand.New(rand.NewSource(seed))
	for _, k := range kinds {
		seeds := seedsFor(k)
		ms := make([]*minify.M, len(k.configs))
		for i, c := range k.configs {
			ms[i] = configByName(c)
		}
		for i := 0; i < n; i++ {
			in := mutate(r, seeds, k.dict)
			ci := i % len(k.configs)
			mt := k.mediatypes[(i/len(k.configs))%len(k.mediatypes)]
			minRec(w, k.configs[ci], ms[ci], mt, in)
			if k.configs[ci] != "seeksnack" && i%3 == 0 {
				minRec(w, "seeksnack", configByName("seeksnack"), k.mediatypes[0], in)
			}
		}
	}
}

// fuzzGen writes a large random differential set (fuzz.txt.gz) to OUTDIR.
func fuzzGen(outDir string, n int, seed int64, _ []string) {
	w := newFix(outDir, "fuzz")
	genFuzzRecords(w, n, seed)
	w.close()
}

var numberPrecs = []int{-1, 0, 1, 2, 3, 6, 15}
var decimalPrecs = []int{-1, 0, 1, 2, 3}

// genUnits writes records for the byte-level helpers:
//
//	num PREC IN OUT AFTER / dec PREC IN OUT AFTER / mt IN OUT AFTER /
//	duri CONFIG IN OUT AFTER / path PREC IN OUT AFTER
func genUnits(w *fixWriter) {
	r := rand.New(rand.NewSource(7))
	// numbers
	var nums [][]byte
	nums = append(nums, testLiterals("")...)
	if p := os.Getenv("NUMBERS_JSONL"); p != "" {
		f, err := os.Open(p)
		if err == nil {
			sc := bufio.NewScanner(f)
			sc.Buffer(make([]byte, 1<<20), 1<<20)
			for sc.Scan() {
				var rec map[string]any
				if stdjson.Unmarshal(sc.Bytes(), &rec) == nil {
					nums = append(nums, []byte(rec["in"].(string)))
				}
			}
			_ = f.Close()
		}
	}
	numDict := []string{"0", "1", "5", "9", ".", "e", "E", "-", "+", "00", "99", "e-", "e+", "000000000", "999999999", "123456789", "1e308", "5e-324", "9223372036854775807", "-9223372036854775808"}
	numSeeds := append([][]byte{}, nums...)
	for i := 0; i < 3000*scale; i++ {
		nums = append(nums, mutate(r, numSeeds, numDict))
	}
	for _, in := range nums {
		if len(in) > 120 {
			continue
		}
		for _, p := range numberPrecs {
			buf := cp(in)
			out := minify.Number(buf, p)
			w.rec("num", strconv.Itoa(p), hx(in), sameOr(out, in), sameOr(buf, in))
		}
		for _, p := range decimalPrecs {
			buf := cp(in)
			out := minify.Decimal(buf, p)
			w.rec("dec", strconv.Itoa(p), hx(in), sameOr(out, in), sameOr(buf, in))
		}
	}

	// mediatypes
	mts := testLiterals("")
	mtDict := []string{" ", "\t", "\n", "\"", ";", "=", "text/HTML", "Charset=UTF-8", "\"A B\"", "x", "/", ","}
	mtSeeds := append([][]byte{}, mts...)
	for i := 0; i < 800*scale; i++ {
		mts = append(mts, mutate(r, mtSeeds, mtDict))
	}
	for _, in := range mts {
		buf := cp(in)
		out := minify.Mediatype(buf)
		w.rec("mt", hx(in), sameOr(out, in), sameOr(buf, in))
	}

	// data URIs
	duris := testLiterals("")
	duriDict := []string{"data:", "data:text/plain;charset=us-ascii,", "data:image/svg+xml;charset=utf-8,", "data:;base64,", ";base64,", "%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3E%3Cpath d='M0 0L1 1'/%3E%3C/svg%3E", "%20", "%", "+", ",", ";", "text/x,", "<?xx?>", "dGV4dA==", "IyMjIyMj", "&#43;", "\"", "#", " "}
	duriSeeds := append([][]byte{}, duris...)
	for i := 0; i < 800*scale; i++ {
		duris = append(duris, mutate(r, duriSeeds, duriDict))
	}
	for _, cfg := range []string{"seeksnack", "t-datauri", "default"} {
		m := configByName(cfg)
		for _, in := range duris {
			buf := cp(in)
			out := minify.DataURI(m, buf)
			w.rec("duri", cfg, hx(in), sameOr(out, in), sameOr(buf, in))
		}
	}

	// path data (fresh PathData per input, newPrecision unset as in upstream tests)
	paths := testLiterals("svg")
	pathDict := []string{"M", "m", "L", "l", "H", "h", "V", "v", "C", "c", "S", "s", "Q", "q", "T", "t", "A", "a", "Z", "z", " ", ",", "-", ".", "0", "1", "10", "100", ".5", "1e2", "1.5e-3", "0 0", "1 0 1", "4.646 1.646", "-.708"}
	pathSeeds := append([][]byte{}, paths...)
	for i := 0; i < 1500*scale; i++ {
		paths = append(paths, mutate(r, pathSeeds, pathDict))
	}
	for _, prec := range []int{0, 1, 3} {
		for _, in := range paths {
			p := svg.NewPathData(&svg.Minifier{Precision: prec})
			buf := cp(in)
			out := p.ShortenPathData(buf)
			w.rec("path", strconv.Itoa(prec), hx(in), sameOr(out, in), sameOr(buf, in))
		}
	}
}

var htmlDict = []string{"<", ">", "</", "/>", "=", "\"", "'", " ", "\n", "\t", "  ", "&amp;", "&lt;", "&#x27;", "&#39;", "&quot;", "&nbsp;", "&hellip;", "&#128512;", "&#x2026;", "&amp;x", "<!--", "-->", "<!--[if IE]>", "<![endif]-->", "<!--[if lt IE 9]><p>x</p><![endif]-->", "<!--#include file=x-->", "<!doctype html>", "<!DOCTYPE html>", "<script>", "</script>", "<style>", "</style>", "<pre>", "</pre>", "<p>", "</p>", "<a href=", "<a id=x name=x>", "<meta name=viewport content=\"width=device-width, initial-scale=1.0\">", "<meta http-equiv=content-type content=\"text/html; charset=utf-8\">", "<meta name=keywords content=\"a, b, c\">", "<input type=text value=\"\">", "<input type=radio value=on>", "style=\"color:red;\"", "style=\"\"", "onclick=\"javascript:x()\"", "onclick=\"  \"", "type=\"text/javascript\"", "href=\"HTTP://x.com\"", "href=\" https://x \"", "src=\"data:text/plain;charset=us-ascii,hi\"", "<select>", "<option>", "</option>", "<optgroup>", "</optgroup>", "<svg>", "</svg>", "<math>", "</math>", "<textarea>", "</textarea>", "<iframe>", "</iframe>", "<template>", "</template>", "{{", "}}", "{{ .X }}", "<?", "?>", "<?php x ?>", "<span>", "</span>", "<i class=x></i>", "<div>", "</div>", "<br>", "<colgroup>", "<html>", "<head>", "<body>", "property=\"og:x\"", "content=\"\"", "content", "class=\"\"", "<script type=\"application/ld+json\">{\"a\": 1.50, \"b\": [1, 2,]}</script>", "<style>a { color : #FF0000 ; }</style>", "<script type=\"text/x-tmpl\">x</script>", "<script src=a charset=utf-8></script>", "<style amp-boilerplate>x</style>", "<table><tr><td>", "</td>", "<ul><li>", "</li>", "<form action=\"\">", "<button type=submit>", "<link rel=stylesheet type=text/css href=x>", "<img src=x alt=\"a 'b' \\\"c\\\"\">", "`", "\x00", "\u00a0", "é"}

var cssDict = []string{"{", "}", ";", ":", ",", " ", "\n", "(", ")", "[", "]", "rgb(255,0,0)", "rgb(10%,20%,40%)", "rgba(0,0,0,0)", "rgba(1,2,3,1)", "rgba(1,2,3,.5)", "rgb(1 2 3 / 50%)", "hsl(120,100%,50%)", "hsla(0,0%,0%,.5)", "hsl(-120,50%,50%)", "#FFFFFF", "#aabbccdd", "#ff000000", "0px", "0.50em", "+.5", "-0.0", "1e3", "100%", "050%", "!important", " !important", "url(a b.png)", "url( x.png )", "url(\"data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16'%3E%3Cpath d='M0 0h1'/%3E%3C/svg%3E\")", "url('x')", "@import url(x.css);", "@import url( x.css );", "@media (min-width:1px){", "@font-face{", "@charset \"utf-8\";", "/*! c */", "/* c */", "--x:", "--y: a b ;", "var(--x)", "calc(1px + 2px)", "margin:0 0 0 0", "margin:1px 2px 1px 2px", "background:none", "background:transparent url(x) no-repeat 0 0 / auto", "background:url(x) repeat no-repeat left top/auto auto padding-box border-box", "background-position:right 10% bottom 20%", "background-position:center", "background-size:auto auto", "background-repeat:repeat no-repeat", "font:normal bold 12px/normal Arial, \"Helvetica Neue\"", "font-family:\"Arial\",'-apple-system'", "font-weight:bold", "border:none", "outline:none", "flex:0 1 auto", "flex:1 0 0%", "box-shadow:0 0 0 0 #000", "box-shadow:initial", "unicode-range:U+0000-00FF,U+0100,U+4??", "U+4??", "-ms-filter:\"progid:DXImageTransform.Microsoft.Alpha(Opacity=80)\"", "filter:progid:DXImageTransform.Microsoft.Alpha(opacity=80)", "transform:rotate(0deg)", "z-index:0010", "color:WHITE", "color:black", "border-color:currentColor red red red", "text-decoration:none solid", "\\\n", "\"a\\\nb\"", "a[href=\"x\"]", "a[x=y i]", ".Class", "DIV", "*zoom:1", "0PX", "10E2", ".0", "00.10", "\x00", "é"}

var svgDict = []string{"<svg xmlns=\"http://www.w3.org/2000/svg\" version=\"1.1\" x=\"0\" y=\"0\" viewBox=\"0 0 100.00 100\">", "</svg>", "<path d=\"M 10.50,20 L 30 40 C 1 1 2 2 3 3 S 4 4 5 5 Q 1 1 2 2 T 3 3 A 5 5 0 1 0 10 10 Z\"/>", "<path d=\"M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6\"/>", "<rect width=\"10px\" height=\"10.0PX\" fill=\"#FF0000\" stroke=\"white\"/>", "<circle r=\"1e2\" fill=\"#ffffff\" stroke=\"url(#a)\"/>", "<style>", "</style>", "<style>a { fill : red ; }</style>", "<![CDATA[", "]]>", "<style><![CDATA[ a{x:y} ]]></style>", "<metadata>", "</metadata>", "<defs/>", "<defs></defs>", "<defs><g/></defs>", "<!-- c -->", "<?xml version=\"1.0\"?>", "<!DOCTYPE svg>", "<!DOCTYPE svg [ <!ENTITY a \"b\"> ]>", "inkscape:x=\"1\"", "sodipodi:y=\"2\"", "xmlns:xlink=\"http://www.w3.org/1999/xlink\"", "xlink:href=\"#a\"", "style=\"fill: red ;\"", "&amp;", "&quot;", "&apos;", "<foreignObject>", "</foreignObject>", "<text>", "</text>", "preserveAspectRatio=\"xMidYMid meet\"", "xml:space=\"preserve\"", "<svg:g>", "</svg:g>", "d=\"m0 0h10v10h-10z\"", "1e2", ".5.5", " ", "\n", "=", "'", "\"", "contentStyleType=\"TEXT/CSS\"", "baseProfile=\"none\"", "<g transform=\"translate(1 2)\">", "</g>"}

var xmlDict = []string{"<?xml version=\"1.0\" encoding=\"utf-8\" ?>", "<a>", "</a>", "<b x=\"1\" y='2' z=3>", "</b >", "<![CDATA[<x&y>]]>", "<![CDATA[ a ]]>", "<![CDATA[]]>", "<!-- c -->", "<!DOCTYPE x [ <!ENTITY y \"z\"> ]>", "<!DOCTYPE x>", "&apos;", "&gt;", "&quot;", "&lt;", "&amp;", "&#34;", "\t\n", " ", "  ", "\n", "<c/>", "<c />", "<!x>", "text", "\"", "'", "<", ">", "=", "<rss><channel><item><title>", "</title>", "<description><![CDATA[<img src=\"x\" alt=\"y\"/> text & more]]></description>", "<atom:link href=\"x\" rel=\"self\" />", "a=\"b\tc\nd\""}

var jsonDict = []string{"{", "}", "[", "]", ",", ":", "\"a\"", "\"\\\"\"", "\"\\\\\"", "1.50", "-0.5", ".5", "-.5", "1e10", "1E-7", "0.000001", "100", "1000000", "true", "false", "null", " ", "\n", "\t", "123456789012345678901234567890", ",}", ",]", "\"\\u00e9\"", "\"\\/\"", "0", "-0", "01"}
