package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/constant"
	"go/importer"
	"go/parser"
	"go/token"
	"go/types"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"sync"

	"github.com/tdewolff/minify/v2/css"
	"github.com/tdewolff/minify/v2/html"
	"github.com/tdewolff/minify/v2/svg"
	"github.com/tdewolff/minify/v2/xml"
)

// minifyModuleDir returns the module cache directory of the
// tdewolff/minify version pinned in go.mod.
// (Run the oracle from inside the neohugo module.)
func minifyModuleDir() string {
	minifyDirOnce.Do(func() {
		out, err := exec.Command("go", "list", "-m", "-f", "{{.Dir}}", "github.com/tdewolff/minify/v2").Output()
		if err != nil {
			panic(fmt.Sprintf("go list (run the oracle from inside the neohugo module): %v", err))
		}
		minifyDir = strings.TrimSpace(string(out))
	})
	return minifyDir
}

var (
	minifyDirOnce sync.Once
	minifyDir     string
)

// typedPkg parses and type-checks the given files of one minify package
// (only files without imports: hash.go and table.go).
type typedPkg struct {
	fset  *token.FileSet
	files map[string]*ast.File
	info  *types.Info
	pkg   *types.Package
}

func loadPkg(pkg string, names ...string) *typedPkg {
	dir := filepath.Join(minifyModuleDir(), pkg)
	fset := token.NewFileSet()
	files := map[string]*ast.File{}
	var list []*ast.File
	for _, n := range names {
		f, err := parser.ParseFile(fset, filepath.Join(dir, n), nil, parser.ParseComments)
		if err != nil {
			panic(err)
		}
		files[n] = f
		list = append(list, f)
	}
	info := &types.Info{Types: map[ast.Expr]types.TypeAndValue{}, Defs: map[*ast.Ident]types.Object{}}
	conf := types.Config{Importer: importer.Default()}
	p, err := conf.Check(pkg, fset, list, info)
	if err != nil {
		panic(err)
	}
	return &typedPkg{fset, files, info, p}
}

func (p *typedPkg) constVal(name string) constant.Value {
	return p.pkg.Scope().Lookup(name).(*types.Const).Val()
}

func u64(v constant.Value) uint64 {
	x, ok := constant.Uint64Val(v)
	if !ok {
		panic("not uint64")
	}
	return x
}

func rustBytes(s string) string {
	var b strings.Builder
	b.WriteString("b\"")
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case c == '"':
			b.WriteString("\\\"")
		case c == '\\':
			b.WriteString("\\\\")
		case c >= 0x20 && c < 0x7f:
			b.WriteByte(c)
		default:
			fmt.Fprintf(&b, "\\x%02x", c)
		}
	}
	b.WriteString("\"")
	return b.String()
}

// genHash converts a hasher-generated hash.go into Rust (constants, table
// and ToHash ported literally).
func genHash(pkg string, check func(name string, h uint32) bool) string {
	p := loadPkg(pkg, "hash.go")
	f := p.files["hash.go"]
	var b bytes.Buffer
	fmt.Fprintf(&b, "//! Go: minify/%s/hash.go (generated by hasher; converted by\n//! tools/go-oracle/tdewolff-minify `tables`; DO NOT EDIT). The perfect-hash\n//! table and `ToHash` are ported literally.\n\n", pkg)
	b.WriteString("use tdewolff_parse::ByteView;\n\n")
	b.WriteString("/// Go: Hash — perfect hashes for a predefined list of strings.\n")
	b.WriteString("#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]\npub struct Hash(pub u32);\n\n")
	b.WriteString("// Unique hash definitions to be used instead of strings\n")
	n := 0
	for _, decl := range f.Decls {
		gd, ok := decl.(*ast.GenDecl)
		if !ok || gd.Tok != token.CONST {
			continue
		}
		for _, spec := range gd.Specs {
			vs := spec.(*ast.ValueSpec)
			for _, id := range vs.Names {
				if strings.HasPrefix(id.Name, "_") {
					continue
				}
				c := p.info.Defs[id].(*types.Const)
				h := uint32(u64(c.Val()))
				name := strings.TrimSpace(vs.Comment.Text())
				if !check(name, h) {
					panic(fmt.Sprintf("%s: ToHash(%q) != %#x", pkg, name, h))
				}
				fmt.Fprintf(&b, "pub const %s: Hash = Hash(%#x); // %s\n", id.Name, h, name)
				n++
			}
		}
	}
	hash0 := u64(p.constVal("_Hash_hash0"))
	maxLen := u64(p.constVal("_Hash_maxLen"))
	var text string
	if c, ok := p.pkg.Scope().Lookup("_Hash_text").(*types.Const); ok {
		text = constant.StringVal(c.Val())
	} else {
		// var _Hash_text = []byte("" + ...)
		ast.Inspect(f, func(nd ast.Node) bool {
			if vs, ok := nd.(*ast.ValueSpec); ok && len(vs.Names) == 1 && vs.Names[0].Name == "_Hash_text" {
				call := vs.Values[0].(*ast.CallExpr)
				text = constant.StringVal(p.info.Types[call.Args[0]].Value)
			}
			return true
		})
	}
	fmt.Fprintf(&b, "\n/// Number of names in the table.\npub const HASH_COUNT: usize = %d;\n\n", n)
	fmt.Fprintf(&b, "const HASH_HASH0: u32 = %#x;\nconst HASH_MAX_LEN: usize = %d;\n", hash0, maxLen)
	fmt.Fprintf(&b, "const HASH_TEXT: &[u8] = %s;\n\n", rustBytes(text))

	// _Hash_table
	var tbl *ast.CompositeLit
	var size int64
	ast.Inspect(f, func(nd ast.Node) bool {
		if vs, ok := nd.(*ast.ValueSpec); ok && len(vs.Names) == 1 && vs.Names[0].Name == "_Hash_table" {
			tbl = vs.Values[0].(*ast.CompositeLit)
			at := p.info.Types[tbl].Type.(*types.Array)
			size = at.Len()
		}
		return true
	})
	entries := map[int64]uint32{}
	for _, e := range tbl.Elts {
		kv := e.(*ast.KeyValueExpr)
		k, _ := constant.Int64Val(p.info.Types[kv.Key].Value)
		v := u64(p.info.Types[kv.Value].Value)
		entries[k] = uint32(v)
	}
	fmt.Fprintf(&b, "static HASH_TABLE: [Hash; %d] = [\n", size)
	for i := int64(0); i < size; i++ {
		v := entries[i]
		if v == 0 {
			fmt.Fprintf(&b, "    Hash(0x0),\n")
		} else {
			fmt.Fprintf(&b, "    Hash(%#x), // %s\n", v, text[v>>8:v>>8+v&0xff])
		}
	}
	b.WriteString("];\n\n")
	b.WriteString(`impl Hash {
    // Go: Hash.String
    /// Returns the hash' name.
    pub fn string(self) -> &'static [u8] {
        let start = (self.0 >> 8) as usize;
        let n = (self.0 & 0xff) as usize;
        if start + n > HASH_TEXT.len() {
            return b"";
        }
        &HASH_TEXT[start..start + n]
    }
}

// Go: ToHash
/// Returns the hash whose name is s. It returns zero if there is no such
/// hash. It is case sensitive.
pub fn to_hash<B: ByteView + ?Sized>(s: &B) -> Hash {
    if s.len() == 0 || s.len() > HASH_MAX_LEN {
        return Hash(0);
    }
    let mut h: u32 = HASH_HASH0;
    for i in 0..s.len() {
        h ^= s.at(i) as u32;
        h = h.wrapping_mul(16777619);
    }
    let i = HASH_TABLE[(h & (HASH_TABLE.len() as u32 - 1)) as usize];
    if (i.0 & 0xff) as usize == s.len() {
        let t = &HASH_TEXT[(i.0 >> 8) as usize..(i.0 >> 8) as usize + (i.0 & 0xff) as usize];
        let mut ok = true;
        for k in 0..s.len() {
            if t[k] != s.at(k) {
                ok = false; // goto NEXT
                break;
            }
        }
        if ok {
            return i;
        }
    }
    // NEXT:
    let i = HASH_TABLE[((h >> 16) & (HASH_TABLE.len() as u32 - 1)) as usize];
    if (i.0 & 0xff) as usize == s.len() {
        let t = &HASH_TEXT[(i.0 >> 8) as usize..(i.0 >> 8) as usize + (i.0 & 0xff) as usize];
        for k in 0..s.len() {
            if t[k] != s.at(k) {
                return Hash(0);
            }
        }
        return i;
    }
    Hash(0)
}
`)
	return b.String()
}

// mapLit returns the composite literal of the package-level var `name`.
func (p *typedPkg) mapLit(file, name string) *ast.CompositeLit {
	var lit *ast.CompositeLit
	ast.Inspect(p.files[file], func(nd ast.Node) bool {
		if vs, ok := nd.(*ast.ValueSpec); ok && len(vs.Names) == 1 && vs.Names[0].Name == name {
			lit = vs.Values[0].(*ast.CompositeLit)
		}
		return true
	})
	if lit == nil {
		panic("no var " + name)
	}
	return lit
}

func (p *typedPkg) src(e ast.Expr) string {
	var b bytes.Buffer
	start := p.fset.Position(e.Pos()).Offset
	end := p.fset.Position(e.End()).Offset
	fn := p.fset.Position(e.Pos()).Filename
	data, err := os.ReadFile(fn)
	if err != nil {
		panic(err)
	}
	b.Write(data[start:end])
	return b.String()
}

// traitsMatch emits `fn name(h: Hash) -> Traits` for a map[Hash]traits
// literal, keeping the Go key names and trait expressions.
func traitsMatch(p *typedPkg, file, varName, fnName, doc string) string {
	lit := p.mapLit(file, varName)
	var b bytes.Buffer
	fmt.Fprintf(&b, "/// Go: %s — %s\npub fn %s(h: Hash) -> Traits {\n    match h {\n", varName, doc, fnName)
	seen := map[uint64]string{}
	for _, e := range lit.Elts {
		kv := e.(*ast.KeyValueExpr)
		k := u64(p.info.Types[kv.Key].Value)
		if prev, ok := seen[k]; ok {
			panic(fmt.Sprintf("duplicate key %s/%s", prev, p.src(kv.Key)))
		}
		seen[k] = p.src(kv.Key)
		fmt.Fprintf(&b, "        %s => %s,\n", p.src(kv.Key), p.src(kv.Value))
	}
	b.WriteString("        _ => 0, // zero if not exist\n    }\n}\n")
	return b.String()
}

func boolMatch(p *typedPkg, file, varName, fnName, doc string) string {
	lit := p.mapLit(file, varName)
	var b bytes.Buffer
	fmt.Fprintf(&b, "/// Go: %s — %s\npub fn %s(h: Hash) -> bool {\n    match h {\n", varName, doc, fnName)
	for _, e := range lit.Elts {
		kv := e.(*ast.KeyValueExpr)
		if p.src(kv.Value) != "true" {
			panic("non-true value")
		}
		fmt.Fprintf(&b, "        %s => true,\n", p.src(kv.Key))
	}
	b.WriteString("        _ => false,\n    }\n}\n")
	return b.String()
}

func stringBoolMatch(p *typedPkg, file, varName, fnName, doc string) string {
	lit := p.mapLit(file, varName)
	var b bytes.Buffer
	fmt.Fprintf(&b, "/// Go: %s — %s\npub fn %s(s: &[u8]) -> bool {\n    match s {\n", varName, doc, fnName)
	for _, e := range lit.Elts {
		kv := e.(*ast.KeyValueExpr)
		if p.src(kv.Value) != "true" {
			panic("non-true value")
		}
		k := constant.StringVal(p.info.Types[kv.Key].Value)
		fmt.Fprintf(&b, "        %s => true,\n", rustBytes(k))
	}
	b.WriteString("        _ => false,\n    }\n}\n")
	return b.String()
}

func writeFile(dir, name, content string) {
	fn := filepath.Join(dir, name)
	if err := os.MkdirAll(filepath.Dir(fn), 0o755); err != nil {
		panic(err)
	}
	if err := os.WriteFile(fn, []byte(content), 0o644); err != nil {
		panic(err)
	}
}

// genTables writes the generated Rust sources into OUTDIR (the crate's
// src/ directory).
func genTables(outDir string) {
	header := "// generated by tools/go-oracle/tdewolff-minify tables (" + goVersion() + "); DO NOT EDIT\n"

	// hash.go files
	writeFile(outDir, "html/hash.rs", genHash("html", func(n string, h uint32) bool {
		return uint32(html.ToHash([]byte(n))) == h && html.Hash(h).String() == n
	}))
	writeFile(outDir, "css/hash.rs", genHash("css", func(n string, h uint32) bool { return uint32(css.ToHash([]byte(n))) == h && css.Hash(h).String() == n }))
	writeFile(outDir, "svg/hash.rs", genHash("svg", func(n string, h uint32) bool { return uint32(svg.ToHash([]byte(n))) == h && svg.Hash(h).String() == n }))

	// html/table.go
	{
		p := loadPkg("html", "hash.go", "table.go")
		var b bytes.Buffer
		b.WriteString("//! Go: minify/html/table.go (tag/attribute traits, jsMimetypes,\n//! EntitiesMap, TextRevEntitiesMap).\n")
		b.WriteString(header)
		b.WriteString("\nuse super::hash::*;\n\n")
		b.WriteString("/// Go: html.traits\npub type Traits = u16;\n\n")
		b.WriteString("pub const normalTag: Traits = 1 << 0;\npub const rawTag: Traits = 1 << 1; // raw tags need special processing for their content\npub const blockTag: Traits = 1 << 2; // remove spaces around these tags\npub const objectTag: Traits = 1 << 3; // keep spaces after these open/close tags\npub const omitPTag: Traits = 1 << 4; // omit p end tag if it is followed by this start tag\npub const keepPTag: Traits = 1 << 5; // keep p end tag if it is followed by this end tag\n\n")
		b.WriteString("pub const booleanAttr: Traits = 1 << 0;\npub const urlAttr: Traits = 1 << 1;\npub const trimAttr: Traits = 1 << 2;\n\n")
		b.WriteString(traitsMatch(p, "table.go", "tagMap", "tag_map", "traits of a tag hash."))
		b.WriteString("\n")
		b.WriteString(traitsMatch(p, "table.go", "attrMap", "attr_map", "traits of an attribute hash."))
		b.WriteString("\n")
		b.WriteString(stringBoolMatch(p, "table.go", "jsMimetypes", "js_mimetypes", "JS mimetypes (default `type` values)."))
		writeFile(outDir, "html/table.rs", b.String())

		// entities
		var e bytes.Buffer
		e.WriteString("//! Go: minify/html/table.go EntitiesMap and TextRevEntitiesMap (data).\n")
		e.WriteString(header)
		keys := make([]string, 0, len(html.EntitiesMap))
		for k := range html.EntitiesMap {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		fmt.Fprintf(&e, "\n/// Go: html.EntitiesMap, sorted by name (%d entries).\npub(crate) static ENTITIES: [(&[u8], &[u8]); %d] = [\n", len(keys), len(keys))
		for _, k := range keys {
			fmt.Fprintf(&e, "    (%s, %s),\n", rustBytes(k), rustBytes(string(html.EntitiesMap[k])))
		}
		e.WriteString("];\n")
		if len(html.TextRevEntitiesMap) != 1 || string(html.TextRevEntitiesMap['<']) != "&lt;" {
			panic("unexpected html.TextRevEntitiesMap")
		}
		writeFile(outDir, "html/entities.rs", e.String())
	}

	// xml/table.go sanity (hand-ported)
	if len(xml.EntitiesMap) != 3 || string(xml.EntitiesMap["apos"]) != "'" || string(xml.EntitiesMap["gt"]) != ">" || string(xml.EntitiesMap["quot"]) != "\"" ||
		len(xml.TextRevEntitiesMap) != 2 || string(xml.TextRevEntitiesMap['<']) != "&lt;" || string(xml.TextRevEntitiesMap['&']) != "&amp;" {
		panic("unexpected xml tables")
	}

	// css/table.go
	{
		p := loadPkg("css", "hash.go", "table.go")
		var b bytes.Buffer
		b.WriteString("//! Go: minify/css/table.go (optionalZeroDimension, ShortenColorHex,\n//! ShortenColorName). PropertyOverrides is not used by the minifier and is\n//! not ported.\n")
		b.WriteString(header)
		b.WriteString("\nuse super::hash::*;\n\n")
		b.WriteString(stringBoolMatch(p, "table.go", "optionalZeroDimension", "optional_zero_dimension", "units that can be dropped from a zero value."))
		// ShortenColorHex
		keys := make([]string, 0, len(css.ShortenColorHex))
		for k := range css.ShortenColorHex {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		b.WriteString("\n/// Go: css.ShortenColorHex — maps a color hexcode to its shorter name.\npub fn shorten_color_hex(s: &[u8]) -> Option<&'static [u8]> {\n    match s {\n")
		for _, k := range keys {
			fmt.Fprintf(&b, "        %s => Some(%s),\n", rustBytes(k), rustBytes(string(css.ShortenColorHex[k])))
		}
		b.WriteString("        _ => Option::None,\n    }\n}\n")
		// ShortenColorName (keep source order and names)
		lit := p.mapLit("table.go", "ShortenColorName")
		b.WriteString("\n/// Go: css.ShortenColorName — maps a color name to its shorter hexcode.\npub fn shorten_color_name(h: Hash) -> Option<&'static [u8]> {\n    match h {\n")
		cnt := 0
		for _, el := range lit.Elts {
			kv := el.(*ast.KeyValueExpr)
			k := css.Hash(u64(p.info.Types[kv.Key].Value))
			fmt.Fprintf(&b, "        %s => Some(%s),\n", p.src(kv.Key), rustBytes(string(css.ShortenColorName[k])))
			cnt++
		}
		if cnt != len(css.ShortenColorName) {
			panic("ShortenColorName mismatch")
		}
		b.WriteString("        _ => Option::None,\n    }\n}\n")
		writeFile(outDir, "css/table.rs", b.String())
	}

	// svg/table.go
	{
		p := loadPkg("svg", "hash.go", "table.go")
		var b bytes.Buffer
		b.WriteString("//! Go: minify/svg/table.go (colorAttrMap).\n")
		b.WriteString(header)
		b.WriteString("\nuse super::hash::*;\n\n")
		b.WriteString(boolMatch(p, "table.go", "colorAttrMap", "color_attr_map", "attributes holding a color."))
		writeFile(outDir, "svg/table.rs", b.String())
	}
}
