package main

import (
	"bytes"
	stdjson "encoding/json"
	"fmt"
	"hash/fnv"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/tdewolff/parse/v2/buffer"
)

// mediatypeFor maps a published file to the media type neohugo minifies it
// with (RSS and sitemaps both reach the same XML minifier).
func mediatypeFor(p string) (string, bool) {
	switch strings.ToLower(filepath.Ext(p)) {
	case ".html", ".htm":
		return "text/html", true
	case ".xml":
		return "application/rss+xml", true
	case ".json":
		return "application/json", true
	case ".css", ".scss":
		return "text/css", true
	case ".svg":
		return "image/svg+xml", true
	}
	return "", false
}

func fnv64(b []byte) string {
	h := fnv.New64a()
	h.Write(b)
	return fmt.Sprintf("%016x", h.Sum64())
}

func walkFiles(root string, exts []string) []string {
	var files []string
	_ = filepath.Walk(root, func(p string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() {
			return nil
		}
		for _, e := range exts {
			if strings.HasSuffix(p, e) {
				files = append(files, p)
				return nil
			}
		}
		return nil
	})
	sort.Strings(files)
	return files
}

// minifyTree minifies every .html/.xml/.json of SRC (seeksnack config, no
// JS) into OUT (same relative paths); files that fail get OUT/rel.err.
func minifyTree(src, out string) {
	m := seeksnackM()
	n, nerr := 0, 0
	for _, p := range walkFiles(src, []string{".html", ".xml", ".json"}) {
		rel, _ := filepath.Rel(src, p)
		mt, _ := mediatypeFor(p)
		in, err := os.ReadFile(p)
		if err != nil {
			panic(err)
		}
		var w bytes.Buffer
		err = m.Minify(mt, &w, buffer.NewReader(in))
		op := filepath.Join(out, rel)
		_ = os.MkdirAll(filepath.Dir(op), 0o755)
		if err != nil {
			nerr++
			_ = os.WriteFile(op+".err", []byte(err.Error()), 0o644)
		}
		_ = os.WriteFile(op, w.Bytes(), 0o644)
		n++
	}
	fmt.Fprintf(os.Stderr, "minified %d files (%d errors)\n", n, nerr)
}

// treeDigests writes `REL INLEN OUTLEN FNV64(OUT) ERR` for every file of
// SRC with one of the extensions (seeksnack config, no JS).
func treeDigests(src, outTSV string, exts []string) {
	if len(exts) == 0 {
		exts = []string{".html", ".xml", ".json"}
	}
	m := seeksnackM()
	var b strings.Builder
	fmt.Fprintf(&b, "# generated by tools/go-oracle/tdewolff-minify digests (%s); DO NOT EDIT\n", goVersion())
	for _, p := range walkFiles(src, exts) {
		rel, _ := filepath.Rel(src, p)
		mt, _ := mediatypeFor(p)
		in, err := os.ReadFile(p)
		if err != nil {
			panic(err)
		}
		var w bytes.Buffer
		err = m.Minify(mt, &w, buffer.NewReader(in))
		fmt.Fprintf(&b, "%s\t%d\t%d\t%s\t%s\n", rel, len(in), w.Len(), fnv64(w.Bytes()), errStr(err))
	}
	if err := os.WriteFile(outTSV, []byte(b.String()), 0o644); err != nil {
		panic(err)
	}
}

// nestedDigests runs the recorded nested inputs of corpus2/KIND (the
// minifier calls made while building seeksnack) through the seeksnack M
// with the recorded mimetype parameters, and writes
// `KEY INLEN OUTLEN FNV64(OUT) ERR SAME_AS_RECORDED`.
func nestedDigests(root, kindName, outTSV string) {
	m := seeksnackM()
	dir := filepath.Join(root, kindName)
	var mimetype string
	switch kindName {
	case "css", "css-resource":
		mimetype = "text/css"
	case "json":
		mimetype = "application/json"
	case "svg":
		mimetype = "image/svg+xml"
	default:
		panic("unknown nested kind " + kindName)
	}
	var b strings.Builder
	fmt.Fprintf(&b, "# generated by tools/go-oracle/tdewolff-minify nested (%s); DO NOT EDIT\n", goVersion())
	for _, p := range walkFiles(dir, []string{".in"}) {
		key := strings.TrimSuffix(filepath.Base(p), ".in")
		in, err := os.ReadFile(p)
		if err != nil {
			panic(err)
		}
		params := map[string]string(nil)
		if mb, err := os.ReadFile(strings.TrimSuffix(p, ".in") + ".meta.json"); err == nil {
			var meta struct {
				Params map[string]string `json:"params"`
			}
			if err := stdjson.Unmarshal(mb, &meta); err != nil {
				panic(err)
			}
			params = meta.Params
		}
		var w bytes.Buffer
		err = m.MinifyMimetype([]byte(mimetype), &w, buffer.NewReader(in), params)
		same := "-"
		if rec, e := os.ReadFile(strings.TrimSuffix(p, ".in") + ".out"); e == nil {
			same = strconv.FormatBool(bytes.Equal(rec, w.Bytes()))
		}
		ps := "-"
		if params != nil {
			var keys []string
			for k := range params {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			var kv []string
			for _, k := range keys {
				kv = append(kv, k+"="+params[k])
			}
			ps = strings.Join(kv, ";")
		}
		fmt.Fprintf(&b, "%s\t%s\t%d\t%d\t%s\t%s\t%s\n", key, ps, len(in), w.Len(), fnv64(w.Bytes()), errStr(err), same)
	}
	if err := os.WriteFile(outTSV, []byte(b.String()), 0o644); err != nil {
		panic(err)
	}
}

// allConfigDigests writes `CONFIG REL INLEN OUTLEN FNV64(OUT) ERR
// FNV64(INPUT AFTER)` for every file of SRC with one of the extensions,
// through every named configuration (the golden corpus exercises far more
// minifier options than the seeksnack configuration alone).
func allConfigDigests(src, outTSV string, cfgs []string, exts []string) {
	var b strings.Builder
	fmt.Fprintf(&b, "# generated by tools/go-oracle/tdewolff-minify cfgdigests (%s); DO NOT EDIT\n", goVersion())
	files := walkFiles(src, exts)
	for _, cfg := range cfgs {
		m := configByName(cfg)
		for _, p := range files {
			rel, _ := filepath.Rel(src, p)
			mt, _ := mediatypeFor(p)
			in, err := os.ReadFile(p)
			if err != nil {
				panic(err)
			}
			out, after, err := runM(m, mt, in)
			fmt.Fprintf(&b, "%s\t%s\t%d\t%d\t%s\t%s\t%s\n", cfg, rel, len(in), len(out), fnv64(out), errStr(err), fnv64(after))
		}
	}
	if err := os.WriteFile(outTSV, []byte(b.String()), 0o644); err != nil {
		panic(err)
	}
}
