//! Ports of goldmark's own Go tests: ast/ast_test.go (TestWalk),
//! ast_test.go (TestASTBlockNodeText, TestASTInlineNodeText,
//! TestHasBlankPreviousLines), extra_test.go (TestEndsWithNonSpaceCharacters,
//! TestWindowsNewLine, TestAutogeneratedIDs, the *Performance tests,
//! TestDangerousURLStringCase). CommonMark spec.json, extra.txt and
//! options.txt are in tests/oracle.rs.

mod common;

use goldmark::ast::{self, Ast, NodeId, NodeKind, WalkStatus};
use goldmark::parser::{self, IDs};
use goldmark::renderer::html;
use goldmark::text;

fn xu() -> goldmark::Markdown {
    common::new_markdown("xu")
}

fn convert(md: &goldmark::Markdown, src: &[u8]) -> String {
    let mut out: Vec<u8> = Vec::new();
    md.convert(src, &mut out).unwrap();
    String::from_utf8(out).unwrap()
}

// Go: ast/ast_test.go:TestWalk
#[test]
fn walk() {
    fn build(ast: &mut Ast) -> NodeId {
        let doc = ast.new_document();
        let h = ast.new_heading(1);
        let t = ast.new_text();
        ast.append_child(h, t);
        ast.append_child(doc, h);
        let l = ast.new_link();
        ast.append_child(doc, l);
        doc
    }
    type Case = (&'static str, Vec<NodeKind>, Vec<(NodeKind, WalkStatus)>);
    let cases: Vec<Case> = vec![
        (
            "visits all in depth first order",
            vec![
                ast::KIND_DOCUMENT,
                ast::KIND_HEADING,
                ast::KIND_TEXT,
                ast::KIND_LINK,
            ],
            vec![],
        ),
        (
            "stops after heading",
            vec![ast::KIND_DOCUMENT, ast::KIND_HEADING],
            vec![(ast::KIND_HEADING, WalkStatus::Stop)],
        ),
        (
            "skip children",
            vec![ast::KIND_DOCUMENT, ast::KIND_HEADING, ast::KIND_LINK],
            vec![(ast::KIND_HEADING, WalkStatus::SkipChildren)],
        ),
    ];
    for (name, want, action) in cases {
        let mut a = Ast::new();
        let doc = build(&mut a);
        let mut kinds = Vec::new();
        ast::walk(&mut a, doc, &mut |a, n, entering| {
            if entering {
                kinds.push(a.kind(n));
            }
            for (k, s) in &action {
                if *k == a.kind(n) {
                    return Ok(*s);
                }
            }
            Ok(WalkStatus::Continue)
        })
        .unwrap();
        assert_eq!(kinds, want, "{name}");
    }
}

fn parse(src: &[u8]) -> goldmark::parser::ParseResult {
    let md = goldmark::new(vec![]);
    let mut pc = parser::new_context(vec![]);
    md.parse(src, &mut pc)
}

// Go: ast_test.go:TestASTBlockNodeText
#[test]
fn ast_block_node_text() {
    let cases: Vec<(&str, &str, &str, &str, bool)> = vec![
        ("AtxHeading", "# l1\n\na\n\n# l2", "l1", "l2", false),
        (
            "SetextHeading",
            "l1\nl2\n===============\n\na\n\nl3\nl4\n==============",
            "l1\nl2",
            "l3\nl4",
            false,
        ),
        (
            "CodeBlock",
            "    l1\n    l2\n\na\n\n    l3\n\tl4",
            "l1\nl2\n",
            "l3\nl4\n",
            false,
        ),
        (
            "FencedCodeBlock",
            "```\nl1\nl2\n```\n\na\n\n```\nl3\nl4",
            "l1\nl2\n",
            "l3\nl4\n",
            false,
        ),
        (
            "Blockquote",
            "> l1\n> l2\n\na\n\n> l3\n> l4",
            "l1\nl2",
            "l3\nl4",
            false,
        ),
        (
            "List",
            "- l1\n  l2\n\na\n\n- l3\n  l4",
            "l1\nl2",
            "l3\nl4",
            true,
        ),
        (
            "HTMLBlock",
            "<div>\nl1\nl2\n</div>\n\na\n\n<div>\nl3\nl4",
            "<div>\nl1\nl2\n</div>\n",
            "<div>\nl3\nl4",
            false,
        ),
    ];
    for (name, source, t1, t2, c) in cases {
        let s = source.as_bytes();
        let doc = parse(s);
        let a = &doc.ast;
        let mut c1 = a.first_child(doc.root).unwrap();
        let mut c2 = a.next_sibling(a.next_sibling(c1).unwrap()).unwrap();
        if c {
            c1 = a.first_child(c1).unwrap();
            c2 = a.first_child(c2).unwrap();
        }
        assert_eq!(String::from_utf8_lossy(&a.text(c1, s)), t1, "{name}");
        assert_eq!(String::from_utf8_lossy(&a.text(c2, s)), t2, "{name}(EOF)");
    }
}

// Go: ast_test.go:TestASTInlineNodeText
#[test]
fn ast_inline_node_text() {
    let cases = [
        ("CodeSpan", "`c1`", "c1"),
        ("Emphasis", "*c1 **c2***", "c1 c2"),
        ("Link", "[label](url)", "label"),
        ("AutoLink", "<http://url>", "http://url"),
        ("RawHTML", "<span>c1</span>", "<span>"),
    ];
    for (name, source, t1) in cases {
        let s = source.as_bytes();
        let doc = parse(s);
        let a = &doc.ast;
        let c1 = a.first_child(a.first_child(doc.root).unwrap()).unwrap();
        assert_eq!(String::from_utf8_lossy(&a.text(c1, s)), t1, "{name}");
    }
}

// Go: ast_test.go:TestHasBlankPreviousLines
#[test]
fn has_blank_previous_lines() {
    type Pick = fn(&Ast, NodeId) -> NodeId;
    let fc = |a: &Ast, n: NodeId| a.first_child(n).unwrap();
    let ns = |a: &Ast, n: NodeId| a.next_sibling(n).unwrap();
    let _ = (fc, ns);
    let p2: Pick = |a, n| {
        a.next_sibling(a.first_child(a.first_child(n).unwrap()).unwrap())
            .unwrap()
    };
    let p3: Pick = |a, n| {
        a.next_sibling(
            a.first_child(a.first_child(a.first_child(n).unwrap()).unwrap())
                .unwrap(),
        )
        .unwrap()
    };
    let cases: Vec<(&str, &str, Pick, bool)> = vec![
        (
            "nesting paragraphs in blockquotes",
            "\n> a\n> \n> b\n",
            p2,
            true,
        ),
        (
            "nesting HTML blocks in blockquotes",
            "\n> <!-- a -->\n> \n> <!-- b -->\n",
            p2,
            true,
        ),
        (
            "nesting HTML blocks in blockquotes",
            "\n> <!-- a -->\n> <!-- b -->\n",
            p2,
            false,
        ),
        (
            "nesting loose lists in blockquotes",
            "\n> - a\n> \n> - b\n",
            p3,
            true,
        ),
        (
            "nesting tight lists in blockquotes",
            "\n> - a\n> - b\n",
            p3,
            false,
        ),
        ("nesting paragraphs in lists", "\n- a\n\n  b\n", p3, true),
    ];
    for (name, source, pick, expected) in cases {
        let doc = parse(source.as_bytes());
        let n = pick(&doc.ast, doc.root);
        assert_eq!(doc.ast.has_blank_previous_lines(n), expected, "{name}");
    }
}

// Go: extra_test.go:TestEndsWithNonSpaceCharacters
#[test]
fn ends_with_non_space_characters() {
    assert_eq!(
        convert(&xu(), b"```\na\n```"),
        "<pre><code>a\n</code></pre>\n"
    );
}

// Go: extra_test.go:TestWindowsNewLine
#[test]
fn windows_new_line() {
    let md = goldmark::new(vec![goldmark::with_renderer_options(vec![Box::new(
        html::with_xhtml(),
    )])]);
    assert_eq!(convert(&md, b"a  \r\nb\n"), "<p>a<br />\nb</p>\n");
    assert_eq!(convert(&md, b"a\\\r\nb\r\n"), "<p>a<br />\nb</p>\n");
}

struct MyIDs;

impl IDs for MyIDs {
    fn generate(&mut self, _value: &[u8], _kind: NodeKind) -> Vec<u8> {
        b"my-id".to_vec()
    }
    fn put(&mut self, _value: &[u8]) {}
}

// Go: extra_test.go:TestAutogeneratedIDs
#[test]
fn autogenerated_ids() {
    let mut ctx = parser::new_context(vec![parser::with_ids(Box::new(MyIDs))]);
    let md = goldmark::new(vec![goldmark::with_parser_options(vec![Box::new(
        parser::with_auto_heading_id(),
    )])]);
    let mut out: Vec<u8> = Vec::new();
    md.convert_with_context(b"# Title1\n## Title2", &mut out, &mut ctx)
        .unwrap();
    assert_eq!(
        String::from_utf8(out).unwrap(),
        "<h1 id=\"my-id\">Title1</h1>\n<h2 id=\"my-id\">Title2</h2>\n"
    );
}

fn perf(src: Vec<u8>) {
    // Go: 5s * GOLDMARK_TEST_TIMEOUT_MULTIPLIER. The default multiplier here
    // is 6: unoptimized builds and loaded CI machines are slower, and the
    // tests exist to catch quadratic blow-ups (minutes), not constant factors.
    let multiplier: f64 = std::env::var("GOLDMARK_TEST_TIMEOUT_MULTIPLIER")
        .ok()
        .and_then(|v| v.parse().ok())
        .unwrap_or(6.0);
    let md = xu();
    let started = std::time::Instant::now();
    let mut out: Vec<u8> = Vec::new();
    let _ = md.convert(&src, &mut out);
    assert!(
        started.elapsed().as_secs_f64() < 5.0 * multiplier,
        "took too long: {:?}",
        started.elapsed()
    );
}

// Go: extra_test.go:TestDeepNestedLabelPerformance
#[test]
fn deep_nested_label_performance() {
    let n = 50000;
    let mut s = "[".repeat(n);
    s.push_str(&"]".repeat(n));
    perf(s.into_bytes());
}

// Go: extra_test.go:TestManyProcessingInstructionPerformance
#[test]
fn many_processing_instruction_performance() {
    perf(format!("a {}", "<?".repeat(50000)).into_bytes());
}

// Go: extra_test.go:TestManyCDATAPerformance
#[test]
fn many_cdata_performance() {
    perf("a <![CDATA[".repeat(50000).into_bytes());
}

// Go: extra_test.go:TestManyDeclPerformance
#[test]
fn many_decl_performance() {
    perf("a <!A ".repeat(50000).into_bytes());
}

// Go: extra_test.go:TestManyCommentPerformance
#[test]
fn many_comment_performance() {
    perf("a <!-- ".repeat(50000).into_bytes());
}

// Go: extra_test.go:TestDangerousURLStringCase
#[test]
fn dangerous_url_string_case() {
    let md = goldmark::new(vec![]);
    let source = b"[Basic](javascript:alert('Basic'))\n[CaseInsensitive](JaVaScRiPt:alert('CaseInsensitive'))\n";
    assert_eq!(
        convert(&md, source),
        "<p><a href=\"\">Basic</a>\n<a href=\"\">CaseInsensitive</a></p>\n"
    );
}

#[test]
fn text_reader_basics() {
    use text::Reader;
    let src = b"ab\ncd";
    let mut r = text::new_reader(src);
    let (l, _) = r.peek_line();
    assert_eq!(&*l.unwrap(), b"ab\n");
    r.advance(3);
    assert_eq!(r.position().0, 1);
    assert_eq!(r.peek(), b'c');
    r.advance(2);
    assert_eq!(r.peek(), text::EOF);
    assert!(r.peek_line().0.is_none());
}

#[test]
fn markdown_is_send_and_sync() {
    fn assert_send_sync<T: Send + Sync>() {}
    assert_send_sync::<goldmark::Markdown>();
    assert_send_sync::<goldmark::ast::Ast>();
    fn assert_send<T: Send>() {}
    assert_send::<goldmark::parser::Context>();
}

#[test]
fn deep_nesting_on_a_small_stack() {
    // Go recurses on growable goroutine stacks; the port must not overflow
    // a 2 MiB thread stack on deeply nested input.
    let h = std::thread::Builder::new()
        .stack_size(2 << 20)
        .spawn(|| {
            let md = goldmark::new(vec![]);
            let mut src = ">".repeat(20000);
            src.push_str(" a\n");
            src.push_str(&"*".repeat(50000));
            src.push('a');
            src.push_str(&"*".repeat(50000));
            src.push_str("\n![");
            src.push_str(&"*".repeat(20000));
            src.push('a');
            src.push_str(&"*".repeat(20000));
            src.push_str("](x)\n");
            let mut out: Vec<u8> = Vec::new();
            md.convert(src.as_bytes(), &mut out).unwrap();
            out.len()
        })
        .unwrap();
    assert!(h.join().unwrap() > 100_000);
}
