//! Differential tests against fixtures generated by tools/go-oracle/go-time
//! (Go go1.27.1 `time`). Local is pinned to Asia/Bangkok ("Local").

mod common;

use std::collections::HashMap;
use std::sync::Arc;

use common::*;
use go_time::{Duration, GoTimeExt, Location, Month, Time};

#[test]
fn format_fixture() {
    setup();
    let mut c = Checker::new("format");
    for r in records("format.txt") {
        let t = t_in(r.i(2), r.i(3), &r.s(1));
        match r.tag() {
            b"F" => {
                let got = t.format_bytes(r.b(4));
                c.check(got == r.b(5), || {
                    format!("{} got {:?}", show(&r), String::from_utf8_lossy(&got))
                });
                // Format(&str) must agree whenever the layout is UTF-8.
                if let Ok(layout) = std::str::from_utf8(r.b(4)) {
                    let s = t.format(layout);
                    c.check(s.as_bytes() == r.b(5), || {
                        format!("{} format(&str) got {:?}", show(&r), s)
                    });
                }
            }
            b"S" => {
                let s = t.string();
                c.check(s.as_bytes() == r.b(4), || {
                    format!("{} String got {:?}", show(&r), s)
                });
                let g = t.go_string();
                c.check(g.as_bytes() == r.b(5), || {
                    format!("{} GoString got {:?}", show(&r), g)
                });
            }
            other => panic!("unknown tag {:?}", other),
        }
    }
    c.finish();
}

#[test]
fn parse_fixture() {
    setup();
    let mut c = Checker::new("parse");
    for r in records("parse.txt") {
        assert_eq!(r.tag(), b"P");
        let mode = r.s(1);
        let res = if mode == "Parse" {
            go_time::parse(r.b(3), r.b(4))
        } else {
            go_time::parse_in_location(r.b(3), r.b(4), &loc(&r.s(2)))
        };
        match (&res, r.b(5)) {
            (Ok(t), b"OK") => {
                let got = time_fields(t);
                c.check(fields_eq(&r, 6, &got), || {
                    format!("{} got {:?}", show(&r), got)
                });
            }
            (Err(e), b"ERR") => {
                let msg = e.error();
                c.check(msg.as_bytes() == r.b(6), || {
                    format!("{} got error {:?}", show(&r), msg)
                });
            }
            (Ok(t), _) => c.check(false, || {
                format!("{} got OK {:?}", show(&r), time_fields(t))
            }),
            (Err(e), _) => c.check(false, || format!("{} got ERR {:?}", show(&r), e.error())),
        }
    }
    c.finish();
}

#[test]
fn duration_fixture() {
    let mut c = Checker::new("duration");
    for r in records("duration.txt") {
        match r.tag() {
            b"D" => {
                let d = Duration(r.i(1));
                let bits = |f: f64| format!("{:x}", f.to_bits());
                let got = vec![
                    d.string(),
                    bits(d.hours()),
                    bits(d.minutes()),
                    bits(d.seconds()),
                    d.milliseconds().to_string(),
                    d.microseconds().to_string(),
                    d.abs().0.to_string(),
                ];
                c.check(fields_eq(&r, 2, &got), || {
                    format!("{} got {:?}", show(&r), got)
                });
                c.check(format!("{}", d) == got[0], || "Display".to_string());
            }
            b"DR" => {
                let d = Duration(r.i(1));
                let m = Duration(r.i(2));
                let got = vec![d.round(m).0.to_string(), d.truncate(m).0.to_string()];
                c.check(fields_eq(&r, 3, &got), || {
                    format!("{} got {:?}", show(&r), got)
                });
            }
            b"PD" => {
                let res = go_time::parse_duration(r.b(1));
                match (&res, r.b(2)) {
                    (Ok(d), b"OK") => {
                        c.check(d.0 == r.i(3), || format!("{} got {}", show(&r), d.0))
                    }
                    (Err(e), b"ERR") => c.check(e.error().as_bytes() == r.b(3), || {
                        format!("{} got {:?}", show(&r), e.error())
                    }),
                    _ => c.check(false, || format!("{} got {:?}", show(&r), res)),
                }
            }
            other => panic!("unknown tag {:?}", other),
        }
    }
    c.finish();
}

#[test]
fn calendar_fixture() {
    setup();
    let mut c = Checker::new("calendar");
    let b2s = |b: bool| if b { "1".to_string() } else { "0".to_string() };
    let zb = |t: &Time| {
        if t.go_is_zero() {
            "Z".to_string()
        } else {
            t.go_unix().to_string()
        }
    };
    for r in records("calendar.txt") {
        match r.tag() {
            b"C" => {
                let t = t_in(r.i(2), r.i(3), &r.s(1));
                let (y, m, d) = t.date();
                let (h, mi, s) = t.clock();
                let (iy, iw) = t.iso_week();
                let (st, en) = t.zone_bounds();
                let got = vec![
                    y.to_string(),
                    m.0.to_string(),
                    d.to_string(),
                    h.to_string(),
                    mi.to_string(),
                    s.to_string(),
                    t.year_day().to_string(),
                    t.weekday().0.to_string(),
                    iy.to_string(),
                    iw.to_string(),
                    t.unix_milli().to_string(),
                    t.unix_micro().to_string(),
                    t.go_unix_nano().to_string(),
                    b2s(t.go_is_zero()),
                    b2s(t.is_dst()),
                    zb(&st),
                    zb(&en),
                    t.month().string(),
                    t.weekday().string(),
                ];
                c.check(fields_eq(&r, 4, &got), || {
                    format!("{} got {:?}", show(&r), got)
                });
                // The single-field accessors agree with Date/Clock.
                c.check(
                    t.year() == y
                        && t.month() == m
                        && t.day() == d
                        && t.hour() == h
                        && t.minute() == mi
                        && t.second() == s,
                    || format!("{} accessors", show(&r)),
                );
            }
            b"AD" => {
                let t = t_in(r.i(2), r.i(3), &r.s(1));
                let got = time_fields(&t.add_date(r.i(4), r.i(5), r.i(6)));
                c.check(fields_eq(&r, 7, &got), || {
                    format!("{} got {:?}", show(&r), got)
                });
            }
            b"AS" => {
                let t = t_in(r.i(2), r.i(3), &r.s(1));
                let got = time_fields(&t.add(Duration(r.i(4))));
                c.check(fields_eq(&r, 5, &got), || {
                    format!("{} got {:?}", show(&r), got)
                });
            }
            b"SUB" => {
                let t = go_time::unix(r.i(1), r.i(2));
                let u = go_time::unix(r.i(3), r.i(4));
                let got = vec![
                    t.sub(&u).0.to_string(),
                    t.compare(&u).to_string(),
                    b2s(t.go_before(&u)),
                    b2s(t.go_after(&u)),
                    b2s(t.go_equal(&u)),
                ];
                c.check(fields_eq(&r, 5, &got), || {
                    format!("{} got {:?}", show(&r), got)
                });
            }
            b"TR" => {
                let t = t_in(r.i(2), r.i(3), &r.s(1));
                let d = Duration(r.i(4));
                let mut got = time_fields(&t.truncate(d));
                got.extend(time_fields(&t.round(d)));
                c.check(fields_eq(&r, 5, &got), || {
                    format!("{} got {:?}", show(&r), got)
                });
            }
            b"DT" => {
                let l = loc(&r.s(1));
                let t = go_time::date(
                    r.i(2),
                    Month(r.i(3)),
                    r.i(4),
                    r.i(5),
                    r.i(6),
                    r.i(7),
                    r.i(8),
                    &l,
                );
                let got = time_fields(&t);
                c.check(fields_eq(&r, 9, &got), || {
                    format!("{} got {:?}", show(&r), got)
                });
            }
            b"U" => {
                let got = time_fields(&go_time::unix(r.i(1), r.i(2)));
                c.check(fields_eq(&r, 3, &got), || {
                    format!("{} got {:?}", show(&r), got)
                });
            }
            b"UM" => {
                let got = time_fields(&go_time::unix_milli(r.i(1)));
                c.check(fields_eq(&r, 2, &got), || {
                    format!("{} got {:?}", show(&r), got)
                });
            }
            b"UU" => {
                let got = time_fields(&go_time::unix_micro(r.i(1)));
                c.check(fields_eq(&r, 2, &got), || {
                    format!("{} got {:?}", show(&r), got)
                });
            }
            b"MS" => {
                let v = r.i(1);
                let got = vec![Month(v).string(), go_time::Weekday(v).string()];
                c.check(fields_eq(&r, 2, &got), || {
                    format!("{} got {:?}", show(&r), got)
                });
            }
            other => panic!("unknown tag {:?}", other),
        }
    }
    c.finish();
}

#[test]
fn binary_fixture() {
    setup();
    let mut c = Checker::new("binary");
    let or_err = |r: Result<Vec<u8>, go_time::TimeError>, hexed: bool| -> Vec<u8> {
        match r {
            Ok(b) if hexed => hex(&b).into_bytes(),
            Ok(b) => b,
            Err(e) => format!("ERR:{}", e.error()).into_bytes(),
        }
    };
    for r in records("binary.txt") {
        match r.tag() {
            b"MB" => {
                let t = t_in(r.i(2), r.i(3), &r.s(1));
                let mb = or_err(t.marshal_binary(), true);
                c.check(mb == r.b(4), || {
                    format!(
                        "{} MarshalBinary got {}",
                        show(&r),
                        String::from_utf8_lossy(&mb)
                    )
                });
                let js = or_err(t.marshal_json(), false);
                c.check(js == r.b(5), || {
                    format!(
                        "{} MarshalJSON got {}",
                        show(&r),
                        String::from_utf8_lossy(&js)
                    )
                });
                let tx = or_err(t.marshal_text(), false);
                c.check(tx == r.b(6), || {
                    format!(
                        "{} MarshalText got {}",
                        show(&r),
                        String::from_utf8_lossy(&tx)
                    )
                });
                // AppendText with the AppendText prefix; AppendBinary leaves b on error.
                let at = t.append_text(b"x".to_vec());
                let want_at: Vec<u8> = match t.marshal_text() {
                    Ok(b) => [b"x".to_vec(), b].concat(),
                    Err(e) => format!("ERR:{}", e.error().replace("MarshalText", "AppendText"))
                        .into_bytes(),
                };
                c.check(or_err(at, false) == want_at, || {
                    format!("{} AppendText", show(&r))
                });
                let mut ab = b"yy".to_vec();
                let res = t.append_binary(&mut ab);
                c.check(
                    match res {
                        Ok(()) => hex(&ab[2..]).as_bytes() == r.b(4),
                        Err(_) => ab == b"yy",
                    },
                    || format!("{} AppendBinary", show(&r)),
                );
            }
            b"UB" => {
                let data = unhex(&r.s(1));
                let mut t = Time::zero();
                let res = go_time::unmarshal_binary(&mut t, &data);
                match (res, r.b(2)) {
                    (Ok(()), b"OK") => {
                        let got = time_fields(&t);
                        c.check(fields_eq(&r, 3, &got), || {
                            format!("{} got {:?}", show(&r), got)
                        });
                    }
                    (Err(e), b"ERR") => c.check(e.error().as_bytes() == r.b(3), || {
                        format!("{} got {}", show(&r), e)
                    }),
                    (res, _) => c.check(false, || format!("{} got {:?}", show(&r), res)),
                }
            }
            b"UJ" | b"UT" => {
                let mut t = Time::zero();
                let res = if r.tag() == b"UJ" {
                    go_time::unmarshal_json(&mut t, r.b(1))
                } else {
                    go_time::unmarshal_text(&mut t, r.b(1))
                };
                match (res, r.b(2)) {
                    (Ok(()), b"OK") => {
                        let got = time_fields(&t);
                        c.check(fields_eq(&r, 3, &got), || {
                            format!("{} got {:?}", show(&r), got)
                        });
                    }
                    (Err(e), b"ERR") => {
                        c.check(e.error().as_bytes() == r.b(3), || {
                            format!("{} got {}", show(&r), e)
                        });
                        let got = time_fields(&t);
                        c.check(fields_eq(&r, 4, &got), || {
                            format!("{} time after error {:?}", show(&r), got)
                        });
                    }
                    (res, _) => c.check(false, || format!("{} got {:?}", show(&r), res)),
                }
            }
            other => panic!("unknown tag {:?}", other),
        }
    }
    c.finish();
}

#[test]
fn zones_fixture() {
    setup();
    let mut c = Checker::new("zones");
    let zb = |t: &Time| {
        if t.go_is_zero() {
            "Z".to_string()
        } else {
            t.go_unix().to_string()
        }
    };
    for r in records("zones.txt") {
        match r.tag() {
            b"L" => {
                let l = loc(&format!("Zone:{}", r.s(1)));
                let t = go_time::unix(r.i(2), 0).in_loc(&l);
                let (name, off) = t.zone();
                let (st, en) = t.zone_bounds();
                let got = vec![
                    name,
                    off.to_string(),
                    if t.is_dst() { "1" } else { "0" }.to_string(),
                    zb(&st),
                    zb(&en),
                ];
                c.check(fields_eq(&r, 3, &got), || {
                    format!("{} got {:?}", show(&r), got)
                });
            }
            b"E" => {
                let data = unhex(&r.s(2));
                let got = match go_time::load_location_from_tz_data("X", &data) {
                    Err(e) => format!("ERR {}", e),
                    Ok(l) => {
                        let (name, off) = go_time::date(2020, Month(6), 1, 0, 0, 0, 0, &l).zone();
                        format!("OK {} {}", name, off)
                    }
                };
                c.check(got.as_bytes() == r.b(3), || {
                    format!("{} got {}", show(&r), got)
                });
            }
            other => panic!("unknown tag {:?}", other),
        }
    }
    c.finish();
}

#[test]
fn tzset_fixture() {
    setup();
    let mut c = Checker::new("tzset");
    let mut cache: HashMap<String, Arc<Location>> = HashMap::new();
    let zb = |t: &Time| {
        if t.go_is_zero() {
            "Z".to_string()
        } else {
            t.go_unix().to_string()
        }
    };
    for r in records("tzset.txt") {
        let hexdata = r.s(2);
        match r.tag() {
            b"TE" => {
                let res = go_time::load_location_from_tz_data("T", &unhex(&hexdata));
                c.check(
                    matches!(&res, Err(e) if e.error().as_bytes() == r.b(3)),
                    || format!("{} got {:?}", show(&r), res.map(|l| l.name.clone())),
                );
                continue;
            }
            b"T" | b"TD" => {}
            other => panic!("unknown tag {:?}", other),
        }
        let l = cache
            .entry(hexdata.clone())
            .or_insert_with(|| {
                go_time::load_location_from_tz_data("T", &unhex(&hexdata)).expect("tzif")
            })
            .clone();
        if r.tag() == b"T" {
            let t = go_time::unix(r.i(3), 0).in_loc(&l);
            let (name, off) = t.zone();
            let (st, en) = t.zone_bounds();
            let got = vec![
                name,
                off.to_string(),
                if t.is_dst() { "1" } else { "0" }.to_string(),
                zb(&st),
                zb(&en),
            ];
            c.check(fields_eq(&r, 4, &got), || {
                format!("{} got {:?}", show(&r), got)
            });
        } else {
            let t = go_time::date(r.i(3), Month(r.i(4)), r.i(5), r.i(6), 30, 0, 0, &l);
            let got = time_fields(&t);
            c.check(fields_eq(&r, 7, &got), || {
                format!("{} got {:?}", show(&r), got)
            });
        }
    }
    c.finish();
}

fn lookups_of(l: &Arc<Location>) -> Vec<String> {
    [
        -5000000000i64,
        0,
        1600000000,
        1720000000,
        1735000000,
        4102444800,
    ]
    .iter()
    .map(|&s| {
        let (name, off) = go_time::unix(s, 0).in_loc(l).zone();
        format!("{} {}", name, off)
    })
    .collect()
}

#[test]
fn zip_fixture() {
    setup();
    let mut c = Checker::new("zip");
    let zip = fixtures_dir().join("test.zip");
    let zip = zip.to_str().unwrap().to_string();
    let mut oracle_path = String::new();
    for r in records("zip.txt") {
        match r.tag() {
            b"P" => oracle_path = r.s(1),
            b"Z" => {
                let name = r.s(1);
                let res = go_time::load_location_env(&name, &zip, Some("/nonexistent-goroot"));
                match (&res, r.b(2)) {
                    (Ok(l), b"OK") => {
                        let mut got = vec![l.name.clone()];
                        got.extend(lookups_of(l));
                        c.check(fields_eq(&r, 3, &got), || {
                            format!("{} got {:?}", show(&r), got)
                        });
                    }
                    (Err(e), b"ERR") => {
                        let want = r.s(3).replace(&oracle_path, &zip);
                        c.check(e.error() == want, || format!("{} got {}", show(&r), e));
                    }
                    _ => c.check(false, || {
                        format!(
                            "{} got {:?}",
                            show(&r),
                            res.as_ref().map(|l| l.name.clone())
                        )
                    }),
                }
            }
            other => panic!("unknown tag {:?}", other),
        }
    }
    c.finish();
}

fn sha256_file(p: &str) -> String {
    use sha2::Digest;
    match std::fs::read(p) {
        Ok(b) => hex(&sha2::Sha256::digest(&b)),
        Err(_) => "missing".to_string(),
    }
}

/// System-dependent fixtures are only compared when the system files hash
/// like they did when the fixture was generated.
fn system_matches(recs: &[Rec]) -> bool {
    for r in recs {
        if r.tag() == b"H" && sha256_file(&r.s(1)) != r.s(2) {
            eprintln!(
                "system zoneinfo differs from fixture ({}); skipping",
                r.s(1)
            );
            return false;
        }
    }
    true
}

#[test]
fn system_fixture() {
    setup();
    let recs = records("system.txt");
    if !system_matches(&recs) {
        return;
    }
    let mut c = Checker::new("system");
    for r in &recs {
        if r.tag() != b"Y" {
            continue;
        }
        let name = String::from_utf8(r.f[1].clone()).unwrap();
        let res = go_time::load_location_env(&name, "", Some("/nonexistent-goroot"));
        match (&res, r.b(2)) {
            (Ok(l), b"OK") => {
                let mut got = vec![l.name.clone()];
                got.extend(lookups_of(l));
                c.check(fields_eq(r, 3, &got), || {
                    format!("{} got {:?}", show(r), got)
                });
            }
            (Err(e), b"ERR") => c.check(e.error().as_bytes() == r.b(3), || {
                format!("{} got {}", show(r), e)
            }),
            _ => c.check(false, || {
                format!("{} got {:?}", show(r), res.as_ref().map(|l| l.name.clone()))
            }),
        }
    }
    c.finish();
}

#[test]
fn localenv_fixture() {
    let recs = records("localenv.txt");
    if !system_matches(&recs) {
        return;
    }
    let mut c = Checker::new("localenv");
    for r in &recs {
        if r.tag() != b"V" {
            continue;
        }
        let tz = r.s(1);
        let tz = if tz == "<unset>" {
            None
        } else {
            Some(tz.as_str())
        };
        let l = Arc::new(go_time::init_local_from_env(
            tz,
            Some("/nonexistent-goroot"),
        ));
        let mut got = vec![l.name.clone()];
        got.extend(lookups_of(&l));
        c.check(fields_eq(r, 2, &got), || {
            format!("{} got {:?}", show(r), got)
        });
    }
    c.finish();
}

/// cast v1.9.2 `internal.TimeFormats` (layout, type).
const CAST_LAYOUTS: [(&str, i64); 24] = [
    ("2006-01-02", 0),
    (go_time::RFC3339, 2),
    ("2006-01-02T15:04:05", 0),
    (go_time::RFC1123Z, 2),
    (go_time::RFC1123, 1),
    (go_time::RFC822Z, 2),
    (go_time::RFC822, 1),
    (go_time::RFC850, 1),
    ("2006-01-02 15:04:05.999999999 -0700 MST", 3),
    ("2006-01-02T15:04:05-0700", 2),
    ("2006-01-02 15:04:05Z0700", 2),
    ("2006-01-02 15:04:05", 0),
    (go_time::ANSIC, 0),
    (go_time::UNIX_DATE, 1),
    (go_time::RUBY_DATE, 2),
    ("2006-01-02 15:04:05Z07:00", 2),
    ("02 Jan 2006", 0),
    ("2006-01-02 15:04:05 -07:00", 2),
    ("2006-01-02 15:04:05 -0700", 2),
    (go_time::KITCHEN, 4),
    (go_time::STAMP, 4),
    (go_time::STAMP_MILLI, 4),
    (go_time::STAMP_MICRO, 4),
    (go_time::STAMP_NANO, 4),
];

const SITE_FORMATS: [&str; 9] = [
    "Mon, 02 Jan 2006 15:04:05 -0700",
    "2006-01-02T15:04:05-07:00",
    "2006",
    "2006 ",
    "Jan 2, 2006",
    "January 2, 2006",
    "2006-01-02",
    "2006-01-02T15:04:05Z07:00",
    go_time::RFC3339,
];

/// The seeksnack date strings through cast's `ParseDateWith` (emulated with
/// this crate's primitives) and the site's layouts.
#[test]
fn seeksnack_fixture() {
    setup();
    let mut c = Checker::new("seeksnack");
    let utc = go_time::utc();
    for r in records("seeksnack.txt") {
        assert_eq!(r.tag(), b"K");
        let v = r.b(1);
        let mut idx: i64 = -1;
        let mut d = Time::zero();
        for (i, (layout, typ)) in CAST_LAYOUTS.iter().enumerate() {
            if let Ok(t) = go_time::parse(layout, v) {
                idx = i as i64;
                d = t;
                if *typ <= 1 {
                    let (y, m, dd) = d.date();
                    let (h, mi, s) = d.clock();
                    d = go_time::date(y, m, dd, h, mi, s, d.nanosecond(), &utc);
                }
                break;
            }
        }
        let mut got = vec![idx.to_string()];
        got.extend(time_fields(&d));
        for f in SITE_FORMATS {
            got.push(d.format(f));
        }
        got.push(d.format(go_time::RFC3339));
        c.check(fields_eq(&r, 2, &got), || {
            format!("{} got {:?}", show(&r), got)
        });
    }
    c.finish();
}
