package main

// Adversarial differential tests (added by the independent verification
// pass). Like tests.go, every test is split into chunks and each chunk is
// reduced to one FNV-1a hash. The Rust mirror is
// crates/go-strconv/tests/adv.rs; any change here must be mirrored there.
//
// Families:
//
//	f32all     every float32 bit pattern (2^32): shortest 'e', its
//	           ParseFloat(.., 32) round trip, and two fixed precisions.
//	f64pow2    every float64 exponent x {0,1,2,3,2^51,2^52-1,2^52-2}
//	           mantissas x both signs, through all formats and many precs.
//	ties       exact decimal ties n*2^-k (and (10j+5)*10^q integers) at
//	           every precision that can round on them.
//	nearshort  floats nearest to short decimals and their +-1, +-2 ulp
//	           neighbours (shortest-format boundary cases).
//	midpoints  exact decimal midpoints between adjacent float64/float32
//	           values (up to ~770 digits) and near-midpoint perturbations,
//	           in plain, scientific, underscored, padded and truncated forms.
//	hexmid     hexadecimal midpoints, sticky bits, >16 hex digits, extreme
//	           exponents.
//	quote2     every string of 0, 1 and 2 bytes through all quoting funcs.
//	quote3     every 3-byte string (16.7M).
//	quote4     4-byte strings: any first byte, then 3 bytes from a set of
//	           16 UTF-8 boundary/special values.
//	unqesc     \U, \u, \x and octal escapes over their whole value range.
//	atoiall    every string of length <= 4 over a 16-char alphabet, through
//	           ParseInt/ParseUint for 11 bases x 11 bit sizes, Atoi, ParseBool.
//	atoibound  2^k+-d boundaries for every bit size, in bases 2/8/10/16/36,
//	           with and without prefixes and underscores.
//	longties   exact midpoints followed by >800 zeros and a final 1 (or
//	           decremented and followed by >800 nines): the slow path's
//	           800-digit truncation at an exact tie.
//	fmtbytes   every fmt byte 0..255 through AppendFloat (FormatFloat for
//	           ASCII) at several precisions and both bit sizes.
//	complex    FormatComplex over all formats/precisions and its
//	           ParseComplex round trip.
//	wildrunes  IsPrint/IsGraphic/QuoteRune* of negative and >MaxRune runes
//	           whose low 16 bits are special (int32 -> uint16 truncation).

import (
	"bufio"
	"fmt"
	"log"
	"math"
	"math/big"
	"os"
	"runtime"
	"strconv"
	"strings"
	"sync"
)

type advDef struct {
	name   string
	seed   uint64
	chunks int
	run    func(s *sink, r *rng, c int)
}

var advTests = []advDef{
	{"f32all", 101, 1024, runF32All},
	{"f64pow2", 102, 32, runF64Pow2},
	{"ties", 103, 64, runTies},
	{"nearshort", 104, 64, runNearShort},
	{"midpoints", 105, 64, runMidpoints},
	{"hexmid", 106, 32, runHexMid},
	{"quote2", 107, 1, runQuote2},
	{"quote3", 108, 256, runQuote3},
	{"quote4", 109, 16, runQuote4},
	{"unqesc", 110, 18, runUnqEsc},
	{"atoiall", 111, 17, runAtoiAll},
	{"atoibound", 112, 4, runAtoiBound},
	{"longties", 113, 16, runLongTies},
	{"fmtbytes", 114, 4, runFmtBytes},
	{"complex", 115, 8, runComplex},
	{"wildrunes", 116, 16, runWildRunes},
}

// writeAdvHashes computes the chunk hashes of advTests. If only is not
// empty (comma-separated family names), only those families are recomputed
// and the other lines are kept from the existing out file.
func writeAdvHashes(out, only string) {
	type job struct{ t, c int }
	keep := map[string]bool{}
	if only != "" {
		for _, n := range strings.Split(only, ",") {
			keep[n] = true
		}
	}
	old := map[string]string{}
	if only != "" {
		data, err := os.ReadFile(out)
		if err != nil {
			log.Fatal(err)
		}
		for _, l := range strings.Split(string(data), "\n") {
			f := strings.Fields(l)
			if len(f) == 3 && !strings.HasPrefix(l, "#") {
				old[f[0]+" "+f[1]] = f[2]
			}
		}
	}
	results := make([][]uint64, len(advTests))
	var jobs []job
	for ti, t := range advTests {
		results[ti] = make([]uint64, t.chunks)
		if only != "" && !keep[t.name] {
			continue
		}
		for c := 0; c < t.chunks; c++ {
			jobs = append(jobs, job{ti, c})
		}
	}
	strconvOptimize = true
	ch := make(chan job)
	var wg sync.WaitGroup
	for w := 0; w < runtime.NumCPU(); w++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for j := range ch {
				t := advTests[j.t]
				s := newSink(nil)
				t.run(s, chunkRng(t.seed, j.c), j.c)
				results[j.t][j.c] = s.h
			}
		}()
	}
	for _, j := range jobs {
		ch <- j
	}
	close(ch)
	wg.Wait()

	f, err := os.Create(out)
	if err != nil {
		log.Fatal(err)
	}
	w := bufio.NewWriter(f)
	_, _ = fmt.Fprintf(w, "# generated by tools/go-oracle/go-strconv -mode advhashes (%s); test chunk fnv1a64\n", runtime.Version())
	for ti, t := range advTests {
		for c, h := range results[ti] {
			if only != "" && !keep[t.name] {
				o, ok := old[fmt.Sprintf("%s %d", t.name, c)]
				if !ok {
					log.Fatalf("%s %d: not in %s; regenerate without -only", t.name, c, out)
				}
				_, _ = fmt.Fprintf(w, "%s %d %s\n", t.name, c, o)
				continue
			}
			_, _ = fmt.Fprintf(w, "%s %d %016x\n", t.name, c, h)
		}
	}
	if err := w.Flush(); err != nil {
		log.Fatal(err)
	}
	if err := f.Close(); err != nil {
		log.Fatal(err)
	}
}

func advDump(name string, chunk int) {
	for _, t := range advTests {
		if t.name == name {
			w := bufio.NewWriter(os.Stdout)
			s := newSink(w)
			t.run(s, chunkRng(t.seed, chunk), chunk)
			_, _ = fmt.Fprintf(w, "hash %016x\n", s.h)
			_ = w.Flush()
			return
		}
	}
	log.Fatalf("unknown adv test %q", name)
}

func (s *sink) parse(str string, bs int) {
	v, err := strconv.ParseFloat(str, bs)
	s.ctx("parse %s %d", str, bs)
	s.putU64(math.Float64bits(v))
	s.putErr(err)
}

// ---------------------------------------------------------------------------
// float formatting

func runF32All(s *sink, _ *rng, c int) {
	for b := uint32(c) << 22; ; b++ {
		f := float64(math.Float32frombits(b))
		s.ctx("value %08x", b)
		e1 := strconv.FormatFloat(f, 'e', -1, 32)
		s.putStr(e1)
		v, err := strconv.ParseFloat(e1, 32)
		s.putU64(math.Float64bits(v))
		s.putErr(err)
		s.putStr(strconv.FormatFloat(f, 'e', 8, 32))
		s.putStr(strconv.FormatFloat(f, 'e', 5, 32))
		if b&(1<<22-1) == 1<<22-1 {
			break
		}
	}
}

var pow2Mants = [7]uint64{0, 1, 2, 3, 1 << 51, 1<<52 - 1, 1<<52 - 2}

var pow2FPrecs = [9]int{0, 1, 2, 3, 5, 10, 17, 20, 30}

func runF64Pow2(s *sink, _ *rng, c int) {
	for exp := uint64(c * 64); exp < uint64(c*64+64); exp++ {
		for sign := uint64(0); sign < 2; sign++ {
			for _, mant := range pow2Mants {
				b := sign<<63 | exp<<52 | mant
				f := math.Float64frombits(b)
				s.ctx("value %016x", b)
				for i := 0; i < len(fmts); i++ {
					s.putStr(strconv.FormatFloat(f, fmts[i], -1, 64))
				}
				for prec := 0; prec <= 20; prec++ {
					s.putStr(strconv.FormatFloat(f, 'e', prec, 64))
					s.putStr(strconv.FormatFloat(f, 'g', prec, 64))
				}
				for _, prec := range pow2FPrecs {
					s.putStr(strconv.FormatFloat(f, 'f', prec, 64))
				}
				for prec := 0; prec <= 14; prec++ {
					s.putStr(strconv.FormatFloat(f, 'x', prec, 64))
				}
				s.putStr(strconv.FormatFloat(f, 'e', -1, 32))
				s.putStr(strconv.FormatFloat(f, 'g', 9, 32))
				s.putStr(strconv.FormatFloat(f, 'x', -1, 32))
				strs := [3]string{
					strconv.FormatFloat(f, 'g', -1, 64),
					strconv.FormatFloat(f, 'x', -1, 64),
					strconv.FormatFloat(f, 'e', 16, 64),
				}
				for _, str := range strs {
					s.parse(str, 64)
					s.parse(str, 32)
				}
			}
		}
	}
}

func runTies(s *sink, _ *rng, c int) {
	k := c + 1
	for n := 1; n <= 2001; n += 2 {
		f := math.Ldexp(float64(n), -k)
		s.ctx("tie %d %d", n, k)
		for prec := 0; prec <= 50; prec++ {
			s.putStr(strconv.FormatFloat(f, 'e', prec, 64))
		}
		for prec := 0; prec <= k+2; prec++ {
			s.putStr(strconv.FormatFloat(f, 'f', prec, 64))
		}
		for prec := 1; prec <= 30; prec++ {
			s.putStr(strconv.FormatFloat(f, 'g', prec, 64))
		}
		for prec := 0; prec <= 30; prec++ {
			s.putStr(strconv.FormatFloat(f, 'e', prec, 32))
		}
	}
	q := c % 16
	for j := 0; j < 1000; j++ {
		n := uint64(10*j+5) * pow10u[q]
		f := float64(n)
		s.ctx("inttie %d", n)
		for prec := 0; prec <= 20; prec++ {
			s.putStr(strconv.FormatFloat(f, 'e', prec, 64))
			s.putStr(strconv.FormatFloat(f, 'g', prec+1, 64))
		}
		s.putStr(strconv.FormatFloat(f, 'f', 0, 64))
		s.putStr(strconv.FormatFloat(f, 'f', 2, 64))
		for prec := 0; prec <= 12; prec++ {
			s.putStr(strconv.FormatFloat(f, 'e', prec, 32))
		}
	}
}

func nearShortOps(s *sink, g float64, bs, nd int) {
	e1 := strconv.FormatFloat(g, 'e', -1, bs)
	s.putStr(e1)
	s.parse(e1, bs)
	s.putStr(strconv.FormatFloat(g, 'e', nd-1, bs))
	if nd >= 2 {
		s.putStr(strconv.FormatFloat(g, 'e', nd-2, bs))
	}
	s.putStr(strconv.FormatFloat(g, 'g', nd, bs))
	s.putStr(strconv.FormatFloat(g, 'f', -1, bs))
}

func runNearShort(s *sink, r *rng, _ int) {
	for i := 0; i < 1<<12; i++ {
		nd := 1 + r.intn(17)
		n := pow10u[nd-1] + r.next()%(9*pow10u[nd-1])
		q := r.intn(660) - 350
		str := strconv.FormatUint(n, 10) + "e" + strconv.Itoa(q)
		f, _ := strconv.ParseFloat(str, 64)
		s.ctx("near %s", str)
		b0 := math.Float64bits(f)
		for d := -2; d <= 2; d++ {
			b := b0 + uint64(int64(d))
			s.ctx("value %016x", b)
			nearShortOps(s, math.Float64frombits(b), 64, nd)
		}
		nd32 := 1 + r.intn(9)
		n32 := pow10u[nd32-1] + r.next()%(9*pow10u[nd32-1])
		q32 := r.intn(100) - 55
		str32 := strconv.FormatUint(n32, 10) + "e" + strconv.Itoa(q32)
		f32, _ := strconv.ParseFloat(str32, 32)
		s.ctx("near32 %s", str32)
		b32 := math.Float32bits(float32(f32))
		for d := -2; d <= 2; d++ {
			b := b32 + uint32(int32(d))
			s.ctx("value %08x", b)
			nearShortOps(s, float64(math.Float32frombits(b)), 32, nd32)
		}
	}
}

// ---------------------------------------------------------------------------
// parsing: exact midpoints

// genMid64 returns positive finite float64 bits from a mix of hard classes.
func genMid64(r *rng) uint64 {
	const mask52 = 1<<52 - 1
	switch r.intn(8) {
	case 0, 1:
		b := r.next() &^ (1 << 63)
		if (b>>52)&0x7ff == 0x7ff {
			b &^= 1 << 62
		}
		return b
	case 2: // subnormal
		return r.next() >> uint(12+r.intn(52))
	case 3: // around the smallest normal
		ef := uint64(r.intn(3))
		return ef<<52 | r.next()&mask52
	case 4: // around the largest finite
		ef := uint64(2046 - r.intn(2))
		return ef<<52 | (mask52 - r.next()%8)
	case 5: // powers of two
		return uint64(r.intn(2047)) << 52
	case 6: // moderate
		ef := uint64(1023 - 70 + r.intn(141))
		return ef<<52 | r.next()&mask52
	default:
		ef := uint64(r.intn(2047))
		mants := [8]uint64{0, 1, 2, mask52, mask52 - 1, 1 << 51, 1<<51 - 1, 1<<51 + 1}
		return ef<<52 | mants[r.intn(8)]
	}
}

// genMid32 returns positive finite float32 bits from a mix of hard classes.
func genMid32(r *rng) uint32 {
	const mask23 = 1<<23 - 1
	switch r.intn(8) {
	case 0, 1:
		b := uint32(r.next()) &^ (1 << 31)
		if (b>>23)&0xff == 0xff {
			b &^= 1 << 30
		}
		return b
	case 2:
		return uint32(r.next() >> uint(41+r.intn(23)))
	case 3:
		ef := uint32(r.intn(3))
		return ef<<23 | uint32(r.next())&mask23
	case 4:
		ef := uint32(254 - r.intn(2))
		return ef<<23 | (mask23 - uint32(r.next()%8))
	case 5:
		return uint32(r.intn(255)) << 23
	case 6:
		ef := uint32(127 - 30 + r.intn(61))
		return ef<<23 | uint32(r.next())&mask23
	default:
		ef := uint32(r.intn(255))
		mants := [8]uint32{0, 1, 2, mask23, mask23 - 1, 1 << 22, 1<<22 - 1, 1<<22 + 1}
		return ef<<23 | mants[r.intn(8)]
	}
}

// A midpoint is x * 2**e2.
type advMid struct {
	x  uint64
	e2 int
}

// floatMids returns the midpoints between the float (exponent field ef,
// fraction frac, mantissa width mb, subnormal exponent emin) and its
// neighbours: the upper one always, the lower one if the float is not zero.
func floatMids(ef, frac uint64, mb uint, emin int) []advMid {
	var m uint64
	var e int
	if ef == 0 {
		m, e = frac, emin
	} else {
		m, e = frac|1<<mb, int(ef)+emin-1
	}
	mids := []advMid{{2*m + 1, e - 1}}
	switch {
	case m == 0:
	case frac == 0 && ef > 1:
		mids = append(mids, advMid{4*m - 1, e - 2})
	default:
		mids = append(mids, advMid{2*m - 1, e - 1})
	}
	return mids
}

// exactDecimal returns the digits D and the number of fraction digits of
// x * 2**e2 (value = D / 10**frac).
func exactDecimal(x uint64, e2 int) (string, int) {
	v := new(big.Int).SetUint64(x)
	if e2 >= 0 {
		v.Lsh(v, uint(e2))
		return v.String(), 0
	}
	v.Mul(v, new(big.Int).Exp(big.NewInt(5), big.NewInt(int64(-e2)), nil))
	return v.String(), -e2
}

// advPlain formats digits d with p digits before the decimal point.
func advPlain(d string, p int) string {
	n := len(d)
	switch {
	case p <= 0:
		return "0." + strings.Repeat("0", -p) + d
	case p >= n:
		return d + strings.Repeat("0", p-n)
	default:
		return d[:p] + "." + d[p:]
	}
}

// advSci formats the first k digits of d (p digits before the point) in
// scientific notation with exponent character ec.
func advSci(d string, p, k int, ec string) string {
	if k > len(d) {
		k = len(d)
	}
	m := d[:k]
	var b strings.Builder
	b.WriteByte(m[0])
	if len(m) > 1 {
		b.WriteByte('.')
		b.WriteString(m[1:])
	}
	b.WriteString(ec)
	b.WriteString(strconv.Itoa(p - 1))
	return b.String()
}

// advUnderscored is advSci(d, p, len(d), "e") with '_' after every 4th
// fraction digit (when more digits follow).
func advUnderscored(d string, p int) string {
	var b strings.Builder
	b.WriteByte(d[0])
	if len(d) > 1 {
		b.WriteByte('.')
		for i := 1; i < len(d); i++ {
			b.WriteByte(d[i])
			if i%4 == 0 && i+1 < len(d) {
				b.WriteByte('_')
			}
		}
	}
	b.WriteString("e")
	b.WriteString(strconv.Itoa(p - 1))
	return b.String()
}

// advDecrement subtracts one unit in the last place of the decimal digit
// string d (d > 0), keeping its length.
func advDecrement(d string) string {
	b := []byte(d)
	for i := len(b) - 1; i >= 0; i-- {
		if b[i] > '0' {
			b[i]--
			break
		}
		b[i] = '9'
	}
	return string(b)
}

func midForms(d string, frac int) []string {
	n := len(d)
	p := n - frac
	plain := advPlain(d, p)
	up := plain + "000001"
	if frac == 0 {
		up = plain + ".000001"
	}
	down := advPlain(advDecrement(d)+"999999", p)
	forms := []string{
		plain,
		advSci(d, p, n, "e"),
		up,
		down,
	}
	for _, k := range [4]int{17, 19, 20, 25} {
		if k < n {
			forms = append(forms, advSci(d, p, k, "e"))
		}
	}
	padded := "+000" + plain
	if frac > 0 {
		padded += "000"
	}
	forms = append(forms,
		advUnderscored(d, p),
		padded,
		"-"+advSci(d, p, n, "E"),
	)
	if p-1 >= 0 {
		forms = append(forms, advSci(d, p, n, "E+"))
	}
	return forms
}

func runMidpoints(s *sink, r *rng, _ int) {
	emit := func(mids []advMid) {
		for _, m := range mids {
			d, frac := exactDecimal(m.x, m.e2)
			s.ctx("mid %d %d", m.x, m.e2)
			for _, str := range midForms(d, frac) {
				s.parse(str, 64)
				s.parse(str, 32)
			}
		}
	}
	for i := 0; i < 256; i++ {
		b := genMid64(r)
		s.ctx("value %016x", b)
		emit(floatMids((b>>52)&0x7ff, b&(1<<52-1), 52, -1074))
	}
	for i := 0; i < 128; i++ {
		b := genMid32(r)
		s.ctx("value32 %08x", b)
		emit(floatMids(uint64(b>>23)&0xff, uint64(b)&(1<<23-1), 23, -149))
	}
}

// ---------------------------------------------------------------------------
// parsing: hexadecimal midpoints

func advUnderscoredHex(h string) string {
	var b strings.Builder
	for i := 0; i < len(h); i++ {
		b.WriteByte(h[i])
		if i%2 == 1 && i+1 < len(h) {
			b.WriteByte('_')
		}
	}
	return b.String()
}

func hexForms(x uint64, e2 int) []string {
	h := strconv.FormatUint(x, 16)
	pm := func(e int) string { return "p" + strconv.Itoa(e) }
	forms := []string{
		"0x" + h + pm(e2),
		"0x" + h + "000" + pm(e2-12),
		"0x" + h + "0000001" + pm(e2-28),
		"0x" + strconv.FormatUint(x*16-1, 16) + pm(e2-4),
	}
	if len(h) > 1 {
		forms = append(forms, "0x"+h[:1]+"."+h[1:]+pm(e2+4*(len(h)-1)))
	} else {
		forms = append(forms, "0x"+h+"."+pm(e2))
	}
	exp := strconv.Itoa(e2)
	if e2 >= 0 {
		exp = "+" + exp
	}
	forms = append(forms,
		"0x_"+advUnderscoredHex(h)+pm(e2),
		"-0X"+strings.ToUpper(h)+"P"+exp,
		"0x0.00"+h+pm(e2+4*(2+len(h))),
		"0x"+h+pm(e2-5000),
		"0x"+h+pm(e2+5000),
	)
	return forms
}

func runHexMid(s *sink, r *rng, _ int) {
	emit := func(mids []advMid) {
		for _, m := range mids {
			s.ctx("mid %d %d", m.x, m.e2)
			for _, str := range hexForms(m.x, m.e2) {
				s.parse(str, 64)
				s.parse(str, 32)
			}
		}
	}
	for i := 0; i < 1024; i++ {
		b := genMid64(r)
		s.ctx("value %016x", b)
		emit(floatMids((b>>52)&0x7ff, b&(1<<52-1), 52, -1074))
		b32 := genMid32(r)
		s.ctx("value32 %08x", b32)
		emit(floatMids(uint64(b32>>23)&0xff, uint64(b32)&(1<<23-1), 23, -149))
	}
}

// ---------------------------------------------------------------------------
// quoting

func runQuote2(s *sink, _ *rng, _ int) {
	quoteOps(s, nil)
	for a := 0; a < 256; a++ {
		quoteOps(s, []byte{byte(a)})
	}
	for a := 0; a < 256; a++ {
		for b := 0; b < 256; b++ {
			quoteOps(s, []byte{byte(a), byte(b)})
		}
	}
}

func runQuote3(s *sink, _ *rng, c int) {
	for b := 0; b < 256; b++ {
		for d := 0; d < 256; d++ {
			quoteOps(s, []byte{byte(c), byte(b), byte(d)})
		}
	}
}

var quote4Set = [16]byte{0x00, 0x0a, 0x22, 0x27, 0x30, 0x5c, 0x60, 0x78, 0x7f, 0x80, 0x8f, 0x90, 0x9f, 0xa0, 0xbf, 0xc0}

func runQuote4(s *sink, _ *rng, c int) {
	for a := c * 16; a < c*16+16; a++ {
		for _, b := range quote4Set {
			for _, d := range quote4Set {
				for _, e := range quote4Set {
					quoteOps(s, []byte{byte(a), b, d, e})
				}
			}
		}
	}
}

func (s *sink) unquote(str string) {
	u, err := strconv.Unquote(str)
	s.ctx("unquote %x", str)
	s.putStr(u)
	s.putErr(err)
}

func runUnqEsc(s *sink, _ *rng, c int) {
	if c < 17 {
		for v := c << 16; v < (c+1)<<16; v++ {
			s.unquote(fmt.Sprintf(`"\U%08x"`, v))
			s.unquote(fmt.Sprintf(`'\U%08X'`, v))
			s.unquote(fmt.Sprintf(`"a\U%08xb"`, v))
			if v < 0x10000 {
				s.unquote(fmt.Sprintf(`"\u%04x"`, v))
				s.unquote(fmt.Sprintf(`'\u%04X'`, v))
				s.unquote(fmt.Sprintf("`\\u%04x`", v))
			}
			val, mb, tail, err := strconv.UnquoteChar(fmt.Sprintf(`\U%08xz`, v), '"')
			s.putU64(uint64(int64(val)))
			s.putBool(mb)
			s.putU64(uint64(len(tail)))
			s.putErr(err)
		}
		return
	}
	for v := 0; v < 256; v++ {
		b := string([]byte{byte(v)})
		s.unquote(fmt.Sprintf(`"\x%02x"`, v))
		s.unquote(fmt.Sprintf(`"\x%02X"`, v))
		s.unquote(fmt.Sprintf(`'\x%02x'`, v))
		s.unquote("\"\\" + b + "\"")
		s.unquote("'\\" + b + "'")
		s.unquote("\"\\" + b + "00\"")
		s.unquote("\"\\x" + b + "0\"")
		s.unquote("\"\\u00" + b + "0\"")
	}
	for v := 0; v < 512; v++ {
		s.unquote(fmt.Sprintf(`"\%03o"`, v))
		s.unquote(fmt.Sprintf(`'\%03o'`, v))
	}
}

// ---------------------------------------------------------------------------
// integers

const atoiAlphabet = "01789abfxXoO_+-z"

var atoiBases = [11]int{-1, 0, 1, 2, 3, 8, 10, 16, 35, 36, 37}
var atoiBits = [11]int{-1, 0, 1, 7, 8, 9, 16, 32, 63, 64, 65}

func atoiOps(s *sink, str string) {
	s.ctx("input %q", str)
	for _, base := range atoiBases {
		for _, bits := range atoiBits {
			v, err := strconv.ParseInt(str, base, bits)
			s.putU64(uint64(v))
			s.putErr(err)
			u, err := strconv.ParseUint(str, base, bits)
			s.putU64(u)
			s.putErr(err)
		}
	}
	v, err := strconv.Atoi(str)
	s.putU64(uint64(v))
	s.putErr(err)
	b, err := strconv.ParseBool(str)
	s.putBool(b)
	s.putErr(err)
}

func runAtoiAll(s *sink, _ *rng, c int) {
	if c < 16 {
		for i := 0; i < 16*16*16; i++ {
			str := []byte{atoiAlphabet[c], atoiAlphabet[i>>8], atoiAlphabet[(i>>4)&15], atoiAlphabet[i&15]}
			atoiOps(s, string(str))
		}
		return
	}
	atoiOps(s, "")
	for n := 1; n <= 3; n++ {
		total := 1 << (4 * n)
		for i := 0; i < total; i++ {
			str := make([]byte, n)
			for j := 0; j < n; j++ {
				str[j] = atoiAlphabet[(i>>(4*(n-1-j)))&15]
			}
			atoiOps(s, string(str))
		}
	}
}

var boundBases = [5]int{2, 8, 10, 16, 36}

func runAtoiBound(s *sink, _ *rng, c int) {
	for bits := c*16 + 1; bits <= c*16+16; bits++ {
		for _, sh := range [2]int{bits - 1, bits} {
			for d := int64(-2); d <= 2; d++ {
				for _, neg := range [2]bool{false, true} {
					v := new(big.Int).Lsh(big.NewInt(1), uint(sh))
					v.Add(v, big.NewInt(d))
					if neg {
						v.Neg(v)
					}
					for _, base := range boundBases {
						digits := v.Text(base)
						sign := ""
						if digits[0] == '-' {
							sign, digits = "-", digits[1:]
						}
						prefix := ""
						switch base {
						case 2:
							prefix = "0b"
						case 8:
							prefix = "0o"
						case 16:
							prefix = "0x"
						}
						strs := []string{sign + digits}
						if prefix != "" || base == 10 {
							us := advUnderscoredHex(digits)
							strs = append(strs, sign+prefix+digits, sign+prefix+"_"+us, sign+prefix+us+"_")
						}
						for _, str := range strs {
							s.ctx("bound %s base %d bits %d", str, base, bits)
							for _, b := range [2]int{base, 0} {
								for _, bs := range [3]int{bits, 64, 0} {
									iv, err := strconv.ParseInt(str, b, bs)
									s.putU64(uint64(iv))
									s.putErr(err)
									uv, err := strconv.ParseUint(str, b, bs)
									s.putU64(uv)
									s.putErr(err)
								}
							}
							iv, err := strconv.Atoi(str)
							s.putU64(uint64(iv))
							s.putErr(err)
						}
					}
				}
			}
		}
	}
}

// ---------------------------------------------------------------------------
// round 2

// longTieForms returns near-tie strings for the midpoint digits d (frac
// fraction digits) that are longer than the 800-digit decimal buffer.
func longTieForms(d string, frac int) []string {
	p := len(d) - frac
	plain := advPlain(d, p)
	dot := ""
	if frac == 0 {
		dot = "."
	}
	return []string{
		plain + dot + strings.Repeat("0", 820) + "1",
		plain + dot + strings.Repeat("0", 820),
		advPlain(advDecrement(d)+strings.Repeat("9", 820), p),
		strings.Repeat("0", 790) + plain + dot + "1",
		"-" + plain + dot + strings.Repeat("0", 820) + "1",
		d[:1] + "." + d[1:] + strings.Repeat("0", 850) + "1e" + strconv.Itoa(p-1),
	}
}

func runLongTies(s *sink, r *rng, _ int) {
	emit := func(mids []advMid) {
		for _, m := range mids {
			d, frac := exactDecimal(m.x, m.e2)
			s.ctx("mid %d %d", m.x, m.e2)
			for _, str := range longTieForms(d, frac) {
				s.parse(str, 64)
				s.parse(str, 32)
			}
		}
	}
	for i := 0; i < 64; i++ {
		b := genMid64(r)
		s.ctx("value %016x", b)
		emit(floatMids((b>>52)&0x7ff, b&(1<<52-1), 52, -1074))
		b32 := genMid32(r)
		s.ctx("value32 %08x", b32)
		emit(floatMids(uint64(b32>>23)&0xff, uint64(b32)&(1<<23-1), 23, -149))
	}
}

var fmtBytesPrecs = [10]int{-5, -1, 0, 1, 5, 17, 18, 30, 400, 1100}

func runFmtBytes(s *sink, r *rng, c int) {
	for fm := c * 64; fm < c*64+64; fm++ {
		for i := 0; i < 32; i++ {
			f := math.Float64frombits(genF64(r))
			for _, prec := range fmtBytesPrecs {
				for _, bs := range [2]int{64, 32} {
					s.ctx("fmt %d value %016x prec %d bs %d", fm, math.Float64bits(f), prec, bs)
					s.put(strconv.AppendFloat([]byte("x"), f, byte(fm), prec, bs))
				}
			}
		}
	}
}

func runComplex(s *sink, r *rng, _ int) {
	for i := 0; i < 1<<11; i++ {
		re := math.Float64frombits(genF64(r))
		im := math.Float64frombits(genF64(r))
		v := complex(re, im)
		s.ctx("complex %016x %016x", math.Float64bits(re), math.Float64bits(im))
		for j := 0; j < len(fmts); j++ {
			for _, prec := range [4]int{-1, 0, 3, 17} {
				for _, bs := range [2]int{128, 64} {
					str := strconv.FormatComplex(v, fmts[j], prec, bs)
					s.putStr(str)
					if prec == -1 && fmts[j] != 'b' {
						p, err := strconv.ParseComplex(str, bs)
						s.putU64(math.Float64bits(real(p)))
						s.putU64(math.Float64bits(imag(p)))
						s.putErr(err)
					}
				}
			}
		}
	}
}

var wildLows = [24]uint32{
	0x0000, 0x0020, 0x0041, 0x007e, 0x007f, 0x00a0, 0x00ad, 0x0378,
	0x1680, 0x2000, 0x200a, 0x2028, 0x202f, 0x205f, 0x3000, 0xd800,
	0xdfff, 0xe000, 0xf8ff, 0xfeff, 0xfffd, 0xffff, 0x0085, 0x00ff,
}

func runWildRunes(s *sink, _ *rng, c int) {
	for hi := c * 4096; hi < c*4096+4096; hi++ {
		for _, lo := range wildLows {
			x := rune(int32(uint32(hi)<<16 | lo))
			s.ctx("rune %d", x)
			s.putBool(strconv.IsPrint(x))
			s.putBool(strconv.IsGraphic(x))
			s.putStr(strconv.QuoteRune(x))
			s.putStr(strconv.QuoteRuneToASCII(x))
			s.putStr(strconv.QuoteRuneToGraphic(x))
		}
	}
}
