// Command go-strconv is the Go oracle for crates/go-strconv.
//
// Usage:
//
//	go build -tags strconvslow -ldflags=-checklinkname=0 -o oracle ./tools/go-oracle/go-strconv
//	./oracle -mode hashes  -out crates/go-strconv/tests/fixtures/hashes.txt
//	./oracle -mode vectors -dir crates/go-strconv/tests/fixtures
//	./oracle -mode dump -test ftoa64 -chunk 3 > dump.txt
//	./oracle -mode advhashes -out crates/go-strconv/tests/fixtures/adv_hashes.txt
//	./oracle -mode advdump -test midpoints -chunk 3 > dump.txt
//	./oracle -mode corpus -site <seeksnack> -golden <golden output> -dir crates/go-strconv/tests/fixtures
//
// The strconvslow tag and -checklinkname=0 are required because slowpath.go
// links to internal/strconv.optimize (Go's SetOptimize test hook); without
// them the package still builds (slowpath_stub.go) but refuses to generate.
//
// "hashes" runs the chunked differential tests (tests.go) over deterministic
// generators (gen.go) and writes one FNV-1a hash per chunk. "vectors" writes
// readable explicit test vectors. "dump" prints every hashed value of one
// chunk (the Rust test writes the same format to GO_STRCONV_DUMP_DIR) so a
// hash mismatch can be located with diff.
package main

import (
	"bufio"
	"flag"
	"fmt"
	"log"
	"os"
	"runtime"
	"sync"
)

func main() {
	mode := flag.String("mode", "hashes", "hashes | vectors | dump | advhashes | advdump | corpus")
	out := flag.String("out", "hashes.txt", "output file for -mode hashes")
	dir := flag.String("dir", ".", "output directory for -mode vectors")
	testName := flag.String("test", "", "test name for -mode dump")
	chunk := flag.Int("chunk", 0, "chunk index for -mode dump")
	site := flag.String("site", "", "seeksnack source dir for -mode corpus")
	golden := flag.String("golden", "", "golden output dir for -mode corpus (optional)")
	only := flag.String("only", "", "comma-separated families to recompute (-mode advhashes; others kept from -out)")
	scale := flag.Int("scale", 1, "multiply the chunk count of the generator-driven tests (-mode hashes)")
	flag.Parse()
	log.SetFlags(0)
	log.SetPrefix("go-strconv oracle: ")

	if !haveSlowPath && (*mode == "hashes" || *mode == "vectors") {
		log.Fatal("build with -tags strconvslow -ldflags=-checklinkname=0 (needs internal/strconv.optimize)")
	}
	switch *mode {
	case "hashes":
		writeHashes(*out, *scale)
	case "vectors":
		writeVectors(*dir)
	case "advhashes":
		writeAdvHashes(*out, *only)
	case "advdump":
		advDump(*testName, *chunk)
	case "corpus":
		writeCorpus(*site, *golden, *dir)
	case "dump":
		for _, t := range tests {
			if t.name == *testName {
				w := bufio.NewWriter(os.Stdout)
				s := newSink(w)
				if t.slow && !haveSlowPath {
					log.Fatal("build with -tags strconvslow -ldflags=-checklinkname=0 to dump slow-path tests")
				}
				strconvOptimize = !t.slow
				t.run(s, chunkRng(t.seed, *chunk), *chunk)
				fmt.Fprintf(w, "hash %016x\n", s.h)
				w.Flush()
				return
			}
		}
		log.Fatalf("unknown test %q", *testName)
	default:
		log.Fatalf("unknown mode %q", *mode)
	}
}

func writeHashes(out string, scale int) {
	type job struct{ t, c int }
	results := make([][]uint64, len(tests))
	var jobs []job
	for ti := range tests {
		t := &tests[ti]
		if t.name != "quoteall" && t.name != "nanconv" {
			t.chunks *= scale
		}
		results[ti] = make([]uint64, t.chunks)
	}
	// Two phases: fast-path tests, then slow-path tests with the global
	// internal/strconv.optimize flag turned off.
	for _, slow := range []bool{false, true} {
		jobs = jobs[:0]
		for ti, t := range tests {
			if t.slow != slow {
				continue
			}
			for c := 0; c < t.chunks; c++ {
				jobs = append(jobs, job{ti, c})
			}
		}
		strconvOptimize = !slow
		ch := make(chan job)
		var wg sync.WaitGroup
		for w := 0; w < runtime.NumCPU(); w++ {
			wg.Add(1)
			go func() {
				defer wg.Done()
				for j := range ch {
					t := tests[j.t]
					s := newSink(nil)
					t.run(s, chunkRng(t.seed, j.c), j.c)
					results[j.t][j.c] = s.h
				}
			}()
		}
		for _, j := range jobs {
			ch <- j
		}
		close(ch)
		wg.Wait()
	}
	strconvOptimize = true

	f, err := os.Create(out)
	if err != nil {
		log.Fatal(err)
	}
	w := bufio.NewWriter(f)
	fmt.Fprintf(w, "# generated by tools/go-oracle/go-strconv (%s); test chunk fnv1a64\n", runtime.Version())
	for ti, t := range tests {
		for c, h := range results[ti] {
			fmt.Fprintf(w, "%s %d %016x\n", t.name, c, h)
		}
	}
	if err := w.Flush(); err != nil {
		log.Fatal(err)
	}
	if err := f.Close(); err != nil {
		log.Fatal(err)
	}
}
