package main

// Explicit (readable) test vectors, checked in under
// crates/go-strconv/tests/fixtures/.

import (
	"bufio"
	"errors"
	"fmt"
	"log"
	"math"
	"math/big"
	"os"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
)

func create(dir, name string) (*os.File, *bufio.Writer) {
	f, err := os.Create(filepath.Join(dir, name))
	if err != nil {
		log.Fatal(err)
	}
	w := bufio.NewWriter(f)
	_, _ = fmt.Fprintf(w, "# generated by tools/go-oracle/go-strconv (%s)\n", runtime.Version())
	return f, w
}

func closeW(f *os.File, w *bufio.Writer) {
	if err := w.Flush(); err != nil {
		log.Fatal(err)
	}
	if err := f.Close(); err != nil {
		log.Fatal(err)
	}
}

func goTestdata(name string) []string {
	p := filepath.Join(runtime.GOROOT(), "src", "internal", "strconv", "testdata", name)
	data, err := os.ReadFile(p)
	if err != nil {
		log.Fatal(err)
	}
	var lines []string
	for _, l := range strings.Split(string(data), "\n") {
		l = strings.TrimSpace(l)
		if l == "" || strings.HasPrefix(l, "#") {
			continue
		}
		lines = append(lines, l)
	}
	return lines
}

func errCode(err error) string {
	switch {
	case err == nil:
		return "nil"
	case errors.Is(err, strconv.ErrRange):
		return "range"
	case errors.Is(err, strconv.ErrSyntax):
		return "syntax"
	}
	return "other"
}

func writeVectors(dir string) {
	writeFtoaVectors(dir)
	writeAtofVectors(dir)
	writeAtoiVectors(dir)
	writeQuoteVectors(dir)
	writeNumErrors(dir)
}

// ftoa_vectors.txt: f64bits bitSize fmt prec output
func writeFtoaVectors(dir string) {
	f, w := create(dir, "ftoa_vectors.txt")
	_, _ = fmt.Fprintf(w, "# float64-bits bitSize fmt prec FormatFloat-output slow-path-output(= if identical)\n")
	line := func(x float64, bs int, fm byte, prec int) {
		out := strconv.FormatFloat(x, fm, prec, bs)
		strconvOptimize = false
		slow := strconv.FormatFloat(x, fm, prec, bs)
		strconvOptimize = true
		if slow == out {
			slow = "="
		}
		_, _ = fmt.Fprintf(w, "%016x %d %c %d %s %s\n", math.Float64bits(x), bs, fm, prec, out, slow)
	}
	allFmts := "beEfgGxX?y"
	r := newRng(100)
	pick := func() (byte, int) {
		fm := allFmts[r.intn(len(allFmts))]
		var prec int
		if r.intn(2) == 0 {
			prec = r.intn(22) - 1
		} else {
			prec = precGrid[r.intn(len(precGrid))]
		}
		return fm, prec
	}
	for i := 0; i < 6000; i++ {
		x := math.Float64frombits(genF64(r))
		fm, prec := pick()
		line(x, 64, fm, prec)
	}
	for i := 0; i < 3000; i++ {
		x := float64(math.Float32frombits(genF32(r)))
		fm, prec := pick()
		line(x, 32, fm, prec)
	}
	for i := 0; i < 500; i++ {
		x := math.Float64frombits(genF64(r))
		fm, prec := pick()
		line(x, 32, fm, prec)
	}
	// powers of two
	for e := -1074; e <= 1023; e++ {
		line(math.Ldexp(1, e), 64, 'e', -1)
	}
	for e := -149; e <= 127; e++ {
		line(math.Ldexp(1, e), 32, 'e', -1)
	}
	// Go testdata/ftoa1k.txt inputs, 'e' at several precisions.
	for _, l := range goTestdata("ftoa1k.txt") {
		x, err := strconv.ParseFloat(l, 64)
		if err != nil {
			log.Fatal(err)
		}
		for _, prec := range []int{0, 5, 10, 16, 17, 18} {
			line(x, 64, 'e', prec)
		}
	}
	closeW(f, w)
}

// exactDecimal returns the digits and decimal exponent of (2m+1)*2^(e-1) as
// "d.ddd...e±N" (exact, trailing zeros removed).
func midpointString(m uint64, e int) (digits string, exp10 int) {
	n := new(big.Int).SetUint64(m)
	n.Lsh(n, 1)
	n.Add(n, big.NewInt(1))
	k := e - 1
	var s string
	var pointPos int // value = 0.s * 10^pointPos
	if k >= 0 {
		n.Lsh(n, uint(k))
		s = n.String()
		pointPos = len(s)
	} else {
		five := new(big.Int).Exp(big.NewInt(5), big.NewInt(int64(-k)), nil)
		n.Mul(n, five)
		s = n.String()
		pointPos = len(s) + k
	}
	s = strings.TrimRight(s, "0")
	return s, pointPos - 1
}

func sci(digits string, exp10 int, neg bool) string {
	var b strings.Builder
	if neg {
		b.WriteByte('-')
	}
	b.WriteByte(digits[0])
	if len(digits) > 1 {
		b.WriteByte('.')
		b.WriteString(digits[1:])
	}
	fmt.Fprintf(&b, "e%d", exp10)
	return b.String()
}

func decrementLast(d string) string {
	b := []byte(d)
	i := len(b) - 1
	for i >= 0 && b[i] == '0' {
		b[i] = '9'
		i--
	}
	if i < 0 {
		return d
	}
	b[i]--
	return string(b)
}

// atof_vectors.txt: input \t bits64 \t err64 \t bits32 \t err32
func writeAtofVectors(dir string) {
	f, w := create(dir, "atof_vectors.txt")
	_, _ = fmt.Fprintf(w, "# input<TAB>ParseFloat(64)-bits<TAB>err<TAB>ParseFloat(32)-bits<TAB>err<TAB>then the same four with optimize=false (slow path), or = if identical\n")
	line := func(s string) {
		v64, e64 := strconv.ParseFloat(s, 64)
		v32, e32 := strconv.ParseFloat(s, 32)
		strconvOptimize = false
		sv64, se64 := strconv.ParseFloat(s, 64)
		sv32, se32 := strconv.ParseFloat(s, 32)
		strconvOptimize = true
		fast := fmt.Sprintf("%016x\t%s\t%016x\t%s", math.Float64bits(v64), errCode(e64), math.Float64bits(v32), errCode(e32))
		slow := fmt.Sprintf("%016x\t%s\t%016x\t%s", math.Float64bits(sv64), errCode(se64), math.Float64bits(sv32), errCode(se32))
		if slow == fast {
			slow = "="
		}
		_, _ = fmt.Fprintf(w, "%s\t%s\t%s\n", s, fast, slow)
	}
	for _, l := range goTestdata("atof1k.txt") {
		line(l)
	}
	for _, l := range goTestdata("testfp.txt") {
		fields := strings.Split(l, " ")
		if len(fields) == 4 && !strings.Contains(fields[2], "p") {
			line(fields[2])
		}
	}
	r := newRng(200)
	variants := func(digits string, exp10 int, neg bool) {
		line(sci(digits, exp10, neg))
		line(sci(decrementLast(digits), exp10, neg))
		line(sci(digits+"000001", exp10, neg))
		if len(digits) > 20 {
			line(sci(digits[:17+r.intn(4)], exp10, neg))
		}
	}
	// float64 midpoints
	for i := 0; i < 1200; i++ {
		var b uint64
		if i < 1000 {
			// moderate magnitudes: shorter midpoints
			b = uint64(1023-60+r.intn(121))<<52 | r.next()&(1<<52-1)
		} else {
			b = genF64(r) &^ (1 << 63)
			if b>>52 >= 0x7fe {
				continue
			}
		}
		exp := int(b>>52) & 0x7ff
		mant := b & (1<<52 - 1)
		if exp == 0 {
			exp = 1
		} else {
			mant |= 1 << 52
		}
		e := exp - 1023 - 52
		d, x := midpointString(mant, e)
		variants(d, x, r.intn(4) == 0)
	}
	// float32 midpoints
	for i := 0; i < 1500; i++ {
		b := genF32(r) &^ (1 << 31)
		if b>>23 >= 0xfe {
			continue
		}
		exp := int(b>>23) & 0xff
		mant := uint64(b & (1<<23 - 1))
		if exp == 0 {
			exp = 1
		} else {
			mant |= 1 << 23
		}
		e := exp - 127 - 23
		d, x := midpointString(mant, e)
		variants(d, x, r.intn(4) == 0)
	}
	// long inputs around the 800-digit decimal buffer and 19-digit mantissa
	for _, n := range []int{17, 18, 19, 20, 21, 790, 799, 800, 801, 900} {
		line("1" + strings.Repeat("0", n) + "1")
		line("0." + strings.Repeat("0", n) + "1e" + strconv.Itoa(n))
		line("9" + strings.Repeat("9", n) + "e-" + strconv.Itoa(n))
		line("1." + strings.Repeat("0", n) + "1")
		line("4." + strings.Repeat("9", n) + "e-324")
		line("2.4703282292062327" + strings.Repeat("0", n) + "1e-324")
		line("2.4703282292062327208828439643411068618252990130716238221279284125033775363510437593264991818081799618989828234772285886546332835517796989819938739800539093906315035659515570226392290858392449105184435931802849936536152500319370457678249219365623669863658480757001585769269903706311928279558551332927834338409351978015531246597263579574622766465272827220056374006485499977096599470454020828166226237857393450736339007967761930577506740176324673600968951340535537458516661134223766678604162159680461914467291840300530057530849048765391711386591646239524912623653881879636239373280423891018672348497668235089863388587925628302755995657524455507255189313690836254779186948667994968324049705821028513185451396213837722826145437693412532098591327667236328125e-324")
	}
	// hex floats near boundaries
	for i := 0; i < 500; i++ {
		var b strings.Builder
		if r.intn(3) == 0 {
			b.WriteByte('-')
		}
		b.WriteString("0x")
		nd := 1 + r.intn(20)
		for j := 0; j < nd; j++ {
			b.WriteByte(hexDigits[r.intn(16)])
		}
		if r.intn(2) == 0 {
			b.WriteByte('.')
			nf := r.intn(20)
			for j := 0; j < nf; j++ {
				b.WriteByte(hexDigits[r.intn(16)])
			}
		}
		exps := []int{-1150, -1100, -1080, -1074, -1060, -1030, -1022, -160, -150, -149, -140, -126, 0, 100, 127, 128, 1000, 1023, 1024}
		fmt.Fprintf(&b, "p%d", exps[r.intn(len(exps))]-4*r.intn(nd+1))
		line(b.String())
	}
	closeW(f, w)
}

// atoi_vectors.txt: hex(input) base bitSize ParseInt-value ParseInt-err ParseUint-value ParseUint-err Atoi-value Atoi-err
func writeAtoiVectors(dir string) {
	f, w := create(dir, "atoi_vectors.txt")
	_, _ = fmt.Fprintf(w, "# hex(input)<TAB>base<TAB>bitSize<TAB>ParseInt<TAB>err<TAB>ParseUint<TAB>err<TAB>Atoi<TAB>err\n")
	r := newRng(300)
	for i := 0; i < 2500; i++ {
		s := string(genIntString(r))
		base := []int{0, 0, 0, 10, 16, 2, 8, 36, r.intn(40) - 1}[r.intn(9)]
		bits := []int{0, 8, 16, 32, 64, r.intn(70) - 2}[r.intn(6)]
		v, e1 := strconv.ParseInt(s, base, bits)
		u, e2 := strconv.ParseUint(s, base, bits)
		a, e3 := strconv.Atoi(s)
		_, _ = fmt.Fprintf(w, "%x\t%d\t%d\t%d\t%s\t%d\t%s\t%d\t%s\n", s, base, bits, v, errStr(e1), u, errStr(e2), a, errStr(e3))
	}
	closeW(f, w)
}

func errStr(err error) string {
	if err == nil {
		return "nil"
	}
	return err.Error()
}

// quote_vectors.txt: hex(input) Quote QuoteToASCII QuoteToGraphic CanBackquote hex(Unquote) err
func writeQuoteVectors(dir string) {
	f, w := create(dir, "quote_vectors.txt")
	_, _ = fmt.Fprintf(w, "# hex(input)<TAB>Quote<TAB>QuoteToASCII<TAB>QuoteToGraphic<TAB>CanBackquote<TAB>hex(Unquote(input))<TAB>err\n")
	r := newRng(400)
	for i := 0; i < 2500; i++ {
		s := string(genBytes(r))
		if i%3 == 0 {
			s = "\"" + s + "\""
		}
		u, err := strconv.Unquote(s)
		_, _ = fmt.Fprintf(w, "%x\t%s\t%s\t%s\t%v\t%x\t%s\n", s, strconv.Quote(s), strconv.QuoteToASCII(s), strconv.QuoteToGraphic(s), strconv.CanBackquote(s), u, errStr(err))
	}
	closeW(f, w)
}

// numerror.txt: func hex(input) base bitSize message
func writeNumErrors(dir string) {
	f, w := create(dir, "numerror.txt")
	_, _ = fmt.Fprintf(w, "# func<TAB>hex(input)<TAB>base<TAB>bitSize<TAB>error-message\n")
	type c struct {
		fn         string
		in         string
		base, bits int
	}
	cases := []c{
		{"ParseInt", "0", 1, 0}, {"ParseInt", "0", 37, 0}, {"ParseInt", "0", -1, 0},
		{"ParseInt", "0", 0, 65}, {"ParseInt", "0", 0, -1}, {"ParseInt", "0", 10, 100},
		{"ParseUint", "12", 1, 64}, {"ParseUint", "12", 10, 65},
		{"ParseInt", "", 1, 65}, {"ParseInt", "x", 1, 65}, {"ParseUint", "", 1, 0},
		{"ParseInt", "99999999999999999999", 10, 64}, {"ParseInt", "-99999999999999999999", 10, 64},
		{"ParseInt", "128", 10, 8}, {"ParseUint", "256", 10, 8}, {"ParseUint", "-1", 10, 8},
		{"ParseFloat", "1e400", 0, 64}, {"ParseFloat", "1e40", 0, 32}, {"ParseFloat", "abc", 0, 64},
		{"ParseFloat", "1\x00.2", 0, 64}, {"ParseFloat", "`", 0, 64}, {"ParseFloat", "\xff\xfe", 0, 64},
		{"ParseFloat", "é☺\U0001F600", 0, 64},
		{"ParseComplex", "1+2", 0, 128}, {"ParseComplex", "1e400i", 0, 128},
		{"ParseBool", "yes", 0, 0}, {"ParseBool", "", 0, 0},
		{"Atoi", "12a", 0, 0}, {"Atoi", "99999999999999999999", 0, 0}, {"Atoi", "", 0, 0}, {"Atoi", "-", 0, 0}, {"Atoi", "+", 0, 0},
		{"Atoi", "1_000", 0, 0},
	}
	for _, t := range cases {
		var err error
		switch t.fn {
		case "ParseInt":
			_, err = strconv.ParseInt(t.in, t.base, t.bits)
		case "ParseUint":
			_, err = strconv.ParseUint(t.in, t.base, t.bits)
		case "ParseFloat":
			_, err = strconv.ParseFloat(t.in, t.bits)
		case "ParseComplex":
			_, err = strconv.ParseComplex(t.in, t.bits)
		case "ParseBool":
			_, err = strconv.ParseBool(t.in)
		case "Atoi":
			_, err = strconv.Atoi(t.in)
		}
		_, _ = fmt.Fprintf(w, "%s\t%x\t%d\t%d\t%s\n", t.fn, t.in, t.base, t.bits, errStr(err))
	}
	closeW(f, w)
}
