// Code generated by tools/go-oracle/nh-publisher/xnethtml -atoms from golang.org/x/net@v0.41.0/html/atom/table.go; DO NOT EDIT.

//! The atoms of `golang.org/x/net/html/atom` (Go `Atom` values, names and `atomText`).

use super::Atom;

/// `a`
pub const A: Atom = 0x1;
/// `abbr`
pub const ABBR: Atom = 0x4;
/// `accept`
pub const ACCEPT: Atom = 0x1a06;
/// `accept-charset`
pub const ACCEPT_CHARSET: Atom = 0x1a0e;
/// `accesskey`
pub const ACCESSKEY: Atom = 0x2c09;
/// `acronym`
pub const ACRONYM: Atom = 0xaa07;
/// `action`
pub const ACTION: Atom = 0x26506;
/// `address`
pub const ADDRESS: Atom = 0x6f107;
/// `align`
pub const ALIGN: Atom = 0xb105;
/// `allowfullscreen`
pub const ALLOWFULLSCREEN: Atom = 0x3280f;
/// `allowpaymentrequest`
pub const ALLOWPAYMENTREQUEST: Atom = 0xc113;
/// `allowusermedia`
pub const ALLOWUSERMEDIA: Atom = 0xdd0e;
/// `alt`
pub const ALT: Atom = 0xf303;
/// `annotation`
pub const ANNOTATION: Atom = 0x1c90a;
/// `annotation-xml`
pub const ANNOTATION_XML: Atom = 0x1c90e;
/// `applet`
pub const APPLET: Atom = 0x30806;
/// `area`
pub const AREA: Atom = 0x35004;
/// `article`
pub const ARTICLE: Atom = 0x3f607;
/// `as`
pub const AS: Atom = 0x3c02;
/// `aside`
pub const ASIDE: Atom = 0x10705;
/// `async`
pub const ASYNC: Atom = 0xff05;
/// `audio`
pub const AUDIO: Atom = 0x11505;
/// `autocomplete`
pub const AUTOCOMPLETE: Atom = 0x26b0c;
/// `autofocus`
pub const AUTOFOCUS: Atom = 0x12109;
/// `autoplay`
pub const AUTOPLAY: Atom = 0x13c08;
/// `b`
pub const B: Atom = 0x101;
/// `base`
pub const BASE: Atom = 0x3b04;
/// `basefont`
pub const BASEFONT: Atom = 0x3b08;
/// `bdi`
pub const BDI: Atom = 0xba03;
/// `bdo`
pub const BDO: Atom = 0x14b03;
/// `bgsound`
pub const BGSOUND: Atom = 0x15e07;
/// `big`
pub const BIG: Atom = 0x17003;
/// `blink`
pub const BLINK: Atom = 0x17305;
/// `blockquote`
pub const BLOCKQUOTE: Atom = 0x1870a;
/// `body`
pub const BODY: Atom = 0x2804;
/// `br`
pub const BR: Atom = 0x202;
/// `button`
pub const BUTTON: Atom = 0x19106;
/// `canvas`
pub const CANVAS: Atom = 0x10306;
/// `caption`
pub const CAPTION: Atom = 0x22407;
/// `center`
pub const CENTER: Atom = 0x21306;
/// `challenge`
pub const CHALLENGE: Atom = 0x28e09;
/// `charset`
pub const CHARSET: Atom = 0x2107;
/// `checked`
pub const CHECKED: Atom = 0x5b507;
/// `cite`
pub const CITE: Atom = 0x19c04;
/// `class`
pub const CLASS: Atom = 0x55805;
/// `code`
pub const CODE: Atom = 0x5ee04;
/// `col`
pub const COL: Atom = 0x1ab03;
/// `colgroup`
pub const COLGROUP: Atom = 0x1ab08;
/// `color`
pub const COLOR: Atom = 0x1bf05;
/// `cols`
pub const COLS: Atom = 0x1c404;
/// `colspan`
pub const COLSPAN: Atom = 0x1c407;
/// `command`
pub const COMMAND: Atom = 0x1d707;
/// `content`
pub const CONTENT: Atom = 0x57b07;
/// `contenteditable`
pub const CONTENTEDITABLE: Atom = 0x57b0f;
/// `contextmenu`
pub const CONTEXTMENU: Atom = 0x37a0b;
/// `controls`
pub const CONTROLS: Atom = 0x1de08;
/// `coords`
pub const COORDS: Atom = 0x1f006;
/// `crossorigin`
pub const CROSSORIGIN: Atom = 0x1fa0b;
/// `data`
pub const DATA: Atom = 0x49904;
/// `datalist`
pub const DATALIST: Atom = 0x49908;
/// `datetime`
pub const DATETIME: Atom = 0x2ab08;
/// `dd`
pub const DD: Atom = 0x2bf02;
/// `default`
pub const DEFAULT: Atom = 0x10a07;
/// `defer`
pub const DEFER: Atom = 0x5f005;
/// `del`
pub const DEL: Atom = 0x44c03;
/// `desc`
pub const DESC: Atom = 0x55504;
/// `details`
pub const DETAILS: Atom = 0x7207;
/// `dfn`
pub const DFN: Atom = 0x8703;
/// `dialog`
pub const DIALOG: Atom = 0xbb06;
/// `dir`
pub const DIR: Atom = 0x9303;
/// `dirname`
pub const DIRNAME: Atom = 0x9307;
/// `disabled`
pub const DISABLED: Atom = 0x16408;
/// `div`
pub const DIV: Atom = 0x16b03;
/// `dl`
pub const DL: Atom = 0x5d602;
/// `download`
pub const DOWNLOAD: Atom = 0x45d08;
/// `draggable`
pub const DRAGGABLE: Atom = 0x17a09;
/// `dropzone`
pub const DROPZONE: Atom = 0x3ff08;
/// `dt`
pub const DT: Atom = 0x64002;
/// `em`
pub const EM: Atom = 0x6e02;
/// `embed`
pub const EMBED: Atom = 0x6e05;
/// `enctype`
pub const ENCTYPE: Atom = 0x28007;
/// `face`
pub const FACE: Atom = 0x21104;
/// `fieldset`
pub const FIELDSET: Atom = 0x21908;
/// `figcaption`
pub const FIGCAPTION: Atom = 0x2210a;
/// `figure`
pub const FIGURE: Atom = 0x23b06;
/// `font`
pub const FONT: Atom = 0x3f04;
/// `footer`
pub const FOOTER: Atom = 0xf606;
/// `for`
pub const FOR: Atom = 0x24703;
/// `foreignObject`
pub const FOREIGN_OBJECT: Atom = 0x2470d;
/// `foreignobject`
pub const FOREIGNOBJECT: Atom = 0x2540d;
/// `form`
pub const FORM: Atom = 0x26104;
/// `formaction`
pub const FORMACTION: Atom = 0x2610a;
/// `formenctype`
pub const FORMENCTYPE: Atom = 0x27c0b;
/// `formmethod`
pub const FORMMETHOD: Atom = 0x2970a;
/// `formnovalidate`
pub const FORMNOVALIDATE: Atom = 0x2a10e;
/// `formtarget`
pub const FORMTARGET: Atom = 0x2b30a;
/// `frame`
pub const FRAME: Atom = 0x8b05;
/// `frameset`
pub const FRAMESET: Atom = 0x8b08;
/// `h1`
pub const H1: Atom = 0x15c02;
/// `h2`
pub const H2: Atom = 0x56102;
/// `h3`
pub const H3: Atom = 0x2cd02;
/// `h4`
pub const H4: Atom = 0x2fc02;
/// `h5`
pub const H5: Atom = 0x33f02;
/// `h6`
pub const H6: Atom = 0x34902;
/// `head`
pub const HEAD: Atom = 0x32004;
/// `header`
pub const HEADER: Atom = 0x32006;
/// `headers`
pub const HEADERS: Atom = 0x32007;
/// `height`
pub const HEIGHT: Atom = 0x5206;
/// `hgroup`
pub const HGROUP: Atom = 0x64206;
/// `hidden`
pub const HIDDEN: Atom = 0x2bd06;
/// `high`
pub const HIGH: Atom = 0x2ca04;
/// `hr`
pub const HR: Atom = 0x15702;
/// `href`
pub const HREF: Atom = 0x2cf04;
/// `hreflang`
pub const HREFLANG: Atom = 0x2cf08;
/// `html`
pub const HTML: Atom = 0x5604;
/// `http-equiv`
pub const HTTP_EQUIV: Atom = 0x2d70a;
/// `i`
pub const I: Atom = 0x601;
/// `icon`
pub const ICON: Atom = 0x57a04;
/// `id`
pub const ID: Atom = 0x10902;
/// `iframe`
pub const IFRAME: Atom = 0x2eb06;
/// `image`
pub const IMAGE: Atom = 0x2f105;
/// `img`
pub const IMG: Atom = 0x2f603;
/// `input`
pub const INPUT: Atom = 0x44505;
/// `inputmode`
pub const INPUTMODE: Atom = 0x44509;
/// `ins`
pub const INS: Atom = 0x20303;
/// `integrity`
pub const INTEGRITY: Atom = 0x23209;
/// `is`
pub const IS: Atom = 0x16502;
/// `isindex`
pub const ISINDEX: Atom = 0x2fe07;
/// `ismap`
pub const ISMAP: Atom = 0x30505;
/// `itemid`
pub const ITEMID: Atom = 0x38506;
/// `itemprop`
pub const ITEMPROP: Atom = 0x19d08;
/// `itemref`
pub const ITEMREF: Atom = 0x3c707;
/// `itemscope`
pub const ITEMSCOPE: Atom = 0x66f09;
/// `itemtype`
pub const ITEMTYPE: Atom = 0x30e08;
/// `kbd`
pub const KBD: Atom = 0xb903;
/// `keygen`
pub const KEYGEN: Atom = 0x3206;
/// `keytype`
pub const KEYTYPE: Atom = 0xd607;
/// `kind`
pub const KIND: Atom = 0x17704;
/// `label`
pub const LABEL: Atom = 0x5905;
/// `lang`
pub const LANG: Atom = 0x2d304;
/// `legend`
pub const LEGEND: Atom = 0x18106;
/// `li`
pub const LI: Atom = 0xb202;
/// `link`
pub const LINK: Atom = 0x17404;
/// `list`
pub const LIST: Atom = 0x49d04;
/// `listing`
pub const LISTING: Atom = 0x49d07;
/// `loop`
pub const LOOP: Atom = 0x5d04;
/// `low`
pub const LOW: Atom = 0xc303;
/// `main`
pub const MAIN: Atom = 0x1004;
/// `malignmark`
pub const MALIGNMARK: Atom = 0xb00a;
/// `manifest`
pub const MANIFEST: Atom = 0x6d508;
/// `map`
pub const MAP: Atom = 0x30703;
/// `mark`
pub const MARK: Atom = 0xb604;
/// `marquee`
pub const MARQUEE: Atom = 0x31607;
/// `math`
pub const MATH: Atom = 0x31d04;
/// `max`
pub const MAX: Atom = 0x33703;
/// `maxlength`
pub const MAXLENGTH: Atom = 0x33709;
/// `media`
pub const MEDIA: Atom = 0xe605;
/// `mediagroup`
pub const MEDIAGROUP: Atom = 0xe60a;
/// `menu`
pub const MENU: Atom = 0x38104;
/// `menuitem`
pub const MENUITEM: Atom = 0x38108;
/// `meta`
pub const META: Atom = 0x4ac04;
/// `meter`
pub const METER: Atom = 0x9805;
/// `method`
pub const METHOD: Atom = 0x29b06;
/// `mglyph`
pub const MGLYPH: Atom = 0x2f706;
/// `mi`
pub const MI: Atom = 0x34102;
/// `min`
pub const MIN: Atom = 0x34103;
/// `minlength`
pub const MINLENGTH: Atom = 0x34109;
/// `mn`
pub const MN: Atom = 0x2a402;
/// `mo`
pub const MO: Atom = 0xa402;
/// `ms`
pub const MS: Atom = 0x67202;
/// `mtext`
pub const MTEXT: Atom = 0x34b05;
/// `multiple`
pub const MULTIPLE: Atom = 0x35908;
/// `muted`
pub const MUTED: Atom = 0x36105;
/// `name`
pub const NAME: Atom = 0x9604;
/// `nav`
pub const NAV: Atom = 0x1303;
/// `nobr`
pub const NOBR: Atom = 0x3704;
/// `noembed`
pub const NOEMBED: Atom = 0x6c07;
/// `noframes`
pub const NOFRAMES: Atom = 0x8908;
/// `nomodule`
pub const NOMODULE: Atom = 0xa208;
/// `nonce`
pub const NONCE: Atom = 0x1a605;
/// `noscript`
pub const NOSCRIPT: Atom = 0x2c208;
/// `novalidate`
pub const NOVALIDATE: Atom = 0x2a50a;
/// `object`
pub const OBJECT: Atom = 0x25b06;
/// `ol`
pub const OL: Atom = 0x13702;
/// `onabort`
pub const ONABORT: Atom = 0x19507;
/// `onafterprint`
pub const ONAFTERPRINT: Atom = 0x2290c;
/// `onautocomplete`
pub const ONAUTOCOMPLETE: Atom = 0x2690e;
/// `onautocompleteerror`
pub const ONAUTOCOMPLETEERROR: Atom = 0x26913;
/// `onauxclick`
pub const ONAUXCLICK: Atom = 0x6140a;
/// `onbeforeprint`
pub const ONBEFOREPRINT: Atom = 0x69c0d;
/// `onbeforeunload`
pub const ONBEFOREUNLOAD: Atom = 0x6e50e;
/// `onblur`
pub const ONBLUR: Atom = 0x1ea06;
/// `oncancel`
pub const ONCANCEL: Atom = 0x11908;
/// `oncanplay`
pub const ONCANPLAY: Atom = 0x14d09;
/// `oncanplaythrough`
pub const ONCANPLAYTHROUGH: Atom = 0x14d10;
/// `onchange`
pub const ONCHANGE: Atom = 0x41508;
/// `onclick`
pub const ONCLICK: Atom = 0x2e407;
/// `onclose`
pub const ONCLOSE: Atom = 0x36607;
/// `oncontextmenu`
pub const ONCONTEXTMENU: Atom = 0x3780d;
/// `oncopy`
pub const ONCOPY: Atom = 0x38b06;
/// `oncuechange`
pub const ONCUECHANGE: Atom = 0x3910b;
/// `oncut`
pub const ONCUT: Atom = 0x39c05;
/// `ondblclick`
pub const ONDBLCLICK: Atom = 0x3a10a;
/// `ondrag`
pub const ONDRAG: Atom = 0x3ab06;
/// `ondragend`
pub const ONDRAGEND: Atom = 0x3ab09;
/// `ondragenter`
pub const ONDRAGENTER: Atom = 0x3b40b;
/// `ondragexit`
pub const ONDRAGEXIT: Atom = 0x3bf0a;
/// `ondragleave`
pub const ONDRAGLEAVE: Atom = 0x3d90b;
/// `ondragover`
pub const ONDRAGOVER: Atom = 0x3e40a;
/// `ondragstart`
pub const ONDRAGSTART: Atom = 0x3ee0b;
/// `ondrop`
pub const ONDROP: Atom = 0x3fd06;
/// `ondurationchange`
pub const ONDURATIONCHANGE: Atom = 0x40d10;
/// `onemptied`
pub const ONEMPTIED: Atom = 0x40409;
/// `onended`
pub const ONENDED: Atom = 0x41d07;
/// `onerror`
pub const ONERROR: Atom = 0x42407;
/// `onfocus`
pub const ONFOCUS: Atom = 0x42b07;
/// `onhashchange`
pub const ONHASHCHANGE: Atom = 0x4370c;
/// `oninput`
pub const ONINPUT: Atom = 0x44307;
/// `oninvalid`
pub const ONINVALID: Atom = 0x44f09;
/// `onkeydown`
pub const ONKEYDOWN: Atom = 0x45809;
/// `onkeypress`
pub const ONKEYPRESS: Atom = 0x4650a;
/// `onkeyup`
pub const ONKEYUP: Atom = 0x47407;
/// `onlanguagechange`
pub const ONLANGUAGECHANGE: Atom = 0x48110;
/// `onload`
pub const ONLOAD: Atom = 0x49106;
/// `onloadeddata`
pub const ONLOADEDDATA: Atom = 0x4910c;
/// `onloadedmetadata`
pub const ONLOADEDMETADATA: Atom = 0x4a410;
/// `onloadend`
pub const ONLOADEND: Atom = 0x4ba09;
/// `onloadstart`
pub const ONLOADSTART: Atom = 0x4c30b;
/// `onmessage`
pub const ONMESSAGE: Atom = 0x4ce09;
/// `onmessageerror`
pub const ONMESSAGEERROR: Atom = 0x4ce0e;
/// `onmousedown`
pub const ONMOUSEDOWN: Atom = 0x4dc0b;
/// `onmouseenter`
pub const ONMOUSEENTER: Atom = 0x4e70c;
/// `onmouseleave`
pub const ONMOUSELEAVE: Atom = 0x4f30c;
/// `onmousemove`
pub const ONMOUSEMOVE: Atom = 0x4ff0b;
/// `onmouseout`
pub const ONMOUSEOUT: Atom = 0x50a0a;
/// `onmouseover`
pub const ONMOUSEOVER: Atom = 0x5170b;
/// `onmouseup`
pub const ONMOUSEUP: Atom = 0x52209;
/// `onmousewheel`
pub const ONMOUSEWHEEL: Atom = 0x5300c;
/// `onoffline`
pub const ONOFFLINE: Atom = 0x53c09;
/// `ononline`
pub const ONONLINE: Atom = 0x54508;
/// `onpagehide`
pub const ONPAGEHIDE: Atom = 0x54d0a;
/// `onpageshow`
pub const ONPAGESHOW: Atom = 0x5630a;
/// `onpaste`
pub const ONPASTE: Atom = 0x56f07;
/// `onpause`
pub const ONPAUSE: Atom = 0x58a07;
/// `onplay`
pub const ONPLAY: Atom = 0x59406;
/// `onplaying`
pub const ONPLAYING: Atom = 0x59409;
/// `onpopstate`
pub const ONPOPSTATE: Atom = 0x59d0a;
/// `onprogress`
pub const ONPROGRESS: Atom = 0x5a70a;
/// `onratechange`
pub const ONRATECHANGE: Atom = 0x5bc0c;
/// `onrejectionhandled`
pub const ONREJECTIONHANDLED: Atom = 0x5c812;
/// `onreset`
pub const ONRESET: Atom = 0x5da07;
/// `onresize`
pub const ONRESIZE: Atom = 0x5e108;
/// `onscroll`
pub const ONSCROLL: Atom = 0x5f508;
/// `onsecuritypolicyviolation`
pub const ONSECURITYPOLICYVIOLATION: Atom = 0x5fd19;
/// `onseeked`
pub const ONSEEKED: Atom = 0x61e08;
/// `onseeking`
pub const ONSEEKING: Atom = 0x62609;
/// `onselect`
pub const ONSELECT: Atom = 0x62f08;
/// `onshow`
pub const ONSHOW: Atom = 0x63906;
/// `onsort`
pub const ONSORT: Atom = 0x64d06;
/// `onstalled`
pub const ONSTALLED: Atom = 0x65709;
/// `onstorage`
pub const ONSTORAGE: Atom = 0x66009;
/// `onsubmit`
pub const ONSUBMIT: Atom = 0x66908;
/// `onsuspend`
pub const ONSUSPEND: Atom = 0x67909;
/// `ontimeupdate`
pub const ONTIMEUPDATE: Atom = 0x400c;
/// `ontoggle`
pub const ONTOGGLE: Atom = 0x68208;
/// `onunhandledrejection`
pub const ONUNHANDLEDREJECTION: Atom = 0x68a14;
/// `onunload`
pub const ONUNLOAD: Atom = 0x6a908;
/// `onvolumechange`
pub const ONVOLUMECHANGE: Atom = 0x6b10e;
/// `onwaiting`
pub const ONWAITING: Atom = 0x6bf09;
/// `onwheel`
pub const ONWHEEL: Atom = 0x6c807;
/// `open`
pub const OPEN: Atom = 0x1a304;
/// `optgroup`
pub const OPTGROUP: Atom = 0x5f08;
/// `optimum`
pub const OPTIMUM: Atom = 0x6cf07;
/// `option`
pub const OPTION: Atom = 0x6e106;
/// `output`
pub const OUTPUT: Atom = 0x51106;
/// `p`
pub const P: Atom = 0xc01;
/// `param`
pub const PARAM: Atom = 0xc05;
/// `pattern`
pub const PATTERN: Atom = 0x6607;
/// `picture`
pub const PICTURE: Atom = 0x7b07;
/// `ping`
pub const PING: Atom = 0xef04;
/// `placeholder`
pub const PLACEHOLDER: Atom = 0x1310b;
/// `plaintext`
pub const PLAINTEXT: Atom = 0x1b209;
/// `playsinline`
pub const PLAYSINLINE: Atom = 0x1400b;
/// `poster`
pub const POSTER: Atom = 0x64706;
/// `pre`
pub const PRE: Atom = 0x46a03;
/// `preload`
pub const PRELOAD: Atom = 0x47a07;
/// `progress`
pub const PROGRESS: Atom = 0x5a908;
/// `prompt`
pub const PROMPT: Atom = 0x52a06;
/// `public`
pub const PUBLIC: Atom = 0x57606;
/// `q`
pub const Q: Atom = 0xcf01;
/// `radiogroup`
pub const RADIOGROUP: Atom = 0x30a;
/// `rb`
pub const RB: Atom = 0x3a02;
/// `readonly`
pub const READONLY: Atom = 0x35108;
/// `referrerpolicy`
pub const REFERRERPOLICY: Atom = 0x3cb0e;
/// `rel`
pub const REL: Atom = 0x47b03;
/// `required`
pub const REQUIRED: Atom = 0x23f08;
/// `reversed`
pub const REVERSED: Atom = 0x8008;
/// `rows`
pub const ROWS: Atom = 0x9c04;
/// `rowspan`
pub const ROWSPAN: Atom = 0x9c07;
/// `rp`
pub const RP: Atom = 0x22f02;
/// `rt`
pub const RT: Atom = 0x19a02;
/// `rtc`
pub const RTC: Atom = 0x19a03;
/// `ruby`
pub const RUBY: Atom = 0xfb04;
/// `s`
pub const S: Atom = 0x2501;
/// `samp`
pub const SAMP: Atom = 0x7804;
/// `sandbox`
pub const SANDBOX: Atom = 0x12907;
/// `scope`
pub const SCOPE: Atom = 0x67305;
/// `scoped`
pub const SCOPED: Atom = 0x67306;
/// `script`
pub const SCRIPT: Atom = 0x2c406;
/// `seamless`
pub const SEAMLESS: Atom = 0x36b08;
/// `search`
pub const SEARCH: Atom = 0x55c06;
/// `section`
pub const SECTION: Atom = 0x1e507;
/// `select`
pub const SELECT: Atom = 0x63106;
/// `selected`
pub const SELECTED: Atom = 0x63108;
/// `shape`
pub const SHAPE: Atom = 0x1f505;
/// `size`
pub const SIZE: Atom = 0x5e504;
/// `sizes`
pub const SIZES: Atom = 0x5e505;
/// `slot`
pub const SLOT: Atom = 0x20504;
/// `small`
pub const SMALL: Atom = 0x32605;
/// `sortable`
pub const SORTABLE: Atom = 0x64f08;
/// `sorted`
pub const SORTED: Atom = 0x37206;
/// `source`
pub const SOURCE: Atom = 0x43106;
/// `spacer`
pub const SPACER: Atom = 0x46e06;
/// `span`
pub const SPAN: Atom = 0x9f04;
/// `spellcheck`
pub const SPELLCHECK: Atom = 0x5b00a;
/// `src`
pub const SRC: Atom = 0x5e903;
/// `srcdoc`
pub const SRCDOC: Atom = 0x5e906;
/// `srclang`
pub const SRCLANG: Atom = 0x6f707;
/// `srcset`
pub const SRCSET: Atom = 0x6fe06;
/// `start`
pub const START: Atom = 0x3f405;
/// `step`
pub const STEP: Atom = 0x57304;
/// `strike`
pub const STRIKE: Atom = 0xd206;
/// `strong`
pub const STRONG: Atom = 0x6db06;
/// `style`
pub const STYLE: Atom = 0x70405;
/// `sub`
pub const SUB: Atom = 0x66b03;
/// `summary`
pub const SUMMARY: Atom = 0x70907;
/// `sup`
pub const SUP: Atom = 0x71003;
/// `svg`
pub const SVG: Atom = 0x71303;
/// `system`
pub const SYSTEM: Atom = 0x71606;
/// `tabindex`
pub const TABINDEX: Atom = 0x4b208;
/// `table`
pub const TABLE: Atom = 0x58505;
/// `target`
pub const TARGET: Atom = 0x2b706;
/// `tbody`
pub const TBODY: Atom = 0x2705;
/// `td`
pub const TD: Atom = 0x9202;
/// `template`
pub const TEMPLATE: Atom = 0x71908;
/// `textarea`
pub const TEXTAREA: Atom = 0x34c08;
/// `tfoot`
pub const TFOOT: Atom = 0xf505;
/// `th`
pub const TH: Atom = 0x15602;
/// `thead`
pub const THEAD: Atom = 0x31f05;
/// `time`
pub const TIME: Atom = 0x4204;
/// `title`
pub const TITLE: Atom = 0x11005;
/// `tr`
pub const TR: Atom = 0xcc02;
/// `track`
pub const TRACK: Atom = 0x1ba05;
/// `translate`
pub const TRANSLATE: Atom = 0x20809;
/// `tt`
pub const TT: Atom = 0x6802;
/// `type`
pub const TYPE: Atom = 0xd904;
/// `typemustmatch`
pub const TYPEMUSTMATCH: Atom = 0x2830d;
/// `u`
pub const U: Atom = 0xb01;
/// `ul`
pub const UL: Atom = 0xa702;
/// `updateviacache`
pub const UPDATEVIACACHE: Atom = 0x460e;
/// `usemap`
pub const USEMAP: Atom = 0x58e06;
/// `value`
pub const VALUE: Atom = 0x1505;
/// `var`
pub const VAR: Atom = 0x16d03;
/// `video`
pub const VIDEO: Atom = 0x2e005;
/// `wbr`
pub const WBR: Atom = 0x56c03;
/// `width`
pub const WIDTH: Atom = 0x63e05;
/// `workertype`
pub const WORKERTYPE: Atom = 0x7210a;
/// `wrap`
pub const WRAP: Atom = 0x72b04;
/// `xmp`
pub const XMP: Atom = 0x12f03;

/// Go `atomText`.
pub(super) const ATOM_TEXT: &[u8] = b"abbradiogrouparamainavalueaccept-charsetbodyaccesskeygenobrbasefontimeupdateviacacheightmlabelooptgroupatternoembedetailsampictureversedfnoframesetdirnameterowspanomoduleacronymalignmarkbdialogallowpaymentrequestrikeytypeallowusermediagroupingaltfooterubyasyncanvasidefaultitleaudioncancelautofocusandboxmplaceholderautoplaysinlinebdoncanplaythrough1bgsoundisabledivarbigblinkindraggablegendblockquotebuttonabortcitempropenoncecolgrouplaintextrackcolorcolspannotation-xmlcommandcontrolsectionblurcoordshapecrossoriginslotranslatefacenterfieldsetfigcaptionafterprintegrityfigurequiredforeignObjectforeignobjectformactionautocompleteerrorformenctypemustmatchallengeformmethodformnovalidatetimeformtargethiddenoscripthigh3hreflanghttp-equivideonclickiframeimageimglyph4isindexismappletitemtypemarqueematheadersmallowfullscreenmaxlength5minlength6mtextareadonlymultiplemutedoncloseamlessortedoncontextmenuitemidoncopyoncuechangeoncutondblclickondragendondragenterondragexitemreferrerpolicyondragleaveondragoverondragstarticleondropzonemptiedondurationchangeonendedonerroronfocusourceonhashchangeoninputmodeloninvalidonkeydownloadonkeypresspaceronkeyupreloadonlanguagechangeonloadeddatalistingonloadedmetadatabindexonloadendonloadstartonmessageerroronmousedownonmouseenteronmouseleaveonmousemoveonmouseoutputonmouseoveronmouseupromptonmousewheelonofflineononlineonpagehidesclassearch2onpageshowbronpastepublicontenteditableonpausemaponplayingonpopstateonprogresspellcheckedonratechangeonrejectionhandledonresetonresizesrcdocodeferonscrollonsecuritypolicyviolationauxclickonseekedonseekingonselectedonshowidthgrouposteronsortableonstalledonstorageonsubmitemscopedonsuspendontoggleonunhandledrejectionbeforeprintonunloadonvolumechangeonwaitingonwheeloptimumanifestrongoptionbeforeunloaddressrclangsrcsetstylesummarysupsvgsystemplateworkertypewrap";

/// Every atom by name (sorted), for `Lookup`.
pub(super) static BY_NAME: [(&[u8], Atom); 369] = [
    (b"a", 0x1),
    (b"abbr", 0x4),
    (b"accept", 0x1a06),
    (b"accept-charset", 0x1a0e),
    (b"accesskey", 0x2c09),
    (b"acronym", 0xaa07),
    (b"action", 0x26506),
    (b"address", 0x6f107),
    (b"align", 0xb105),
    (b"allowfullscreen", 0x3280f),
    (b"allowpaymentrequest", 0xc113),
    (b"allowusermedia", 0xdd0e),
    (b"alt", 0xf303),
    (b"annotation", 0x1c90a),
    (b"annotation-xml", 0x1c90e),
    (b"applet", 0x30806),
    (b"area", 0x35004),
    (b"article", 0x3f607),
    (b"as", 0x3c02),
    (b"aside", 0x10705),
    (b"async", 0xff05),
    (b"audio", 0x11505),
    (b"autocomplete", 0x26b0c),
    (b"autofocus", 0x12109),
    (b"autoplay", 0x13c08),
    (b"b", 0x101),
    (b"base", 0x3b04),
    (b"basefont", 0x3b08),
    (b"bdi", 0xba03),
    (b"bdo", 0x14b03),
    (b"bgsound", 0x15e07),
    (b"big", 0x17003),
    (b"blink", 0x17305),
    (b"blockquote", 0x1870a),
    (b"body", 0x2804),
    (b"br", 0x202),
    (b"button", 0x19106),
    (b"canvas", 0x10306),
    (b"caption", 0x22407),
    (b"center", 0x21306),
    (b"challenge", 0x28e09),
    (b"charset", 0x2107),
    (b"checked", 0x5b507),
    (b"cite", 0x19c04),
    (b"class", 0x55805),
    (b"code", 0x5ee04),
    (b"col", 0x1ab03),
    (b"colgroup", 0x1ab08),
    (b"color", 0x1bf05),
    (b"cols", 0x1c404),
    (b"colspan", 0x1c407),
    (b"command", 0x1d707),
    (b"content", 0x57b07),
    (b"contenteditable", 0x57b0f),
    (b"contextmenu", 0x37a0b),
    (b"controls", 0x1de08),
    (b"coords", 0x1f006),
    (b"crossorigin", 0x1fa0b),
    (b"data", 0x49904),
    (b"datalist", 0x49908),
    (b"datetime", 0x2ab08),
    (b"dd", 0x2bf02),
    (b"default", 0x10a07),
    (b"defer", 0x5f005),
    (b"del", 0x44c03),
    (b"desc", 0x55504),
    (b"details", 0x7207),
    (b"dfn", 0x8703),
    (b"dialog", 0xbb06),
    (b"dir", 0x9303),
    (b"dirname", 0x9307),
    (b"disabled", 0x16408),
    (b"div", 0x16b03),
    (b"dl", 0x5d602),
    (b"download", 0x45d08),
    (b"draggable", 0x17a09),
    (b"dropzone", 0x3ff08),
    (b"dt", 0x64002),
    (b"em", 0x6e02),
    (b"embed", 0x6e05),
    (b"enctype", 0x28007),
    (b"face", 0x21104),
    (b"fieldset", 0x21908),
    (b"figcaption", 0x2210a),
    (b"figure", 0x23b06),
    (b"font", 0x3f04),
    (b"footer", 0xf606),
    (b"for", 0x24703),
    (b"foreignObject", 0x2470d),
    (b"foreignobject", 0x2540d),
    (b"form", 0x26104),
    (b"formaction", 0x2610a),
    (b"formenctype", 0x27c0b),
    (b"formmethod", 0x2970a),
    (b"formnovalidate", 0x2a10e),
    (b"formtarget", 0x2b30a),
    (b"frame", 0x8b05),
    (b"frameset", 0x8b08),
    (b"h1", 0x15c02),
    (b"h2", 0x56102),
    (b"h3", 0x2cd02),
    (b"h4", 0x2fc02),
    (b"h5", 0x33f02),
    (b"h6", 0x34902),
    (b"head", 0x32004),
    (b"header", 0x32006),
    (b"headers", 0x32007),
    (b"height", 0x5206),
    (b"hgroup", 0x64206),
    (b"hidden", 0x2bd06),
    (b"high", 0x2ca04),
    (b"hr", 0x15702),
    (b"href", 0x2cf04),
    (b"hreflang", 0x2cf08),
    (b"html", 0x5604),
    (b"http-equiv", 0x2d70a),
    (b"i", 0x601),
    (b"icon", 0x57a04),
    (b"id", 0x10902),
    (b"iframe", 0x2eb06),
    (b"image", 0x2f105),
    (b"img", 0x2f603),
    (b"input", 0x44505),
    (b"inputmode", 0x44509),
    (b"ins", 0x20303),
    (b"integrity", 0x23209),
    (b"is", 0x16502),
    (b"isindex", 0x2fe07),
    (b"ismap", 0x30505),
    (b"itemid", 0x38506),
    (b"itemprop", 0x19d08),
    (b"itemref", 0x3c707),
    (b"itemscope", 0x66f09),
    (b"itemtype", 0x30e08),
    (b"kbd", 0xb903),
    (b"keygen", 0x3206),
    (b"keytype", 0xd607),
    (b"kind", 0x17704),
    (b"label", 0x5905),
    (b"lang", 0x2d304),
    (b"legend", 0x18106),
    (b"li", 0xb202),
    (b"link", 0x17404),
    (b"list", 0x49d04),
    (b"listing", 0x49d07),
    (b"loop", 0x5d04),
    (b"low", 0xc303),
    (b"main", 0x1004),
    (b"malignmark", 0xb00a),
    (b"manifest", 0x6d508),
    (b"map", 0x30703),
    (b"mark", 0xb604),
    (b"marquee", 0x31607),
    (b"math", 0x31d04),
    (b"max", 0x33703),
    (b"maxlength", 0x33709),
    (b"media", 0xe605),
    (b"mediagroup", 0xe60a),
    (b"menu", 0x38104),
    (b"menuitem", 0x38108),
    (b"meta", 0x4ac04),
    (b"meter", 0x9805),
    (b"method", 0x29b06),
    (b"mglyph", 0x2f706),
    (b"mi", 0x34102),
    (b"min", 0x34103),
    (b"minlength", 0x34109),
    (b"mn", 0x2a402),
    (b"mo", 0xa402),
    (b"ms", 0x67202),
    (b"mtext", 0x34b05),
    (b"multiple", 0x35908),
    (b"muted", 0x36105),
    (b"name", 0x9604),
    (b"nav", 0x1303),
    (b"nobr", 0x3704),
    (b"noembed", 0x6c07),
    (b"noframes", 0x8908),
    (b"nomodule", 0xa208),
    (b"nonce", 0x1a605),
    (b"noscript", 0x2c208),
    (b"novalidate", 0x2a50a),
    (b"object", 0x25b06),
    (b"ol", 0x13702),
    (b"onabort", 0x19507),
    (b"onafterprint", 0x2290c),
    (b"onautocomplete", 0x2690e),
    (b"onautocompleteerror", 0x26913),
    (b"onauxclick", 0x6140a),
    (b"onbeforeprint", 0x69c0d),
    (b"onbeforeunload", 0x6e50e),
    (b"onblur", 0x1ea06),
    (b"oncancel", 0x11908),
    (b"oncanplay", 0x14d09),
    (b"oncanplaythrough", 0x14d10),
    (b"onchange", 0x41508),
    (b"onclick", 0x2e407),
    (b"onclose", 0x36607),
    (b"oncontextmenu", 0x3780d),
    (b"oncopy", 0x38b06),
    (b"oncuechange", 0x3910b),
    (b"oncut", 0x39c05),
    (b"ondblclick", 0x3a10a),
    (b"ondrag", 0x3ab06),
    (b"ondragend", 0x3ab09),
    (b"ondragenter", 0x3b40b),
    (b"ondragexit", 0x3bf0a),
    (b"ondragleave", 0x3d90b),
    (b"ondragover", 0x3e40a),
    (b"ondragstart", 0x3ee0b),
    (b"ondrop", 0x3fd06),
    (b"ondurationchange", 0x40d10),
    (b"onemptied", 0x40409),
    (b"onended", 0x41d07),
    (b"onerror", 0x42407),
    (b"onfocus", 0x42b07),
    (b"onhashchange", 0x4370c),
    (b"oninput", 0x44307),
    (b"oninvalid", 0x44f09),
    (b"onkeydown", 0x45809),
    (b"onkeypress", 0x4650a),
    (b"onkeyup", 0x47407),
    (b"onlanguagechange", 0x48110),
    (b"onload", 0x49106),
    (b"onloadeddata", 0x4910c),
    (b"onloadedmetadata", 0x4a410),
    (b"onloadend", 0x4ba09),
    (b"onloadstart", 0x4c30b),
    (b"onmessage", 0x4ce09),
    (b"onmessageerror", 0x4ce0e),
    (b"onmousedown", 0x4dc0b),
    (b"onmouseenter", 0x4e70c),
    (b"onmouseleave", 0x4f30c),
    (b"onmousemove", 0x4ff0b),
    (b"onmouseout", 0x50a0a),
    (b"onmouseover", 0x5170b),
    (b"onmouseup", 0x52209),
    (b"onmousewheel", 0x5300c),
    (b"onoffline", 0x53c09),
    (b"ononline", 0x54508),
    (b"onpagehide", 0x54d0a),
    (b"onpageshow", 0x5630a),
    (b"onpaste", 0x56f07),
    (b"onpause", 0x58a07),
    (b"onplay", 0x59406),
    (b"onplaying", 0x59409),
    (b"onpopstate", 0x59d0a),
    (b"onprogress", 0x5a70a),
    (b"onratechange", 0x5bc0c),
    (b"onrejectionhandled", 0x5c812),
    (b"onreset", 0x5da07),
    (b"onresize", 0x5e108),
    (b"onscroll", 0x5f508),
    (b"onsecuritypolicyviolation", 0x5fd19),
    (b"onseeked", 0x61e08),
    (b"onseeking", 0x62609),
    (b"onselect", 0x62f08),
    (b"onshow", 0x63906),
    (b"onsort", 0x64d06),
    (b"onstalled", 0x65709),
    (b"onstorage", 0x66009),
    (b"onsubmit", 0x66908),
    (b"onsuspend", 0x67909),
    (b"ontimeupdate", 0x400c),
    (b"ontoggle", 0x68208),
    (b"onunhandledrejection", 0x68a14),
    (b"onunload", 0x6a908),
    (b"onvolumechange", 0x6b10e),
    (b"onwaiting", 0x6bf09),
    (b"onwheel", 0x6c807),
    (b"open", 0x1a304),
    (b"optgroup", 0x5f08),
    (b"optimum", 0x6cf07),
    (b"option", 0x6e106),
    (b"output", 0x51106),
    (b"p", 0xc01),
    (b"param", 0xc05),
    (b"pattern", 0x6607),
    (b"picture", 0x7b07),
    (b"ping", 0xef04),
    (b"placeholder", 0x1310b),
    (b"plaintext", 0x1b209),
    (b"playsinline", 0x1400b),
    (b"poster", 0x64706),
    (b"pre", 0x46a03),
    (b"preload", 0x47a07),
    (b"progress", 0x5a908),
    (b"prompt", 0x52a06),
    (b"public", 0x57606),
    (b"q", 0xcf01),
    (b"radiogroup", 0x30a),
    (b"rb", 0x3a02),
    (b"readonly", 0x35108),
    (b"referrerpolicy", 0x3cb0e),
    (b"rel", 0x47b03),
    (b"required", 0x23f08),
    (b"reversed", 0x8008),
    (b"rows", 0x9c04),
    (b"rowspan", 0x9c07),
    (b"rp", 0x22f02),
    (b"rt", 0x19a02),
    (b"rtc", 0x19a03),
    (b"ruby", 0xfb04),
    (b"s", 0x2501),
    (b"samp", 0x7804),
    (b"sandbox", 0x12907),
    (b"scope", 0x67305),
    (b"scoped", 0x67306),
    (b"script", 0x2c406),
    (b"seamless", 0x36b08),
    (b"search", 0x55c06),
    (b"section", 0x1e507),
    (b"select", 0x63106),
    (b"selected", 0x63108),
    (b"shape", 0x1f505),
    (b"size", 0x5e504),
    (b"sizes", 0x5e505),
    (b"slot", 0x20504),
    (b"small", 0x32605),
    (b"sortable", 0x64f08),
    (b"sorted", 0x37206),
    (b"source", 0x43106),
    (b"spacer", 0x46e06),
    (b"span", 0x9f04),
    (b"spellcheck", 0x5b00a),
    (b"src", 0x5e903),
    (b"srcdoc", 0x5e906),
    (b"srclang", 0x6f707),
    (b"srcset", 0x6fe06),
    (b"start", 0x3f405),
    (b"step", 0x57304),
    (b"strike", 0xd206),
    (b"strong", 0x6db06),
    (b"style", 0x70405),
    (b"sub", 0x66b03),
    (b"summary", 0x70907),
    (b"sup", 0x71003),
    (b"svg", 0x71303),
    (b"system", 0x71606),
    (b"tabindex", 0x4b208),
    (b"table", 0x58505),
    (b"target", 0x2b706),
    (b"tbody", 0x2705),
    (b"td", 0x9202),
    (b"template", 0x71908),
    (b"textarea", 0x34c08),
    (b"tfoot", 0xf505),
    (b"th", 0x15602),
    (b"thead", 0x31f05),
    (b"time", 0x4204),
    (b"title", 0x11005),
    (b"tr", 0xcc02),
    (b"track", 0x1ba05),
    (b"translate", 0x20809),
    (b"tt", 0x6802),
    (b"type", 0xd904),
    (b"typemustmatch", 0x2830d),
    (b"u", 0xb01),
    (b"ul", 0xa702),
    (b"updateviacache", 0x460e),
    (b"usemap", 0x58e06),
    (b"value", 0x1505),
    (b"var", 0x16d03),
    (b"video", 0x2e005),
    (b"wbr", 0x56c03),
    (b"width", 0x63e05),
    (b"workertype", 0x7210a),
    (b"wrap", 0x72b04),
    (b"xmp", 0x12f03),
];
