[package]
name = "ssg-jsbuild"
description = "js.Build: bundles scripts in process with rolldown"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true
autotests = false

[lib]
doctest = false

[[test]]
name = "it"
path = "tests/it/main.rs"

[lints]
workspace = true

[dependencies]
ssg-workspace-hack.workspace = true
rolldown.workspace = true
rolldown_common.workspace = true
rolldown_error.workspace = true
rolldown_plugin.workspace = true
rolldown_sourcemap.workspace = true
oxc.workspace = true
oxc_sourcemap.workspace = true
lightningcss.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread"] }
anyhow.workspace = true
base64.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
ssg-testkit.workspace = true
rayon.workspace = true
