package main

// Randomized differential cases (-mode fuzz). Inputs are generated by a
// portable splitmix64-driven generator that crates/libwebp-sys/tests/fuzz.rs
// re-implements bit for bit, so the fixture only stores the case parameters,
// an FNV-1a-64 hash of the generated pixel buffer (to validate the Rust
// generator) and the length + FNV-1a-64 hash of the gowebp output.

import (
	"bufio"
	"fmt"
	"image"
	"os"
	"path/filepath"

	"github.com/bep/gowebp/libwebp/webpoptions"
)

// rng is splitmix64.
type rng struct{ s uint64 }

func (r *rng) next() uint64 {
	r.s += 0x9E3779B97F4A7C15
	z := r.s
	z = (z ^ (z >> 30)) * 0xBF58476D1CE4E5B9
	z = (z ^ (z >> 27)) * 0x94D049BB133111EB
	return z ^ (z >> 31)
}

// intn returns a value in [0, n) (n > 0).
func (r *rng) intn(n int) int { return int(r.next() % uint64(n)) }

// rangeIn returns a value in [lo, hi].
func (r *rng) rangeIn(lo, hi int) int { return lo + r.intn(hi-lo+1) }

func fnv64(b []byte) uint64 {
	h := uint64(0xcbf29ce484222325)
	for _, c := range b {
		h ^= uint64(c)
		h *= 0x100000001b3
	}
	return h
}

// fuzzParams describes one generated case. Everything in it is derived from
// the case seed by genFuzzCase.
type fuzzParams struct {
	kind            string // nrgba | rgba | gray
	w, h, mx, my    int
	stride, tail    int
	pattern, alpha  int
	quality, preset int
	sharp           bool
}

// genFuzzCase derives the parameters and the pixel buffer (starting at the
// pixel at Rect.Min, like Go's Pix) for case seed.
func genFuzzCase(seed uint64) (fuzzParams, []byte) {
	r := &rng{s: seed}
	var p fuzzParams
	switch r.intn(10) {
	case 0, 1, 2, 3:
		p.kind = "nrgba"
	case 4, 5, 6:
		p.kind = "rgba"
	default:
		p.kind = "gray"
	}
	switch r.intn(20) {
	case 0, 1:
		// Thin shapes.
		if r.intn(2) == 0 {
			p.w, p.h = 1, r.rangeIn(1, 300)
		} else {
			p.w, p.h = r.rangeIn(1, 300), 1
		}
	case 2:
		p.w, p.h = r.rangeIn(131, 420), r.rangeIn(131, 320)
	case 3, 4, 5, 6, 7:
		p.w, p.h = r.rangeIn(41, 130), r.rangeIn(41, 130)
	default:
		p.w, p.h = r.rangeIn(1, 40), r.rangeIn(1, 40)
	}
	if r.intn(5) == 0 {
		p.mx, p.my = r.rangeIn(0, 5), r.rangeIn(0, 5)
	}
	bpp := 4
	if p.kind == "gray" {
		bpp = 1
	}
	maxX, maxY := p.mx+p.w, p.my+p.h
	switch r.intn(10) {
	case 0:
		// Stride for Dx only: gowebp reads Max.X per row, so with a non-zero
		// Min.X this is short (RGBA: "failed to encode"; Gray: overlapping rows).
		p.stride = p.w * bpp
	case 1, 2:
		p.stride = maxX*bpp + r.rangeIn(1, 17)
	default:
		p.stride = maxX * bpp
	}
	p.tail = 0
	if r.intn(4) == 0 {
		p.tail = r.rangeIn(1, 9)
	}
	p.pattern = r.intn(6)
	p.alpha = r.intn(7)

	switch q := r.intn(20); {
	case q < 9:
		p.quality = 75
	case q < 15:
		p.quality = r.rangeIn(1, 100)
	case q < 17:
		p.quality = 0
	case q < 18:
		p.quality = 100
	default:
		p.quality = []int{101, -1, 1000, 2}[r.intn(4)]
	}
	switch pr := r.intn(20); {
	case pr < 8:
		p.preset = 2
	case pr < 19:
		p.preset = r.rangeIn(0, 5)
	default:
		p.preset = []int{6, -1}[r.intn(2)]
	}
	p.sharp = r.intn(3) != 0

	// Buffer: enough for what gowebp reads (Max.Y-1)*stride + Max.X*bpp.
	need := (maxY-1)*p.stride + maxX*bpp
	buf := make([]byte, need+p.tail)
	// Pixels: x, y are relative to Pix[0] (row = i / stride).
	for i := range buf {
		buf[i] = byte(r.next())
	}
	if p.kind == "gray" {
		for i := range buf {
			y, x := i/p.stride, i%p.stride
			buf[i] = pixelChan(p.pattern, r, x, y, 0, p.w, p.h)
		}
		return p, buf
	}
	for i := 0; i+3 < len(buf); i += 4 {
		// Pixel coordinates when the stride is a multiple of 4.
		y, x := i/p.stride, (i%p.stride)/4
		c := [4]byte{
			pixelChan(p.pattern, r, x, y, 0, p.w, p.h),
			pixelChan(p.pattern, r, x, y, 1, p.w, p.h),
			pixelChan(p.pattern, r, x, y, 2, p.w, p.h),
			0,
		}
		c[3] = alphaChan(p.alpha, r, x, y, p.w, p.h)
		if p.kind == "rgba" && r.intn(4) != 0 {
			// Mostly valid premultiplied data (gowebp does not care).
			for k := 0; k < 3; k++ {
				c[k] = byte(uint32(c[k]) * uint32(c[3]) / 255)
			}
		}
		copy(buf[i:i+4], c[:])
	}
	return p, buf
}

// pixelChan returns a colour channel value (integer math only).
func pixelChan(pattern int, r *rng, x, y, ch, w, h int) byte {
	switch pattern {
	case 0: // noise
		return byte(r.next())
	case 1: // smooth gradient + small noise
		v := (x*255)/max(w, 1) + (y*97)/max(h, 1) + ch*40 + r.intn(9)
		return byte(v)
	case 2: // few-colour blocks (palette path in lossless)
		pal := [5][3]byte{{250, 20, 20}, {10, 40, 230}, {255, 255, 255}, {0, 0, 0}, {30, 200, 90}}
		return pal[((x/5)+(y/3)*3)%5][ch]
	case 3: // lines
		if (x+y*2)%7 == 0 || x%11 == 0 {
			return byte(40 * ch)
		}
		return byte(220 - 30*ch)
	case 4: // photo-like: separable smooth waves from a triangle function
		t := func(v int) int {
			v %= 128
			if v > 64 {
				v = 128 - v
			}
			return v
		}
		return byte(t(x*3+ch*17)*2 + t(y*5+ch*29) + r.intn(5))
	default: // flat with rare noise
		if r.intn(50) == 0 {
			return byte(r.next())
		}
		return byte(128 + ch*30)
	}
}

func alphaChan(mode int, r *rng, x, y, w, h int) byte {
	switch mode {
	case 0, 1: // opaque
		return 255
	case 2: // binary
		if (x/4+y/4)%3 == 0 {
			return 0
		}
		return 255
	case 3: // full random
		return byte(r.next())
	case 4: // mostly opaque
		if r.intn(30) == 0 {
			return byte(r.intn(255))
		}
		return 255
	case 5: // fully transparent
		return 0
	default: // gradient
		return byte((x*255)/max(w, 1) ^ (y * 3))
	}
}

func (p fuzzParams) image(buf []byte) image.Image {
	rect := image.Rect(p.mx, p.my, p.mx+p.w, p.my+p.h)
	switch p.kind {
	case "nrgba":
		return &image.NRGBA{Pix: buf, Stride: p.stride, Rect: rect}
	case "rgba":
		return &image.RGBA{Pix: buf, Stride: p.stride, Rect: rect}
	default:
		return &image.Gray{Pix: buf, Stride: p.stride, Rect: rect}
	}
}

// fuzzCases writes <out>/fuzz.tsv with n cases starting at seed.
func fuzzCases(out string, seed uint64, n int) {
	if err := os.MkdirAll(out, 0o755); err != nil {
		panic(err)
	}
	f, err := os.Create(filepath.Join(out, "fuzz.tsv"))
	if err != nil {
		panic(err)
	}
	w := bufio.NewWriter(f)
	_, _ = fmt.Fprintln(w, "#seed\tkind\tw\th\tmx\tmy\tstride\tquality\tpreset\tsharp\tin_len\tin_fnv\tout_len\tout_fnv\texpect")
	var ok, errs int
	for i := 0; i < n; i++ {
		s := seed + uint64(i)
		p, buf := genFuzzCase(s)
		o := webpoptions.EncodingOptions{Quality: p.quality, EncodingPreset: webpoptions.EncodingPreset(p.preset), UseSharpYuv: p.sharp}
		res, exp := encodeCase(p.image(buf), o)
		if exp == "ok" {
			ok++
		} else {
			errs++
		}
		sharp := 0
		if p.sharp {
			sharp = 1
		}
		_, _ = fmt.Fprintf(w, "%d\t%s\t%d\t%d\t%d\t%d\t%d\t%d\t%d\t%d\t%d\t%016x\t%d\t%016x\t%s\n",
			s, p.kind, p.w, p.h, p.mx, p.my, p.stride, p.quality, p.preset, sharp,
			len(buf), fnv64(buf), len(res), fnv64(res), exp)
	}
	fmt.Fprintf(os.Stderr, "fuzz: %d cases (%d ok, %d errors)\n", n, ok, errs)
	if err := w.Flush(); err != nil {
		panic(err)
	}
	if err := f.Close(); err != nil {
		panic(err)
	}
}
