// Command nfc generates the normalization data of crates/nh-hugofs/src/nfc.rs
// and its test fixture (Wave B task T05). Hugo NFC-normalizes file names on
// darwin with golang.org/x/text/unicode/norm (v0.26.0, Unicode 15.0.0):
// hugofs/fileinfo.go normalizeFilename and componentFs.applyMeta.
//
//	go run ./tools/go-oracle/nh-hugofs/nfc [-data crates/nh-hugofs/src/nfc15.txt] [-out crates/nh-hugofs/tests/fixtures/nfc]
//
// The data file lists, from the public norm API, every rune's canonical
// combining class (C lines), its full canonical decomposition (D lines;
// Hangul syllables are algorithmic and not listed) and the primary composites
// (P lines: first, second, composite; each pair is checked to compose to the
// composite with norm.NFC). The fixture holds norm.NFC.String results for
// every code point, the NFD form of every decomposable one, Hangul, Thai,
// file-name-like strings and seeded random mixes of starters and marks.
package main

import (
	"bufio"
	"flag"
	"fmt"
	"log"
	"math/rand"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode/utf8"

	"github.com/neohugo/neohugo/tools/go-oracle/nh-common/goval"
	"golang.org/x/text/unicode/norm"
)

func isHangulSyllable(r rune) bool { return r >= 0xAC00 && r <= 0xD7A3 }

func main() {
	data := flag.String("data", "crates/nh-hugofs/src/nfc15.txt", "data file")
	out := flag.String("out", "crates/nh-hugofs/tests/fixtures/nfc", "fixture directory")
	flag.Parse()

	var cccLines, decLines, pairLines []string
	var marks, decomposable []rune
	for r := rune(0); r <= utf8.MaxRune; r++ {
		if r >= 0xD800 && r <= 0xDFFF {
			continue
		}
		s := string(r)
		ccc := norm.NFD.PropertiesString(s).CCC()
		if ccc != 0 {
			cccLines = append(cccLines, fmt.Sprintf("C %X %d", r, ccc))
			marks = append(marks, r)
		}
		nfd := norm.NFD.String(s)
		if nfd == s || isHangulSyllable(r) {
			continue
		}
		decomposable = append(decomposable, r)
		var hs []string
		for _, x := range nfd {
			hs = append(hs, fmt.Sprintf("%X", x))
		}
		decLines = append(decLines, fmt.Sprintf("D %X %s", r, strings.Join(hs, " ")))
		if norm.NFC.String(s) != s {
			continue
		}
		d := []rune(nfd)
		last := d[len(d)-1]
		first := norm.NFC.String(string(d[:len(d)-1]))
		fr := []rune(first)
		if len(fr) != 1 || norm.NFC.String(first+string(last)) != s {
			log.Fatalf("U+%04X: no primary pair", r)
		}
		pairLines = append(pairLines, fmt.Sprintf("P %X %X %X", fr[0], last, r))
	}

	fd, err := os.Create(*data)
	if err != nil {
		log.Fatal(err)
	}
	w := bufio.NewWriter(fd)
	if _, err := fmt.Fprintf(w, "# x/text unicode/norm %s: generated by tools/go-oracle/nh-hugofs/nfc (do not edit)\n", norm.Version); err != nil {
		log.Fatal(err)
	}
	for _, ls := range [][]string{cccLines, decLines, pairLines} {
		for _, l := range ls {
			if _, err := fmt.Fprintln(w, l); err != nil {
				log.Fatal(err)
			}
		}
	}
	if err := w.Flush(); err != nil {
		log.Fatal(err)
	}
	if err := fd.Close(); err != nil {
		log.Fatal(err)
	}

	// Test strings.
	var inputs []string
	seen := map[string]bool{}
	add := func(s string) {
		if !seen[s] {
			seen[s] = true
			inputs = append(inputs, s)
		}
	}
	// Single code points: only those NFC changes are listed (the test checks
	// that every other code point is unchanged).
	for r := rune(0); r <= utf8.MaxRune; r++ {
		if r >= 0xD800 && r <= 0xDFFF {
			continue
		}
		if norm.NFC.String(string(r)) != string(r) {
			add(string(r))
		}
	}
	for _, r := range decomposable {
		add(norm.NFD.String(string(r)))
		add("a" + norm.NFD.String(string(r)) + "b")
	}
	for r := rune(0xAC00); r <= 0xD7A3; r += 7 {
		add(norm.NFD.String(string(r)))
	}
	for _, s := range []string{
		"café.md", "café.md", "Café́.md", "potato-chips/wise-chili-olé", "บทความ/ไทย.md",
		"เกม", "ก่ำ", "กํา", "ȩ́", "ȩ́", "각",
		"가", "가ᆧ", "각", "á́́", "̈́", "ཱི", "ཱྀ",
		"ÅÅÅ", "ẛ̣", "ﬁ", "क़", "क़", "אַ", "",
		strings.Repeat("́", 40), "a" + strings.Repeat("́", 29), "a" + strings.Repeat("́", 30),
		"a" + strings.Repeat("́", 31), "a" + strings.Repeat("́", 61) + "b",
		"e" + strings.Repeat("̧́", 20), strings.Repeat("ᅡ", 35), "ᄀ" + strings.Repeat("ᅡ", 3),
	} {
		add(s)
	}
	r := rand.New(rand.NewSource(15))
	starters := []rune{'a', 'e', 'o', 'u', 'A', 'E', 'O', 'U', 'n', 'c', 'y', 0x0391, 0x03b1, 0x0415, 0x0435, 0x05d0, 0x0627, 0x0915, 0x0e01, 0x1100, 0x1161, 0x11a8, 0xac00, 0x3042, 0x304b, '/', '.', '-', 0x0e40}
	sort.Slice(marks, func(i, j int) bool { return marks[i] < marks[j] })
	for range 20000 {
		var b strings.Builder
		n := 1 + r.Intn(8)
		for range n {
			switch r.Intn(4) {
			case 0, 1:
				b.WriteRune(starters[r.Intn(len(starters))])
			case 2:
				b.WriteRune(marks[r.Intn(len(marks))])
			default:
				b.WriteString(norm.NFD.String(string(decomposable[r.Intn(len(decomposable))])))
			}
		}
		add(b.String())
	}

	var cases []map[string]any
	for _, s := range inputs {
		nfc := norm.NFC.String(s)
		c := map[string]any{"in": goval.Str(s)}
		if nfc != s {
			c["out"] = goval.Str(nfc)
		}
		cases = append(cases, c)
	}
	if err := os.MkdirAll(*out, 0o755); err != nil {
		log.Fatal(err)
	}
	if err := goval.WriteCasesGz(filepath.Join(*out, "nfc.json.gz"), map[string]any{"version": norm.Version, "singleRunesListedOnlyIfChanged": true}, cases); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("nfc: %d C, %d D, %d P lines; %d cases\n", len(cccLines), len(decLines), len(pairLines), len(cases))
}
