// Command gentables generates crates/nh-markup/src/goldmark/autoid_accents.rs:
// the data the Rust port needs to reproduce text.RemoveAccents (x/text
// transform.Chain(norm.NFD, runes.Remove(runes.In(unicode.Mn)), norm.NFC),
// x/text v0.26.0 with Unicode 15.0.0 normalization tables and go1.27.1's
// unicode.Mn) as used by goldmark's `github-ascii` auto IDs.
//
//	go run ./tools/go-oracle/nh-markup/gentables [-out crates/nh-markup/src/goldmark/autoid_accents.rs] [-chroma crates/nh-markup/src/highlight/chromalexers_data.rs]
//
// sanitizeAnchorNameWithHook only looks at RemoveAccents' output through
// bytes.TrimSpace and then keeps single-byte runes, so per input rune r it is
// enough to know RemoveAccents(string(r)) up to this projection: every ASCII
// byte, and whether each non-ASCII rune is a space. The table lists every rune
// that is not in unicode.Mn (Mn runes are removed: the Rust port tests
// unicode.Mn itself) whose output differs from string(r) under the
// projection. The generator also checks the assumptions that make the
// per-rune model exact:
//
//   - every rune in unicode.Mn maps to "";
//   - NFC never composes an ASCII byte with a following non-Mn rune (the
//     output of "a"+string(r) keeps the leading "a" for every ASCII a);
//   - no output contains a space rune that the input rune did not have.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"log"
	"os"
	"sort"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/alecthomas/chroma/v2/lexers"
	"github.com/neohugo/neohugo/common/text"
	"golang.org/x/text/unicode/norm"
)

// project maps s to one token per rune: the ASCII byte itself, 0x80 for a
// non-ASCII space and 0x81 for any other rune.
func project(s []byte) []byte {
	var out []byte
	for len(s) > 0 {
		r, size := utf8.DecodeRune(s)
		switch {
		case size == 1 && r < utf8.RuneSelf:
			out = append(out, byte(r))
		case unicode.IsSpace(r):
			out = append(out, 0x80)
		default:
			out = append(out, 0x81)
		}
		s = s[size:]
	}
	return out
}

func main() {
	out := flag.String("out", "crates/nh-markup/src/goldmark/autoid_accents.rs", "output file")
	chromaOut := flag.String("chroma", "crates/nh-markup/src/highlight/chromalexers_data.rs", "chroma lexer data output file")
	flag.Parse()

	writeChroma(*chromaOut)

	type entry struct {
		r   rune
		out []byte
	}
	var entries []entry
	for r := rune(0); r <= unicode.MaxRune; r++ {
		if !utf8.ValidRune(r) {
			continue
		}
		s := []byte(string(r))
		o := text.RemoveAccents(append([]byte(nil), s...))
		if unicode.Is(unicode.Mn, r) {
			if len(o) != 0 {
				log.Fatalf("Mn rune %U maps to %q", r, o)
			}
			continue
		}
		if !bytes.Equal(project(o), project(s)) {
			entries = append(entries, entry{r, o})
		}
		// NFC must not merge an ASCII starter with this rune.
		for a := byte(0x20); a < 0x7f; a++ {
			in := append([]byte{a}, s...)
			oo := text.RemoveAccents(in)
			want := append([]byte{a}, text.RemoveAccents(append([]byte(nil), s...))...)
			if !bytes.Equal(project(oo), project(want)) {
				log.Fatalf("context dependent: %q%U -> %q", a, r, oo)
			}
		}
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, `//! Generated by tools/go-oracle/nh-markup/gentables (go1.27.1, x/text v0.26.0,
//! normalization tables Unicode %s). Do not edit.
//!
//! text.RemoveAccents(string(r)) for the runes r (not in unicode.Mn) whose result differs
//! from string(r) in its ASCII bytes or in the space-ness of its other runes.

/// (rune, RemoveAccents(string(rune))), sorted by rune.
pub(crate) static REMOVE_ACCENTS: &[(u32, &str)] = &[
`, norm.Version)
	for _, e := range entries {
		fmt.Fprintf(&b, "    (0x%04X, \"%s\"),\n", e.r, rustEscape(e.out))
	}
	b.WriteString("];\n")
	if err := os.WriteFile(*out, b.Bytes(), 0o644); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("%d entries\n", len(entries))
}

// rustEscape writes s as the body of a Rust string literal.
func rustEscape(s []byte) string {
	var b bytes.Buffer
	for _, r := range string(s) {
		switch {
		case r == '"' || r == '\\':
			b.WriteByte('\\')
			b.WriteRune(r)
		case r >= 0x20 && r < 0x7f:
			b.WriteRune(r)
		default:
			fmt.Fprintf(&b, "\\u{%x}", r)
		}
	}
	return b.String()
}

func writeChroma(out string) {
	names := map[string]bool{}
	globs := map[string]bool{}
	var globList []string
	for _, l := range lexers.GlobalLexerRegistry.Lexers {
		c := l.Config()
		names[c.Name] = true
		names[strings.ToLower(c.Name)] = true
		for _, a := range c.Aliases {
			names[a] = true
			names[strings.ToLower(a)] = true
		}
		for _, g := range append(append([]string(nil), c.Filenames...), c.AliasFilenames...) {
			if !globs[g] {
				globs[g] = true
				globList = append(globList, g)
			}
		}
	}
	var nameList []string
	for n := range names {
		nameList = append(nameList, n)
	}
	sort.Strings(nameList)
	sort.Strings(globList)

	var b bytes.Buffer
	b.WriteString("//! Generated by tools/go-oracle/nh-markup/gentables from chroma v2.19.0's global lexer\n")
	b.WriteString("//! registry. Do not edit.\n\n")
	b.WriteString("/// Lexer names and aliases (Go's byName and byAlias keys), sorted.\n")
	b.WriteString("pub(crate) static NAMES_AND_ALIASES: &[&str] = &[\n")
	for _, n := range nameList {
		fmt.Fprintf(&b, "    \"%s\",\n", rustEscape([]byte(n)))
	}
	b.WriteString("];\n\n")
	b.WriteString("/// File name globs (Filenames and AliasFilenames of every lexer), sorted.\n")
	b.WriteString("pub(crate) static FILENAME_GLOBS: &[&str] = &[\n")
	for _, g := range globList {
		fmt.Fprintf(&b, "    \"%s\",\n", rustEscape([]byte(g)))
	}
	b.WriteString("];\n")
	if err := os.WriteFile(out, b.Bytes(), 0o644); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("chroma: %d names, %d globs\n", len(nameList), len(globList))
}
