package main

import "strings"

// edgeCases are hand-written inputs aimed at goldmark quirks the Rust port
// must reproduce (child count bookkeeping, opened-block slice aliasing,
// reader caching, delimiter bottoms, entity/number handling, attributes...).
var edgeCases = []string{
	"",
	"\n",
	"a",
	"# Heading\n\nParagraph with *emphasis* and **strong** and `code`.\n",
	"Setext\n===\n\nSetext 2\n---\n",
	"- a\n- b\n\n- c\n",
	"- a\n  - b\n    - c\n",
	"1. a\n2. b\n\n10) c\n",
	"- foo\n---\n",
	"- foo\n  ---\n",
	"- foo\n  bar\n  ---\n",
	"- a\n\n  b\n- c\n",
	"-\n\n  foo\n",
	"-\n  foo\n-\n  ```\n  bar\n  ```\n-\n      baz\n",
	"> a\n> b\n---\n",
	"> a\nb\n===\n",
	"- a\nb\n===\n",
	"   > > 1. one\n>>\n>>     two\n",
	"[foo]: /url \"title\"\n\n[foo]\n",
	"[foo]:\n/url\n\"title\"\nok\n",
	"[foo]: /url 'title\n\nwith blank line'\n\n[foo]\n",
	"[a]: /x\n[b]: /y\n[c]\n",
	"[\nfoo\n]: /url\nbar\n",
	"*a [b* c](d)*\n",
	"[*a*](b)\n",
	"[*a](b)\n",
	"*[a*](b)\n",
	"**a [b** c](d)\n",
	"[a [b](c) d](e)\n",
	"![a [b](c) d](e)\n",
	"[a](<b)c>)\n",
	"[a](b\\)c)\n",
	"[link](/uri \"title\")\n[link](/uri 'title')\n[link](/uri (title))\n[link]()\n[link](<>)\n",
	"<a href=\"x\" title='y'\nclass=z>text</a>\n",
	"a <span\nclass=\"x\"\n>b</span>\n",
	"<!-- a\nb -->\n\nx <!-- c\n\nd -->\n",
	"<div>\n*a*\n\n*b*\n",
	"<pre>\n*a*\n</pre>\n*b*\n",
	"<script>\nx\n</script>\ny\n",
	"<?php\nx\n?>\n",
	"<!DOCTYPE html>\nx\n",
	"<![CDATA[\nx\n]]>\n",
	"<custom-tag>\n*a*\n\n*b*\n",
	"</custom-tag attr>\n",
	"para\n<custom>\n",
	"&copy; &nosuch; &#123; &#x1F600; &#0; &#X41; &#99999999; &AMP; &amp\n",
	"[a](&#065;) [b](&#x41;) [c](&copy;) [d](\\*)\n",
	"<http://a.b/c?d=e&f> <a@b.co> <mailto:x@y.z> <a b>\n",
	"`a` `` b ` c `` ` ` `\n``\nfoo\n``\n",
	"a  \nb\\\nc\n",
	"a\\\r\nb\r\nc  \r\nd\r\n",
	"\tfoo\tbaz\t\tbim\n",
	"  \tfoo\tbaz\t\tbim\n",
	"- foo\n\n\tbar\n",
	">\t\tfoo\n",
	"*\t*\t*\t\n",
	"```\na\n```",
	"```\na\n",
	"~~~ ruby startline=3 $%@#$\ndef foo(x)\n~~~~~~~\n",
	"``` aa ```\nfoo\n",
	"    code\n\n\n    more\n\n",
	"# Heading {#id .cls}\n## Other ## {.a .b}\n### ###\n#\n",
	"Setext {#sid}\n===\n",
	"# a \\{#x}\n",
	"# a {#x} b\n",
	"# Title\n# Title\n# Title-1\n",
	"# 日本語\n## ไทย\n### Ünïcödé\n",
	"***a***\n**a*\n*a**\n__a__b\n_a_b\na_b_\n",
	"*(*a*)*\n**(**a**)**\n",
	"foo*bar*baz\nfoo_bar_baz\n",
	"a\u00a0**b:**\u00a0c\n",
	"**รสชาติ** ไทย\n",
	"\x00 nul \xff invalid \xc3\n",
	"a\rb\rc\n",
	"[foo\n\n[bar]: /x\n",
	"[" + strings.Repeat("a", 1000) + "]\n\n[" + strings.Repeat("a", 1000) + "]: /x\n",
	"- [ ] task\n- [x] done\n",
	"| a | b |\n|---|---|\n| c | d |\n",
	"1. a\n\n   b\n\n2. c\n",
	"- a\n -  b\n  - c\n   - d\n    - e\n",
	"10. a\n11. b\n",
	"2. a\n\npara\n3. b\n",
	"* a\n+ b\n- c\n",
	"1. a\n1) b\n",
	"- \n  a\n",
	"-  \n\n  a\n",
	"> ```\n> a\n\nb\n",
	"> - a\n- b\n",
	"<div>\n\n# heading\n\n</div>\n",
	"    <div>\n",
	"foo\n    bar\n",
	"   foo\nbar\n",
	"![foo *bar*][]\n\n[foo *bar*]: train.jpg \"train & tracks\"\n",
	"![a](b \"c\")\n![a](javascript:x)\n[a](javascript:x)\n[a](data:image/png;base64,x)\n",
	"\\# not heading\n\\- not list\n\\[not link]\n",
	"a <?x?> b <!X y> c <![CDATA[z]]> d <!-->e<!---> f\n",
	"a <x\n\nb>\n",
	"a < b > c <1> <-> <a/b>\n",
	"***\n---\n___\n* * *\n",
	"a\n***\nb\n",
	"a\n- b\n",
	"a\n1. b\n",
	"a\n2. b\n",
	"- a\n- \n- c\n",
	"1.\n2.\n",
	"-\n",
	"[x]:\n",
	"[x]: <>\n[x]\n",
	"[x]: /u \"t\" extra\n[x]\n",
	"   [x]: /u\n[x]\n",
	"    [x]: /u\n[x]\n",
	"[a]\n[b]\n\n[a]: /1\n[B]: /2\n",
	"[ẞ]\n\n[SS]: /url\n",
	"[a]: /url\n\n[a][]\n[a] []\n[a][ ]\n",
	"*a `*` b*\n",
	"[a `]` b](c)\n",
	"<a href=\"`\">`\n",
	"``a`b``c`\n",
	"x ![y](z) *w ![v](u)*\n",
	"http://example.com www.example.com a@b.com\n",
	"- a\n\n\n- b\n",
	"- a\n  \n  b\n",
	"1. a\n\n       code\n",
	"-     code\n  para\n",
	" -    a\n",
	"*foo`*`\n",
	"**foo \"*bar*\" foo**\n",
	"*foo**bar**baz*\n",
	"foo***bar***baz\n",
	"a*\"foo\"*\n",
	"_foo_bar_baz_\n",
	"_(bar)_.\n",
	"__foo, __bar__, baz__\n",
	"foo-__(bar)__\n",
	"*a\n*b\n",
}

func init() {
	edgeCases = append(edgeCases,
		"{{name}}\n",
		"a {{b}} c\n{{d}}\n",
		"text\n{{x}}\nmore\n",
		"%% note\n%% - item\n%%\n%% > q\n",
		"%%a\nlazy\n",
		"~~del~~ ~single~ ~~~three~~~\n",
		"<b>raw</b> {{m}} <!-- c -->\n",
		"# heading {{x}}\n",
		"- {{x}}\n- b\n",
		"# heading {id=5}\n",
		"# heading {#x .y z=\"w\" n=1.5e3 b=true a=[1,2] o={p=q}}\n",
		"Setext {.cls}\n===\n",
		"%4x %zz %41 [a](%4x) <http://a.b/%4x>\n",
		"[a](&#0123;) [b](&#089;) [c](&#x110000;)\n",
	)
}
