package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/constant"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"unicode/utf8"

	"github.com/yuin/goldmark/util"
)

// goldmarkDir returns the module cache directory of github.com/yuin/goldmark
// at the version pinned by go.mod.
func goldmarkDir() string {
	dir := os.Getenv("GOLDMARK_DIR")
	if dir != "" {
		return dir
	}
	panic("GOLDMARK_DIR must point at $(go env GOMODCACHE)/github.com/yuin/goldmark@v1.7.12")
}

// genDecls parses a generated goldmark table file and returns its top-level
// constant/variable declarations by name.
func genDecls(path string) map[string]ast.Expr {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, path, nil, 0)
	if err != nil {
		panic(err)
	}
	ret := map[string]ast.Expr{}
	for _, d := range f.Decls {
		gd, ok := d.(*ast.GenDecl)
		if !ok {
			continue
		}
		for _, s := range gd.Specs {
			vs := s.(*ast.ValueSpec)
			for i, n := range vs.Names {
				ret[n.Name] = vs.Values[i]
			}
		}
	}
	return ret
}

func stringLit(e ast.Expr) string {
	bl := e.(*ast.BasicLit)
	v := constant.MakeFromLiteral(bl.Value, bl.Kind, 0)
	return constant.StringVal(v)
}

func intLit(e ast.Expr) int64 {
	bl := e.(*ast.BasicLit)
	v, err := strconv.ParseInt(bl.Value, 0, 64)
	if err != nil {
		panic(err)
	}
	return v
}

func intArray(e ast.Expr) []int64 {
	cl := e.(*ast.CompositeLit)
	ret := make([]int64, 0, len(cl.Elts))
	for _, el := range cl.Elts {
		ret = append(ret, intLit(el))
	}
	return ret
}

func rustBytes(b []byte) string {
	var buf bytes.Buffer
	buf.WriteString("b\"")
	for _, c := range b {
		if c >= 0x20 && c < 0x7f && c != '"' && c != '\\' {
			buf.WriteByte(c)
		} else {
			fmt.Fprintf(&buf, "\\x%02x", c)
		}
	}
	buf.WriteString("\"")
	return buf.String()
}

// genTables writes src/util/html5entities.rs and src/util/unicode_case_folding.rs
// from goldmark's generated Go tables, cross-checking every entry against the
// exported goldmark API.
func genTables(outDir string) {
	gm := goldmarkDir()

	// html5entities
	d := genDecls(filepath.Join(gm, "util", "html5entities.gen.go"))
	length := int(intLit(d["_html5entitiesLength"]))
	names := stringLit(d["_html5entitiesName"])
	nameIndex := stringLit(d["_html5entitiesNameIndex"])
	chars := intArray(d["_html5entitiesCharacters"])
	charIndex := stringLit(d["_html5entitiesCharactersIndex"])
	type ent struct {
		name  string
		chars []byte
	}
	var ents []ent
	cName, cChars := 0, 0
	for i := 0; i < length; i++ {
		tName := cName + int(nameIndex[i])
		tChars := cChars + int(charIndex[i])
		name := names[cName:tName]
		cs := make([]byte, 0, tChars-cChars)
		for _, c := range chars[cChars:tChars] {
			cs = append(cs, byte(c))
		}
		e, ok := util.LookUpHTML5EntityByName(name)
		if !ok || !bytes.Equal(e.Characters, cs) {
			panic("entity mismatch: " + name)
		}
		ents = append(ents, ent{name, cs})
		cName, cChars = tName, tChars
	}
	// Sorted by name (byte order) so Rust can binary-search. Go stores them
	// in a map; duplicates would be last-wins, check there are none.
	sort.SliceStable(ents, func(i, j int) bool { return ents[i].name < ents[j].name })
	for i := 1; i < len(ents); i++ {
		if ents[i].name == ents[i-1].name {
			panic("duplicate entity " + ents[i].name)
		}
	}
	var out bytes.Buffer
	out.WriteString("// Code generated by tools/go-oracle/goldmark gentables from\n")
	out.WriteString("// github.com/yuin/goldmark@v1.7.12/util/html5entities.gen.go. DO NOT EDIT.\n\n")
	fmt.Fprintf(&out, "/// Number of entities in goldmark's table.\npub const HTML5_ENTITIES_LENGTH: usize = %d;\n\n", length)
	out.WriteString("/// (name, characters), sorted by name.\n")
	out.WriteString("pub static HTML5_ENTITIES: &[(&str, &[u8])] = &[\n")
	for _, e := range ents {
		fmt.Fprintf(&out, "    (%q, %s),\n", e.name, rustBytes(e.chars))
	}
	out.WriteString("];\n")
	if err := os.WriteFile(filepath.Join(outDir, "html5entities_gen.rs"), out.Bytes(), 0o644); err != nil {
		panic(err)
	}

	// unicode case folding
	d = genDecls(filepath.Join(gm, "util", "unicode_case_folding.gen.go"))
	length = int(intLit(d["_unicodeCaseFoldingLength"]))
	from := intArray(d["_unicodeCaseFoldingFrom"])
	to := intArray(d["_unicodeCaseFoldingTo"])
	toIndex := stringLit(d["_unicodeCaseFoldingToIndex"])
	type fold struct {
		from rune
		to   []rune
	}
	var folds []fold
	cTo := 0
	for i := 0; i < length; i++ {
		tTo := cTo + int(toIndex[i])
		var rs []rune
		for _, r := range to[cTo:tTo] {
			rs = append(rs, rune(r))
		}
		f := fold{rune(from[i]), rs}
		// cross-check through the exported API
		var src [4]byte
		n := utf8.EncodeRune(src[:], f.from)
		got := util.DoFullUnicodeCaseFolding(append([]byte{}, src[:n]...))
		if f.from >= 0x41 && f.from <= 0x5a {
			// ASCII fast path in DoFullUnicodeCaseFolding
			if !bytes.Equal(got, []byte{byte(f.from + 32)}) {
				panic("ascii fold mismatch")
			}
		} else if f.from >= 0xb5 {
			if !bytes.Equal(got, []byte(string(rs))) {
				panic(fmt.Sprintf("fold mismatch %x", f.from))
			}
		}
		folds = append(folds, f)
		cTo = tTo
	}
	sort.SliceStable(folds, func(i, j int) bool { return folds[i].from < folds[j].from })
	for i := 1; i < len(folds); i++ {
		if folds[i].from == folds[i-1].from {
			panic("duplicate fold")
		}
	}
	out.Reset()
	out.WriteString("// Code generated by tools/go-oracle/goldmark gentables from\n")
	out.WriteString("// github.com/yuin/goldmark@v1.7.12/util/unicode_case_folding.gen.go. DO NOT EDIT.\n\n")
	fmt.Fprintf(&out, "/// Number of entries in goldmark's table.\npub const UNICODE_CASE_FOLDING_LENGTH: usize = %d;\n\n", length)
	out.WriteString("/// (from, to), sorted by from.\n")
	out.WriteString("pub static UNICODE_CASE_FOLDINGS: &[(i32, &[i32])] = &[\n")
	for _, f := range folds {
		out.WriteString(fmt.Sprintf("    (0x%x, &[", f.from))
		for i, r := range f.to {
			if i != 0 {
				out.WriteString(", ")
			}
			fmt.Fprintf(&out, "0x%x", r)
		}
		out.WriteString("]),\n")
	}
	out.WriteString("];\n")
	if err := os.WriteFile(filepath.Join(outDir, "unicode_case_folding_gen.rs"), out.Bytes(), 0o644); err != nil {
		panic(err)
	}
	fmt.Fprintf(os.Stderr, "wrote %d entities, %d folds\n", len(ents), len(folds))
}
