// Port of go1.27.1 src/internal/strconv/ftoa.go.
//
// Binary to decimal floating point conversion.
// Algorithm:
//   1) store mantissa in multiprecision decimal
//   2) shift decimal by exponent
//   3) read digits out & format

use super::atof::optimize;
use super::decimal::Decimal;
use super::deps::{f64_to_f32, float32bits, float64bits};
use super::itoa::{append_int, append_uint};
use super::uscale::{
    FloatParams, SHORT_F32, SHORT_F64, fixed_width_float, len64, log10_pow2, num_digits,
    set_digits, short_float,
};

pub(crate) const LOWERHEX: &[u8; 16] = b"0123456789abcdef";
pub(crate) const UPPERHEX: &[u8; 16] = b"0123456789ABCDEF";

pub(crate) const FLOAT32_MANT_BITS: i64 = 23;
pub(crate) const FLOAT32_EXP_BITS: i64 = 8;
pub(crate) const FLOAT32_BIAS: i64 = -127;
pub(crate) const FLOAT32_MIN_EXP: i64 = -189;

pub(crate) const FLOAT64_MANT_BITS: i64 = 52;
pub(crate) const FLOAT64_EXP_BITS: i64 = 11;
pub(crate) const FLOAT64_BIAS: i64 = -1023;
pub(crate) const FLOAT64_MIN_EXP: i64 = -1085;

// Go: internal/strconv/ftoa.go:FormatFloat
/// FormatFloat converts the floating-point number f to a string,
/// according to the format fmt and precision prec. It rounds the
/// result assuming that the original was obtained from a floating-point
/// value of bitSize bits (32 for float32, 64 for float64).
///
/// The format fmt is one of
///   - 'b' (-ddddp±ddd, a binary exponent),
///   - 'e' (-d.dddde±dd, a decimal exponent),
///   - 'E' (-d.ddddE±dd, a decimal exponent),
///   - 'f' (-ddd.dddd, no exponent),
///   - 'g' ('e' for large exponents, 'f' otherwise),
///   - 'G' ('E' for large exponents, 'f' otherwise),
///   - 'x' (-0xd.ddddp±ddd, a hexadecimal fraction and binary exponent), or
///   - 'X' (-0Xd.ddddP±ddd, a hexadecimal fraction and binary exponent).
///
/// The precision prec controls the number of digits (excluding the exponent)
/// printed by the 'e', 'E', 'f', 'g', 'G', 'x', and 'X' formats.
/// For 'e', 'E', 'f', 'x', and 'X', it is the number of digits after the decimal point.
/// For 'g' and 'G' it is the maximum number of significant digits (trailing
/// zeros are removed).
/// The special precision -1 uses the smallest number of digits
/// necessary such that ParseFloat will return f exactly.
///
/// Panics (like Go) if bitSize is not 32 or 64.
///
/// Deviation: for a finite value and a non-ASCII `fmt` byte (>= 0x80) Go
/// returns the invalid-UTF-8 string `"%" + fmt`, which a Rust `String`
/// cannot hold, so this panics instead; [`append_float`] returns Go's bytes.
pub fn format_float(f: f64, fmt: u8, prec: i64, bit_size: i64) -> String {
    let mut dst = Vec::with_capacity((prec.saturating_add(4)).clamp(24, 1 << 16) as usize);
    if bit_size == 32 {
        ftoa32(&mut dst, f64_to_f32(f), fmt, prec);
        return float_string(dst);
    }
    if bit_size == 64 {
        ftoa64(&mut dst, f, fmt, prec);
        return float_string(dst);
    }
    panic!("strconv: illegal FormatFloat bitSize");
}

/// Converts FormatFloat/FormatComplex output to a String. The output is
/// ASCII except for Go's `"%" + fmt` form with a non-ASCII fmt byte.
pub(crate) fn float_string(b: Vec<u8>) -> String {
    String::from_utf8(b).unwrap_or_else(|e| {
        panic!(
            "go_strconv: FormatFloat with non-ASCII fmt byte gives invalid UTF-8 {:?}; use append_float",
            e.as_bytes()
        )
    })
}

// Go: internal/strconv/ftoa.go:AppendFloat
/// AppendFloat appends the string form of the floating-point number f,
/// as generated by FormatFloat, to dst.
///
/// Panics (like Go) if bitSize is not 32 or 64.
pub fn append_float(dst: &mut Vec<u8>, f: f64, fmt: u8, prec: i64, bit_size: i64) {
    if bit_size == 32 {
        return ftoa32(dst, f64_to_f32(f), fmt, prec);
    }
    if bit_size == 64 {
        return ftoa64(dst, f, fmt, prec);
    }
    panic!("strconv: illegal AppendFloat bitSize");
}

/// The parameterized constants of Go's ftoa32/ftoa64 specializations.
struct FloatInfoF {
    exp_bits: i64,
    mant_bits: i64,
    bias: i64,
    short: FloatParams,
}

const F32: FloatInfoF = FloatInfoF {
    exp_bits: FLOAT32_EXP_BITS,
    mant_bits: FLOAT32_MANT_BITS,
    bias: FLOAT32_BIAS,
    short: SHORT_F32,
};

const F64: FloatInfoF = FloatInfoF {
    exp_bits: FLOAT64_EXP_BITS,
    mant_bits: FLOAT64_MANT_BITS,
    bias: FLOAT64_BIAS,
    short: SHORT_F64,
};

// Go: internal/strconv/ftoa.go:ftoa32
/// Appends the formatting of the float32 val.
pub fn ftoa32(dst: &mut Vec<u8>, val: f32, fmt: u8, prec: i64) {
    ftoa(dst, float32bits(val) as u64, &F32, fmt, prec)
}

// Go: internal/strconv/ftoa.go:ftoa64
/// Appends the formatting of the float64 val.
pub fn ftoa64(dst: &mut Vec<u8>, val: f64, fmt: u8, prec: i64) {
    ftoa(dst, float64bits(val), &F64, fmt, prec)
}

// Go: internal/strconv/ftoa.go:ftoa32 / ftoa64 (identical bodies; Go keeps two
// manual specializations of one generic function only because of a compiler
// issue, go.dev/issue/79547).
fn ftoa(dst: &mut Vec<u8>, b: u64, fi: &FloatInfoF, fmt: u8, prec: i64) {
    let mut prec = prec;
    let exp_bits = fi.exp_bits;
    let mant_bits = fi.mant_bits;
    let bias = fi.bias;

    let neg = b >> (exp_bits + mant_bits) != 0;
    let mut exp = (b >> mant_bits) as i64 & ((1 << exp_bits) - 1);
    let mut mant = b & ((1u64 << mant_bits) - 1);
    if exp == (1 << exp_bits) - 1 {
        if mant != 0 {
            dst.extend_from_slice(b"NaN");
            return;
        }
        if neg {
            dst.extend_from_slice(b"-Inf");
            return;
        }
        dst.extend_from_slice(b"+Inf");
        return;
    }
    if exp == 0 {
        exp += 1;
    } else {
        mant |= 1u64 << mant_bits;
    }
    exp += bias;

    // Pick off easy binary, hex formats.
    if fmt == b'b' {
        return fmt_b(dst, neg, mant, exp - mant_bits);
    }
    if fmt == b'x' || fmt == b'X' {
        return fmt_x(dst, prec, fmt, neg, mant, exp, mant_bits);
    }

    // Pick off zero.
    if mant == 0 {
        return fmt_efg(dst, neg, &[], 0, 0, prec, fmt, prec < 0);
    }

    // Negative precision means "only as much as needed to be exact."
    if prec < 0 {
        // Use fast unrounded scaling.
        let mut buf = [0u8; 32];
        let s = 64 - len64(mant);
        let m = mant << s;
        let e = exp - s;
        let (d, p) = short_float(fi.short, m, e - mant_bits);
        let (dp, nd) = set_digits(&mut buf[..], d, p, num_digits(d));
        // Precision for shortest representation mode.
        match fmt {
            b'e' | b'E' => prec = (nd - 1).max(0),
            b'f' => prec = (nd - dp).max(0),
            b'g' | b'G' => prec = nd,
            _ => {}
        }
        return fmt_efg(dst, neg, &buf[..], dp, nd, prec, fmt, true);
    }

    if optimize() {
        // Fixed number of digits.
        let mut digits = prec;
        match fmt {
            b'f' => {
                // %f precision specifies digits after the decimal point.
                // Estimate an upper bound on the total number of digits needed.
                // ftoaFixed will shorten as needed according to prec.
                if exp >= 0 {
                    digits = (1 + log10_pow2(1 + exp)).wrapping_add(prec);
                } else {
                    digits = 1i64.wrapping_add(prec).wrapping_sub(log10_pow2(-exp));
                }
            }
            b'e' | b'E' => digits = digits.wrapping_add(1),
            b'g' | b'G' => {
                if prec == 0 {
                    prec = 1;
                }
                digits = prec;
            }
            _ => {
                // Invalid mode.
                digits = 1;
            }
        }
        if digits <= 18 {
            // digits <= 0 happens for %f on very small numbers
            // and means that we're guaranteed to print all zeros.
            let mut buf = [0u8; 24];
            let mut dp = 0;
            let mut nd = 0;
            if digits > 0 {
                let s = 64 - len64(mant);
                let m = mant << s;
                let e = exp - s;
                let (d, p) = fixed_width_float(m, e - mant_bits, digits, prec, fmt);
                if d != 0 {
                    (dp, nd) = set_digits(&mut buf[..], d, p, num_digits(d));
                }
            }
            return fmt_efg(dst, neg, &buf[..], dp, nd, prec, fmt, false);
        }
    }

    // Slow bignum case. Only for non-shortest results.
    let mut d = Box::<Decimal>::default();
    d.assign(mant);
    d.shift(exp - mant_bits);
    match fmt {
        b'e' | b'E' => d.round(prec.wrapping_add(1)),
        b'f' => {
            let nd = d.dp.wrapping_add(prec);
            d.round(nd)
        }
        b'g' | b'G' => {
            if prec == 0 {
                prec = 1;
            }
            d.round(prec);
        }
        _ => {}
    }
    fmt_efg(dst, neg, &d.d[..], d.dp, d.nd, prec, fmt, false)
}

// Go: internal/strconv/ftoa.go:fmtEFG
#[allow(clippy::too_many_arguments)]
fn fmt_efg(
    dst: &mut Vec<u8>,
    neg: bool,
    s: &[u8],
    dp: i64,
    nd: i64,
    prec: i64,
    fmt: u8,
    shortest: bool,
) {
    let mut prec = prec;
    let mut fmt = fmt;
    if fmt == b'g' || fmt == b'G' {
        // trailing fractional zeros in 'e' form will be trimmed.
        let mut eprec = prec;
        if eprec > nd && nd >= dp {
            eprec = nd;
        }
        // %e is used if the exponent from the conversion
        // is less than -4 or greater than or equal to the precision.
        // if precision was the shortest possible, use precision 6 for this decision.
        if shortest {
            eprec = 6;
        }
        let exp = dp - 1;
        if exp < -4 || exp >= eprec {
            if prec > nd {
                prec = nd;
            }
            prec -= 1;
            fmt = fmt.wrapping_add(b'e').wrapping_sub(b'g');
        } else {
            if prec > dp {
                prec = nd;
            }
            prec = (prec - dp).max(0);
            fmt = b'f';
        }
    }

    match fmt {
        b'e' | b'E' => {
            // %e: -d.ddddde±dd
            // sign
            if neg {
                dst.push(b'-');
            }

            // first digit
            let mut ch = b'0';
            if nd != 0 {
                ch = s[0];
            }
            dst.push(ch);

            // .moredigits
            if prec > 0 {
                dst.push(b'.');
                let mut i: i64 = 1;
                let m = nd.min(prec + 1);
                if i < m {
                    dst.extend_from_slice(&s[i as usize..m as usize]);
                    i = m;
                }
                for _ in 0..(prec + 1 - i) {
                    dst.push(b'0');
                }
            }

            // e±
            dst.push(fmt);
            let mut exp = dp - 1;
            if nd == 0 {
                // special case: 0 has exponent 0
                exp = 0;
            }
            if exp < 0 {
                ch = b'-';
                exp = -exp;
            } else {
                ch = b'+';
            }
            dst.push(ch);

            // dd or ddd
            if exp < 10 {
                dst.push(b'0');
                dst.push(exp as u8 + b'0');
            } else if exp < 100 {
                dst.push((exp / 10) as u8 + b'0');
                dst.push((exp % 10) as u8 + b'0');
            } else {
                dst.push((exp / 100) as u8 + b'0');
                dst.push(((exp / 10) as u8 % 10) + b'0');
                dst.push((exp % 10) as u8 + b'0');
            }
        }

        b'f' => {
            // %f: -ddddddd.ddddd
            // sign
            if neg {
                dst.push(b'-');
            }

            // integer, padded with zeros as needed.
            if dp > 0 {
                let m = nd.min(dp);
                dst.extend_from_slice(&s[..m as usize]);
                for _ in 0..(dp - m) {
                    dst.push(b'0');
                }
            } else {
                dst.push(b'0');
            }

            // fraction
            if prec > 0 {
                dst.push(b'.');
                let lz = prec.min(0i64.max(-dp)); // leading zeros
                let off = dp + lz;
                let m = (prec - lz).min(0i64.max(nd - off)); // middle digits
                let tz = 0i64.max(prec - lz - m); // trailing zeros
                for _ in 0..lz {
                    dst.push(b'0');
                }
                for i in 0..m {
                    dst.push(s[(off + i) as usize]);
                }
                for _ in 0..tz {
                    dst.push(b'0');
                }
            }
        }

        _ => {
            // unknown format
            dst.push(b'%');
            dst.push(fmt);
        }
    }
}

// Go: internal/strconv/ftoa.go:fmtB
/// %b: -ddddddddp±ddd
fn fmt_b(dst: &mut Vec<u8>, neg: bool, mant: u64, exp: i64) {
    if neg {
        dst.push(b'-');
    }
    append_uint(dst, mant, 10);
    dst.push(b'p');
    if exp >= 0 {
        dst.push(b'+');
    }
    append_int(dst, exp, 10);
}

// Go: internal/strconv/ftoa.go:fmtX
/// %x: -0x1.yyyyyyyyp±ddd or -0x0p+0. (y is hex digit, d is decimal digit)
fn fmt_x(dst: &mut Vec<u8>, prec: i64, fmt: u8, neg: bool, mant: u64, exp: i64, mant_bits: i64) {
    let mut mant = mant;
    let mut exp = exp;
    if mant == 0 {
        exp = 0;
    }

    // Shift digits so leading 1 (if any) is at bit 1<<60.
    mant <<= 60 - mant_bits;
    while mant != 0 && mant & (1 << 60) == 0 {
        mant <<= 1;
        exp -= 1;
    }

    // Round if requested.
    if (0..15).contains(&prec) {
        let shift = (prec * 4) as u32;
        let extra = (mant << shift) & ((1 << 60) - 1);
        mant >>= 60 - shift;
        if (extra | (mant & 1)) > (1 << 59) {
            mant += 1;
        }
        mant <<= 60 - shift;
        if mant & (1 << 61) != 0 {
            // Wrapped around.
            mant >>= 1;
            exp += 1;
        }
    }

    let hex = if fmt == b'X' { UPPERHEX } else { LOWERHEX };

    // sign, 0x, leading digit
    if neg {
        dst.push(b'-');
    }
    dst.push(b'0');
    dst.push(fmt);
    dst.push(b'0' + ((mant >> 60) & 1) as u8);

    // .fraction
    mant <<= 4; // remove leading 0 or 1
    if prec < 0 && mant != 0 {
        dst.push(b'.');
        while mant != 0 {
            dst.push(hex[((mant >> 60) & 15) as usize]);
            mant <<= 4;
        }
    } else if prec > 0 {
        dst.push(b'.');
        let mut i = 0;
        while i < prec {
            dst.push(hex[((mant >> 60) & 15) as usize]);
            mant <<= 4;
            i += 1;
        }
    }

    // p±
    let mut ch = b'P';
    if fmt == lower(fmt) {
        ch = b'p';
    }
    dst.push(ch);
    if exp < 0 {
        ch = b'-';
        exp = -exp;
    } else {
        ch = b'+';
    }
    dst.push(ch);

    // dd or ddd or dddd
    if exp < 100 {
        dst.push((exp / 10) as u8 + b'0');
        dst.push((exp % 10) as u8 + b'0');
    } else if exp < 1000 {
        dst.push((exp / 100) as u8 + b'0');
        dst.push(((exp / 10) % 10) as u8 + b'0');
        dst.push((exp % 10) as u8 + b'0');
    } else {
        dst.push((exp / 1000) as u8 + b'0');
        dst.push(((exp / 100) as u8 % 10) + b'0');
        dst.push(((exp / 10) % 10) as u8 + b'0');
        dst.push((exp % 10) as u8 + b'0');
    }
}

/// lower(c) is a lower-case letter if and only if
/// c is either that lower-case letter or the equivalent upper-case letter.
#[inline]
pub(crate) fn lower(c: u8) -> u8 {
    c | (b'x' - b'X')
}
