// Port of go1.27.1 src/internal/strconv/itoa.go.

use super::uscale::num_digits;

// Go: internal/strconv/itoa.go:FormatUint
/// FormatUint returns the string representation of i in the given base,
/// for 2 <= base <= 36. The result uses the lower-case letters 'a' to 'z'
/// for digit values >= 10.
///
/// Panics (like Go) if base is illegal.
pub fn format_uint(i: u64, base: i64) -> String {
    if base == 10 {
        if i < N_SMALLS {
            return small(i as usize).to_string();
        }
        let mut a = [0u8; 24];
        let nd = num_digits(i) as usize;
        format_base10(&mut a[..nd], i);
        return ascii_string(&a[..nd]);
    }
    let mut v = Vec::new();
    format_bits(&mut v, i, base, false);
    ascii_string(&v)
}

// Go: internal/strconv/itoa.go:FormatInt
/// FormatInt returns the string representation of i in the given base,
/// for 2 <= base <= 36. The result uses the lower-case letters 'a' to 'z'
/// for digit values >= 10.
///
/// Panics (like Go) if base is illegal.
pub fn format_int(i: i64, base: i64) -> String {
    if base == 10 {
        if 0 <= i && i < N_SMALLS as i64 {
            return small(i as usize).to_string();
        }
        let mut a = [0u8; 24];
        let mut u = i as u64;
        if i < 0 {
            u = u.wrapping_neg();
        }
        let nd = num_digits(u) as usize;
        format_base10(&mut a[1..1 + nd], u);
        if i < 0 {
            a[0] = b'-';
            return ascii_string(&a[..1 + nd]);
        }
        return ascii_string(&a[1..1 + nd]);
    }
    let mut v = Vec::new();
    format_bits(&mut v, i as u64, base, i < 0);
    ascii_string(&v)
}

// Go: internal/strconv/itoa.go:Itoa
/// Itoa is equivalent to FormatInt(int64(i), 10).
pub fn itoa(i: i64) -> String {
    format_int(i, 10)
}

// Go: internal/strconv/itoa.go:AppendInt
/// AppendInt appends the string form of the integer i,
/// as generated by FormatInt, to dst.
pub fn append_int(dst: &mut Vec<u8>, i: i64, base: i64) {
    let mut u = i as u64;
    if i < 0 {
        dst.push(b'-');
        u = u.wrapping_neg();
    }
    append_uint(dst, u, base)
}

// Go: internal/strconv/itoa.go:AppendUint
/// AppendUint appends the string form of the unsigned integer i,
/// as generated by FormatUint, to dst.
pub fn append_uint(dst: &mut Vec<u8>, i: u64, base: i64) {
    if base == 10 {
        if i < N_SMALLS {
            dst.extend_from_slice(small(i as usize).as_bytes());
            return;
        }
        let mut a = [0u8; 24];
        let nd = num_digits(i) as usize;
        format_base10(&mut a[..nd], i);
        dst.extend_from_slice(&a[..nd]);
        return;
    }
    format_bits(dst, i, base, false);
}

const DIGITS: &[u8; 36] = b"0123456789abcdefghijklmnopqrstuvwxyz";

// Go: internal/strconv/itoa.go:formatBits
/// formatBits computes the string representation of u in the given base.
/// If neg is set, u is treated as negative int64 value.
/// The result is appended to dst (Go's append_ mode; the string mode is the
/// same bytes).
/// The caller is expected to have handled base 10 separately for speed.
fn format_bits(dst: &mut Vec<u8>, u: u64, base: i64, neg: bool) {
    if base < 2 || base == 10 || base > DIGITS.len() as i64 {
        panic!("strconv: illegal AppendInt/FormatInt base");
    }
    // 2 <= base && base <= len(digits)

    let mut a = [0u8; 64 + 1]; // +1 for sign of 64bit value in base 2
    let mut i = a.len();
    let mut u = u;
    if neg {
        u = u.wrapping_neg();
    }

    // convert bits
    if is_power_of_two(base) {
        // Use shifts and masks instead of / and %.
        let shift = (base as u64).trailing_zeros();
        let b = base as u64;
        let m = base as u64 - 1; // == 1<<shift - 1
        while u >= b {
            i -= 1;
            a[i] = DIGITS[(u & m) as usize];
            u >>= shift;
        }
        // u < base
        i -= 1;
        a[i] = DIGITS[u as usize];
    } else {
        // general case
        let b = base as u64;
        while u >= b {
            i -= 1;
            let q = u / b;
            a[i] = DIGITS[(u - q * b) as usize];
            u = q;
        }
        // u < base
        i -= 1;
        a[i] = DIGITS[u as usize];
    }

    // add sign, if any
    if neg {
        i -= 1;
        a[i] = b'-';
    }

    dst.extend_from_slice(&a[i..]);
}

fn is_power_of_two(x: i64) -> bool {
    x & (x - 1) == 0
}

const N_SMALLS: u64 = 100;

/// smalls is the formatting of 00..99 concatenated.
const SMALLS: &[u8; 200] = b"00010203040506070809\
10111213141516171819\
20212223242526272829\
30313233343536373839\
40414243444546474849\
50515253545556575859\
60616263646566676869\
70717273747576777879\
80818283848586878889\
90919293949596979899";

// Go: internal/strconv/itoa.go:small
/// small returns the string for an i with 0 <= i < nSmalls.
fn small(i: usize) -> &'static str {
    let b: &'static [u8] = if i < 10 {
        &DIGITS[i..i + 1]
    } else {
        &SMALLS[i * 2..i * 2 + 2]
    };
    // ASCII digits only.
    std::str::from_utf8(b).unwrap()
}

// Go: internal/strconv/itoa.go:RuntimeFormatBase10
/// RuntimeFormatBase10 formats u into the tail of a
/// and returns the offset to the first byte written to a.
pub fn runtime_format_base10(a: &mut [u8], u: u64) -> usize {
    // Note: numDigits requires an argument >= 1.
    // The |1 changes 0 to 1 without adding an extra digit
    // to any other value.
    let i = a.len() - num_digits(u | 1) as usize;
    format_base10(&mut a[i..], u);
    i
}

// Go: internal/strconv/itoa.go:formatBase10
/// formatBase10 formats the decimal representation of u into a.
/// The caller is responsible for ensuring that a is big enough to hold u.
/// If a is too big, leading zeros will be filled in as needed.
pub(crate) fn format_base10(a: &mut [u8], u: u64) {
    let mut u = u;
    let mut nd = a.len();
    while nd >= 8 {
        // Format last 8 digits (4 pairs).
        let x3210 = (u % 100000000) as u32;
        u /= 100000000;
        let (x32, x10) = (x3210 / 10000, x3210 % 10000);
        let (x1, x0) = ((x10 / 100) * 2, (x10 % 100) * 2);
        let (x3, x2) = ((x32 / 100) * 2, (x32 % 100) * 2);
        a[nd - 1] = SMALLS[x0 as usize + 1];
        a[nd - 2] = SMALLS[x0 as usize];
        a[nd - 3] = SMALLS[x1 as usize + 1];
        a[nd - 4] = SMALLS[x1 as usize];
        a[nd - 5] = SMALLS[x2 as usize + 1];
        a[nd - 6] = SMALLS[x2 as usize];
        a[nd - 7] = SMALLS[x3 as usize + 1];
        a[nd - 8] = SMALLS[x3 as usize];
        nd -= 8;
    }

    let mut x = u as u32;
    if nd >= 4 {
        // Format last 4 digits (2 pairs).
        let x10 = x % 10000;
        x /= 10000;
        let (x1, x0) = ((x10 / 100) * 2, (x10 % 100) * 2);
        a[nd - 1] = SMALLS[x0 as usize + 1];
        a[nd - 2] = SMALLS[x0 as usize];
        a[nd - 3] = SMALLS[x1 as usize + 1];
        a[nd - 4] = SMALLS[x1 as usize];
        nd -= 4;
    }
    if nd >= 2 {
        // Format last 2 digits.
        let x0 = (x % 100) * 2;
        x /= 100;
        a[nd - 1] = SMALLS[x0 as usize + 1];
        a[nd - 2] = SMALLS[x0 as usize];
        nd -= 2;
    }
    if nd > 0 {
        // Format final digit.
        a[0] = b'0'.wrapping_add(x as u8);
    }
}

/// Converts formatter output (always ASCII) to a String.
#[inline]
pub(crate) fn ascii_string(b: &[u8]) -> String {
    debug_assert!(b.is_ascii());
    // All formatter outputs are ASCII.
    String::from_utf8(b.to_vec()).unwrap()
}
