// Builds the vendored LibSass 3.6.6 exactly like cgo builds
// github.com/bep/golibsass@v1.2.0/internal/libsass (`go build -n`, go1.27.1
// darwin/arm64, CGO_CFLAGS/CGO_CXXFLAGS unset => cgo default "-O2 -g"):
//
//   c++ -I . -fPIC -arch arm64 -pthread -fmessage-length=0 -fno-common \
//       -I<golibsass>/libsass_src/include -I $WORK/b002/ \
//       -O2 -g -g -std=c++0x -O2 -fPIC -c <unit>.cpp
//   cc  -I . -fPIC -arch arm64 -pthread -fmessage-length=0 -fno-common \
//       -I<golibsass>/libsass_src/include -I $WORK/b002/ \
//       -O2 -g -O2 -fPIC -c <unit>.c
//
// (a__cgo.go: CFLAGS -O2 -fPIC; CPPFLAGS -I../../libsass_src/include;
// CXXFLAGS -g -std=c++0x -O2 -fPIC; LDFLAGS -lstdc++ -lm -ldl.) No -D
// defines.
//
// cgo compiles one stub per unit (`#include "../../libsass_src/src/<X>"`),
// generated by golibsass gen/main.go from the *top level* of
// libsass_src/src only: src/memory/{allocator,shared_ptr}.cpp are NOT
// compiled. libsass_units.txt is that exact list (62 .cpp + 2 .c).
use std::env;
use std::fs;
use std::path::PathBuf;
use std::process::Command;

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let src_root = manifest.join("libsass_src");
    let include = src_root.join("include");
    let units =
        fs::read_to_string(manifest.join("libsass_units.txt")).expect("read libsass_units.txt");

    let mut cxx = cc::Build::new();
    cxx.cpp(true)
        .no_default_flags(true)
        .warnings(false)
        .extra_warnings(false);
    for f in cgo_default_flags() {
        cxx.flag(f);
    }
    cxx.include(&include);
    for f in ["-O2", "-g", "-g", "-std=c++0x", "-O2", "-fPIC"] {
        cxx.flag(f);
    }
    arm64_parity(&mut cxx, true);

    let mut c = cc::Build::new();
    c.no_default_flags(true)
        .warnings(false)
        .extra_warnings(false);
    for f in cgo_default_flags() {
        c.flag(f);
    }
    c.include(&include);
    for f in ["-O2", "-g", "-O2", "-fPIC"] {
        c.flag(f);
    }
    arm64_parity(&mut c, false);

    for line in units.lines() {
        let unit = line.trim();
        if unit.is_empty() || unit.starts_with('#') {
            continue;
        }
        let path = src_root.join(unit);
        assert!(path.exists(), "missing libsass unit {}", path.display());
        if unit.ends_with(".c") {
            c.file(path);
        } else {
            cxx.file(path);
        }
    }
    c.compile("golibsass_c");
    cxx.compile("golibsass_cxx");

    // a__cgo.go: `#cgo LDFLAGS: -lstdc++ -lm` (+ `-ldl` on darwin/linux). The
    // C++ runtime itself is linked by cc (`cpp(true)`: libc++ on Apple,
    // libstdc++ elsewhere).
    println!("cargo:rustc-link-lib=m");
    let os = env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
    if os == "macos" || os == "linux" {
        println!("cargo:rustc-link-lib=dl");
    }
    println!("cargo:rerun-if-changed=libsass_units.txt");
    println!("cargo:rerun-if-changed=libsass_src");
    println!("cargo:rerun-if-changed=build.rs");
}

/// The flags cgo puts in front of every C/C++ compile (go1.27.1
/// `cmd/go/internal/work` gccCmd/gxxCmd): `-fPIC`, the arch flag, `-pthread`,
/// `-fmessage-length=0`, `-fno-common` (darwin).
fn cgo_default_flags() -> Vec<&'static str> {
    let os = env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
    let arch = env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_default();
    let mut v = vec!["-fPIC"];
    match (os.as_str(), arch.as_str()) {
        ("macos", "aarch64") => v.extend(["-arch", "arm64"]),
        ("macos", "x86_64") => v.extend(["-arch", "x86_64"]),
        (_, "x86_64") => v.push("-m64"),
        _ => {}
    }
    v.extend(["-pthread", "-fmessage-length=0"]);
    if os == "macos" {
        v.push("-fno-common");
    }
    v
}

/// darwin/arm64 parity on other hosts. The golden was built by Apple clang on
/// arm64, where clang's default `-ffp-contract=on` fuses `a*b+c` within one
/// expression into an FMA instruction, and C++ call arguments are evaluated
/// left to right. Elsewhere:
///
/// * gcc evaluates arguments right to left (LibSass error columns change)
///   and contracts across statements (`-ffp-contract=fast`, and `on` means
///   `off` before gcc 14), so off Apple we compile with clang unless the
///   user set CC/CXX;
/// * x86_64 has no FMA in the baseline ISA, so clang lowers the fused
///   operations to a multiply and an add, and the float results (libwebp's
///   encoder decisions) differ; `-mfma` restores them.
///
/// Verified on linux/x86_64 (clang 18): every checked-in darwin/arm64 fixture
/// matches; with gcc 13, or with clang without `-mfma`, some do not.
/// `NEOHUGO_NO_FMA=1` drops `-mfma` for CPUs without FMA3, at the cost of
/// rare output differences.
fn arm64_parity(b: &mut cc::Build, cpp: bool) {
    let os = env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
    let arch = env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_default();
    let target = env::var("TARGET").unwrap_or_default();
    let var = if cpp { "CXX" } else { "CC" };
    let vars = [
        var.to_string(),
        format!("{var}_{target}"),
        format!("{var}_{}", target.replace('-', "_")),
    ];
    for v in &vars {
        println!("cargo:rerun-if-env-changed={v}");
    }
    println!("cargo:rerun-if-env-changed=NEOHUGO_NO_FMA");
    if os != "macos" && vars.iter().all(|v| env::var_os(v).is_none()) {
        let clang = if cpp { "clang++" } else { "clang" };
        if Command::new(clang)
            .arg("--version")
            .output()
            .is_ok_and(|o| o.status.success())
        {
            b.compiler(clang);
        }
    }
    if b.get_compiler().is_like_clang() {
        b.flag("-ffp-contract=on");
    } else {
        println!(
            "cargo:warning={var} is not clang: output may differ from the darwin/arm64 golden (see PORTING.md)"
        );
    }
    if arch == "x86_64" && env::var_os("NEOHUGO_NO_FMA").is_none() {
        b.flag("-mfma");
    }
}
