//! Port of `golang.org/x/text/unicode/norm` (x/text v0.26.0, Unicode 15.0.0): the NFC and NFD
//! forms (`Form.String`, `Form.Bytes`, `Form.QuickSpan`, `Form.Properties` and
//! `Form.Transform`, the `transform.Transformer` used by `text.RemoveAccents`).
//!
//! Moved here from nh-hugofs (`nfc.rs`) and rewritten as a function-by-function port of
//! `normalize.go`, `composition.go`, `forminfo.go`, `input.go`, `transform.go` and `trie.go`,
//! over x/text's own trie (`tables15.rs`, generated by `tools/go-oracle/nh-common/norm` from
//! `tables15.0.0.go`). Not ported (no caller): the compatibility forms (NFKC, NFKD), the
//! iterator, the reader/writer, `Append`, `IsNormal`, `Span` and the boundary functions.
//! x/text's `input` distinguishes `string` and `[]byte` sources only for speed; both are `&[u8]`
//! here.
//!
//! `unicode-normalization` is not used: it carries a newer Unicode version than x/text's tables
//! and does not reproduce x/text's stream-safe segmentation (a CGJ after 30 non-starters, reset
//! at every `Transform` call).

#[rustfmt::skip]
mod tables15;

use go_unicode::utf8;

use super::xtransform::{TransformError, Transformer};
use tables15::*;

/// Go: `norm.Version` — the Unicode edition of the tables.
pub const VERSION: &str = tables15::VERSION;

/// Go: `norm.MaxTransformChunkSize`.
pub const MAX_TRANSFORM_CHUNK_SIZE: usize = 35 + MAX_NON_STARTERS * 4;

/// Go: `norm.GraphemeJoiner` (U+034F COMBINING GRAPHEME JOINER).
pub const GRAPHEME_JOINER: &str = "\u{034F}";

// Go: composition.go constants.
const MAX_NON_STARTERS: usize = 30;
const MAX_BUFFER_SIZE: usize = MAX_NON_STARTERS + 2;
const MAX_BYTE_BUFFER_SIZE: usize = utf8::UTF_MAX * MAX_BUFFER_SIZE; // 128

// Go: forminfo.go constants.
const QC_INFO_MASK: u8 = 0x3F;
const HEADER_LEN_MASK: u8 = 0x3F;
const HEADER_FLAGS_MASK: u8 = 0xC0;

/// Go: `norm.Form` (NFC and NFD only).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Form {
    /// Go: `norm.NFC` — canonical decomposition followed by canonical composition.
    Nfc,
    /// Go: `norm.NFD` — canonical decomposition.
    Nfd,
}

/// Go: `norm.NFC`.
pub const NFC: Form = Form::Nfc;
/// Go: `norm.NFD`.
pub const NFD: Form = Form::Nfd;

/// Go: `formInfo` (both ported forms use `lookupInfoNFC`).
#[derive(Clone, Copy, Debug)]
struct FormInfo {
    composing: bool,
}

// Go: forminfo.go:formTable
fn form_table(f: Form) -> FormInfo {
    match f {
        Form::Nfc => FormInfo { composing: true },
        Form::Nfd => FormInfo { composing: false },
    }
}

impl FormInfo {
    // Go: forminfo.go:lookupInfoNFC (formInfo.info)
    fn info(&self, src: &[u8], i: usize) -> Properties {
        let (v, sz) = nfc_lookup(&src[i..]);
        comp_info(v, sz)
    }
}

// ---------------------------------------------------------------------------
// trie.go + the nfcTrie of tables15.0.0.go

// Go: tables15.0.0.go:nfcTrie.lookup (lookupString is identical over string bytes)
fn nfc_lookup(s: &[u8]) -> (u16, usize) {
    let c0 = s[0];
    match c0 {
        0..0x80 => (NFC_VALUES[c0 as usize], 1),
        0x80..0xC2 => (0, 1), // Illegal UTF-8: not a starter, not ASCII.
        0xC2..0xE0 => {
            if s.len() < 2 {
                return (0, 0);
            }
            let i = NFC_INDEX[c0 as usize];
            let c1 = s[1];
            if !(0x80..0xC0).contains(&c1) {
                return (0, 1); // Illegal UTF-8: not a continuation byte.
            }
            (nfc_lookup_value(i as u32, c1), 2)
        }
        0xE0..0xF0 => {
            if s.len() < 3 {
                return (0, 0);
            }
            let mut i = NFC_INDEX[c0 as usize];
            let c1 = s[1];
            if !(0x80..0xC0).contains(&c1) {
                return (0, 1);
            }
            let o = ((i as u32) << 6) + c1 as u32;
            i = NFC_INDEX[o as usize];
            let c2 = s[2];
            if !(0x80..0xC0).contains(&c2) {
                return (0, 2);
            }
            (nfc_lookup_value(i as u32, c2), 3)
        }
        0xF0..0xF8 => {
            if s.len() < 4 {
                return (0, 0);
            }
            let mut i = NFC_INDEX[c0 as usize];
            let c1 = s[1];
            if !(0x80..0xC0).contains(&c1) {
                return (0, 1);
            }
            let mut o = ((i as u32) << 6) + c1 as u32;
            i = NFC_INDEX[o as usize];
            let c2 = s[2];
            if !(0x80..0xC0).contains(&c2) {
                return (0, 2);
            }
            o = ((i as u32) << 6) + c2 as u32;
            i = NFC_INDEX[o as usize];
            let c3 = s[3];
            if !(0x80..0xC0).contains(&c3) {
                return (0, 3);
            }
            (nfc_lookup_value(i as u32, c3), 4)
        }
        // Illegal rune
        _ => (0, 1),
    }
}

// Go: tables15.0.0.go:nfcTrie.lookupValue
fn nfc_lookup_value(n: u32, b: u8) -> u16 {
    if n < NFC_DENSE_BLOCKS {
        NFC_VALUES[((n << 6) + b as u32) as usize]
    } else {
        sparse_lookup(n - NFC_DENSE_BLOCKS, b)
    }
}

// Go: trie.go:sparseBlocks.lookup (nfcSparse)
fn sparse_lookup(n: u32, b: u8) -> u16 {
    let offset = NFC_SPARSE_OFFSET[n as usize];
    let header = NFC_SPARSE_VALUES[offset as usize];
    let mut lo = offset + 1;
    let mut hi = lo + header.1 as u16;
    while lo < hi {
        let m = lo + (hi - lo) / 2;
        let r = NFC_SPARSE_VALUES[m as usize];
        if r.1 <= b && b <= r.2 {
            return r.0.wrapping_add(((b - r.1) as u16).wrapping_mul(header.0));
        }
        if b < r.1 {
            hi = m;
        } else {
            lo = m + 1;
        }
    }
    0
}

// ---------------------------------------------------------------------------
// forminfo.go

/// Go: `norm.Properties` — the normalization properties of a rune.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Properties {
    /// start position in reorderBuffer; used in composition.go
    pos: u8,
    /// length of UTF-8 encoding of this rune
    size: u8,
    /// leading canonical combining class (ccc if not decomposition)
    ccc: u8,
    /// trailing canonical combining class (ccc if not decomposition)
    tccc: u8,
    /// number of leading non-starters.
    n_lead: u8,
    /// quick check flags
    flags: u8,
    index: u16,
}

impl Properties {
    /// Go: `Properties.BoundaryBefore`.
    // Go: forminfo.go:BoundaryBefore
    pub fn boundary_before(&self) -> bool {
        self.ccc == 0 && !self.combines_backward()
    }

    /// Go: `Properties.BoundaryAfter`.
    // Go: forminfo.go:BoundaryAfter
    pub fn boundary_after(&self) -> bool {
        // TODO: loosen these conditions.
        self.is_inert()
    }

    // Go: forminfo.go:isYesC
    fn is_yes_c(&self) -> bool {
        self.flags & 0x10 == 0
    }

    // Go: forminfo.go:isYesD
    fn is_yes_d(&self) -> bool {
        self.flags & 0x4 == 0
    }

    // Go: forminfo.go:combinesBackward
    fn combines_backward(&self) -> bool {
        self.flags & 0x8 != 0
    }

    // Go: forminfo.go:hasDecomposition
    fn has_decomposition(&self) -> bool {
        self.flags & 0x4 != 0
    }

    // Go: forminfo.go:isInert
    fn is_inert(&self) -> bool {
        self.flags & QC_INFO_MASK == 0 && self.ccc == 0
    }

    // Go: forminfo.go:nLeadingNonStarters
    fn n_leading_non_starters(&self) -> u8 {
        self.n_lead
    }

    // Go: forminfo.go:nTrailingNonStarters
    fn n_trailing_non_starters(&self) -> u8 {
        self.flags & 0x03
    }

    /// Go: `Properties.Decomposition` — the decomposition bytes (`None` for Go's nil).
    // Go: forminfo.go:Decomposition
    pub fn decomposition(&self) -> Option<&'static [u8]> {
        // TODO: create the decomposition for Hangul?
        if self.index == 0 {
            return None;
        }
        let mut i = self.index as usize;
        let n = (DECOMPS[i] & HEADER_LEN_MASK) as usize;
        i += 1;
        Some(&DECOMPS[i..i + n])
    }

    /// Go: `Properties.Size`.
    // Go: forminfo.go:Size
    pub fn size(&self) -> usize {
        self.size as usize
    }

    /// Go: `Properties.CCC`.
    // Go: forminfo.go:CCC
    pub fn ccc(&self) -> u8 {
        if self.index >= FIRST_CCC_ZERO_EXCEPT {
            return 0;
        }
        CCC[self.ccc as usize]
    }

    /// Go: `Properties.LeadCCC`.
    // Go: forminfo.go:LeadCCC
    pub fn lead_ccc(&self) -> u8 {
        CCC[self.ccc as usize]
    }

    /// Go: `Properties.TrailCCC`.
    // Go: forminfo.go:TrailCCC
    pub fn trail_ccc(&self) -> u8 {
        CCC[self.tccc as usize]
    }
}

// Go: forminfo.go:combine — the key truncates both runes to 16 bits, as x/text does.
fn combine(a: i32, b: i32) -> i32 {
    let key = ((a as u16 as u32) << 16).wrapping_add(b as u16 as u32);
    match RECOMP_MAP.binary_search_by_key(&key, |e| e.0) {
        Ok(k) => RECOMP_MAP[k].1 as i32,
        Err(_) => 0,
    }
}

// Go: forminfo.go:compInfo
fn comp_info(v: u16, sz: usize) -> Properties {
    if v == 0 {
        return Properties {
            size: sz as u8,
            ..Default::default()
        };
    } else if v >= 0x8000 {
        let mut p = Properties {
            size: sz as u8,
            ccc: v as u8,
            tccc: v as u8,
            flags: (v >> 8) as u8,
            ..Default::default()
        };
        if p.ccc > 0 || p.combines_backward() {
            p.n_lead = p.flags & 0x3;
        }
        return p;
    }
    // has decomposition
    let mut v = v;
    let h = DECOMPS[v as usize];
    let f = ((h & HEADER_FLAGS_MASK) >> 2) | 0x4;
    let mut p = Properties {
        size: sz as u8,
        flags: f,
        index: v,
        ..Default::default()
    };
    if v >= FIRST_CCC {
        v += (h & HEADER_LEN_MASK) as u16 + 1;
        let c = DECOMPS[v as usize];
        p.tccc = c >> 2;
        p.flags |= c & 0x3;
        if v >= FIRST_LEADING_CCC {
            p.n_lead = c & 0x3;
            if v >= FIRST_STARTER_WITH_N_LEAD {
                // We were tricked. Remove the decomposition.
                p.flags &= 0x03;
                p.index = 0;
                return p;
            }
            p.ccc = DECOMPS[v as usize + 1];
        }
    }
    p
}

// ---------------------------------------------------------------------------
// input.go (over bytes; Go's string input behaves identically)

// Go: input.go:skipASCII
fn skip_ascii(src: &[u8], mut p: usize, max: usize) -> usize {
    while p < max && src[p] < 0x80 {
        p += 1;
    }
    p
}

// Go: input.go:hangul
fn input_hangul(src: &[u8], p: usize) -> i32 {
    if !is_hangul(&src[p..]) {
        return 0;
    }
    let (r, size) = utf8::decode_rune(&src[p..]);
    if size != HANGUL_UTF8_SIZE {
        return 0;
    }
    r
}

// ---------------------------------------------------------------------------
// composition.go

/// Go: `ssState`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum SsState {
    /// Indicates a rune was successfully added to the segment.
    Success,
    /// Indicates a rune starts a new segment and should not be added.
    Starter,
    /// Indicates a rune caused a segment overflow and a CGJ should be inserted.
    Overflow,
}

/// Go: `streamSafe` — the number of non-starters in the current segment.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
struct StreamSafe(u8);

impl StreamSafe {
    // (streamSafe.first, backwards and isMax serve the unported boundary functions.)

    // Go: composition.go:streamSafe.next
    fn next(&mut self, p: Properties) -> SsState {
        if self.0 as usize > MAX_NON_STARTERS {
            panic!("streamSafe was not reset");
        }
        let n = p.n_leading_non_starters();
        self.0 = self.0.wrapping_add(n);
        if self.0 as usize > MAX_NON_STARTERS {
            self.0 = 0;
            return SsState::Overflow;
        }
        // The Stream-Safe Text Processing prescribes that the counting can stop
        // as soon as a starter is encountered. However, there are some starters,
        // like Jamo V and T, that can combine with other runes, leaving their
        // successive non-starters appended to the previous, possibly a segment
        // with too many non-starters.
        if n == 0 {
            self.0 = p.n_trailing_non_starters();
            return SsState::Starter;
        }
        SsState::Success
    }
}

/// Go: `reorderBuffer.flushF` — `appendFlush` or `flushTransform`.
enum Out<'d> {
    /// `appendFlush`: rb.out grows.
    Append(Vec<u8>),
    /// `flushTransform`: rb.out is `dst[pos..]`.
    Transform { dst: &'d mut [u8], pos: usize },
}

/// Go: `reorderBuffer`.
struct ReorderBuffer<'s, 'd> {
    /// Per character info.
    rune: [Properties; MAX_BUFFER_SIZE],
    /// UTF-8 buffer. Referenced by runeInfo.pos.
    byte: [u8; MAX_BYTE_BUFFER_SIZE],
    /// Number or bytes.
    nbyte: u8,
    /// For limiting length of non-starter sequence.
    ss: StreamSafe,
    /// Number of runeInfos.
    nrune: usize,
    f: FormInfo,

    src: &'s [u8],
    nsrc: usize,

    out: Out<'d>,
}

impl<'s, 'd> ReorderBuffer<'s, 'd> {
    // Go: composition.go:reorderBuffer.init / initString (+ setFlusher)
    fn new(f: Form, src: &'s [u8], out: Out<'d>) -> Self {
        ReorderBuffer {
            rune: [Properties::default(); MAX_BUFFER_SIZE],
            byte: [0; MAX_BYTE_BUFFER_SIZE],
            nbyte: 0,
            ss: StreamSafe(0),
            nrune: 0,
            f: form_table(f),
            src,
            nsrc: src.len(),
            out,
        }
    }

    // Go: composition.go:reorderBuffer.reset
    fn reset(&mut self) {
        self.nrune = 0;
        self.nbyte = 0;
    }

    // Go: composition.go:reorderBuffer.doFlush
    fn do_flush(&mut self) -> bool {
        if self.f.composing {
            self.compose();
        }
        let res = match self.out {
            Out::Append(_) => self.append_flush(),
            Out::Transform { .. } => self.flush_transform(),
        };
        self.reset();
        res
    }

    // Go: composition.go:appendFlush
    fn append_flush(&mut self) -> bool {
        let Out::Append(out) = &mut self.out else {
            unreachable!()
        };
        for i in 0..self.nrune {
            let start = self.rune[i].pos as usize;
            let end = start + self.rune[i].size as usize;
            out.extend_from_slice(&self.byte[start..end]);
        }
        true
    }

    // Go: transform.go:flushTransform
    fn flush_transform(&mut self) -> bool {
        let nrune = self.nrune;
        let Out::Transform { dst, pos } = &mut self.out else {
            unreachable!()
        };
        // Write out (must fully fit in dst, or else it is an ErrShortDst).
        if dst.len() - *pos < nrune * utf8::UTF_MAX {
            return false;
        }
        // Go: reorderBuffer.flushCopy
        let mut p = *pos;
        for i in 0..nrune {
            let runep = self.rune[i];
            let b = &self.byte[runep.pos as usize..runep.pos as usize + runep.size as usize];
            let n = b.len().min(dst.len() - p);
            dst[p..p + n].copy_from_slice(&b[..n]);
            p += n;
        }
        *pos = p;
        // flushCopy's reset; doFlush resets again.
        self.reset();
        true
    }

    // Go: composition.go:reorderBuffer.insertOrdered
    fn insert_ordered(&mut self, mut info: Properties) {
        let mut n = self.nrune;
        let b = &mut self.rune;
        let cc = info.ccc;
        if cc > 0 {
            // Find insertion position + move elements to make room.
            while n > 0 {
                if b[n - 1].ccc <= cc {
                    break;
                }
                b[n] = b[n - 1];
                n -= 1;
            }
        }
        self.nrune += 1;
        let pos = self.nbyte;
        self.nbyte += utf8::UTF_MAX as u8;
        info.pos = pos;
        b[n] = info;
    }

    // Go: composition.go:reorderBuffer.insertFlush
    fn insert_flush(&mut self, src: &[u8], i: usize, info: Properties) -> InsertErr {
        let rune = input_hangul(src, i);
        if rune != 0 {
            self.decompose_hangul(rune);
            return InsertErr::Success;
        }
        if info.has_decomposition() {
            return self.insert_decomposed(info.decomposition().unwrap_or(&[]));
        }
        self.insert_single(src, i, info);
        InsertErr::Success
    }

    // Go: composition.go:reorderBuffer.insertDecomposed
    fn insert_decomposed(&mut self, dcomp: &[u8]) -> InsertErr {
        let mut i = 0;
        while i < dcomp.len() {
            let info = self.f.info(dcomp, i);
            if info.boundary_before() && self.nrune > 0 && !self.do_flush() {
                return InsertErr::ShortDst;
            }
            let nb = self.nbyte as usize;
            let n = (info.size as usize).min(MAX_BYTE_BUFFER_SIZE - nb);
            self.byte[nb..nb + n].copy_from_slice(&dcomp[i..i + n]);
            i += n;
            self.insert_ordered(info);
        }
        InsertErr::Success
    }

    // Go: composition.go:reorderBuffer.insertSingle
    fn insert_single(&mut self, src: &[u8], i: usize, info: Properties) {
        let nb = self.nbyte as usize;
        let n = (info.size as usize).min(MAX_BYTE_BUFFER_SIZE - nb);
        self.byte[nb..nb + n].copy_from_slice(&src[i..i + n]);
        self.insert_ordered(info);
    }

    // Go: composition.go:reorderBuffer.insertCGJ
    fn insert_cgj(&mut self) {
        self.insert_single(
            GRAPHEME_JOINER.as_bytes(),
            0,
            Properties {
                size: GRAPHEME_JOINER.len() as u8,
                ..Default::default()
            },
        );
    }

    // Go: composition.go:reorderBuffer.appendRune
    fn append_rune(&mut self, r: i32) {
        let bn = self.nbyte;
        let sz = utf8::encode_rune(&mut self.byte[bn as usize..], r);
        self.nbyte += utf8::UTF_MAX as u8;
        self.rune[self.nrune] = Properties {
            pos: bn,
            size: sz as u8,
            ..Default::default()
        };
        self.nrune += 1;
    }

    // Go: composition.go:reorderBuffer.assignRune
    fn assign_rune(&mut self, pos: usize, r: i32) {
        let bn = self.rune[pos].pos;
        let sz = utf8::encode_rune(&mut self.byte[bn as usize..], r);
        self.rune[pos] = Properties {
            pos: bn,
            size: sz as u8,
            ..Default::default()
        };
    }

    // Go: composition.go:reorderBuffer.runeAt
    fn rune_at(&self, n: usize) -> i32 {
        let inf = self.rune[n];
        let (r, _) = utf8::decode_rune(&self.byte[inf.pos as usize..(inf.pos + inf.size) as usize]);
        r
    }

    // Go: composition.go:reorderBuffer.bytesAt
    fn bytes_at(&self, n: usize) -> &[u8] {
        let inf = self.rune[n];
        &self.byte[inf.pos as usize..inf.pos as usize + inf.size as usize]
    }

    // Go: composition.go:reorderBuffer.decomposeHangul
    fn decompose_hangul(&mut self, r: i32) {
        let mut r = r - HANGUL_BASE;
        let x = r % JAMO_T_COUNT;
        r /= JAMO_T_COUNT;
        self.append_rune(JAMO_L_BASE + r / JAMO_V_COUNT);
        self.append_rune(JAMO_V_BASE + r % JAMO_V_COUNT);
        if x != 0 {
            self.append_rune(JAMO_T_BASE + x);
        }
    }

    // Go: composition.go:reorderBuffer.combineHangul
    fn combine_hangul(&mut self, mut s: usize, mut i: usize, mut k: usize) {
        let bn = self.nrune;
        while i < bn {
            let ccc_b = self.rune[k - 1].ccc;
            let ccc_c = self.rune[i].ccc;
            if ccc_b == 0 {
                s = k - 1;
            }
            if s != k - 1 && ccc_b >= ccc_c {
                // b[i] is blocked by greater-equal cccX below it
                self.rune[k] = self.rune[i];
                k += 1;
            } else {
                let l = self.rune_at(s); // also used to compare to hangulBase
                let v = self.rune_at(i); // also used to compare to jamoT
                if (JAMO_L_BASE..JAMO_L_END).contains(&l) && (JAMO_V_BASE..JAMO_V_END).contains(&v)
                {
                    // 11xx plus 116x to LV
                    self.assign_rune(
                        s,
                        HANGUL_BASE
                            + (l - JAMO_L_BASE) * JAMO_VT_COUNT
                            + (v - JAMO_V_BASE) * JAMO_T_COUNT,
                    );
                } else if (HANGUL_BASE..HANGUL_END).contains(&l)
                    && JAMO_T_BASE < v
                    && v < JAMO_T_END
                    && (l - HANGUL_BASE) % JAMO_T_COUNT == 0
                {
                    // ACxx plus 11Ax to LVT
                    self.assign_rune(s, l + v - JAMO_T_BASE);
                } else {
                    self.rune[k] = self.rune[i];
                    k += 1;
                }
            }
            i += 1;
        }
        self.nrune = k;
    }

    // Go: composition.go:reorderBuffer.compose
    fn compose(&mut self) {
        // Lazily load the map used by the combine func below, but do
        // it outside of the loop.
        let bn = self.nrune;
        if bn == 0 {
            return;
        }
        let mut k = 1;
        let mut s = 0;
        let mut i = 1;
        while i < bn {
            if is_jamo_vt(self.bytes_at(i)) {
                // Redo from start in Hangul mode. Necessary to support
                // U+320E..U+321E in NFKC mode.
                self.combine_hangul(s, i, k);
                return;
            }
            let ii = self.rune[i];
            // We can only use combineForward as a filter if we later
            // get the info for the combined character. This is more
            // expensive than using the filter. Using combinesBackward()
            // is safe.
            if ii.combines_backward() {
                let ccc_b = self.rune[k - 1].ccc;
                let ccc_c = ii.ccc;
                let mut blocked = false; // b[i] blocked by starter or greater or equal CCC?
                if ccc_b == 0 {
                    s = k - 1;
                } else {
                    blocked = s != k - 1 && ccc_b >= ccc_c;
                }
                if !blocked {
                    let combined = combine(self.rune_at(s), self.rune_at(i));
                    if combined != 0 {
                        self.assign_rune(s, combined);
                        i += 1;
                        continue;
                    }
                }
            }
            self.rune[k] = self.rune[i];
            k += 1;
            i += 1;
        }
        self.nrune = k;
    }
}

/// Go: `insertErr` (`iSuccess` 0, `iShortDst` -1, `iShortSrc` -2).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum InsertErr {
    Success = 0,
    ShortDst = -1,
    ShortSrc = -2,
}

// Go: composition.go Hangul constants.
const HANGUL_BASE: i32 = 0xAC00; // UTF-8(hangulBase) -> EA B0 80
const HANGUL_BASE0: u8 = 0xEA;
const HANGUL_BASE1: u8 = 0xB0;
const HANGUL_END: i32 = HANGUL_BASE + JAMO_LVT_COUNT; // UTF-8(0xD7A4) -> ED 9E A4
const HANGUL_END0: u8 = 0xED;
const HANGUL_END1: u8 = 0x9E;
const HANGUL_END2: u8 = 0xA4;
const JAMO_L_BASE: i32 = 0x1100; // UTF-8(jamoLBase) -> E1 84 00
const JAMO_L_BASE0: u8 = 0xE1;
const JAMO_L_BASE1: u8 = 0x84;
const JAMO_L_END: i32 = 0x1113;
const JAMO_V_BASE: i32 = 0x1161;
const JAMO_V_END: i32 = 0x1176;
const JAMO_T_BASE: i32 = 0x11A7;
const JAMO_T_END: i32 = 0x11C3;
const JAMO_T_COUNT: i32 = 28;
const JAMO_V_COUNT: i32 = 21;
const JAMO_VT_COUNT: i32 = 21 * 28;
const JAMO_LVT_COUNT: i32 = 19 * 21 * 28;
const HANGUL_UTF8_SIZE: usize = 3;

// Go: composition.go:isHangul (isHangulString is identical over string bytes)
fn is_hangul(b: &[u8]) -> bool {
    if b.len() < HANGUL_UTF8_SIZE {
        return false;
    }
    let b0 = b[0];
    if b0 < HANGUL_BASE0 {
        return false;
    }
    let b1 = b[1];
    if b0 == HANGUL_BASE0 {
        return b1 >= HANGUL_BASE1;
    }
    if b0 < HANGUL_END0 {
        return true;
    }
    if b0 > HANGUL_END0 {
        return false;
    }
    if b1 < HANGUL_END1 {
        return true;
    }
    b1 == HANGUL_END1 && b[2] < HANGUL_END2
}

// Go: composition.go:isJamoVT
fn is_jamo_vt(b: &[u8]) -> bool {
    // True if (rune & 0xff00) == jamoLBase
    b[0] == JAMO_L_BASE0 && (b[1] & 0xFC) == JAMO_L_BASE1
}

// ---------------------------------------------------------------------------
// normalize.go

impl Form {
    /// Go: `Form.Bytes` — the form of `b`.
    // Go: normalize.go:Bytes
    pub fn bytes(self, b: &[u8]) -> Vec<u8> {
        let ft = form_table(self);
        let (n, ok) = ft.quick_span(b, 0, b.len(), true);
        if ok {
            return b.to_vec();
        }
        let mut out = Vec::with_capacity(b.len());
        out.extend_from_slice(&b[..n]);
        let mut rb = ReorderBuffer::new(self, b, Out::Append(out));
        do_append_inner(&mut rb, n)
    }

    /// Go: `Form.String` over Go string bytes (which may hold invalid UTF-8).
    // Go: normalize.go:String
    pub fn string_bytes(self, s: &[u8]) -> Vec<u8> {
        // String and Bytes differ only in their input type.
        self.bytes(s)
    }

    /// Go: `Form.String`. Normalizing valid UTF-8 gives valid UTF-8.
    // Go: normalize.go:String
    pub fn string(self, s: &str) -> String {
        String::from_utf8(self.string_bytes(s.as_bytes()))
            .expect("x/text norm keeps valid UTF-8 valid")
    }

    /// Go: `Form.QuickSpan`.
    // Go: normalize.go:QuickSpan
    pub fn quick_span(self, b: &[u8]) -> usize {
        form_table(self).quick_span(b, 0, b.len(), true).0
    }

    /// Go: `Form.Properties` (`PropertiesString` is identical over string bytes).
    // Go: forminfo.go:Properties
    pub fn properties(self, s: &[u8]) -> Properties {
        let (v, sz) = nfc_lookup(s);
        comp_info(v, sz)
    }
}

// Go: normalize.go:appendQuick
fn append_quick(rb: &mut ReorderBuffer, i: usize) -> usize {
    if rb.nsrc == i {
        return i;
    }
    let (end, _) = rb.f.quick_span(rb.src, i, rb.nsrc, true);
    let Out::Append(out) = &mut rb.out else {
        unreachable!()
    };
    out.extend_from_slice(&rb.src[i..end]);
    end
}

// Go: normalize.go:doAppendInner
fn do_append_inner(rb: &mut ReorderBuffer, mut p: usize) -> Vec<u8> {
    let n = rb.nsrc;
    while p < n {
        // decomposeSegment returns 0 (never < 0) here: atEOF is true and the
        // append flusher never fails.
        p = decompose_segment(rb, p, true) as usize;
        p = append_quick(rb, p);
    }
    match std::mem::replace(&mut rb.out, Out::Append(Vec::new())) {
        Out::Append(out) => out,
        Out::Transform { .. } => unreachable!(),
    }
}

impl FormInfo {
    // Go: normalize.go:formInfo.quickSpan
    fn quick_span(&self, src: &[u8], mut i: usize, end: usize, at_eof: bool) -> (usize, bool) {
        let mut last_cc: u8 = 0;
        let mut ss = StreamSafe(0);
        let mut last_seg_start = i;
        let mut n = end;
        while i < n {
            let j = skip_ascii(src, i, n);
            if i != j {
                i = j;
                last_seg_start = i - 1;
                last_cc = 0;
                ss = StreamSafe(0);
                continue;
            }
            let info = self.info(src, i);
            if info.size == 0 {
                if at_eof {
                    // include incomplete runes
                    return (n, true);
                }
                return (last_seg_start, true);
            }
            // This block needs to be before the next, because it is possible to
            // have an overflow for runes that are starters (e.g. with U+FF9E).
            match ss.next(info) {
                SsState::Starter => last_seg_start = i,
                SsState::Overflow => return (last_seg_start, false),
                SsState::Success => {
                    if last_cc > info.ccc {
                        return (last_seg_start, false);
                    }
                }
            }
            if self.composing {
                if !info.is_yes_c() {
                    break;
                }
            } else if !info.is_yes_d() {
                break;
            }
            last_cc = info.ccc;
            i += info.size as usize;
        }
        if i == n {
            if !at_eof {
                n = last_seg_start;
            }
            return (n, true);
        }
        (last_seg_start, false)
    }
}

// Go: normalize.go:decomposeSegment — returns the end of the segment, or an `InsertErr` (< 0).
fn decompose_segment(rb: &mut ReorderBuffer, mut sp: usize, at_eof: bool) -> isize {
    // Force one character to be consumed.
    let mut info = rb.f.info(rb.src, sp);
    if info.size == 0 {
        return 0;
    }
    let mut skip_to_end = false;
    match rb.ss.next(info) {
        SsState::Starter => {
            if rb.nrune > 0 {
                skip_to_end = true;
            }
        }
        SsState::Overflow => {
            rb.insert_cgj();
            skip_to_end = true;
        }
        SsState::Success => {}
    }
    if !skip_to_end {
        let src = rb.src;
        let err = rb.insert_flush(src, sp, info);
        if err != InsertErr::Success {
            return err as isize;
        }
        loop {
            sp += info.size as usize;
            if sp >= rb.nsrc {
                if !at_eof && !info.boundary_after() {
                    return InsertErr::ShortSrc as isize;
                }
                break;
            }
            info = rb.f.info(rb.src, sp);
            if info.size == 0 {
                if !at_eof {
                    return InsertErr::ShortSrc as isize;
                }
                break;
            }
            match rb.ss.next(info) {
                SsState::Starter => break,
                SsState::Overflow => {
                    rb.insert_cgj();
                    break;
                }
                SsState::Success => {}
            }
            let err = rb.insert_flush(src, sp, info);
            if err != InsertErr::Success {
                return err as isize;
            }
        }
    }
    // end:
    if !rb.do_flush() {
        return InsertErr::ShortDst as isize;
    }
    sp as isize
}

// ---------------------------------------------------------------------------
// transform.go

impl Form {
    /// Go: `Form.Transform` — implements `transform.Transformer`.
    // Go: transform.go:Transform
    pub fn transform_bytes(
        self,
        dst: &mut [u8],
        src: &[u8],
        at_eof: bool,
    ) -> (usize, usize, Option<TransformError>) {
        // Cap the maximum number of src bytes to check.
        let mut b = src;
        let mut eof = at_eof;
        let mut err = None;
        let ns = dst.len();
        if ns < b.len() {
            err = Some(TransformError::ShortDst);
            eof = false;
            b = &b[..ns];
        }
        let (i, ok) = form_table(self).quick_span(b, 0, b.len(), eof);
        let n = i.min(dst.len());
        dst[..n].copy_from_slice(&b[..n]);
        if !ok {
            let (n_dst, n_src, err) = self.transform_inner(&mut dst[n..], &src[n..], at_eof);
            return (n_dst + n, n_src + n, err);
        }

        if err.is_none() && n < src.len() && !at_eof {
            err = Some(TransformError::ShortSrc);
        }
        (n, n, err)
    }

    // Go: transform.go:transform
    fn transform_inner(
        self,
        dst: &mut [u8],
        src: &[u8],
        at_eof: bool,
    ) -> (usize, usize, Option<TransformError>) {
        let dst_len = dst.len();
        let mut rb = ReorderBuffer::new(self, src, Out::Transform { dst, pos: 0 });
        let mut n_dst = 0;
        let mut n_src = 0;
        let mut err = None;
        loop {
            // Load segment into reorder buffer.
            // Go: rb.setFlusher(dst[nDst:], flushTransform)
            if let Out::Transform { pos, .. } = &mut rb.out {
                *pos = n_dst;
            }
            let end = decompose_segment(&mut rb, n_src, at_eof);
            if end < 0 {
                // Go: errs[-end]
                let e = if end == InsertErr::ShortDst as isize {
                    TransformError::ShortDst
                } else {
                    TransformError::ShortSrc
                };
                return (n_dst, n_src, Some(e));
            }
            let Out::Transform { dst, pos } = &mut rb.out else {
                unreachable!()
            };
            n_dst = *pos;
            n_src = end as usize;

            // Next quickSpan.
            let mut end = rb.nsrc;
            let mut eof = at_eof;
            let n = n_src + dst_len - n_dst;
            if n < end {
                err = Some(TransformError::ShortDst);
                end = n;
                eof = false;
            }
            let (end, ok) = rb.f.quick_span(rb.src, n_src, end, eof);
            let n = (end - n_src).min(dst.len() - n_dst);
            dst[n_dst..n_dst + n].copy_from_slice(&rb.src[n_src..n_src + n]);
            n_src += n;
            n_dst += n;
            if ok {
                if err.is_none() && n < rb.nsrc && !at_eof {
                    err = Some(TransformError::ShortSrc);
                }
                return (n_dst, n_src, err);
            }
        }
    }
}

impl Transformer for Form {
    // Go: transform.go:Transform
    fn transform(
        &mut self,
        dst: &mut [u8],
        src: &[u8],
        at_eof: bool,
    ) -> (usize, usize, Option<TransformError>) {
        self.transform_bytes(dst, src, at_eof)
    }

    /// Go: `Form.Reset` — implements the Reset method of the transform.Transformer interface.
    // Go: transform.go:Reset
    fn reset(&mut self) {}
}

// ---------------------------------------------------------------------------
// Callers' conveniences

/// Go: `norm.NFC.String(s)` — the darwin file-name normalization of `hugofs/fileinfo.go`
/// (`normalizeFilename`) and `component_fs.go` (`applyMeta`).
pub fn nfc_string(s: &str) -> String {
    NFC.string(s)
}

/// Go: `norm.NFD.String(s)`.
pub fn nfd_string(s: &str) -> String {
    NFD.string(s)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn basics() {
        assert_eq!(VERSION, "15.0.0");
        assert_eq!(nfc_string("cafe\u{301}.md"), "café.md");
        assert_eq!(nfc_string("café.md"), "café.md");
        assert_eq!(nfd_string("café.md"), "cafe\u{301}.md");
        assert_eq!(nfc_string("\u{1100}\u{1161}\u{11a8}"), "\u{ac01}");
        assert_eq!(nfd_string("\u{ac01}"), "\u{1100}\u{1161}\u{11a8}");
        assert_eq!(nfc_string("e\u{327}\u{306}"), "\u{1e1d}");
        assert_eq!(nfc_string("บทความ/ไทย.md"), "บทความ/ไทย.md");
        assert_eq!(nfc_string(""), "");
        // A CGJ after 30 non-starters.
        let s = format!("a{}", "\u{301}".repeat(31));
        assert_eq!(
            nfd_string(&s),
            format!("a{}\u{34f}\u{301}", "\u{301}".repeat(30))
        );
        assert_eq!(NFC.bytes(b"e\xcc\x81\xff"), b"\xc3\xa9\xff");
        assert_eq!(NFC.quick_span("cafe\u{301}".as_bytes()), 3);
        assert_eq!(NFD.properties("\u{301}".as_bytes()).ccc(), 230);
    }
}
