//! Chroma's `c++.xml` lexer, converted to Rust (crate README, "Lexer and style files").

use crate::chroma::defs::prelude::*;

#[rustfmt::skip]
pub(crate) static LEXER: LexerDef = LexerDef {
    file: "c++",
    config: ConfigDef {
        name: "C++",
        aliases: &["cpp", "c++"],
        filenames: &[
            "*.cpp",
            "*.hpp",
            "*.c++",
            "*.h++",
            "*.cc",
            "*.hh",
            "*.cxx",
            "*.hxx",
            "*.C",
            "*.H",
            "*.cp",
            "*.CPP",
            "*.tpp",
        ],
        mime_types: &["text/x-c++hdr", "text/x-c++src"],
        ensure_nl: true,
        analyse: Some(AnalyseDef {
            first: true,
            regexes: &[
                (r"#include <[a-z_]+>", 0.2),
                (r"using namespace ", 0.4),
            ],
        }),
        ..ConfigDef::EMPTY
    },
    states: &[
        ("classname", &[
            rule(r"(\[\[.+\]\])(\s*)").groups(&[T::NameAttribute, T::Text]),
            rule(r"[a-zA-Z_]\w*").token(T::NameClass).pop(1),
            rule(r"\s*(?=[>{])").token(T::Text).pop(1),
        ]),
        ("whitespace", &[
            rule(r"^#if\s+0").token(T::CommentPreproc).push(&["if0"]),
            rule(r"^#").token(T::CommentPreproc).push(&["macro"]),
            rule(r"^(\s*(?:/[*].*?[*]/\s*)?)(#if\s+0)").bygroups(&[E::UsingSelf("root"), E::Token(T::CommentPreproc)]).push(&["if0"]),
            rule(r"^(\s*(?:/[*].*?[*]/\s*)?)(#)").bygroups(&[E::UsingSelf("root"), E::Token(T::CommentPreproc)]).push(&["macro"]),
            rule(r"\n").token(T::Text),
            rule(r"\s+").token(T::Text),
            rule(r"\\\n").token(T::Text),
            rule(r"//(\n|[\w\W]*?[^\\]\n)").token(T::CommentSingle),
            rule(r"/(\\\n)?[*][\w\W]*?[*](\\\n)?/").token(T::CommentMultiline),
            rule(r"/(\\\n)?[*][\w\W]*").token(T::CommentMultiline),
        ]),
        ("macro", &[
            rule(r#"(include)(\s+)("[^"]+?"|<[^>]+?>)"#).groups(&[T::CommentPreproc, T::Text, T::CommentPreprocFile]),
            rule(r"[^/\n]+").token(T::CommentPreproc),
            rule(r"/[*](.|\n)*?[*]/").token(T::CommentMultiline),
            rule(r"//.*?\n").token(T::CommentSingle).pop(1),
            rule(r"/").token(T::CommentPreproc),
            rule(r"(?<=\\)\n").token(T::CommentPreproc),
            rule(r"\n").token(T::CommentPreproc).pop(1),
        ]),
        ("statements", &[
            rule(r"(reinterpret_cast|static_assert|thread_local|dynamic_cast|static_cast|const_cast|co_return|protected|namespace|consteval|constexpr|typename|co_await|co_yield|operator|restrict|explicit|template|override|noexcept|requires|decltype|alignof|private|alignas|virtual|mutable|nullptr|concept|export|friend|typeid|throws|public|delete|final|throw|catch|using|this|new|try)\b").token(T::Keyword),
            rule(r"(enum)\b(\s+)(class)\b(\s*)").groups(&[T::Keyword, T::Text, T::Keyword, T::Text]).push(&["classname"]),
            rule(r"(class|struct|enum|union)\b(\s*)").groups(&[T::Keyword, T::Text]).push(&["classname"]),
            rule(r"\[\[.+\]\]").token(T::NameAttribute),
            rule(r#"(R)(")([^\\()\s]{,16})(\()((?:.|\n)*?)(\)\3)(")"#).groups(&[T::LiteralStringAffix, T::LiteralString, T::LiteralStringDelimiter, T::LiteralStringDelimiter, T::LiteralString, T::LiteralStringDelimiter, T::LiteralString]),
            rule(r#"(u8|u|U)(")"#).groups(&[T::LiteralStringAffix, T::LiteralString]).push(&["string"]),
            rule(r#"(L?)(")"#).groups(&[T::LiteralStringAffix, T::LiteralString]).push(&["string"]),
            rule(r"(L?)(')(\\.|\\[0-7]{1,3}|\\x[a-fA-F0-9]{1,2}|[^\\\'\n])(')").groups(&[T::LiteralStringAffix, T::LiteralStringChar, T::LiteralStringChar, T::LiteralStringChar]),
            rule(r"(\d+\.\d*|\.\d+|\d+)[eE][+-]?\d+[LlUu]*").token(T::LiteralNumberFloat),
            rule(r"(\d+\.\d*|\.\d+|\d+[fF])[fF]?").token(T::LiteralNumberFloat),
            rule(r"0[xX]([0-9A-Fa-f]('?[0-9A-Fa-f]+)*)[LlUu]*").token(T::LiteralNumberHex),
            rule(r"0('?[0-7]+)+[LlUu]*").token(T::LiteralNumberOct),
            rule(r"0[Bb][01]('?[01]+)*[LlUu]*").token(T::LiteralNumberBin),
            rule(r"[0-9]('?[0-9]+)*[LlUu]*").token(T::LiteralNumberInteger),
            rule(r"\*/").token(T::Error),
            rule(r"[~!%^&*+=|?:<>/-]").token(T::Operator),
            rule(r"[()\[\],.]").token(T::Punctuation),
            rule(r"(restricted|volatile|continue|register|default|typedef|struct|extern|switch|sizeof|static|return|union|while|const|break|goto|enum|else|case|auto|for|asm|if|do)\b").token(T::Keyword),
            rule(r"(bool|int|long|float|short|double|char((8|16|32)_t)?|wchar_t|unsigned|signed|void|u?int(_fast|_least|)(8|16|32|64)_t)\b").token(T::KeywordType),
            rule(r"(typename|__inline|restrict|_inline|thread|inline|naked)\b").token(T::KeywordReserved),
            rule(r"(__m(128i|128d|128|64))\b").token(T::KeywordReserved),
            rule(r"__(forceinline|identifier|unaligned|declspec|fastcall|stdcall|finally|except|assume|int32|cdecl|int64|based|leave|int16|raise|noop|int8|w64|try|asm)\b").token(T::KeywordReserved),
            rule(r"(true|false|NULL)\b").token(T::NameBuiltin),
            rule(r"([a-zA-Z_]\w*)(\s*)(:)(?!:)").groups(&[T::NameLabel, T::Text, T::Punctuation]),
            rule(r"[a-zA-Z_]\w*").token(T::Name),
        ]),
        ("function", &[
            include("whitespace"),
            include("statements"),
            rule(r";").token(T::Punctuation),
            rule(r"\{").token(T::Punctuation).push(&[]),
            rule(r"\}").token(T::Punctuation).pop(1),
        ]),
        ("string", &[
            rule(r#"""#).token(T::LiteralString).pop(1),
            rule(r#"\\([\\abfnrtv"\']|x[a-fA-F0-9]{2,4}|u[a-fA-F0-9]{4}|U[a-fA-F0-9]{8}|[0-7]{1,3})"#).token(T::LiteralStringEscape),
            rule(r#"[^\\"\n]+"#).token(T::LiteralString),
            rule(r"\\\n").token(T::LiteralString),
            rule(r"\\").token(T::LiteralString),
        ]),
        ("if0", &[
            rule(r"^\s*#if.*?(?<!\\)\n").token(T::CommentPreproc).push(&[]),
            rule(r"^\s*#el(?:se|if).*\n").token(T::CommentPreproc).pop(1),
            rule(r"^\s*#endif.*?(?<!\\)\n").token(T::CommentPreproc).pop(1),
            rule(r".*?\n").token(T::Comment),
        ]),
        ("root", &[
            include("whitespace"),
            rule(r"((?:[\w*\s])+?(?:\s|[*]))([a-zA-Z_]\w*)(\s*\([^;]*?\))([^;{]*)(\{)").bygroups(&[E::UsingSelf("root"), E::Token(T::NameFunction), E::UsingSelf("root"), E::UsingSelf("root"), E::Token(T::Punctuation)]).push(&["function"]),
            rule(r"((?:[\w*\s])+?(?:\s|[*]))([a-zA-Z_]\w*)(\s*\([^;]*?\))([^;]*)(;)").bygroups(&[E::UsingSelf("root"), E::Token(T::NameFunction), E::UsingSelf("root"), E::UsingSelf("root"), E::Token(T::Punctuation)]),
            rule("").push(&["statement"]),
            rule(r"__(multiple_inheritance|virtual_inheritance|single_inheritance|interface|uuidof|super|event)\b").token(T::KeywordReserved),
            rule(r"__(offload|blockingoffload|outer)\b").token(T::KeywordPseudo),
        ]),
        ("statement", &[
            include("whitespace"),
            include("statements"),
            rule(r"[{]").token(T::Punctuation).push(&["root"]),
            rule(r"[;}]").token(T::Punctuation).pop(1),
        ]),
    ],
};
