//! Chroma's `crystal.xml` lexer, converted to Rust (crate README, "Lexer and style files").

use crate::chroma::defs::prelude::*;

#[rustfmt::skip]
pub(crate) static LEXER: LexerDef = LexerDef {
    file: "crystal",
    config: ConfigDef {
        name: "Crystal",
        aliases: &["cr", "crystal"],
        filenames: &["*.cr"],
        mime_types: &["text/x-crystal"],
        dot_all: true,
        ..ConfigDef::EMPTY
    },
    states: &[
        ("pa-intp-string", &[
            rule(r"\\[\(]").token(T::LiteralStringOther),
            rule(r"\(").token(T::LiteralStringOther).push(&[]),
            rule(r"\)").token(T::LiteralStringOther).pop(1),
            include("string-intp-escaped"),
            rule(r"[\\#()]").token(T::LiteralStringOther),
            rule(r"[^\\#()]+").token(T::LiteralStringOther),
        ]),
        ("ab-regex", &[
            rule(r"\\[\\<>]").token(T::LiteralStringRegex),
            rule(r"<").token(T::LiteralStringRegex).push(&[]),
            rule(r">[imsx]*").token(T::LiteralStringRegex).pop(1),
            include("string-intp"),
            rule(r"[\\#<>]").token(T::LiteralStringRegex),
            rule(r"[^\\#<>]+").token(T::LiteralStringRegex),
        ]),
        ("cb-regex", &[
            rule(r"\\[\\{}]").token(T::LiteralStringRegex),
            rule(r"\{").token(T::LiteralStringRegex).push(&[]),
            rule(r"\}[imsx]*").token(T::LiteralStringRegex).pop(1),
            include("string-intp"),
            rule(r"[\\#{}]").token(T::LiteralStringRegex),
            rule(r"[^\\#{}]+").token(T::LiteralStringRegex),
        ]),
        ("simple-backtick", &[
            include("string-intp-escaped"),
            rule(r"[^\\`#]+").token(T::LiteralStringBacktick),
            rule(r"[\\#]").token(T::LiteralStringBacktick),
            rule(r"`").token(T::LiteralStringBacktick).pop(1),
        ]),
        ("string-intp", &[
            rule(r"#\{").token(T::LiteralStringInterpol).push(&["in-intp"]),
        ]),
        ("interpolated-regex", &[
            include("string-intp"),
            rule(r"[\\#]").token(T::LiteralStringRegex),
            rule(r"[^\\#]+").token(T::LiteralStringRegex),
        ]),
        ("cb-string", &[
            rule(r"\\[\\{}]").token(T::LiteralStringOther),
            rule(r"\{").token(T::LiteralStringOther).push(&[]),
            rule(r"\}").token(T::LiteralStringOther).pop(1),
            rule(r"[\\#{}]").token(T::LiteralStringOther),
            rule(r"[^\\#{}]+").token(T::LiteralStringOther),
        ]),
        ("in-macro-control", &[
            rule(r"\{%").token(T::LiteralStringInterpol).push(&[]),
            rule(r"%\}").token(T::LiteralStringInterpol).pop(1),
            rule(r"for\b|in\b").token(T::Keyword),
            include("root"),
        ]),
        ("interpolated-string", &[
            include("string-intp"),
            rule(r"[\\#]").token(T::LiteralStringOther),
            rule(r"[^\\#]+").token(T::LiteralStringOther),
        ]),
        ("in-macro-expr", &[
            rule(r"\{\{").token(T::LiteralStringInterpol).push(&[]),
            rule(r"\}\}").token(T::LiteralStringInterpol).pop(1),
            include("root"),
        ]),
        ("simple-string", &[
            include("string-intp-escaped"),
            rule(r##"[^\\"#]+"##).token(T::LiteralStringDouble),
            rule(r"[\\#]").token(T::LiteralStringDouble),
            rule(r#"""#).token(T::LiteralStringDouble).pop(1),
        ]),
        ("cb-intp-string", &[
            rule(r"\\[\{]").token(T::LiteralStringOther),
            rule(r"\{").token(T::LiteralStringOther).push(&[]),
            rule(r"\}").token(T::LiteralStringOther).pop(1),
            include("string-intp-escaped"),
            rule(r"[\\#{}]").token(T::LiteralStringOther),
            rule(r"[^\\#{}]+").token(T::LiteralStringOther),
        ]),
        ("string-intp-escaped", &[
            include("string-intp"),
            include("string-escaped"),
        ]),
        ("sb-regex", &[
            rule(r"\\[\\\[\]]").token(T::LiteralStringRegex),
            rule(r"\[").token(T::LiteralStringRegex).push(&[]),
            rule(r"\][imsx]*").token(T::LiteralStringRegex).pop(1),
            include("string-intp"),
            rule(r"[\\#\[\]]").token(T::LiteralStringRegex),
            rule(r"[^\\#\[\]]+").token(T::LiteralStringRegex),
        ]),
        ("classname", &[
            rule(r"[A-Z_]\w*").token(T::NameClass),
            rule(r"(\()(\s*)([A-Z_]\w*)(\s*)(\))").groups(&[T::Punctuation, T::Text, T::NameClass, T::Text, T::Punctuation]),
            rule("").pop(1),
        ]),
        ("string-escaped", &[
            rule(r#"\\([\\befnstv#"\']|x[a-fA-F0-9]{1,2}|[0-7]{1,3})"#).token(T::LiteralStringEscape),
        ]),
        ("sb-intp-string", &[
            rule(r"\\[\[]").token(T::LiteralStringOther),
            rule(r"\[").token(T::LiteralStringOther).push(&[]),
            rule(r"\]").token(T::LiteralStringOther).pop(1),
            include("string-intp-escaped"),
            rule(r"[\\#\[\]]").token(T::LiteralStringOther),
            rule(r"[^\\#\[\]]+").token(T::LiteralStringOther),
        ]),
        ("pa-regex", &[
            rule(r"\\[\\()]").token(T::LiteralStringRegex),
            rule(r"\(").token(T::LiteralStringRegex).push(&[]),
            rule(r"\)[imsx]*").token(T::LiteralStringRegex).pop(1),
            include("string-intp"),
            rule(r"[\\#()]").token(T::LiteralStringRegex),
            rule(r"[^\\#()]+").token(T::LiteralStringRegex),
        ]),
        ("in-attr", &[
            rule(r"\[").token(T::Operator).push(&[]),
            rule(r"\]").token(T::Operator).pop(1),
            include("root"),
        ]),
        ("ab-intp-string", &[
            rule(r"\\[<]").token(T::LiteralStringOther),
            rule(r"<").token(T::LiteralStringOther).push(&[]),
            rule(r">").token(T::LiteralStringOther).pop(1),
            include("string-intp-escaped"),
            rule(r"[\\#<>]").token(T::LiteralStringOther),
            rule(r"[^\\#<>]+").token(T::LiteralStringOther),
        ]),
        ("in-intp", &[
            rule(r"\{").token(T::LiteralStringInterpol).push(&[]),
            rule(r"\}").token(T::LiteralStringInterpol).pop(1),
            include("root"),
        ]),
        ("end-part", &[
            rule(r".+").token(T::CommentPreproc).pop(1),
        ]),
        ("root", &[
            rule(r"#.*?$").token(T::CommentSingle),
            rule(r"(instance_sizeof|pointerof|protected|abstract|require|private|include|unless|typeof|sizeof|return|extend|ensure|rescue|ifdef|super|break|begin|until|while|elsif|yield|next|when|else|then|case|with|end|asm|if|do|as|of)\b").token(T::Keyword),
            rule(r"(false|true|nil)\b").token(T::KeywordConstant),
            rule(r"(module|lib)(\s+)([a-zA-Z_]\w*(?:::[a-zA-Z_]\w*)*)").groups(&[T::Keyword, T::Text, T::NameNamespace]),
            rule(r"(def|fun|macro)(\s+)((?:[a-zA-Z_]\w*::)*)").groups(&[T::Keyword, T::Text, T::NameNamespace]).push(&["funcname"]),
            rule(r"def(?=[*%&^`~+-/\[<>=])").token(T::Keyword).push(&["funcname"]),
            rule(r"(class|struct|union|type|alias|enum)(\s+)((?:[a-zA-Z_]\w*::)*)").groups(&[T::Keyword, T::Text, T::NameNamespace]).push(&["classname"]),
            rule(r"(self|out|uninitialized)\b|(is_a|responds_to)\?").token(T::KeywordPseudo),
            rule(r"(def_equals_and_hash|assert_responds_to|forward_missing_to|def_equals|property|def_hash|parallel|delegate|debugger|getter|record|setter|spawn|pp)\b").token(T::NameBuiltinPseudo),
            rule(r"getter[!?]|property[!?]|__(DIR|FILE|LINE)__\b").token(T::NameBuiltinPseudo),
            rule(r"(?<!\.)(get_stack_top|StaticArray|Concurrent|with_color|Reference|Scheduler|read_line|Exception|at_exit|Pointer|Channel|Float64|sprintf|Float32|Process|Object|Struct|caller|UInt16|UInt32|UInt64|system|future|Number|printf|String|Symbol|Int32|Range|Slice|Regex|Mutex|sleep|Array|Class|raise|Tuple|Deque|delay|Float|Int16|print|abort|Value|UInt8|Int64|puts|Proc|File|Void|exit|fork|Bool|Char|gets|lazy|loop|main|rand|Enum|Int8|Time|Hash|Set|Box|Nil|Dir|Int|p)\b").token(T::NameBuiltin),
            rule(r#"(?<!\w)(<<-?)(["`\']?)([a-zA-Z_]\w*)(\2)(.*?\n)"#).token(T::LiteralStringHeredoc),
            rule(r#"(<<-?)("|\')()(\2)(.*?\n)"#).token(T::LiteralStringHeredoc),
            rule(r"__END__").token(T::CommentPreproc).push(&["end-part"]),
            rule(r"(?:^|(?<=[=<>~!:])|(?<=(?:\s|;)when\s)|(?<=(?:\s|;)or\s)|(?<=(?:\s|;)and\s)|(?<=\.index\s)|(?<=\.scan\s)|(?<=\.sub\s)|(?<=\.sub!\s)|(?<=\.gsub\s)|(?<=\.gsub!\s)|(?<=\.match\s)|(?<=(?:\s|;)if\s)|(?<=(?:\s|;)elsif\s)|(?<=^when\s)|(?<=^index\s)|(?<=^scan\s)|(?<=^sub\s)|(?<=^gsub\s)|(?<=^sub!\s)|(?<=^gsub!\s)|(?<=^match\s)|(?<=^if\s)|(?<=^elsif\s))(\s*)(/)").groups(&[T::Text, T::LiteralStringRegex]).push(&["multiline-regex"]),
            rule(r"(?<=\(|,|\[)/").token(T::LiteralStringRegex).push(&["multiline-regex"]),
            rule(r"(\s+)(/)(?![\s=])").groups(&[T::Text, T::LiteralStringRegex]).push(&["multiline-regex"]),
            rule(r"(0o[0-7]+(?:_[0-7]+)*(?:_?[iu][0-9]+)?)\b(\s*)([/?])?").groups(&[T::LiteralNumberOct, T::Text, T::Operator]),
            rule(r"(0x[0-9A-Fa-f]+(?:_[0-9A-Fa-f]+)*(?:_?[iu][0-9]+)?)\b(\s*)([/?])?").groups(&[T::LiteralNumberHex, T::Text, T::Operator]),
            rule(r"(0b[01]+(?:_[01]+)*(?:_?[iu][0-9]+)?)\b(\s*)([/?])?").groups(&[T::LiteralNumberBin, T::Text, T::Operator]),
            rule(r"((?:0(?![0-9])|[1-9][\d_]*)(?:\.\d[\d_]*)(?:e[+-]?[0-9]+)?(?:_?f[0-9]+)?)(\s*)([/?])?").groups(&[T::LiteralNumberFloat, T::Text, T::Operator]),
            rule(r"((?:0(?![0-9])|[1-9][\d_]*)(?:\.\d[\d_]*)?(?:e[+-]?[0-9]+)(?:_?f[0-9]+)?)(\s*)([/?])?").groups(&[T::LiteralNumberFloat, T::Text, T::Operator]),
            rule(r"((?:0(?![0-9])|[1-9][\d_]*)(?:\.\d[\d_]*)?(?:e[+-]?[0-9]+)?(?:_?f[0-9]+))(\s*)([/?])?").groups(&[T::LiteralNumberFloat, T::Text, T::Operator]),
            rule(r"(0\b|[1-9][\d]*(?:_\d+)*(?:_?[iu][0-9]+)?)\b(\s*)([/?])?").groups(&[T::LiteralNumberInteger, T::Text, T::Operator]),
            rule(r"@@[a-zA-Z_]\w*").token(T::NameVariableClass),
            rule(r"@[a-zA-Z_]\w*").token(T::NameVariableInstance),
            rule(r"\$\w+").token(T::NameVariableGlobal),
            rule(r#"\$[!@&`\'+~=/\\,;.<>_*$?:"^-]"#).token(T::NameVariableGlobal),
            rule(r"\$-[0adFiIlpvw]").token(T::NameVariableGlobal),
            rule(r"::").token(T::Operator),
            include("strings"),
            rule(r#"\?(\\[MC]-)*(\\([\\befnrtv#"\']|x[a-fA-F0-9]{1,2}|[0-7]{1,3})|\S)(?!\w)"#).token(T::LiteralStringChar),
            rule(r"[A-Z][A-Z_]+\b").token(T::NameConstant),
            rule(r"\{%").token(T::LiteralStringInterpol).push(&["in-macro-control"]),
            rule(r"\{\{").token(T::LiteralStringInterpol).push(&["in-macro-expr"]),
            rule(r"(@\[)(\s*)([A-Z]\w*)").groups(&[T::Operator, T::Text, T::NameDecorator]).push(&["in-attr"]),
            rule(r"(\.|::)(\[\]\?|<=>|===|\[\]=|>>|&&|\*\*|\[\]|\|\||>=|=~|!~|<<|<=|!=|==|<|/|=|-|\+|>|\*|&|%|\^|!|\||~)").groups(&[T::Operator, T::NameOperator]),
            rule(r"(\.|::)([a-zA-Z_]\w*[!?]?|[*%&^`~+\-/\[<>=])").groups(&[T::Operator, T::Name]),
            rule(r"[a-zA-Z_]\w*(?:[!?](?!=))?").token(T::Name),
            rule(r"(\[|\]\??|\*\*|<=>?|>=|<<?|>>?|=~|===|!~|&&?|\|\||\.{1,3})").token(T::Operator),
            rule(r"[-+/*%=<>&!^|~]=?").token(T::Operator),
            rule(r"[(){};,/?:\\]").token(T::Punctuation),
            rule(r"\s+").token(T::Text),
        ]),
        ("multiline-regex", &[
            include("string-intp"),
            rule(r"\\\\").token(T::LiteralStringRegex),
            rule(r"\\/").token(T::LiteralStringRegex),
            rule(r"[\\#]").token(T::LiteralStringRegex),
            rule(r"[^\\/#]+").token(T::LiteralStringRegex),
            rule(r"/[imsx]*").token(T::LiteralStringRegex).pop(1),
        ]),
        ("ab-string", &[
            rule(r"\\[\\<>]").token(T::LiteralStringOther),
            rule(r"<").token(T::LiteralStringOther).push(&[]),
            rule(r">").token(T::LiteralStringOther).pop(1),
            rule(r"[\\#<>]").token(T::LiteralStringOther),
            rule(r"[^\\#<>]+").token(T::LiteralStringOther),
        ]),
        ("pa-string", &[
            rule(r"\\[\\()]").token(T::LiteralStringOther),
            rule(r"\(").token(T::LiteralStringOther).push(&[]),
            rule(r"\)").token(T::LiteralStringOther).pop(1),
            rule(r"[\\#()]").token(T::LiteralStringOther),
            rule(r"[^\\#()]+").token(T::LiteralStringOther),
        ]),
        ("strings", &[
            rule(r"\:@{0,2}[a-zA-Z_]\w*[!?]?").token(T::LiteralStringSymbol),
            rule(r"\:@{0,2}(\[\]\?|<=>|===|\[\]=|>>|&&|\*\*|\[\]|\|\||>=|=~|!~|<<|<=|!=|==|<|/|=|-|\+|>|\*|&|%|\^|!|\||~)").token(T::LiteralStringSymbol),
            rule(r":'(\\\\|\\'|[^'])*'").token(T::LiteralStringSymbol),
            rule(r"'(\\\\|\\'|[^']|\\[^'\\]+)'").token(T::LiteralStringChar),
            rule(r#":""#).token(T::LiteralStringSymbol).push(&["simple-sym"]),
            rule(r"([a-zA-Z_]\w*)(:)(?!:)").groups(&[T::LiteralStringSymbol, T::Punctuation]),
            rule(r#"""#).token(T::LiteralStringDouble).push(&["simple-string"]),
            rule(r"(?<!\.)`").token(T::LiteralStringBacktick).push(&["simple-backtick"]),
            rule(r"%\{").token(T::LiteralStringOther).push(&["cb-intp-string"]),
            rule(r"%[wi]\{").token(T::LiteralStringOther).push(&["cb-string"]),
            rule(r"%r\{").token(T::LiteralStringRegex).push(&["cb-regex"]),
            rule(r"%\[").token(T::LiteralStringOther).push(&["sb-intp-string"]),
            rule(r"%[wi]\[").token(T::LiteralStringOther).push(&["sb-string"]),
            rule(r"%r\[").token(T::LiteralStringRegex).push(&["sb-regex"]),
            rule(r"%\(").token(T::LiteralStringOther).push(&["pa-intp-string"]),
            rule(r"%[wi]\(").token(T::LiteralStringOther).push(&["pa-string"]),
            rule(r"%r\(").token(T::LiteralStringRegex).push(&["pa-regex"]),
            rule(r"%<").token(T::LiteralStringOther).push(&["ab-intp-string"]),
            rule(r"%[wi]<").token(T::LiteralStringOther).push(&["ab-string"]),
            rule(r"%r<").token(T::LiteralStringRegex).push(&["ab-regex"]),
            rule(r"(%r([\W_]))((?:\\\2|(?!\2).)*)(\2[imsx]*)").token(T::LiteralString),
            rule(r"(%[wi]([\W_]))((?:\\\2|(?!\2).)*)(\2)").token(T::LiteralString),
            rule(r"(?<=[-+/*%=<>&!^|~,(])(\s*)(%([\t ])(?:(?:\\\3|(?!\3).)*)\3)").groups(&[T::Text, T::LiteralStringOther, T::NoHighlight]),
            rule(r"^(\s*)(%([\t ])(?:(?:\\\3|(?!\3).)*)\3)").groups(&[T::Text, T::LiteralStringOther, T::NoHighlight]),
            rule(r"(%([\[{(<]))((?:\\\2|(?!\2).)*)(\2)").token(T::LiteralString),
        ]),
        ("sb-string", &[
            rule(r"\\[\\\[\]]").token(T::LiteralStringOther),
            rule(r"\[").token(T::LiteralStringOther).push(&[]),
            rule(r"\]").token(T::LiteralStringOther).pop(1),
            rule(r"[\\#\[\]]").token(T::LiteralStringOther),
            rule(r"[^\\#\[\]]+").token(T::LiteralStringOther),
        ]),
        ("funcname", &[
            rule(r"(?:([a-zA-Z_]\w*)(\.))?([a-zA-Z_]\w*[!?]?|\*\*?|[-+]@?|[/%&|^`~]|\[\]=?|<<|>>|<=?>|>=?|===?)").groups(&[T::NameClass, T::Operator, T::NameFunction]).pop(1),
            rule("").pop(1),
        ]),
        ("simple-sym", &[
            include("string-escaped"),
            rule(r##"[^\\"#]+"##).token(T::LiteralStringSymbol),
            rule(r"[\\#]").token(T::LiteralStringSymbol),
            rule(r#"""#).token(T::LiteralStringSymbol).pop(1),
        ]),
    ],
};
