//! Chroma's `elixir.xml` lexer, converted to Rust (crate README, "Lexer and style files").

use crate::chroma::defs::prelude::*;

#[rustfmt::skip]
pub(crate) static LEXER: LexerDef = LexerDef {
    file: "elixir",
    config: ConfigDef {
        name: "Elixir",
        aliases: &["elixir", "ex", "exs"],
        filenames: &["*.ex", "*.eex", "*.exs"],
        mime_types: &["text/x-elixir"],
        ..ConfigDef::EMPTY
    },
    states: &[
        ("cb-intp", &[
            rule(r"[^#\}\\]+").token(T::LiteralStringOther),
            include("escapes"),
            rule(r"\\.").token(T::LiteralStringOther),
            rule(r"\}[a-zA-Z]*").token(T::LiteralStringOther).pop(1),
            include("interpol"),
        ]),
        ("triquot-end", &[
            rule(r"[a-zA-Z]+").token(T::LiteralStringOther).pop(1),
            rule("").pop(1),
        ]),
        ("apos-no-intp", &[
            rule(r"[^'\\]+").token(T::LiteralStringOther),
            rule(r"\\.").token(T::LiteralStringOther),
            rule(r"'[a-zA-Z]*").token(T::LiteralStringOther).pop(1),
        ]),
        ("slas-no-intp", &[
            rule(r"[^/\\]+").token(T::LiteralStringOther),
            rule(r"\\.").token(T::LiteralStringOther),
            rule(r"/[a-zA-Z]*").token(T::LiteralStringOther).pop(1),
        ]),
        ("pipe-no-intp", &[
            rule(r"[^\|\\]+").token(T::LiteralStringOther),
            rule(r"\\.").token(T::LiteralStringOther),
            rule(r"\|[a-zA-Z]*").token(T::LiteralStringOther).pop(1),
        ]),
        ("apos-intp", &[
            rule(r"[^#'\\]+").token(T::LiteralStringOther),
            include("escapes"),
            rule(r"\\.").token(T::LiteralStringOther),
            rule(r"'[a-zA-Z]*").token(T::LiteralStringOther).pop(1),
            include("interpol"),
        ]),
        ("cb-no-intp", &[
            rule(r"[^\}\\]+").token(T::LiteralStringOther),
            rule(r"\\.").token(T::LiteralStringOther),
            rule(r"\}[a-zA-Z]*").token(T::LiteralStringOther).pop(1),
        ]),
        ("heredoc_double", &[
            rule(r#"^\s*""""#).token(T::LiteralStringHeredoc).pop(1),
            include("heredoc_interpol"),
        ]),
        ("triapos-end", &[
            rule(r"[a-zA-Z]+").token(T::LiteralStringOther).pop(1),
            rule("").pop(1),
        ]),
        ("interpol_string", &[
            rule(r"\}").token(T::LiteralStringInterpol).pop(1),
            include("root"),
        ]),
        ("triquot-intp", &[
            rule(r#"^\s*""""#).token(T::LiteralStringHeredoc).pop(1),
            include("heredoc_interpol"),
        ]),
        ("interpol", &[
            rule(r"#\{").token(T::LiteralStringInterpol).push(&["interpol_string"]),
        ]),
        ("pa-no-intp", &[
            rule(r"[^\)\\]+").token(T::LiteralStringOther),
            rule(r"\\.").token(T::LiteralStringOther),
            rule(r"\)[a-zA-Z]*").token(T::LiteralStringOther).pop(1),
        ]),
        ("map_key", &[
            include("root"),
            rule(r":").token(T::Punctuation).push(&["map_val"]),
            rule(r"=>").token(T::Punctuation).push(&["map_val"]),
            rule(r"\}").token(T::Punctuation).pop(1),
        ]),
        ("pa-intp", &[
            rule(r"[^#\)\\]+").token(T::LiteralStringOther),
            include("escapes"),
            rule(r"\\.").token(T::LiteralStringOther),
            rule(r"\)[a-zA-Z]*").token(T::LiteralStringOther).pop(1),
            include("interpol"),
        ]),
        ("tuple", &[
            include("root"),
            rule(r"\}").token(T::Punctuation).pop(1),
        ]),
        ("root", &[
            rule(r"\s+").token(T::Text),
            rule(r"#.*$").token(T::CommentSingle),
            rule(r"(\?)(\\x\{)([\da-fA-F]+)(\})").groups(&[T::LiteralStringChar, T::LiteralStringEscape, T::LiteralNumberHex, T::LiteralStringEscape]),
            rule(r"(\?)(\\x[\da-fA-F]{1,2})").groups(&[T::LiteralStringChar, T::LiteralStringEscape]),
            rule(r"(\?)(\\[abdefnrstv])").groups(&[T::LiteralStringChar, T::LiteralStringEscape]),
            rule(r"\?\\?.").token(T::LiteralStringChar),
            rule(r":::").token(T::LiteralStringSymbol),
            rule(r"::").token(T::Operator),
            rule(r":(?:\.\.\.|<<>>|%\{\}|%|\{\})").token(T::LiteralStringSymbol),
            rule(r":(?:(?:\.\.\.|[a-z_]\w*[!?]?)|[A-Z]\w*(?:\.[A-Z]\w*)*|(?:\<\<\<|\>\>\>|\|\|\||\&\&\&|\^\^\^|\~\~\~|\=\=\=|\!\=\=|\~\>\>|\<\~\>|\|\~\>|\<\|\>|\=\=|\!\=|\<\=|\>\=|\&\&|\|\||\<\>|\+\+|\-\-|\|\>|\=\~|\-\>|\<\-|\||\.|\=|\~\>|\<\~|\<|\>|\+|\-|\*|\/|\!|\^|\&))").token(T::LiteralStringSymbol),
            rule(r#":""#).token(T::LiteralStringSymbol).push(&["string_double_atom"]),
            rule(r":'").token(T::LiteralStringSymbol).push(&["string_single_atom"]),
            rule(r"((?:\.\.\.|<<>>|%\{\}|%|\{\})|(?:(?:\.\.\.|[a-z_]\w*[!?]?)|[A-Z]\w*(?:\.[A-Z]\w*)*|(?:\<\<\<|\>\>\>|\|\|\||\&\&\&|\^\^\^|\~\~\~|\=\=\=|\!\=\=|\~\>\>|\<\~\>|\|\~\>|\<\|\>|\=\=|\!\=|\<\=|\>\=|\&\&|\|\||\<\>|\+\+|\-\-|\|\>|\=\~|\-\>|\<\-|\||\.|\=|\~\>|\<\~|\<|\>|\+|\-|\*|\/|\!|\^|\&)))(:)(?=\s|\n)").groups(&[T::LiteralStringSymbol, T::Punctuation]),
            rule(r"(fn|do|end|after|else|rescue|catch)\b").token(T::Keyword),
            rule(r"(not|and|or|when|in)\b").token(T::OperatorWord),
            rule(r"(case|cond|for|if|unless|try|receive|raise|quote|unquote|unquote_splicing|throw|super|while)\b").token(T::Keyword),
            rule(r"(def|defp|defmodule|defprotocol|defmacro|defmacrop|defdelegate|defexception|defstruct|defimpl|defcallback)\b").token(T::KeywordDeclaration),
            rule(r"(import|require|use|alias)\b").token(T::KeywordNamespace),
            rule(r"(nil|true|false)\b").token(T::NameConstant),
            rule(r"(_|__MODULE__|__DIR__|__ENV__|__CALLER__)\b").token(T::NamePseudo),
            rule(r"@(?:\.\.\.|[a-z_]\w*[!?]?)").token(T::NameAttribute),
            rule(r"(?:\.\.\.|[a-z_]\w*[!?]?)").token(T::Name),
            rule(r"(%?)([A-Z]\w*(?:\.[A-Z]\w*)*)").groups(&[T::Punctuation, T::NameClass]),
            rule(r"\<\<\<|\>\>\>|\|\|\||\&\&\&|\^\^\^|\~\~\~|\=\=\=|\!\=\=|\~\>\>|\<\~\>|\|\~\>|\<\|\>").token(T::Operator),
            rule(r"\=\=|\!\=|\<\=|\>\=|\&\&|\|\||\<\>|\+\+|\-\-|\|\>|\=\~|\-\>|\<\-|\||\.|\=|\~\>|\<\~").token(T::Operator),
            rule(r"\\\\|\<\<|\>\>|\=\>|\(|\)|\:|\;|\,|\[|\]").token(T::Punctuation),
            rule(r"&\d").token(T::NameEntity),
            rule(r"\<|\>|\+|\-|\*|\/|\!|\^|\&").token(T::Operator),
            rule(r"0b[01](_?[01])*").token(T::LiteralNumberBin),
            rule(r"0o[0-7](_?[0-7])*").token(T::LiteralNumberOct),
            rule(r"0x[\da-fA-F](_?[\dA-Fa-f])*").token(T::LiteralNumberHex),
            rule(r"\d(_?\d)*\.\d(_?\d)*([eE][-+]?\d(_?\d)*)?").token(T::LiteralNumberFloat),
            rule(r"\d(_?\d)*").token(T::LiteralNumberInteger),
            rule(r#""""\s*"#).token(T::LiteralStringHeredoc).push(&["heredoc_double"]),
            rule(r"'''\s*$").token(T::LiteralStringHeredoc).push(&["heredoc_single"]),
            rule(r#"""#).token(T::LiteralStringDouble).push(&["string_double"]),
            rule(r"'").token(T::LiteralStringSingle).push(&["string_single"]),
            include("sigils"),
            rule(r"%\{").token(T::Punctuation).push(&["map_key"]),
            rule(r"\{").token(T::Punctuation).push(&["tuple"]),
        ]),
        ("sigils", &[
            rule(r#"(~[a-z])(""")"#).groups(&[T::LiteralStringOther, T::LiteralStringHeredoc]).push(&["triquot-end", "triquot-intp"]),
            rule(r#"(~[A-Z])(""")"#).groups(&[T::LiteralStringOther, T::LiteralStringHeredoc]).push(&["triquot-end", "triquot-no-intp"]),
            rule(r"(~[a-z])(''')").groups(&[T::LiteralStringOther, T::LiteralStringHeredoc]).push(&["triapos-end", "triapos-intp"]),
            rule(r"(~[A-Z])(''')").groups(&[T::LiteralStringOther, T::LiteralStringHeredoc]).push(&["triapos-end", "triapos-no-intp"]),
            rule(r"~[a-z]\{").token(T::LiteralStringOther).push(&["cb-intp"]),
            rule(r"~[A-Z]\{").token(T::LiteralStringOther).push(&["cb-no-intp"]),
            rule(r"~[a-z]\[").token(T::LiteralStringOther).push(&["sb-intp"]),
            rule(r"~[A-Z]\[").token(T::LiteralStringOther).push(&["sb-no-intp"]),
            rule(r"~[a-z]\(").token(T::LiteralStringOther).push(&["pa-intp"]),
            rule(r"~[A-Z]\(").token(T::LiteralStringOther).push(&["pa-no-intp"]),
            rule(r"~[a-z]<").token(T::LiteralStringOther).push(&["ab-intp"]),
            rule(r"~[A-Z]<").token(T::LiteralStringOther).push(&["ab-no-intp"]),
            rule(r"~[a-z]/").token(T::LiteralStringOther).push(&["slas-intp"]),
            rule(r"~[A-Z]/").token(T::LiteralStringOther).push(&["slas-no-intp"]),
            rule(r"~[a-z]\|").token(T::LiteralStringOther).push(&["pipe-intp"]),
            rule(r"~[A-Z]\|").token(T::LiteralStringOther).push(&["pipe-no-intp"]),
            rule(r#"~[a-z]""#).token(T::LiteralStringOther).push(&["quot-intp"]),
            rule(r#"~[A-Z]""#).token(T::LiteralStringOther).push(&["quot-no-intp"]),
            rule(r"~[a-z]'").token(T::LiteralStringOther).push(&["apos-intp"]),
            rule(r"~[A-Z]'").token(T::LiteralStringOther).push(&["apos-no-intp"]),
        ]),
        ("triapos-intp", &[
            rule(r"^\s*'''").token(T::LiteralStringHeredoc).pop(1),
            include("heredoc_interpol"),
        ]),
        ("string_single_atom", &[
            rule(r"[^#'\\]+").token(T::LiteralStringSymbol),
            include("escapes"),
            rule(r"\\.").token(T::LiteralStringSymbol),
            rule(r"(')").groups(&[T::LiteralStringSymbol]).pop(1),
            include("interpol"),
        ]),
        ("quot-intp", &[
            rule(r#"[^#"\\]+"#).token(T::LiteralStringOther),
            include("escapes"),
            rule(r"\\.").token(T::LiteralStringOther),
            rule(r#""[a-zA-Z]*"#).token(T::LiteralStringOther).pop(1),
            include("interpol"),
        ]),
        ("sb-no-intp", &[
            rule(r"[^\]\\]+").token(T::LiteralStringOther),
            rule(r"\\.").token(T::LiteralStringOther),
            rule(r"\][a-zA-Z]*").token(T::LiteralStringOther).pop(1),
        ]),
        ("slas-intp", &[
            rule(r"[^#/\\]+").token(T::LiteralStringOther),
            include("escapes"),
            rule(r"\\.").token(T::LiteralStringOther),
            rule(r"/[a-zA-Z]*").token(T::LiteralStringOther).pop(1),
            include("interpol"),
        ]),
        ("sb-intp", &[
            rule(r"[^#\]\\]+").token(T::LiteralStringOther),
            include("escapes"),
            rule(r"\\.").token(T::LiteralStringOther),
            rule(r"\][a-zA-Z]*").token(T::LiteralStringOther).pop(1),
            include("interpol"),
        ]),
        ("heredoc_no_interpol", &[
            rule(r"[^\\\n]+").token(T::LiteralStringHeredoc),
            rule(r"\\.").token(T::LiteralStringHeredoc),
            rule(r"\n+").token(T::LiteralStringHeredoc),
        ]),
        ("pipe-intp", &[
            rule(r"[^#\|\\]+").token(T::LiteralStringOther),
            include("escapes"),
            rule(r"\\.").token(T::LiteralStringOther),
            rule(r"\|[a-zA-Z]*").token(T::LiteralStringOther).pop(1),
            include("interpol"),
        ]),
        ("map_val", &[
            include("root"),
            rule(r",").token(T::Punctuation).pop(1),
            rule(r"(?=\})").token(T::Punctuation).pop(1),
        ]),
        ("heredoc_single", &[
            rule(r"^\s*'''").token(T::LiteralStringHeredoc).pop(1),
            include("heredoc_interpol"),
        ]),
        ("heredoc_interpol", &[
            rule(r"[^#\\\n]+").token(T::LiteralStringHeredoc),
            include("escapes"),
            rule(r"\\.").token(T::LiteralStringHeredoc),
            rule(r"\n+").token(T::LiteralStringHeredoc),
            include("interpol"),
        ]),
        ("string_single", &[
            rule(r"[^#'\\]+").token(T::LiteralStringSingle),
            include("escapes"),
            rule(r"\\.").token(T::LiteralStringSingle),
            rule(r"(')").groups(&[T::LiteralStringSingle]).pop(1),
            include("interpol"),
        ]),
        ("string_double_atom", &[
            rule(r#"[^#"\\]+"#).token(T::LiteralStringSymbol),
            include("escapes"),
            rule(r"\\.").token(T::LiteralStringSymbol),
            rule(r#"(")"#).groups(&[T::LiteralStringSymbol]).pop(1),
            include("interpol"),
        ]),
        ("ab-no-intp", &[
            rule(r"[^>\\]+").token(T::LiteralStringOther),
            rule(r"\\.").token(T::LiteralStringOther),
            rule(r">[a-zA-Z]*").token(T::LiteralStringOther).pop(1),
        ]),
        ("ab-intp", &[
            rule(r"[^#>\\]+").token(T::LiteralStringOther),
            include("escapes"),
            rule(r"\\.").token(T::LiteralStringOther),
            rule(r">[a-zA-Z]*").token(T::LiteralStringOther).pop(1),
            include("interpol"),
        ]),
        ("quot-no-intp", &[
            rule(r#"[^"\\]+"#).token(T::LiteralStringOther),
            rule(r"\\.").token(T::LiteralStringOther),
            rule(r#""[a-zA-Z]*"#).token(T::LiteralStringOther).pop(1),
        ]),
        ("triapos-no-intp", &[
            rule(r"^\s*'''").token(T::LiteralStringHeredoc).pop(1),
            include("heredoc_no_interpol"),
        ]),
        ("string_double", &[
            rule(r#"[^#"\\]+"#).token(T::LiteralStringDouble),
            include("escapes"),
            rule(r"\\.").token(T::LiteralStringDouble),
            rule(r#"(")"#).groups(&[T::LiteralStringDouble]).pop(1),
            include("interpol"),
        ]),
        ("escapes", &[
            rule(r"(\\x\{)([\da-fA-F]+)(\})").groups(&[T::LiteralStringEscape, T::LiteralNumberHex, T::LiteralStringEscape]),
            rule(r"(\\x[\da-fA-F]{1,2})").token(T::LiteralStringEscape),
            rule(r"(\\[abdefnrstv])").token(T::LiteralStringEscape),
        ]),
        ("triquot-no-intp", &[
            rule(r#"^\s*""""#).token(T::LiteralStringHeredoc).pop(1),
            include("heredoc_no_interpol"),
        ]),
    ],
};
