//! Chroma's `factor.xml` lexer, converted to Rust (crate README, "Lexer and style files").

use crate::chroma::defs::prelude::*;

#[rustfmt::skip]
pub(crate) static LEXER: LexerDef = LexerDef {
    file: "factor",
    config: ConfigDef {
        name: "Factor",
        aliases: &["factor"],
        filenames: &["*.factor"],
        mime_types: &["text/x-factor"],
        ..ConfigDef::EMPTY
    },
    states: &[
        ("base", &[
            rule(r"\s+").token(T::Text),
            rule(r"((?:MACRO|MEMO|TYPED)?:[:]?)(\s+)(\S+)").groups(&[T::Keyword, T::Text, T::NameFunction]),
            rule(r"(M:[:]?)(\s+)(\S+)(\s+)(\S+)").groups(&[T::Keyword, T::Text, T::NameClass, T::Text, T::NameFunction]),
            rule(r"(C:)(\s+)(\S+)(\s+)(\S+)").groups(&[T::Keyword, T::Text, T::NameFunction, T::Text, T::NameClass]),
            rule(r"(GENERIC:)(\s+)(\S+)").groups(&[T::Keyword, T::Text, T::NameFunction]),
            rule(r"(HOOK:|GENERIC#)(\s+)(\S+)(\s+)(\S+)").groups(&[T::Keyword, T::Text, T::NameFunction, T::Text, T::NameFunction]),
            rule(r"\(\s").token(T::NameFunction).push(&["stackeffect"]),
            rule(r";\s").token(T::Keyword),
            rule(r"(USING:)(\s+)").groups(&[T::KeywordNamespace, T::Text]).push(&["vocabs"]),
            rule(r"(USE:|UNUSE:|IN:|QUALIFIED:)(\s+)(\S+)").groups(&[T::KeywordNamespace, T::Text, T::NameNamespace]),
            rule(r"(QUALIFIED-WITH:)(\s+)(\S+)(\s+)(\S+)").groups(&[T::KeywordNamespace, T::Text, T::NameNamespace, T::Text, T::NameNamespace]),
            rule(r"(FROM:|EXCLUDE:)(\s+)(\S+)(\s+=>\s)").groups(&[T::KeywordNamespace, T::Text, T::NameNamespace, T::Text]).push(&["words"]),
            rule(r"(RENAME:)(\s+)(\S+)(\s+)(\S+)(\s+=>\s+)(\S+)").groups(&[T::KeywordNamespace, T::Text, T::NameFunction, T::Text, T::NameNamespace, T::Text, T::NameFunction]),
            rule(r"(ALIAS:|TYPEDEF:)(\s+)(\S+)(\s+)(\S+)").groups(&[T::KeywordNamespace, T::Text, T::NameFunction, T::Text, T::NameFunction]),
            rule(r"(DEFER:|FORGET:|POSTPONE:)(\s+)(\S+)").groups(&[T::KeywordNamespace, T::Text, T::NameFunction]),
            rule(r"(TUPLE:|ERROR:)(\s+)(\S+)(\s+<\s+)(\S+)").groups(&[T::Keyword, T::Text, T::NameClass, T::Text, T::NameClass]).push(&["slots"]),
            rule(r"(TUPLE:|ERROR:|BUILTIN:)(\s+)(\S+)").groups(&[T::Keyword, T::Text, T::NameClass]).push(&["slots"]),
            rule(r"(MIXIN:|UNION:|INTERSECTION:)(\s+)(\S+)").groups(&[T::Keyword, T::Text, T::NameClass]),
            rule(r"(PREDICATE:)(\s+)(\S+)(\s+<\s+)(\S+)").groups(&[T::Keyword, T::Text, T::NameClass, T::Text, T::NameClass]),
            rule(r"(C:)(\s+)(\S+)(\s+)(\S+)").groups(&[T::Keyword, T::Text, T::NameFunction, T::Text, T::NameClass]),
            rule(r"(INSTANCE:)(\s+)(\S+)(\s+)(\S+)").groups(&[T::Keyword, T::Text, T::NameClass, T::Text, T::NameClass]),
            rule(r"(SLOT:)(\s+)(\S+)").groups(&[T::Keyword, T::Text, T::NameFunction]),
            rule(r"(SINGLETON:)(\s+)(\S+)").groups(&[T::Keyword, T::Text, T::NameClass]),
            rule(r"SINGLETONS:").token(T::Keyword).push(&["classes"]),
            rule(r"(CONSTANT:|SYMBOL:|MAIN:|HELP:)(\s+)(\S+)").groups(&[T::Keyword, T::Text, T::NameFunction]),
            rule(r"SYMBOLS:\s").token(T::Keyword).push(&["words"]),
            rule(r"SYNTAX:\s").token(T::Keyword),
            rule(r"ALIEN:\s").token(T::Keyword),
            rule(r"(STRUCT:)(\s+)(\S+)").groups(&[T::Keyword, T::Text, T::NameClass]),
            rule(r"(FUNCTION:)(\s+\S+\s+)(\S+)(\s+\(\s+[^)]+\)\s)").groups(&[T::KeywordNamespace, T::Text, T::NameFunction, T::Text]),
            rule(r"(FUNCTION-ALIAS:)(\s+)(\S+)(\s+\S+\s+)(\S+)(\s+\(\s+[^)]+\)\s)").groups(&[T::KeywordNamespace, T::Text, T::NameFunction, T::Text, T::NameFunction, T::Text]),
            rule(r"(?:<PRIVATE|PRIVATE>)\s").token(T::KeywordNamespace),
            rule(r#""""\s+(?:.|\n)*?\s+""""#).token(T::LiteralString),
            rule(r#""(?:\\\\|\\"|[^"])*""#).token(T::LiteralString),
            rule(r#"\S+"\s+(?:\\\\|\\"|[^"])*""#).token(T::LiteralString),
            rule(r"CHAR:\s+(?:\\[\\abfnrstv]|[^\\]\S*)\s").token(T::LiteralStringChar),
            rule(r"!\s+.*$").token(T::Comment),
            rule(r"#!\s+.*$").token(T::Comment),
            rule(r"/\*\s+(?:.|\n)*?\s\*/\s").token(T::Comment),
            rule(r"[tf]\s").token(T::NameConstant),
            rule(r"[\\$]\s+\S+").token(T::NameConstant),
            rule(r"M\\\s+\S+\s+\S+").token(T::NameConstant),
            rule(r"[+-]?(?:[\d,]*\d)?\.(?:\d([\d,]*\d)?)?(?:[eE][+-]?\d+)?\s").token(T::LiteralNumber),
            rule(r"[+-]?\d(?:[\d,]*\d)?(?:[eE][+-]?\d+)?\s").token(T::LiteralNumber),
            rule(r"0x[a-fA-F\d](?:[a-fA-F\d,]*[a-fA-F\d])?(?:p\d([\d,]*\d)?)?\s").token(T::LiteralNumber),
            rule(r"NAN:\s+[a-fA-F\d](?:[a-fA-F\d,]*[a-fA-F\d])?(?:p\d([\d,]*\d)?)?\s").token(T::LiteralNumber),
            rule(r"0b[01]+\s").token(T::LiteralNumberBin),
            rule(r"0o[0-7]+\s").token(T::LiteralNumberOct),
            rule(r"(?:\d([\d,]*\d)?)?\+\d(?:[\d,]*\d)?/\d(?:[\d,]*\d)?\s").token(T::LiteralNumber),
            rule(r"(?:\-\d([\d,]*\d)?)?\-\d(?:[\d,]*\d)?/\d(?:[\d,]*\d)?\s").token(T::LiteralNumber),
            rule(r"(?:deprecated|final|foldable|flushable|inline|recursive)\s").token(T::Keyword),
            rule(r"(identity-hashcode|callstack>array|identity-tuple\?|identity-tuple|retainstack|callstack\?|tri-curry\*|tri-curry@|tri-curry|<wrapper>|datastack|bi-curry@|bi-curry\*|hashcode\*|callstack|\?execute|hashcode|boolean\?|compose\?|>boolean|wrapper\?|bi-curry|unless\*|boolean|assert\?|\(clone\)|either\?|prepose|assert=|execute|wrapper|compose|3curry|assert|2curry|curry\?|object|equal\?|tuple\?|unless|build|3drop|same\?|2tri\*|2tri@|both\?|3keep|4drop|throw|2over|swapd|clear|2keep|2drop|until|curry|4keep|clone|while|tuple|when\*|-rot|tri@|dupd|drop|tri\*|call|when|with|4dup|4dip|3tri|3dup|3dip|2tri|keep|loop|most|2nip|swap|2dup|null|2dip|2bi\*|2bi@|pick|over|and|rot|not|nip|new|if\*|tri|2bi|boa|eq\?|dup|3bi|dip|die|bi\*|bi@|\?if|xor|bi|do|if|or|\?|=)\s").token(T::NameBuiltin),
            rule(r"(assoc-clone-like|assoc-filter-as|assoc-partition|assoc-intersect|assoc-hashcode|assoc-combine|assoc-filter!|assoc-subset\?|assoc-union!|maybe-set-at|extract-keys|assoc-map-as|assoc-differ|assoc-refine|assoc-empty\?|assoc-filter|assoc-diff!|sift-values|assoc-union|assoc-stack|clear-assoc|assoc-all\?|delete-at\*|assoc-find|substitute|assoc-each|assoc-size|assoc-diff|assoc-any\?|assoc-like|rename-at|sift-keys|new-assoc|map>assoc|value-at\*|assoc-map|delete-at|change-at|assoc>map|value-at|push-at|assoc=|values|set-at|<enum>|inc-at|2cache|value\?|assoc\?|>alist|cache|enum\?|assoc|unzip|key\?|enum|keys|\?at|\?of|zip|at\+|at\*|at|of)\s").token(T::NameBuiltin),
            rule(r"(shallow-spread>quot|recursive-hashcode|linear-case-quot|deep-spread>quot|to-fixed-point|execute-effect|wrong-values\?|4cleave>quot|2cleave>quot|wrong-values|3cleave>quot|cleave>quot|call-effect|alist>quot|case>quot|case-find|cond>quot|no-case\?|no-cond\?|no-case|no-cond|4cleave|3cleave|2cleave|cleave|spread|cond|case)\s").token(T::NameBuiltin),
            rule(r"(log2-expects-positive\?|integer>fixnum-strict|log2-expects-positive|out-of-fixnum-range\?|out-of-fixnum-range|find-last-integer|next-power-of-2|\(all-integers\?\)|integer>fixnum|\(find-integer\)|\(each-integer\)|imaginary-part|fp-nan-payload|all-integers\?|find-integer|each-integer|fp-infinity\?|fp-special\?|fp-bitwise=|bits>double|double>bits|power-of-2\?|unless-zero|denominator|next-float|bits>float|float>bits|prev-float|unordered\?|real-part|when-zero|numerator|rational\?|>integer|rational|complex\?|<fp-nan>|fp-qnan\?|fp-snan\?|integer\?|number=|bignum\?|integer|>fixnum|fp-sign|fp-nan\?|fixnum\?|number\?|complex|if-zero|>bignum|bignum|number|fixnum|float\?|bitxor|ratio\?|bitnot|bitand|>float|real\?|bitor|zero\?|even\?|times|shift|float|recip|align|ratio|neg\?|real|log2|bit\?|odd\?|/mod|\?1\+|mod|rem|neg|sgn|u<=|u>=|abs|u>|2/|2\^|/i|/f|sq|<=|u<|>=|-|\+|<|\*|/|>)\s").token(T::NameBuiltin),
            rule(r"(non-negative-integer-expected\?|non-negative-integer-expected|immutable-sequence\?|immutable-sequence|virtual-sequence\?|sequence-hashcode|cartesian-product|check-slice-error|unclip-last-slice|assert-sequence=|assert-sequence\?|virtual-exemplar|virtual-sequence|assert-sequence|trim-head-slice|last-index-from|find-index-from|trim-tail-slice|find-last-from|cartesian-each|collapse-slice|but-last-slice|map-find-last|cartesian-map|collector-for|bounds-error\?|accumulate-as|replace-slice|bounds-check\?|binary-reduce|new-resizable|unless-empty|delete-slice|replicate-as|map-integers|selector-for|bounds-check|reduce-index|bounds-error|unclip-slice|new-sequence|<repetition>|slice-error\?|slice-error|unclip-last|drop-prefix|supremum-by|push-either|2map-reduce|accumulate!|tail-slice\*|repetition\?|check-slice|iota-tuple\?|remove-nth!|sum-lengths|head-slice\*|find-index|clone-like|delete-all|change-nth|prepend-as|member-eq\?|max-length|each-index|map-reduce|iota-tuple|produce-as|snip-slice|accumulate|remove-eq!|last-index|min-length|remove-nth|<reversed>|repetition|tail-slice|3append-as|when-empty|interleave|insert-nth|infimum-by|index-from|set-second|immutable\?|rest-slice|set-fourth|head-slice|trim-slice|set-length|set-third|concat-as|immutable|trim-tail|cut-slice|collector|set-first|sequence\?|sequence=|midpoint@|trim-head|each-from|reversed\?|map-index|partition|find-last|2selector|2sequence|replicate|find-from|filter-as|3sequence|append-as|4sequence|remove-eq|1sequence|virtual@|push-all|lengthen|shorter\?|map-find|reverse!|reversed|exchange|pad-tail|pad-head|surround|selector|shortest|sequence|set-last|mismatch|supremum|new-like|if-empty|but-last|\?set-nth|filter!|harvest|member\?|map-sum|indices|padding|set-nth|2map-as|shorter|shorten|prepend|infimum|2reduce|append!|product|subseq\?|longest|longer\?|push-if|suffix!|reverse|join-as|remove!|3append|\?second|3map-as|<slice>|produce|length|\?first|start\*|longer|remove|subseq|unclip|first2|first3|reduce|second|follow|filter|slice\?|map-as|empty\?|fourth|suffix|halves|concat|first4|prefix|append|index|short|2all\?|count|2each|third|tail\*|slice|first|tail\?|head\*|3each|head\?|start|\?last|join|iota|last|like|snip|map!|head|glue|move|tail|2map|find|sift|flip|nths|trim|each|cut\*|3map|pop\*|copy|any\?|all\?|\?nth|push|rest|sum|nth|pop|map|cut)\s").token(T::NameBuiltin),
            rule(r"(init-namespaces|with-variables|with-variable|set-namestack|change-global|with-global|initialize|get-global|set-global|with-scope|make-assoc|is-global|namespace|namestack|counter|change|toggle|global|set|get|dec|off|inc|on|\+@)\s").token(T::NameBuiltin),
            rule(r"(resize-array|<array>|1array|2array|3array|4array|>array|array\?|array|pair\?|pair)\s").token(T::NameBuiltin),
            rule(r"(\(stream-contents-by-length-or-block\)|with-input-output\+error-streams\*|with-input-output\+error-streams|\(stream-contents-by-element\)|\(stream-contents-by-length\)|stream-read-partial-unsafe|\(stream-contents-by-block\)|with-output\+error-stream\*|\(each-stream-block-slice\)|stream-read-partial-into|with-output\+error-stream|each-stream-block-slice|invalid-read-buffer\?|stream-read-partial|stream-element-type|\(each-stream-block\)|with-output-stream\*|invalid-read-buffer|with-output-stream|with-input-stream\*|stream-read-unsafe|with-error-stream\*|with-error-stream|stream-read-until|each-stream-block|with-output>error|with-input-stream|with-error>output|read-partial-into|stream-contents\*|each-stream-line|stream-seekable\?|stream-read-into|each-block-slice|each-block-size|stream-contents|bad-seek-type\?|seek-absolute\?|output-stream\?|seek-relative\?|stream-write1|with-streams\*|output-stream|stream-length|bad-seek-type|seek-absolute|input-stream\?|stream-readln|seek-relative|with-streams|read-partial|stream-copy\*|stream-flush|stream-read1|stream-lines|stream-write|stream-print|error-stream|input-stream|stream-tell|\+character\+|stream-copy|each-morsel|seek-output|stream-read|tell-output|stream-seek|read-until|seek-input|each-block|tell-input|each-line|seek-end\?|read-into|stream-nl|stream-bl|contents|seek-end|write1|\+byte\+|readln|write|read1|print|flush|lines|read|nl|bl)\s").token(T::NameBuiltin),
            rule(r"(resize-string|<string>|1string|>string|string\?|string)\s").token(T::NameBuiltin),
            rule(r"(<vector>|1vector|>vector|vector\?|vector|\?push)\s").token(T::NameBuiltin),
            rule(r"(current-continuation|return-continuation|callback-error-hook|error-continuation|attempt-all-error\?|thread-error-hook|attempt-all-error|rethrow-restarts|continue-restart|compute-restarts|error-in-thread|throw-continue|throw-restarts|with-datastack|<continuation>|original-error|ignore-errors|continue-with|continuation\?|in-callback\?|continuation|error-thread|attempt-all|<condition>|with-return|condition\?|<restart>|condition|continue|restart\?|restarts|rethrow|callcc0|recover|restart|cleanup|callcc1|return|error|ifcc)\s").token(T::NameBuiltin),
            rule(r"\S+").token(T::Text),
        ]),
        ("stackeffect", &[
            rule(r"\s+").token(T::Text),
            rule(r"\(\s+").token(T::NameFunction).push(&["stackeffect"]),
            rule(r"\)\s").token(T::NameFunction).pop(1),
            rule(r"--\s").token(T::NameFunction),
            rule(r"\S+").token(T::NameVariable),
        ]),
        ("slots", &[
            rule(r"\s+").token(T::Text),
            rule(r";\s").token(T::Keyword).pop(1),
            rule(r"(\{\s+)(\S+)(\s+[^}]+\s+\}\s)").groups(&[T::Text, T::NameVariable, T::Text]),
            rule(r"\S+").token(T::NameVariable),
        ]),
        ("vocabs", &[
            rule(r"\s+").token(T::Text),
            rule(r";\s").token(T::Keyword).pop(1),
            rule(r"\S+").token(T::NameNamespace),
        ]),
        ("classes", &[
            rule(r"\s+").token(T::Text),
            rule(r";\s").token(T::Keyword).pop(1),
            rule(r"\S+").token(T::NameClass),
        ]),
        ("words", &[
            rule(r"\s+").token(T::Text),
            rule(r";\s").token(T::Keyword).pop(1),
            rule(r"\S+").token(T::NameFunction),
        ]),
        ("root", &[
            rule(r"#!.*$").token(T::CommentPreproc),
            rule("").push(&["base"]),
        ]),
    ],
};
