//! Chroma's `haskell.xml` lexer, converted to Rust (crate README, "Lexer and style files").

use crate::chroma::defs::prelude::*;

#[rustfmt::skip]
pub(crate) static LEXER: LexerDef = LexerDef {
    file: "haskell",
    config: ConfigDef {
        name: "Haskell",
        aliases: &["haskell", "hs"],
        filenames: &["*.hs"],
        mime_types: &["text/x-haskell"],
        ..ConfigDef::EMPTY
    },
    states: &[
        ("escape", &[
            rule(r#"[abfnrtv"\'&\\]"#).token(T::LiteralStringEscape).pop(1),
            rule(r"\^[][\p{Lu}@^_]").token(T::LiteralStringEscape).pop(1),
            rule(r"NUL|SOH|[SE]TX|EOT|ENQ|ACK|BEL|BS|HT|LF|VT|FF|CR|S[OI]|DLE|DC[1-4]|NAK|SYN|ETB|CAN|EM|SUB|ESC|[FGRU]S|SP|DEL").token(T::LiteralStringEscape).pop(1),
            rule(r"o[0-7]+").token(T::LiteralStringEscape).pop(1),
            rule(r"x[\da-fA-F]+").token(T::LiteralStringEscape).pop(1),
            rule(r"\d+").token(T::LiteralStringEscape).pop(1),
            rule(r"\s+\\").token(T::LiteralStringEscape).pop(1),
        ]),
        ("root", &[
            rule(r"\s+").token(T::Text),
            rule(r"--(?![!#$%&*+./<=>?@^|_~:\\]).*?$").token(T::CommentSingle),
            rule(r"\{-").token(T::CommentMultiline).push(&["comment"]),
            rule(r"\bimport\b").token(T::KeywordReserved).push(&["import"]),
            rule(r"\bmodule\b").token(T::KeywordReserved).push(&["module"]),
            rule(r"\berror\b").token(T::NameException),
            rule(r"\b(case|class|data|default|deriving|do|else|family|if|in|infix[lr]?|instance|let|newtype|of|then|type|where|_)(?!\')\b").token(T::KeywordReserved),
            rule(r"'[^\\]'").token(T::LiteralStringChar),
            rule(r"^[_\p{Ll}][\w\']*").token(T::NameFunction),
            rule(r"'?[_\p{Ll}][\w']*").token(T::Name),
            rule(r"('')?[\p{Lu}][\w\']*").token(T::KeywordType),
            rule(r"(')[\p{Lu}][\w\']*").token(T::KeywordType),
            rule(r"(')\[[^\]]*\]").token(T::KeywordType),
            rule(r"(')\([^)]*\)").token(T::KeywordType),
            rule(r"\\(?![:!#$%&*+.\\/<=>?@^|~-]+)").token(T::NameFunction),
            rule(r"(<-|::|->|=>|=|'([:!#$%&*+.\\/<=>?@^|~-]+))(?![:!#$%&*+.\\/<=>?@^|~-]+)").token(T::OperatorWord),
            rule(r":[:!#$%&*+.\\/<=>?@^|~-]*").token(T::KeywordType),
            rule(r"[:!#$%&*+.\\/<=>?@^|~-]+").token(T::Operator),
            rule(r"\d+_*[eE][+-]?\d+").token(T::LiteralNumberFloat),
            rule(r"\d+(_+[\d]+)*\.\d+(_+[\d]+)*([eE][+-]?\d+)?").token(T::LiteralNumberFloat),
            rule(r"0[oO](_*[0-7])+").token(T::LiteralNumberOct),
            rule(r"0[xX](_*[\da-fA-F])+").token(T::LiteralNumberHex),
            rule(r"0[bB](_*[01])+").token(T::LiteralNumberBin),
            rule(r"\d+(_*[\d])*").token(T::LiteralNumberInteger),
            rule(r"'").token(T::LiteralStringChar).push(&["character"]),
            rule(r#"""#).token(T::LiteralString).push(&["string"]),
            rule(r"\[\]").token(T::KeywordType),
            rule(r"\(\)").token(T::NameBuiltin),
            rule(r"[][(),;`{}]").token(T::Punctuation),
        ]),
        ("import", &[
            rule(r"\s+").token(T::Text),
            rule(r#"""#).token(T::LiteralString).push(&["string"]),
            rule(r"\)").token(T::Punctuation).pop(1),
            rule(r"qualified\b").token(T::Keyword),
            rule(r"([\p{Lu}][\w.]*)(\s+)(as)(\s+)([\p{Lu}][\w.]*)").groups(&[T::NameNamespace, T::Text, T::Keyword, T::Text, T::Name]).pop(1),
            rule(r"([\p{Lu}][\w.]*)(\s+)(hiding)(\s+)(\()").groups(&[T::NameNamespace, T::Text, T::Keyword, T::Text, T::Punctuation]).push(&["funclist"]),
            rule(r"([\p{Lu}][\w.]*)(\s+)(\()").groups(&[T::NameNamespace, T::Text, T::Punctuation]).push(&["funclist"]),
            rule(r"[\w.]+").token(T::NameNamespace).pop(1),
        ]),
        ("module", &[
            rule(r"\s+").token(T::Text),
            rule(r"([\p{Lu}][\w.]*)(\s+)(\()").groups(&[T::NameNamespace, T::Text, T::Punctuation]).push(&["funclist"]),
            rule(r"[\p{Lu}][\w.]*").token(T::NameNamespace).pop(1),
        ]),
        ("funclist", &[
            rule(r"\s+").token(T::Text),
            rule(r"[\p{Lu}]\w*").token(T::KeywordType),
            rule(r"(_[\w\']+|[\p{Ll}][\w\']*)").token(T::NameFunction),
            rule(r"--(?![!#$%&*+./<=>?@^|_~:\\]).*?$").token(T::CommentSingle),
            rule(r"\{-").token(T::CommentMultiline).push(&["comment"]),
            rule(r",").token(T::Punctuation),
            rule(r"[:!#$%&*+.\\/<=>?@^|~-]+").token(T::Operator),
            rule(r"\(").token(T::Punctuation).push(&["funclist", "funclist"]),
            rule(r"\)").token(T::Punctuation).pop(2),
        ]),
        ("comment", &[
            rule(r"[^-{}]+").token(T::CommentMultiline),
            rule(r"\{-").token(T::CommentMultiline).push(&[]),
            rule(r"-\}").token(T::CommentMultiline).pop(1),
            rule(r"[-{}]").token(T::CommentMultiline),
        ]),
        ("character", &[
            rule(r"[^\\']'").token(T::LiteralStringChar).pop(1),
            rule(r"\\").token(T::LiteralStringEscape).push(&["escape"]),
            rule(r"'").token(T::LiteralStringChar).pop(1),
        ]),
        ("string", &[
            rule(r#"[^\\"]+"#).token(T::LiteralString),
            rule(r"\\").token(T::LiteralStringEscape).push(&["escape"]),
            rule(r#"""#).token(T::LiteralString).pop(1),
        ]),
    ],
};
