//! Chroma's `objective-c.xml` lexer, converted to Rust (crate README, "Lexer and style files").

use crate::chroma::defs::prelude::*;

#[rustfmt::skip]
pub(crate) static LEXER: LexerDef = LexerDef {
    file: "objective-c",
    config: ConfigDef {
        name: "Objective-C",
        aliases: &["objective-c", "objectivec", "obj-c", "objc"],
        filenames: &["*.m", "*.h"],
        mime_types: &["text/x-objective-c"],
        ..ConfigDef::EMPTY
    },
    states: &[
        ("macro", &[
            rule(r"(include)(\s*(?:/[*].*?[*]/\s*)?)([^\n]+)").groups(&[T::CommentPreproc, T::Text, T::CommentPreprocFile]),
            rule(r"[^/\n]+").token(T::CommentPreproc),
            rule(r"/[*](.|\n)*?[*]/").token(T::CommentMultiline),
            rule(r"//.*?\n").token(T::CommentSingle).pop(1),
            rule(r"/").token(T::CommentPreproc),
            rule(r"(?<=\\)\n").token(T::CommentPreproc),
            rule(r"\n").token(T::CommentPreproc).pop(1),
        ]),
        ("literal_number", &[
            rule(r"\(").token(T::Punctuation).push(&["literal_number_inner"]),
            rule(r"\)").token(T::Literal).pop(1),
            include("statement"),
        ]),
        ("if0", &[
            rule(r"^\s*#if.*?(?<!\\)\n").token(T::CommentPreproc).push(&[]),
            rule(r"^\s*#el(?:se|if).*\n").token(T::CommentPreproc).pop(1),
            rule(r"^\s*#endif.*?(?<!\\)\n").token(T::CommentPreproc).pop(1),
            rule(r".*?\n").token(T::Comment),
        ]),
        ("root", &[
            rule(r"^([-+])(\s*)(\(.*?\))?(\s*)([a-zA-Z$_][\w$]*:?)").bygroups(&[E::Token(T::Punctuation), E::Token(T::Text), E::UsingSelf("root"), E::Token(T::Text), E::Token(T::NameFunction)]).push(&["method"]),
            include("whitespace"),
            rule(r"((?:[\w*\s])+?(?:\s|[*]))([a-zA-Z_]\w*)(\s*\([^;]*?\))([^;{]*)(\{)").bygroups(&[E::UsingSelf("root"), E::Token(T::NameFunction), E::UsingSelf("root"), E::UsingSelf("root"), E::Token(T::Punctuation)]).push(&["function"]),
            rule(r"((?:[\w*\s])+?(?:\s|[*]))([a-zA-Z_]\w*)(\s*\([^;]*?\))([^;]*)(;)").bygroups(&[E::UsingSelf("root"), E::Token(T::NameFunction), E::UsingSelf("root"), E::UsingSelf("root"), E::Token(T::Punctuation)]),
            rule("").push(&["statement"]),
        ]),
        ("statements", &[
            rule(r#"@""#).token(T::LiteralString).push(&["string"]),
            rule(r"@(YES|NO)").token(T::LiteralNumber),
            rule(r"@'(\\.|\\[0-7]{1,3}|\\x[a-fA-F0-9]{1,2}|[^\\\'\n])'").token(T::LiteralStringChar),
            rule(r"@(\d+\.\d*|\.\d+|\d+)[eE][+-]?\d+[lL]?").token(T::LiteralNumberFloat),
            rule(r"@(\d+\.\d*|\.\d+|\d+[fF])[fF]?").token(T::LiteralNumberFloat),
            rule(r"@0x[0-9a-fA-F]+[Ll]?").token(T::LiteralNumberHex),
            rule(r"@0[0-7]+[Ll]?").token(T::LiteralNumberOct),
            rule(r"@\d+[Ll]?").token(T::LiteralNumberInteger),
            rule(r"@\(").token(T::Literal).push(&["literal_number"]),
            rule(r"@\[").token(T::Literal).push(&["literal_array"]),
            rule(r"@\{").token(T::Literal).push(&["literal_dictionary"]),
            rule(r"(unsafe_unretained|__bridge_transfer|@autoreleasepool|__autoreleasing|@synchronized|@synthesize|@protected|@selector|@required|@optional|readwrite|@property|nonatomic|@finally|__bridge|@dynamic|__strong|readonly|@private|__block|@public|@encode|release|assign|retain|atomic|@throw|@catch|__weak|setter|getter|typeof|strong|inout|class|@try|@end|weak|copy|out|in)\b").token(T::Keyword),
            rule(r"(instancetype|IBOutlet|IBAction|unichar|Class|BOOL|IMP|SEL|id)\b").token(T::KeywordType),
            rule(r"@(true|false|YES|NO)\n").token(T::NameBuiltin),
            rule(r"(YES|NO|nil|self|super)\b").token(T::NameBuiltin),
            rule(r"(Boolean|UInt8|SInt8|UInt16|SInt16|UInt32|SInt32)\b").token(T::KeywordType),
            rule(r"(TRUE|FALSE)\b").token(T::NameBuiltin),
            rule(r"(@interface|@implementation)(\s+)").groups(&[T::Keyword, T::Text]).push(&["#pop", "oc_classname"]),
            rule(r"(@class|@protocol)(\s+)").groups(&[T::Keyword, T::Text]).push(&["#pop", "oc_forward_classname"]),
            rule(r"@").token(T::Punctuation),
            rule(r#"(L?)(")"#).groups(&[T::LiteralStringAffix, T::LiteralString]).push(&["string"]),
            rule(r"(L?)(')(\\.|\\[0-7]{1,3}|\\x[a-fA-F0-9]{1,2}|[^\\\'\n])(')").groups(&[T::LiteralStringAffix, T::LiteralStringChar, T::LiteralStringChar, T::LiteralStringChar]),
            rule(r"(\d+\.\d*|\.\d+|\d+)[eE][+-]?\d+[LlUu]*").token(T::LiteralNumberFloat),
            rule(r"(\d+\.\d*|\.\d+|\d+[fF])[fF]?").token(T::LiteralNumberFloat),
            rule(r"0x[0-9a-fA-F]+[LlUu]*").token(T::LiteralNumberHex),
            rule(r"0[0-7]+[LlUu]*").token(T::LiteralNumberOct),
            rule(r"\d+[LlUu]*").token(T::LiteralNumberInteger),
            rule(r"\*/").token(T::Error),
            rule(r"[~!%^&*+=|?:<>/-]").token(T::Operator),
            rule(r"[()\[\],.]").token(T::Punctuation),
            rule(r"(restricted|volatile|continue|register|default|typedef|struct|extern|switch|sizeof|static|return|union|while|const|break|goto|enum|else|case|auto|for|asm|if|do)\b").token(T::Keyword),
            rule(r"(bool|int|long|float|short|double|char|unsigned|signed|void)\b").token(T::KeywordType),
            rule(r"(typename|__inline|restrict|_inline|thread|inline|naked)\b").token(T::KeywordReserved),
            rule(r"(__m(128i|128d|128|64))\b").token(T::KeywordReserved),
            rule(r"__(forceinline|identifier|unaligned|declspec|fastcall|finally|stdcall|wchar_t|assume|except|int32|cdecl|int16|leave|based|raise|int64|noop|int8|w64|try|asm)\b").token(T::KeywordReserved),
            rule(r"(true|false|NULL)\b").token(T::NameBuiltin),
            rule(r"([a-zA-Z_]\w*)(\s*)(:)(?!:)").groups(&[T::NameLabel, T::Text, T::Punctuation]),
            rule(r"[a-zA-Z_]\w*").token(T::Name),
        ]),
        ("method", &[
            include("whitespace"),
            rule(r",").token(T::Punctuation),
            rule(r"\.\.\.").token(T::Punctuation),
            rule(r"(\(.*?\))(\s*)([a-zA-Z$_][\w$]*)").bygroups(&[E::UsingSelf("root"), E::Token(T::Text), E::Token(T::NameVariable)]),
            rule(r"[a-zA-Z$_][\w$]*:").token(T::NameFunction),
            rule(r";").token(T::Punctuation).pop(1),
            rule(r"\{").token(T::Punctuation).push(&["function"]),
            rule("").pop(1),
        ]),
        ("literal_array", &[
            rule(r"\[").token(T::Punctuation).push(&["literal_array_inner"]),
            rule(r"\]").token(T::Literal).pop(1),
            include("statement"),
        ]),
        ("oc_classname", &[
            rule(r"([a-zA-Z$_][\w$]*)(\s*:\s*)([a-zA-Z$_][\w$]*)?(\s*)(\{)").groups(&[T::NameClass, T::Text, T::NameClass, T::Text, T::Punctuation]).push(&["#pop", "oc_ivars"]),
            rule(r"([a-zA-Z$_][\w$]*)(\s*:\s*)([a-zA-Z$_][\w$]*)?").groups(&[T::NameClass, T::Text, T::NameClass]).pop(1),
            rule(r"([a-zA-Z$_][\w$]*)(\s*)(\([a-zA-Z$_][\w$]*\))(\s*)(\{)").groups(&[T::NameClass, T::Text, T::NameLabel, T::Text, T::Punctuation]).push(&["#pop", "oc_ivars"]),
            rule(r"([a-zA-Z$_][\w$]*)(\s*)(\([a-zA-Z$_][\w$]*\))").groups(&[T::NameClass, T::Text, T::NameLabel]).pop(1),
            rule(r"([a-zA-Z$_][\w$]*)(\s*)(\{)").groups(&[T::NameClass, T::Text, T::Punctuation]).push(&["#pop", "oc_ivars"]),
            rule(r"([a-zA-Z$_][\w$]*)").token(T::NameClass).pop(1),
        ]),
        ("function", &[
            include("whitespace"),
            include("statements"),
            rule(r";").token(T::Punctuation),
            rule(r"\{").token(T::Punctuation).push(&[]),
            rule(r"\}").token(T::Punctuation).pop(1),
        ]),
        ("whitespace", &[
            rule(r"^#if\s+0").token(T::CommentPreproc).push(&["if0"]),
            rule(r"^#").token(T::CommentPreproc).push(&["macro"]),
            rule(r"^(\s*(?:/[*].*?[*]/\s*)?)(#if\s+0)").bygroups(&[E::UsingSelf("root"), E::Token(T::CommentPreproc)]).push(&["if0"]),
            rule(r"^(\s*(?:/[*].*?[*]/\s*)?)(#)").bygroups(&[E::UsingSelf("root"), E::Token(T::CommentPreproc)]).push(&["macro"]),
            rule(r"\n").token(T::Text),
            rule(r"\s+").token(T::Text),
            rule(r"\\\n").token(T::Text),
            rule(r"//(\n|[\w\W]*?[^\\]\n)").token(T::CommentSingle),
            rule(r"/(\\\n)?[*][\w\W]*?[*](\\\n)?/").token(T::CommentMultiline),
            rule(r"/(\\\n)?[*][\w\W]*").token(T::CommentMultiline),
        ]),
        ("literal_number_inner", &[
            rule(r"\(").token(T::Punctuation).push(&[]),
            rule(r"\)").token(T::Punctuation).pop(1),
            include("statement"),
        ]),
        ("statement", &[
            include("whitespace"),
            include("statements"),
            rule(r"[{}]").token(T::Punctuation),
            rule(r";").token(T::Punctuation).pop(1),
        ]),
        ("oc_forward_classname", &[
            rule(r"([a-zA-Z$_][\w$]*)(\s*,\s*)").groups(&[T::NameClass, T::Text]).push(&["oc_forward_classname"]),
            rule(r"([a-zA-Z$_][\w$]*)(\s*;?)").groups(&[T::NameClass, T::Text]).pop(1),
        ]),
        ("literal_array_inner", &[
            rule(r"\[").token(T::Punctuation).push(&[]),
            rule(r"\]").token(T::Punctuation).pop(1),
            include("statement"),
        ]),
        ("literal_dictionary", &[
            rule(r"\}").token(T::Literal).pop(1),
            include("statement"),
        ]),
        ("oc_ivars", &[
            include("whitespace"),
            include("statements"),
            rule(r";").token(T::Punctuation),
            rule(r"\{").token(T::Punctuation).push(&[]),
            rule(r"\}").token(T::Punctuation).pop(1),
        ]),
        ("string", &[
            rule(r#"""#).token(T::LiteralString).pop(1),
            rule(r#"\\([\\abfnrtv"\']|x[a-fA-F0-9]{2,4}|u[a-fA-F0-9]{4}|U[a-fA-F0-9]{8}|[0-7]{1,3})"#).token(T::LiteralStringEscape),
            rule(r#"[^\\"\n]+"#).token(T::LiteralString),
            rule(r"\\\n").token(T::LiteralString),
            rule(r"\\").token(T::LiteralString),
        ]),
    ],
};
