//! Chroma's `perl.xml` lexer, converted to Rust (crate README, "Lexer and style files").

use crate::chroma::defs::prelude::*;

#[rustfmt::skip]
pub(crate) static LEXER: LexerDef = LexerDef {
    file: "perl",
    config: ConfigDef {
        name: "Perl",
        aliases: &["perl", "pl"],
        filenames: &["*.pl", "*.pm", "*.t"],
        mime_types: &["text/x-perl", "application/x-perl"],
        dot_all: true,
        ..ConfigDef::EMPTY
    },
    states: &[
        ("root", &[
            rule(r"\A\#!.+?$").token(T::CommentHashbang),
            rule(r"\#.*?$").token(T::CommentSingle),
            rule(r"^=[a-zA-Z0-9]+\s+.*?\n=cut").token(T::CommentMultiline),
            rule(r"(continue|foreach|unless|return|elsif|CHECK|while|BEGIN|reset|print|until|next|else|INIT|then|last|redo|case|our|new|for|END|if|do|my)\b").token(T::Keyword),
            rule(r"(format)(\s+)(\w+)(\s*)(=)(\s*\n)").groups(&[T::Keyword, T::Text, T::Name, T::Text, T::Punctuation, T::Text]).push(&["format"]),
            rule(r"(eq|lt|gt|le|ge|ne|not|and|or|cmp)\b").token(T::OperatorWord),
            rule(r"s/(\\\\|\\[^\\]|[^\\/])*/(\\\\|\\[^\\]|[^\\/])*/[egimosx]*").token(T::LiteralStringRegex),
            rule(r"s!(\\\\|\\!|[^!])*!(\\\\|\\!|[^!])*![egimosx]*").token(T::LiteralStringRegex),
            rule(r"s\\(\\\\|[^\\])*\\(\\\\|[^\\])*\\[egimosx]*").token(T::LiteralStringRegex),
            rule(r"s@(\\\\|\\[^\\]|[^\\@])*@(\\\\|\\[^\\]|[^\\@])*@[egimosx]*").token(T::LiteralStringRegex),
            rule(r"s%(\\\\|\\[^\\]|[^\\%])*%(\\\\|\\[^\\]|[^\\%])*%[egimosx]*").token(T::LiteralStringRegex),
            rule(r"s\{(\\\\|\\[^\\]|[^\\}])*\}\s*").token(T::LiteralStringRegex).push(&["balanced-regex"]),
            rule(r"s<(\\\\|\\[^\\]|[^\\>])*>\s*").token(T::LiteralStringRegex).push(&["balanced-regex"]),
            rule(r"s\[(\\\\|\\[^\\]|[^\\\]])*\]\s*").token(T::LiteralStringRegex).push(&["balanced-regex"]),
            rule(r"s\((\\\\|\\[^\\]|[^\\)])*\)\s*").token(T::LiteralStringRegex).push(&["balanced-regex"]),
            rule(r"m?/(\\\\|\\[^\\]|[^\\/\n])*/[gcimosx]*").token(T::LiteralStringRegex),
            rule(r"m(?=[/!\\{<\[(@%$])").token(T::LiteralStringRegex).push(&["balanced-regex"]),
            rule(r"((?<==~)|(?<=\())\s*/(\\\\|\\[^\\]|[^\\/])*/[gcimosx]*").token(T::LiteralStringRegex),
            rule(r"\s+").token(T::Text),
            rule(r"(getprotobynumber|getprotobyname|getservbyport|getservbyname|gethostbyname|gethostbyaddr|getnetbyaddr|getnetbyname|setprotoent|setpriority|getsockname|getprotoent|getpriority|getpeername|endprotoent|setsockopt|endhostent|setservent|socketpair|getsockopt|endservent|sethostent|getservent|gethostent|getnetent|wantarray|localtime|quotemeta|setnetent|prototype|endnetent|rewinddir|endpwent|endgrent|getpwent|getpwnam|getgrgid|dbmclose|continue|closedir|shutdown|setpwent|shmwrite|syswrite|truncate|formline|setgrent|getgrent|readpipe|getgrnam|readlink|readline|getpwuid|getlogin|telldir|opendir|shmread|readdir|getpgrp|getppid|waitpid|binmode|reverse|sprintf|unshift|symlink|seekdir|sysopen|defined|dbmopen|sysread|sysseek|connect|lcfirst|ucfirst|setpgrp|syscall|import|chroot|system|gmtime|unlink|unpack|semget|semctl|select|msgrcv|length|printf|listen|scalar|caller|rindex|substr|splice|rename|msgctl|msgget|delete|msgsnd|exists|values|socket|fileno|format|accept|shmget|shmctl|ioctl|alarm|atan2|utime|untie|bless|chdir|chmod|undef|umask|chomp|times|close|crypt|srand|split|mkdir|sleep|lstat|study|rmdir|local|fcntl|flock|write|shift|index|semop|chown|tell|join|send|warn|kill|wait|grep|glob|bind|last|pack|getc|fork|link|seek|push|rand|read|exit|sort|exec|open|eval|sqrt|redo|stat|chop|next|each|dump|time|recv|tied|goto|keys|pipe|map|tie|cos|die|eof|pop|sin|pos|oct|ref|exp|int|ord|log|our|hex|abs|vec|chr|uc|tr|my|lc)\b").token(T::NameBuiltin),
            rule(r"((__(DATA|DIE|WARN)__)|(STD(IN|OUT|ERR)))\b").token(T::NameBuiltinPseudo),
            rule(r#"(<<)([\'"]?)([a-zA-Z_]\w*)(\2;?\n.*?\n)(\3)(\n)"#).groups(&[T::LiteralString, T::LiteralString, T::LiteralStringDelimiter, T::LiteralString, T::LiteralStringDelimiter, T::Text]),
            rule(r"__END__").token(T::CommentPreproc).push(&["end-part"]),
            rule(r"\$\^[ADEFHILMOPSTWX]").token(T::NameVariableGlobal),
            rule(r#"\$[\\\"\[\]'&`+*.,;=%~?@$!<>(^|/-](?!\w)"#).token(T::NameVariableGlobal),
            rule(r"[$@%#]+").token(T::NameVariable).push(&["varname"]),
            rule(r"0_?[0-7]+(_[0-7]+)*").token(T::LiteralNumberOct),
            rule(r"0x[0-9A-Fa-f]+(_[0-9A-Fa-f]+)*").token(T::LiteralNumberHex),
            rule(r"0b[01]+(_[01]+)*").token(T::LiteralNumberBin),
            rule(r"(?i)(\d*(_\d*)*\.\d+(_\d*)*|\d+(_\d*)*\.\d+(_\d*)*)(e[+-]?\d+)?").token(T::LiteralNumberFloat),
            rule(r"(?i)\d+(_\d*)*e[+-]?\d+(_\d*)*").token(T::LiteralNumberFloat),
            rule(r"\d+(_\d+)*").token(T::LiteralNumberInteger),
            rule(r"'(\\\\|\\[^\\]|[^'\\])*'").token(T::LiteralString),
            rule(r#""(\\\\|\\[^\\]|[^"\\])*""#).token(T::LiteralString),
            rule(r"`(\\\\|\\[^\\]|[^`\\])*`").token(T::LiteralStringBacktick),
            rule(r"<([^\s>]+)>").token(T::LiteralStringRegex),
            rule(r"(q|qq|qw|qr|qx)\{").token(T::LiteralStringOther).push(&["cb-string"]),
            rule(r"(q|qq|qw|qr|qx)\(").token(T::LiteralStringOther).push(&["rb-string"]),
            rule(r"(q|qq|qw|qr|qx)\[").token(T::LiteralStringOther).push(&["sb-string"]),
            rule(r"(q|qq|qw|qr|qx)\<").token(T::LiteralStringOther).push(&["lt-string"]),
            rule(r"(q|qq|qw|qr|qx)([\W_])(.|\n)*?\2").token(T::LiteralStringOther),
            rule(r"(package)(\s+)([a-zA-Z_]\w*(?:::[a-zA-Z_]\w*)*)").groups(&[T::Keyword, T::Text, T::NameNamespace]),
            rule(r"(use|require|no)(\s+)([a-zA-Z_]\w*(?:::[a-zA-Z_]\w*)*)").groups(&[T::Keyword, T::Text, T::NameNamespace]),
            rule(r"(sub)(\s+)").groups(&[T::Keyword, T::Text]).push(&["funcname"]),
            rule(r"(package|require|use|no)\b").token(T::Keyword),
            rule(r"(\[\]|\*\*|::|<<|>>|>=|<=>|<=|={3}|!=|=~|!~|&&?|\|\||\.{1,3})").token(T::Operator),
            rule(r"[-+/*%=<>&^|!\\~]=?").token(T::Operator),
            rule(r"[()\[\]:;,<>/?{}]").token(T::Punctuation),
            rule(r"(?=\w)").token(T::Name).push(&["name"]),
        ]),
        ("cb-string", &[
            rule(r"\\[{}\\]").token(T::LiteralStringOther),
            rule(r"\\").token(T::LiteralStringOther),
            rule(r"\{").token(T::LiteralStringOther).push(&["cb-string"]),
            rule(r"\}").token(T::LiteralStringOther).pop(1),
            rule(r"[^{}\\]+").token(T::LiteralStringOther),
        ]),
        ("balanced-regex", &[
            rule(r"/(\\\\|\\[^\\]|[^\\/])*/[egimosx]*").token(T::LiteralStringRegex).pop(1),
            rule(r"!(\\\\|\\[^\\]|[^\\!])*![egimosx]*").token(T::LiteralStringRegex).pop(1),
            rule(r"\\(\\\\|[^\\])*\\[egimosx]*").token(T::LiteralStringRegex).pop(1),
            rule(r"\{(\\\\|\\[^\\]|[^\\}])*\}[egimosx]*").token(T::LiteralStringRegex).pop(1),
            rule(r"<(\\\\|\\[^\\]|[^\\>])*>[egimosx]*").token(T::LiteralStringRegex).pop(1),
            rule(r"\[(\\\\|\\[^\\]|[^\\\]])*\][egimosx]*").token(T::LiteralStringRegex).pop(1),
            rule(r"\((\\\\|\\[^\\]|[^\\)])*\)[egimosx]*").token(T::LiteralStringRegex).pop(1),
            rule(r"@(\\\\|\\[^\\]|[^\\@])*@[egimosx]*").token(T::LiteralStringRegex).pop(1),
            rule(r"%(\\\\|\\[^\\]|[^\\%])*%[egimosx]*").token(T::LiteralStringRegex).pop(1),
            rule(r"\$(\\\\|\\[^\\]|[^\\$])*\$[egimosx]*").token(T::LiteralStringRegex).pop(1),
        ]),
        ("lt-string", &[
            rule(r"\\[<>\\]").token(T::LiteralStringOther),
            rule(r"\\").token(T::LiteralStringOther),
            rule(r"\<").token(T::LiteralStringOther).push(&["lt-string"]),
            rule(r"\>").token(T::LiteralStringOther).pop(1),
            rule(r"[^<>]+").token(T::LiteralStringOther),
        ]),
        ("format", &[
            rule(r"\.\n").token(T::LiteralStringInterpol).pop(1),
            rule(r"[^\n]*\n").token(T::LiteralStringInterpol),
        ]),
        ("funcname", &[
            rule(r"[a-zA-Z_]\w*[!?]?").token(T::NameFunction),
            rule(r"\s+").token(T::Text),
            rule(r"(\([$@%]*\))(\s*)").groups(&[T::Punctuation, T::Text]),
            rule(r";").token(T::Punctuation).pop(1),
            rule(r".*?\{").token(T::Punctuation).pop(1),
        ]),
        ("end-part", &[
            rule(r".+").token(T::CommentPreproc).pop(1),
        ]),
        ("varname", &[
            rule(r"\s+").token(T::Text),
            rule(r"\{").token(T::Punctuation).pop(1),
            rule(r"\)|,").token(T::Punctuation).pop(1),
            rule(r"\w+::").token(T::NameNamespace),
            rule(r"[\w:]+").token(T::NameVariable).pop(1),
        ]),
        ("name", &[
            rule(r"[a-zA-Z_]\w*(::[a-zA-Z_]\w*)*(::)?(?=\s*->)").token(T::NameNamespace).pop(1),
            rule(r"[a-zA-Z_]\w*(::[a-zA-Z_]\w*)*::").token(T::NameNamespace).pop(1),
            rule(r"[\w:]+").token(T::Name).pop(1),
            rule(r"[A-Z_]+(?=\W)").token(T::NameConstant).pop(1),
            rule(r"(?=\W)").token(T::Text).pop(1),
        ]),
        ("rb-string", &[
            rule(r"\\[()\\]").token(T::LiteralStringOther),
            rule(r"\\").token(T::LiteralStringOther),
            rule(r"\(").token(T::LiteralStringOther).push(&["rb-string"]),
            rule(r"\)").token(T::LiteralStringOther).pop(1),
            rule(r"[^()]+").token(T::LiteralStringOther),
        ]),
        ("sb-string", &[
            rule(r"\\[\[\]\\]").token(T::LiteralStringOther),
            rule(r"\\").token(T::LiteralStringOther),
            rule(r"\[").token(T::LiteralStringOther).push(&["sb-string"]),
            rule(r"\]").token(T::LiteralStringOther).pop(1),
            rule(r"[^\[\]]+").token(T::LiteralStringOther),
        ]),
    ],
};
