//! Chroma's `promela.xml` lexer, converted to Rust (crate README, "Lexer and style files").

use crate::chroma::defs::prelude::*;

#[rustfmt::skip]
pub(crate) static LEXER: LexerDef = LexerDef {
    file: "promela",
    config: ConfigDef {
        name: "Promela",
        aliases: &["promela"],
        filenames: &["*.pml", "*.prom", "*.prm", "*.promela", "*.pr", "*.pm"],
        mime_types: &["text/x-promela"],
        ..ConfigDef::EMPTY
    },
    states: &[
        ("statements", &[
            rule(r"(\[\]|<>|/\\|\\/)|(U|W|V)\b").token(T::Operator),
            rule(r"@").token(T::Punctuation),
            rule(r"(\.)([a-zA-Z_]\w*)").groups(&[T::Operator, T::NameAttribute]),
            include("keywords"),
            include("types"),
            rule(r#"([LuU]|u8)?(")"#).groups(&[T::LiteralStringAffix, T::LiteralString]).push(&["string"]),
            rule(r"([LuU]|u8)?(')(\\.|\\[0-7]{1,3}|\\x[a-fA-F0-9]{1,2}|[^\\\'\n])(')").groups(&[T::LiteralStringAffix, T::LiteralStringChar, T::LiteralStringChar, T::LiteralStringChar]),
            rule(r"0[xX]([0-9a-fA-F](\'?[0-9a-fA-F])*\.[0-9a-fA-F](\'?[0-9a-fA-F])*|\.[0-9a-fA-F](\'?[0-9a-fA-F])*|[0-9a-fA-F](\'?[0-9a-fA-F])*)[pP][+-]?[0-9a-fA-F](\'?[0-9a-fA-F])*[lL]?").token(T::LiteralNumberFloat),
            rule(r"(-)?(\d(\'?\d)*\.\d(\'?\d)*|\.\d(\'?\d)*|\d(\'?\d)*)[eE][+-]?\d(\'?\d)*[fFlL]?").token(T::LiteralNumberFloat),
            rule(r"(-)?((\d(\'?\d)*\.(\d(\'?\d)*)?|\.\d(\'?\d)*)[fFlL]?)|(\d(\'?\d)*[fFlL])").token(T::LiteralNumberFloat),
            rule(r"(-)?0[xX][0-9a-fA-F](\'?[0-9a-fA-F])*(([uU][lL]{0,2})|[lL]{1,2}[uU]?)?").token(T::LiteralNumberHex),
            rule(r"(-)?0[bB][01](\'?[01])*(([uU][lL]{0,2})|[lL]{1,2}[uU]?)?").token(T::LiteralNumberBin),
            rule(r"(-)?0(\'?[0-7])+(([uU][lL]{0,2})|[lL]{1,2}[uU]?)?").token(T::LiteralNumberOct),
            rule(r"(-)?\d(\'?\d)*(([uU][lL]{0,2})|[lL]{1,2}[uU]?)?").token(T::LiteralNumberInteger),
            rule(r"[~!%^&*+=|?:<>/-]").token(T::Operator),
            rule(r"[()\[\],.]").token(T::Punctuation),
            rule(r"(true|false|NULL)\b").token(T::NameBuiltin),
            rule(r"(?!\d)(?:[\w$]|\\u[0-9a-fA-F]{4}|\\U[0-9a-fA-F]{8})+").token(T::Name),
        ]),
        ("types", &[
            rule(r"(bit|bool|byte|pid|short|int|unsigned)\b").token(T::KeywordType),
        ]),
        ("keywords", &[
            rule(r"(atomic|break|d_step|do|od|for|in|goto|if|fi|unless)\b").token(T::Keyword),
            rule(r"(assert|get_priority|printf|printm|set_priority)\b").token(T::NameFunction),
            rule(r"(c_code|c_decl|c_expr|c_state|c_track)\b").token(T::Keyword),
            rule(r"(_|_last|_nr_pr|_pid|_priority|else|np_|STDIN)\b").token(T::NameBuiltin),
            rule(r"(empty|enabled|eval|full|len|nempty|nfull|pc_value)\b").token(T::NameFunction),
            rule(r"run\b").token(T::OperatorWord),
            rule(r"(active|chan|D_proctype|hidden|init|local|mtype|never|notrace|proctype|show|trace|typedef|xr|xs)\b").token(T::KeywordDeclaration),
            rule(r"(priority|provided)\b").token(T::Keyword),
            rule(r"(inline|ltl|select)\b").token(T::KeywordDeclaration),
            rule(r"skip\b").token(T::Keyword),
        ]),
        ("whitespace", &[
            rule(r"^#if\s+0").token(T::CommentPreproc).push(&["if0"]),
            rule(r"^#").token(T::CommentPreproc).push(&["macro"]),
            rule(r"^(\s*(?:/[*].*?[*]/\s*)?)(#if\s+0)").bygroups(&[E::UsingSelf("root"), E::Token(T::CommentPreproc)]).push(&["if0"]),
            rule(r"^(\s*(?:/[*].*?[*]/\s*)?)(#)").bygroups(&[E::UsingSelf("root"), E::Token(T::CommentPreproc)]).push(&["macro"]),
            rule(r"(^[ \t]*)(?!(?:public|private|protected|default)\b)((?!\d)(?:[\w$]|\\u[0-9a-fA-F]{4}|\\U[0-9a-fA-F]{8})+)(\s*)(:)(?!:)").groups(&[T::TextWhitespace, T::NameLabel, T::TextWhitespace, T::Punctuation]),
            rule(r"\n").token(T::TextWhitespace),
            rule(r"[^\S\n]+").token(T::TextWhitespace),
            rule(r"\\\n").token(T::Text),
            rule(r"//(?:.|(?<=\\)\n)*\n").token(T::CommentSingle),
            rule(r"/(?:\\\n)?[*](?:[^*]|[*](?!(?:\\\n)?/))*[*](?:\\\n)?/").token(T::CommentMultiline),
            rule(r"/(\\\n)?[*][\w\W]*").token(T::CommentMultiline),
        ]),
        ("root", &[
            include("whitespace"),
            include("keywords"),
            rule(r#"((?!\d)(?:[\w$]|\\u[0-9a-fA-F]{4}|\\U[0-9a-fA-F]{8}|::)+(?:[&*\s])+)(\s*(?:(?:(?://(?:.|(?<=\\)\n)*\n)|(?:/(?:\\\n)?[*](?:[^*]|[*](?!(?:\\\n)?/))*[*](?:\\\n)?/))\s*)*)((?!\d)(?:[\w$]|\\u[0-9a-fA-F]{4}|\\U[0-9a-fA-F]{8}|::)+)(\s*(?:(?:(?://(?:.|(?<=\\)\n)*\n)|(?:/(?:\\\n)?[*](?:[^*]|[*](?!(?:\\\n)?/))*[*](?:\\\n)?/))\s*)*)(\([^;"\')]*?\))(\s*(?:(?:(?://(?:.|(?<=\\)\n)*\n)|(?:/(?:\\\n)?[*](?:[^*]|[*](?!(?:\\\n)?/))*[*](?:\\\n)?/))\s*)*)([^;{/"\']*)(\{)"#).bygroups(&[E::UsingSelf("root"), E::UsingSelf("whitespace"), E::Token(T::NameFunction), E::UsingSelf("whitespace"), E::UsingSelf("root"), E::UsingSelf("whitespace"), E::UsingSelf("root"), E::Token(T::Punctuation)]).push(&["function"]),
            rule(r#"((?!\d)(?:[\w$]|\\u[0-9a-fA-F]{4}|\\U[0-9a-fA-F]{8}|::)+(?:[&*\s])+)(\s*(?:(?:(?://(?:.|(?<=\\)\n)*\n)|(?:/(?:\\\n)?[*](?:[^*]|[*](?!(?:\\\n)?/))*[*](?:\\\n)?/))\s*)*)((?!\d)(?:[\w$]|\\u[0-9a-fA-F]{4}|\\U[0-9a-fA-F]{8}|::)+)(\s*(?:(?:(?://(?:.|(?<=\\)\n)*\n)|(?:/(?:\\\n)?[*](?:[^*]|[*](?!(?:\\\n)?/))*[*](?:\\\n)?/))\s*)*)(\([^;"\')]*?\))(\s*(?:(?:(?://(?:.|(?<=\\)\n)*\n)|(?:/(?:\\\n)?[*](?:[^*]|[*](?!(?:\\\n)?/))*[*](?:\\\n)?/))\s*)*)([^;/"\']*)(;)"#).bygroups(&[E::UsingSelf("root"), E::UsingSelf("whitespace"), E::Token(T::NameFunction), E::UsingSelf("whitespace"), E::UsingSelf("root"), E::UsingSelf("whitespace"), E::UsingSelf("root"), E::Token(T::Punctuation)]),
            include("types"),
            rule("").push(&["statement"]),
        ]),
        ("statement", &[
            include("whitespace"),
            include("statements"),
            rule(r"\}").token(T::Punctuation),
            rule(r"[{;]").token(T::Punctuation).pop(1),
        ]),
        ("function", &[
            include("whitespace"),
            include("statements"),
            rule(r";").token(T::Punctuation),
            rule(r"\{").token(T::Punctuation).push(&[]),
            rule(r"\}").token(T::Punctuation).pop(1),
        ]),
        ("string", &[
            rule(r#"""#).token(T::LiteralString).pop(1),
            rule(r#"\\([\\abfnrtv"\']|x[a-fA-F0-9]{2,4}|u[a-fA-F0-9]{4}|U[a-fA-F0-9]{8}|[0-7]{1,3})"#).token(T::LiteralStringEscape),
            rule(r#"[^\\"\n]+"#).token(T::LiteralString),
            rule(r"\\\n").token(T::LiteralString),
            rule(r"\\").token(T::LiteralString),
        ]),
        ("macro", &[
            rule(r#"(\s*(?:/[*].*?[*]/\s*)?)(include)(\s*(?:/[*].*?[*]/\s*)?)("[^"]+")([^\n]*)"#).bygroups(&[E::UsingSelf("root"), E::Token(T::CommentPreproc), E::UsingSelf("root"), E::Token(T::CommentPreprocFile), E::Token(T::CommentSingle)]),
            rule(r"(\s*(?:/[*].*?[*]/\s*)?)(include)(\s*(?:/[*].*?[*]/\s*)?)(<[^>]+>)([^\n]*)").bygroups(&[E::UsingSelf("root"), E::Token(T::CommentPreproc), E::UsingSelf("root"), E::Token(T::CommentPreprocFile), E::Token(T::CommentSingle)]),
            rule(r"[^/\n]+").token(T::CommentPreproc),
            rule(r"/[*](.|\n)*?[*]/").token(T::CommentMultiline),
            rule(r"//.*?\n").token(T::CommentSingle).pop(1),
            rule(r"/").token(T::CommentPreproc),
            rule(r"(?<=\\)\n").token(T::CommentPreproc),
            rule(r"\n").token(T::CommentPreproc).pop(1),
        ]),
        ("if0", &[
            rule(r"^\s*#if.*?(?<!\\)\n").token(T::CommentPreproc).push(&[]),
            rule(r"^\s*#el(?:se|if).*\n").token(T::CommentPreproc).pop(1),
            rule(r"^\s*#endif.*?(?<!\\)\n").token(T::CommentPreproc).pop(1),
            rule(r".*?\n").token(T::Comment),
        ]),
        ("classname", &[
            rule(r"(?!\d)(?:[\w$]|\\u[0-9a-fA-F]{4}|\\U[0-9a-fA-F]{8})+").token(T::NameClass).pop(1),
            rule(r"\s*(?=>)").token(T::Text).pop(1),
            rule("").pop(1),
        ]),
        ("case-value", &[
            rule(r"(?<!:)(:)(?!:)").token(T::Punctuation).pop(1),
            rule(r"(?!\d)(?:[\w$]|\\u[0-9a-fA-F]{4}|\\U[0-9a-fA-F]{8})+").token(T::NameConstant),
            include("whitespace"),
            include("statements"),
        ]),
    ],
};
