//! Chroma's `python.xml` lexer, converted to Rust (crate README, "Lexer and style files").

use crate::chroma::defs::prelude::*;

#[rustfmt::skip]
pub(crate) static LEXER: LexerDef = LexerDef {
    file: "python",
    config: ConfigDef {
        name: "Python",
        aliases: &["python", "py", "sage", "python3", "py3"],
        filenames: &[
            "*.py",
            "*.pyi",
            "*.pyw",
            "*.jy",
            "*.sage",
            "*.sc",
            "SConstruct",
            "SConscript",
            "*.bzl",
            "BUCK",
            "BUILD",
            "BUILD.bazel",
            "WORKSPACE",
            "WORKSPACE.bzlmod",
            "WORKSPACE.bazel",
            "MODULE.bazel",
            "REPO.bazel",
            "*.tac",
        ],
        mime_types: &[
            "text/x-python",
            "application/x-python",
            "text/x-python3",
            "application/x-python3",
        ],
        ..ConfigDef::EMPTY
    },
    states: &[
        ("numbers", &[
            rule(r"(\d(?:_?\d)*\.(?:\d(?:_?\d)*)?|(?:\d(?:_?\d)*)?\.\d(?:_?\d)*)([eE][+-]?\d(?:_?\d)*)?").token(T::LiteralNumberFloat),
            rule(r"\d(?:_?\d)*[eE][+-]?\d(?:_?\d)*j?").token(T::LiteralNumberFloat),
            rule(r"0[oO](?:_?[0-7])+").token(T::LiteralNumberOct),
            rule(r"0[bB](?:_?[01])+").token(T::LiteralNumberBin),
            rule(r"0[xX](?:_?[a-fA-F0-9])+").token(T::LiteralNumberHex),
            rule(r"\d(?:_?\d)*").token(T::LiteralNumberInteger),
        ]),
        ("expr", &[
            rule(r#"(?i)(rf|fr)(""")"#).groups(&[T::LiteralStringAffix, T::LiteralStringDouble]).combined(&["rfstringescape", "tdqf"]),
            rule(r"(?i)(rf|fr)(''')").groups(&[T::LiteralStringAffix, T::LiteralStringSingle]).combined(&["rfstringescape", "tsqf"]),
            rule(r#"(?i)(rf|fr)(")"#).groups(&[T::LiteralStringAffix, T::LiteralStringDouble]).combined(&["rfstringescape", "dqf"]),
            rule(r"(?i)(rf|fr)(')").groups(&[T::LiteralStringAffix, T::LiteralStringSingle]).combined(&["rfstringescape", "sqf"]),
            rule(r#"([fF])(""")"#).groups(&[T::LiteralStringAffix, T::LiteralStringDouble]).combined(&["fstringescape", "tdqf"]),
            rule(r"([fF])(''')").groups(&[T::LiteralStringAffix, T::LiteralStringSingle]).combined(&["fstringescape", "tsqf"]),
            rule(r#"([fF])(")"#).groups(&[T::LiteralStringAffix, T::LiteralStringDouble]).combined(&["fstringescape", "dqf"]),
            rule(r"([fF])(')").groups(&[T::LiteralStringAffix, T::LiteralStringSingle]).combined(&["fstringescape", "sqf"]),
            rule(r#"(?i)(rb|br|r)(""")"#).groups(&[T::LiteralStringAffix, T::LiteralStringDouble]).push(&["tdqs"]),
            rule(r"(?i)(rb|br|r)(''')").groups(&[T::LiteralStringAffix, T::LiteralStringSingle]).push(&["tsqs"]),
            rule(r#"(?i)(rb|br|r)(")"#).groups(&[T::LiteralStringAffix, T::LiteralStringDouble]).push(&["dqs"]),
            rule(r"(?i)(rb|br|r)(')").groups(&[T::LiteralStringAffix, T::LiteralStringSingle]).push(&["sqs"]),
            rule(r#"([uUbB]?)(""")"#).groups(&[T::LiteralStringAffix, T::LiteralStringDouble]).combined(&["stringescape", "tdqs"]),
            rule(r"([uUbB]?)(''')").groups(&[T::LiteralStringAffix, T::LiteralStringSingle]).combined(&["stringescape", "tsqs"]),
            rule(r#"([uUbB]?)(")"#).groups(&[T::LiteralStringAffix, T::LiteralStringDouble]).combined(&["stringescape", "dqs"]),
            rule(r"([uUbB]?)(')").groups(&[T::LiteralStringAffix, T::LiteralStringSingle]).combined(&["stringescape", "sqs"]),
            rule(r"[^\S\n]+").token(T::Text),
            include("numbers"),
            rule(r"!=|==|<<|>>|:=|[-~+/*%=<>&^|.]").token(T::Operator),
            rule(r"[]{}:(),;[]").token(T::Punctuation),
            rule(r"(in|is|and|or|not)\b").token(T::OperatorWord),
            include("expr-keywords"),
            include("builtins"),
            include("magicfuncs"),
            include("magicvars"),
            include("name"),
        ]),
        ("fstrings-double", &[
            rule(r"\}").token(T::LiteralStringInterpol),
            rule(r"\{").token(T::LiteralStringInterpol).push(&["expr-inside-fstring"]),
            rule(r#"[^\\\'"{}\n]+"#).token(T::LiteralStringDouble),
            rule(r#"[\'"\\]"#).token(T::LiteralStringDouble),
        ]),
        ("keywords", &[
            rule(r"(yield from|nonlocal|continue|finally|except|lambda|assert|global|return|raise|yield|while|break|await|async|pass|else|elif|with|try|for|del|as|if|match|case)\b").token(T::Keyword),
            rule(r"(False|True|None)\b").token(T::KeywordConstant),
        ]),
        ("dqs", &[
            rule(r#"""#).token(T::LiteralStringDouble).pop(1),
            rule(r#"\\\\|\\"|\\\n"#).token(T::LiteralStringEscape),
            include("strings-double"),
        ]),
        ("fromimport", &[
            rule(r"(\s+)(import)\b").groups(&[T::Text, T::KeywordNamespace]).pop(1),
            rule(r"\.").token(T::NameNamespace),
            rule(r"None\b").token(T::NameBuiltinPseudo).pop(1),
            rule(r"[_\p{L}][_\p{L}\p{N}]*").token(T::NameNamespace),
            rule("").pop(1),
        ]),
        ("builtins", &[
            rule(r"(?<!\.)(staticmethod|classmethod|memoryview|__import__|issubclass|isinstance|frozenset|bytearray|enumerate|reversed|property|compile|complex|delattr|hasattr|setattr|globals|getattr|divmod|filter|locals|format|object|sorted|slice|print|bytes|range|input|tuple|round|super|float|eval|list|dict|repr|type|vars|hash|next|bool|open|iter|oct|pow|min|zip|max|map|bin|len|set|any|dir|all|abs|str|sum|chr|int|hex|ord|id)\b").token(T::NameBuiltin),
            rule(r"(?<!\.)(self|Ellipsis|NotImplemented|cls)\b").token(T::NameBuiltinPseudo),
            rule(r"(?<!\.)(PendingDeprecationWarning|ConnectionAbortedError|ConnectionRefusedError|UnicodeTranslateError|ConnectionResetError|ModuleNotFoundError|NotImplementedError|FloatingPointError|StopAsyncIteration|UnicodeDecodeError|DeprecationWarning|UnicodeEncodeError|NotADirectoryError|ProcessLookupError|ZeroDivisionError|IsADirectoryError|FileNotFoundError|UnboundLocalError|KeyboardInterrupt|ChildProcessError|EnvironmentError|IndentationError|InterruptedError|BlockingIOError|ArithmeticError|ConnectionError|BrokenPipeError|FileExistsError|ResourceWarning|PermissionError|RuntimeWarning|ReferenceError|AttributeError|AssertionError|UnicodeWarning|RecursionError|StopIteration|BaseException|OverflowError|SyntaxWarning|FutureWarning|GeneratorExit|ImportWarning|UnicodeError|TimeoutError|WindowsError|RuntimeError|BytesWarning|SystemError|UserWarning|MemoryError|ImportError|LookupError|BufferError|SyntaxError|SystemExit|ValueError|IndexError|NameError|Exception|TypeError|TabError|EOFError|KeyError|VMSError|Warning|OSError|IOError)\b").token(T::NameException),
        ]),
        ("classname", &[
            rule(r"[_\p{L}][_\p{L}\p{N}]*").token(T::NameClass).pop(1),
        ]),
        ("import", &[
            rule(r"(\s+)(as)(\s+)").groups(&[T::Text, T::Keyword, T::Text]),
            rule(r"\.").token(T::NameNamespace),
            rule(r"[_\p{L}][_\p{L}\p{N}]*").token(T::NameNamespace),
            rule(r"(\s*)(,)(\s*)").groups(&[T::Text, T::Operator, T::Text]),
            rule("").pop(1),
        ]),
        ("tsqs", &[
            rule(r"'''").token(T::LiteralStringSingle).pop(1),
            include("strings-single"),
            rule(r"\n").token(T::LiteralStringSingle),
        ]),
        ("strings-double", &[
            rule(r"%(\(\w+\))?[-#0 +]*([0-9]+|[*])?(\.([0-9]+|[*]))?[hlL]?[E-GXc-giorsaux%]").token(T::LiteralStringInterpol),
            rule(r"\{((\w+)((\.\w+)|(\[[^\]]+\]))*)?(\![sra])?(\:(.?[<>=\^])?[-+ ]?#?0?(\d+)?,?(\.\d+)?[E-GXb-gnosx%]?)?\}").token(T::LiteralStringInterpol),
            rule(r#"[^\\\'"%{\n]+"#).token(T::LiteralStringDouble),
            rule(r#"[\'"\\]"#).token(T::LiteralStringDouble),
            rule(r"%|(\{{1,2})").token(T::LiteralStringDouble),
        ]),
        ("tdqf", &[
            rule(r#"""""#).token(T::LiteralStringDouble).pop(1),
            include("fstrings-double"),
            rule(r"\n").token(T::LiteralStringDouble),
        ]),
        ("expr-inside-fstring-inner", &[
            rule(r"[{([]").token(T::Punctuation).push(&["expr-inside-fstring-inner"]),
            rule(r"[])}]").token(T::Punctuation).pop(1),
            rule(r"\s+").token(T::Text),
            include("expr"),
        ]),
        ("sqs", &[
            rule(r"'").token(T::LiteralStringSingle).pop(1),
            rule(r"\\\\|\\'|\\\n").token(T::LiteralStringEscape),
            include("strings-single"),
        ]),
        ("funcname", &[
            include("magicfuncs"),
            rule(r"[_\p{L}][_\p{L}\p{N}]*").token(T::NameFunction).pop(1),
            rule("").pop(1),
        ]),
        ("expr-keywords", &[
            rule(r"(yield from|async for|lambda|yield|await|else|for|if)\b").token(T::Keyword),
            rule(r"(False|True|None)\b").token(T::KeywordConstant),
        ]),
        ("name", &[
            rule(r"@[_\p{L}][_\p{L}\p{N}]*(\s*\.\s*[_\p{L}][_\p{L}\p{N}]*)*").token(T::NameDecorator),
            rule(r"@").token(T::Operator),
            rule(r"[_\p{L}][_\p{L}\p{N}]*").token(T::Name),
        ]),
        ("magicfuncs", &[
            rule(r"(__instancecheck__|__subclasscheck__|__getattribute__|__length_hint__|__rfloordiv__|__ifloordiv__|__itruediv__|__contains__|__floordiv__|__rtruediv__|__reversed__|__setitem__|__complex__|__rdivmod__|__delattr__|__rmatmul__|__ilshift__|__prepare__|__delitem__|__rrshift__|__imatmul__|__rlshift__|__setattr__|__truediv__|__getitem__|__missing__|__getattr__|__irshift__|__rshift__|__format__|__invert__|__matmul__|__divmod__|__delete__|__aenter__|__lshift__|__await__|__bytes__|__anext__|__aiter__|__aexit__|__round__|__float__|__enter__|__index__|__iadd__|__ipow__|__rpow__|__iter__|__init__|__ixor__|__rmul__|__rmod__|__imul__|__imod__|__iand__|__hash__|__rsub__|__exit__|__rxor__|__bool__|__call__|__rand__|__next__|__radd__|__isub__|__repr__|__set__|__add__|__new__|__neg__|__xor__|__and__|__mul__|__mod__|__sub__|__len__|__str__|__ror__|__ior__|__pos__|__del__|__get__|__dir__|__abs__|__int__|__pow__|__eq__|__gt__|__le__|__lt__|__ne__|__or__|__ge__)\b").token(T::NameFunctionMagic),
        ]),
        ("root", &[
            rule(r"\n").token(T::Text),
            rule(r#"^(\s*)([rRuUbB]{,2})("""(?:.|\n)*?""")"#).groups(&[T::Text, T::LiteralStringAffix, T::LiteralStringDoc]),
            rule(r"^(\s*)([rRuUbB]{,2})('''(?:.|\n)*?''')").groups(&[T::Text, T::LiteralStringAffix, T::LiteralStringDoc]),
            rule(r"\A#!.+$").token(T::CommentHashbang),
            rule(r"#.*$").token(T::CommentSingle),
            rule(r"\\\n").token(T::Text),
            rule(r"\\").token(T::Text),
            include("keywords"),
            rule(r"(def)((?:\s|\\\s)+)").groups(&[T::Keyword, T::Text]).push(&["funcname"]),
            rule(r"(class)((?:\s|\\\s)+)").groups(&[T::Keyword, T::Text]).push(&["classname"]),
            rule(r"(from)((?:\s|\\\s)+)").groups(&[T::KeywordNamespace, T::Text]).push(&["fromimport"]),
            rule(r"(import)((?:\s|\\\s)+)").groups(&[T::KeywordNamespace, T::Text]).push(&["import"]),
            include("expr"),
        ]),
        ("fstrings-single", &[
            rule(r"\}").token(T::LiteralStringInterpol),
            rule(r"\{").token(T::LiteralStringInterpol).push(&["expr-inside-fstring"]),
            rule(r#"[^\\\'"{}\n]+"#).token(T::LiteralStringSingle),
            rule(r#"[\'"\\]"#).token(T::LiteralStringSingle),
        ]),
        ("magicvars", &[
            rule(r"(__annotations__|__kwdefaults__|__qualname__|__objclass__|__defaults__|__closure__|__globals__|__weakref__|__module__|__class__|__bases__|__slots__|__file__|__code__|__name__|__func__|__dict__|__self__|__mro__|__doc__)\b").token(T::NameVariableMagic),
        ]),
        ("tsqf", &[
            rule(r"'''").token(T::LiteralStringSingle).pop(1),
            include("fstrings-single"),
            rule(r"\n").token(T::LiteralStringSingle),
        ]),
        ("strings-single", &[
            rule(r"%(\(\w+\))?[-#0 +]*([0-9]+|[*])?(\.([0-9]+|[*]))?[hlL]?[E-GXc-giorsaux%]").token(T::LiteralStringInterpol),
            rule(r"\{((\w+)((\.\w+)|(\[[^\]]+\]))*)?(\![sra])?(\:(.?[<>=\^])?[-+ ]?#?0?(\d+)?,?(\.\d+)?[E-GXb-gnosx%]?)?\}").token(T::LiteralStringInterpol),
            rule(r#"[^\\\'"%{\n]+"#).token(T::LiteralStringSingle),
            rule(r#"[\'"\\]"#).token(T::LiteralStringSingle),
            rule(r"%|(\{{1,2})").token(T::LiteralStringSingle),
        ]),
        ("rfstringescape", &[
            rule(r"\{\{").token(T::LiteralStringEscape),
            rule(r"\}\}").token(T::LiteralStringEscape),
        ]),
        ("sqf", &[
            rule(r"'").token(T::LiteralStringSingle).pop(1),
            rule(r"\\\\|\\'|\\\n").token(T::LiteralStringEscape),
            include("fstrings-single"),
        ]),
        ("dqf", &[
            rule(r#"""#).token(T::LiteralStringDouble).pop(1),
            rule(r#"\\\\|\\"|\\\n"#).token(T::LiteralStringEscape),
            include("fstrings-double"),
        ]),
        ("expr-inside-fstring", &[
            rule(r"[{([]").token(T::Punctuation).push(&["expr-inside-fstring-inner"]),
            rule(r"(=\s*)?(\![sraf])?\}").token(T::LiteralStringInterpol).pop(1),
            rule(r"(=\s*)?(\![sraf])?:").token(T::LiteralStringInterpol).pop(1),
            rule(r"\s+").token(T::Text),
            include("expr"),
        ]),
        ("tdqs", &[
            rule(r#"""""#).token(T::LiteralStringDouble).pop(1),
            include("strings-double"),
            rule(r"\n").token(T::LiteralStringDouble),
        ]),
        ("fstringescape", &[
            include("rfstringescape"),
            include("stringescape"),
        ]),
        ("stringescape", &[
            rule(r#"\\([\\abfnrtv"\']|\n|N\{.*?\}|u[a-fA-F0-9]{4}|U[a-fA-F0-9]{8}|x[a-fA-F0-9]{2}|[0-7]{1,3})"#).token(T::LiteralStringEscape),
        ]),
    ],
};
