//! Chroma's `ruby.xml` lexer, converted to Rust (crate README, "Lexer and style files").

use crate::chroma::defs::prelude::*;

#[rustfmt::skip]
pub(crate) static LEXER: LexerDef = LexerDef {
    file: "ruby",
    config: ConfigDef {
        name: "Ruby",
        aliases: &["rb", "ruby", "duby"],
        filenames: &[
            "*.rb",
            "*.rbw",
            "Rakefile",
            "*.rake",
            "*.gemspec",
            "*.rbx",
            "*.duby",
            "Gemfile",
            "Vagrantfile",
        ],
        mime_types: &["text/x-ruby", "application/x-ruby"],
        dot_all: true,
        ..ConfigDef::EMPTY
    },
    states: &[
        ("simple-sym", &[
            include("string-intp-escaped"),
            rule(r##"[^\\"#]+"##).token(T::LiteralStringSymbol),
            rule(r"[\\#]").token(T::LiteralStringSymbol),
            rule(r#"""#).token(T::LiteralStringSymbol).pop(1),
        ]),
        ("interpolated-regex", &[
            include("string-intp"),
            rule(r"[\\#]").token(T::LiteralStringRegex),
            rule(r"[^\\#]+").token(T::LiteralStringRegex),
        ]),
        ("strings", &[
            rule(r"\:@{0,2}[a-zA-Z_]\w*[!?]?").token(T::LiteralStringSymbol),
            rule(r"\:@{0,2}(===|\[\]=|<=>|\*\*|==|>=|\+@|<>|>>|<<|-@|\[\]|~|`|\^|\||&|<|%|/|>|\+|-|\*)").token(T::LiteralStringSymbol),
            rule(r":'(\\\\|\\'|[^'])*'").token(T::LiteralStringSymbol),
            rule(r"'(\\\\|\\'|[^'])*'").token(T::LiteralStringSingle),
            rule(r#":""#).token(T::LiteralStringSymbol).push(&["simple-sym"]),
            rule(r"([a-zA-Z_]\w*)(:)(?!:)").groups(&[T::LiteralStringSymbol, T::Punctuation]),
            rule(r#"""#).token(T::LiteralStringDouble).push(&["simple-string"]),
            rule(r"(?<!\.)`").token(T::LiteralStringBacktick).push(&["simple-backtick"]),
            rule(r"%[QWx]?\{").token(T::LiteralStringOther).push(&["cb-intp-string"]),
            rule(r"%[qsw]\{").token(T::LiteralStringOther).push(&["cb-string"]),
            rule(r"%r\{").token(T::LiteralStringRegex).push(&["cb-regex"]),
            rule(r"%[QWx]?\[").token(T::LiteralStringOther).push(&["sb-intp-string"]),
            rule(r"%[qsw]\[").token(T::LiteralStringOther).push(&["sb-string"]),
            rule(r"%r\[").token(T::LiteralStringRegex).push(&["sb-regex"]),
            rule(r"%[QWx]?\(").token(T::LiteralStringOther).push(&["pa-intp-string"]),
            rule(r"%[qsw]\(").token(T::LiteralStringOther).push(&["pa-string"]),
            rule(r"%r\(").token(T::LiteralStringRegex).push(&["pa-regex"]),
            rule(r"%[QWx]?<").token(T::LiteralStringOther).push(&["ab-intp-string"]),
            rule(r"%[qsw]<").token(T::LiteralStringOther).push(&["ab-string"]),
            rule(r"%r<").token(T::LiteralStringRegex).push(&["ab-regex"]),
            rule(r"(%r([\W_]))((?:\\\2|(?!\2).)*)(\2[mixounse]*)").token(T::LiteralString),
            rule(r"%[qsw]([\W_])((?:\\\1|(?!\1).)*)\1").token(T::LiteralStringOther),
            rule(r"(%[QWx]([\W_]))((?:\\\2|(?!\2).)*)(\2)").token(T::LiteralString),
            rule(r"(?<=[-+/*%=<>&!^|~,(])(\s*)(%([\t ])(?:(?:\\\3|(?!\3).)*)\3)").groups(&[T::Text, T::LiteralStringOther, T::NoHighlight]),
            rule(r"^(\s*)(%([\t ])(?:(?:\\\3|(?!\3).)*)\3)").groups(&[T::Text, T::LiteralStringOther, T::NoHighlight]),
            rule(r"(%([^a-zA-Z0-9\s]))((?:\\\2|(?!\2).)*)(\2)").token(T::LiteralString),
        ]),
        ("simple-backtick", &[
            include("string-intp-escaped"),
            rule(r"[^\\`#]+").token(T::LiteralStringBacktick),
            rule(r"[\\#]").token(T::LiteralStringBacktick),
            rule(r"`").token(T::LiteralStringBacktick).pop(1),
        ]),
        ("ab-regex", &[
            rule(r"\\[\\<>]").token(T::LiteralStringRegex),
            rule(r"<").token(T::LiteralStringRegex).push(&[]),
            rule(r">[mixounse]*").token(T::LiteralStringRegex).pop(1),
            include("string-intp"),
            rule(r"[\\#<>]").token(T::LiteralStringRegex),
            rule(r"[^\\#<>]+").token(T::LiteralStringRegex),
        ]),
        ("cb-regex", &[
            rule(r"\\[\\{}]").token(T::LiteralStringRegex),
            rule(r"\{").token(T::LiteralStringRegex).push(&[]),
            rule(r"\}[mixounse]*").token(T::LiteralStringRegex).pop(1),
            include("string-intp"),
            rule(r"[\\#{}]").token(T::LiteralStringRegex),
            rule(r"[^\\#{}]+").token(T::LiteralStringRegex),
        ]),
        ("end-part", &[
            rule(r".+").token(T::CommentPreproc).pop(1),
        ]),
        ("string-intp", &[
            rule(r"#\{").token(T::LiteralStringInterpol).push(&["in-intp"]),
            rule(r"#@@?[a-zA-Z_]\w*").token(T::LiteralStringInterpol),
            rule(r"#\$[a-zA-Z_]\w*").token(T::LiteralStringInterpol),
        ]),
        ("interpolated-string", &[
            include("string-intp"),
            rule(r"[\\#]").token(T::LiteralStringOther),
            rule(r"[^\\#]+").token(T::LiteralStringOther),
        ]),
        ("classname", &[
            rule(r"\(").token(T::Punctuation).push(&["defexpr"]),
            rule(r"<<").token(T::Operator).pop(1),
            rule(r"[A-Z_]\w*").token(T::NameClass).pop(1),
            rule("").pop(1),
        ]),
        ("cb-intp-string", &[
            rule(r"\\[\\{}]").token(T::LiteralStringOther),
            rule(r"\{").token(T::LiteralStringOther).push(&[]),
            rule(r"\}").token(T::LiteralStringOther).pop(1),
            include("string-intp-escaped"),
            rule(r"[\\#{}]").token(T::LiteralStringOther),
            rule(r"[^\\#{}]+").token(T::LiteralStringOther),
        ]),
        ("root", &[
            rule(r"\A#!.+?$").token(T::CommentHashbang),
            rule(r"#.*?$").token(T::CommentSingle),
            rule(r"=begin\s.*?\n=end.*?$").token(T::CommentMultiline),
            rule(r"(defined\?|return|ensure|rescue|unless|undef|until|break|begin|elsif|super|alias|while|retry|BEGIN|raise|yield|redo|next|case|when|then|else|end|for|END|do|if|in)\b").token(T::Keyword),
            rule(r"(module)(\s+)([a-zA-Z_]\w*(?:::[a-zA-Z_]\w*)*)").groups(&[T::Keyword, T::Text, T::NameNamespace]),
            rule(r"(def)(\s+)").groups(&[T::Keyword, T::Text]).push(&["funcname"]),
            rule(r"def(?=[*%&^`~+-/\[<>=])").token(T::Keyword).push(&["funcname"]),
            rule(r"(class)(\s+)").groups(&[T::Keyword, T::Text]).push(&["classname"]),
            rule(r"(module_function|attr_accessor|attr_reader|attr_writer|initialize|protected|include|private|extend|public|raise|false|catch|throw|attr|loop|true|new|nil)\b").token(T::KeywordPseudo),
            rule(r"(not|and|or)\b").token(T::OperatorWord),
            rule(r"(protected_method_defined|private_method_defined|public_method_defined|method_defined|const_defined|block_given|instance_of|respond_to|iterator|autoload|kind_of|tainted|include|frozen|equal|is_a|nil|eql)\?").token(T::NameBuiltin),
            rule(r"(chomp|chop|exit|gsub|sub)!").token(T::NameBuiltin),
            rule(r"(?<!\.)(protected_instance_methods|private_instance_methods|public_instance_methods|instance_variable_set|instance_variable_get|private_class_method|public_class_method|instance_variables|protected_methods|singleton_methods|included_modules|instance_methods|global_variables|private_methods|local_variables|instance_method|class_variables|public_methods|const_defined\?|set_trace_func|method_missing|const_missing|instance_eval|module_eval|untrace_var|class_eval|trace_var|const_get|readlines|ancestors|constants|const_set|object_id|readline|autoload|__send__|untaint|methods|display|Integer|sprintf|inspect|require|syscall|at_exit|binding|extend|printf|lambda|__id__|String|callcc|method|select|format|system|freeze|caller|raise|Float|print|throw|taint|clone|srand|Array|abort|split|catch|chomp|sleep|open|puts|putc|fork|fail|trap|exit|scan|getc|self|send|eval|gets|exec|gsub|proc|load|loop|chop|warn|hash|test|name|to_a|rand|to_s|sub|dup|id|p)\b").token(T::NameBuiltin),
            rule(r"__(FILE|LINE)__\b").token(T::NameBuiltinPseudo),
            rule(r#"(?<!\w)(<<-?)(["`\']?)([a-zA-Z_]\w*)(\2)(.*?\n)"#).token(T::LiteralString),
            rule(r#"(<<-?)("|\')()(\2)(.*?\n)"#).token(T::LiteralString),
            rule(r"__END__").token(T::CommentPreproc).push(&["end-part"]),
            rule(r"(?:^|(?<=[=<>~!:])|(?<=(?:\s|;)when\s)|(?<=(?:\s|;)or\s)|(?<=(?:\s|;)and\s)|(?<=\.index\s)|(?<=\.scan\s)|(?<=\.sub\s)|(?<=\.sub!\s)|(?<=\.gsub\s)|(?<=\.gsub!\s)|(?<=\.match\s)|(?<=(?:\s|;)if\s)|(?<=(?:\s|;)elsif\s)|(?<=^when\s)|(?<=^index\s)|(?<=^scan\s)|(?<=^sub\s)|(?<=^gsub\s)|(?<=^sub!\s)|(?<=^gsub!\s)|(?<=^match\s)|(?<=^if\s)|(?<=^elsif\s))(\s*)(/)").groups(&[T::Text, T::LiteralStringRegex]).push(&["multiline-regex"]),
            rule(r"(?<=\(|,|\[)/").token(T::LiteralStringRegex).push(&["multiline-regex"]),
            rule(r"(\s+)(/)(?![\s=])").groups(&[T::Text, T::LiteralStringRegex]).push(&["multiline-regex"]),
            rule(r"(0_?[0-7]+(?:_[0-7]+)*)(\s*)([/?])?").groups(&[T::LiteralNumberOct, T::Text, T::Operator]),
            rule(r"(0x[0-9A-Fa-f]+(?:_[0-9A-Fa-f]+)*)(\s*)([/?])?").groups(&[T::LiteralNumberHex, T::Text, T::Operator]),
            rule(r"(0b[01]+(?:_[01]+)*)(\s*)([/?])?").groups(&[T::LiteralNumberBin, T::Text, T::Operator]),
            rule(r"([\d]+(?:[_e]\d+)*)(\s*)([/?])?").groups(&[T::LiteralNumberInteger, T::Text, T::Operator]),
            rule(r"@@[a-zA-Z_]\w*").token(T::NameVariableClass),
            rule(r"@[a-zA-Z_]\w*").token(T::NameVariableInstance),
            rule(r"\$\w+").token(T::NameVariableGlobal),
            rule(r#"\$[!@&`\'+~=/\\,;.<>_*$?:"^-]"#).token(T::NameVariableGlobal),
            rule(r"\$-[0adFiIlpvw]").token(T::NameVariableGlobal),
            rule(r"::").token(T::Operator),
            include("strings"),
            rule(r#"\?(\\[MC]-)*(\\([\\abefnrstv#"\']|x[a-fA-F0-9]{1,2}|[0-7]{1,3})|\S)(?!\w)"#).token(T::LiteralStringChar),
            rule(r"[A-Z]\w+").token(T::NameConstant),
            rule(r"(\.|::)(===|\[\]=|<=>|\*\*|==|>=|\+@|<>|>>|<<|-@|\[\]|~|`|\^|\||&|<|%|/|>|\+|-|\*)").groups(&[T::Operator, T::NameOperator]),
            rule(r"(\.|::)([a-zA-Z_]\w*[!?]?|[*%&^`~+\-/\[<>=])").groups(&[T::Operator, T::Name]),
            rule(r"[a-zA-Z_]\w*[!?]?").token(T::Name),
            rule(r"(\[|\]|\*\*|<<?|>>?|>=|<=|<=>|=~|={3}|!~|&&?|\|\||\.{1,3})").token(T::Operator),
            rule(r"[-+/*%=<>&!^|~]=?").token(T::Operator),
            rule(r"[(){};,/?:\\]").token(T::Punctuation),
            rule(r"\s+").token(T::Text),
        ]),
        ("defexpr", &[
            rule(r"(\))(\.|::)?").groups(&[T::Punctuation, T::Operator]).pop(1),
            rule(r"\(").token(T::Operator).push(&[]),
            include("root"),
        ]),
        ("in-intp", &[
            rule(r"\{").token(T::LiteralStringInterpol).push(&[]),
            rule(r"\}").token(T::LiteralStringInterpol).pop(1),
            include("root"),
        ]),
        ("multiline-regex", &[
            include("string-intp"),
            rule(r"\\\\").token(T::LiteralStringRegex),
            rule(r"\\/").token(T::LiteralStringRegex),
            rule(r"[\\#]").token(T::LiteralStringRegex),
            rule(r"[^\\/#]+").token(T::LiteralStringRegex),
            rule(r"/[mixounse]*").token(T::LiteralStringRegex).pop(1),
        ]),
        ("cb-string", &[
            rule(r"\\[\\{}]").token(T::LiteralStringOther),
            rule(r"\{").token(T::LiteralStringOther).push(&[]),
            rule(r"\}").token(T::LiteralStringOther).pop(1),
            rule(r"[\\#{}]").token(T::LiteralStringOther),
            rule(r"[^\\#{}]+").token(T::LiteralStringOther),
        ]),
        ("funcname", &[
            rule(r"\(").token(T::Punctuation).push(&["defexpr"]),
            rule(r"(?:([a-zA-Z_]\w*)(\.))?([a-zA-Z_]\w*[!?]?|\*\*?|[-+]@?|[/%&|^`~]|\[\]=?|<<|>>|<=?>|>=?|===?)").groups(&[T::NameClass, T::Operator, T::NameFunction]).pop(1),
            rule("").pop(1),
        ]),
        ("sb-intp-string", &[
            rule(r"\\[\\\[\]]").token(T::LiteralStringOther),
            rule(r"\[").token(T::LiteralStringOther).push(&[]),
            rule(r"\]").token(T::LiteralStringOther).pop(1),
            include("string-intp-escaped"),
            rule(r"[\\#\[\]]").token(T::LiteralStringOther),
            rule(r"[^\\#\[\]]+").token(T::LiteralStringOther),
        ]),
        ("pa-string", &[
            rule(r"\\[\\()]").token(T::LiteralStringOther),
            rule(r"\(").token(T::LiteralStringOther).push(&[]),
            rule(r"\)").token(T::LiteralStringOther).pop(1),
            rule(r"[\\#()]").token(T::LiteralStringOther),
            rule(r"[^\\#()]+").token(T::LiteralStringOther),
        ]),
        ("string-intp-escaped", &[
            include("string-intp"),
            rule(r#"\\([\\abefnrstv#"\']|x[a-fA-F0-9]{1,2}|[0-7]{1,3})"#).token(T::LiteralStringEscape),
        ]),
        ("simple-string", &[
            include("string-intp-escaped"),
            rule(r##"[^\\"#]+"##).token(T::LiteralStringDouble),
            rule(r"[\\#]").token(T::LiteralStringDouble),
            rule(r#"""#).token(T::LiteralStringDouble).pop(1),
        ]),
        ("pa-intp-string", &[
            rule(r"\\[\\()]").token(T::LiteralStringOther),
            rule(r"\(").token(T::LiteralStringOther).push(&[]),
            rule(r"\)").token(T::LiteralStringOther).pop(1),
            include("string-intp-escaped"),
            rule(r"[\\#()]").token(T::LiteralStringOther),
            rule(r"[^\\#()]+").token(T::LiteralStringOther),
        ]),
        ("ab-string", &[
            rule(r"\\[\\<>]").token(T::LiteralStringOther),
            rule(r"<").token(T::LiteralStringOther).push(&[]),
            rule(r">").token(T::LiteralStringOther).pop(1),
            rule(r"[\\#<>]").token(T::LiteralStringOther),
            rule(r"[^\\#<>]+").token(T::LiteralStringOther),
        ]),
        ("sb-regex", &[
            rule(r"\\[\\\[\]]").token(T::LiteralStringRegex),
            rule(r"\[").token(T::LiteralStringRegex).push(&[]),
            rule(r"\][mixounse]*").token(T::LiteralStringRegex).pop(1),
            include("string-intp"),
            rule(r"[\\#\[\]]").token(T::LiteralStringRegex),
            rule(r"[^\\#\[\]]+").token(T::LiteralStringRegex),
        ]),
        ("pa-regex", &[
            rule(r"\\[\\()]").token(T::LiteralStringRegex),
            rule(r"\(").token(T::LiteralStringRegex).push(&[]),
            rule(r"\)[mixounse]*").token(T::LiteralStringRegex).pop(1),
            include("string-intp"),
            rule(r"[\\#()]").token(T::LiteralStringRegex),
            rule(r"[^\\#()]+").token(T::LiteralStringRegex),
        ]),
        ("sb-string", &[
            rule(r"\\[\\\[\]]").token(T::LiteralStringOther),
            rule(r"\[").token(T::LiteralStringOther).push(&[]),
            rule(r"\]").token(T::LiteralStringOther).pop(1),
            rule(r"[\\#\[\]]").token(T::LiteralStringOther),
            rule(r"[^\\#\[\]]+").token(T::LiteralStringOther),
        ]),
        ("ab-intp-string", &[
            rule(r"\\[\\<>]").token(T::LiteralStringOther),
            rule(r"<").token(T::LiteralStringOther).push(&[]),
            rule(r">").token(T::LiteralStringOther).pop(1),
            include("string-intp-escaped"),
            rule(r"[\\#<>]").token(T::LiteralStringOther),
            rule(r"[^\\#<>]+").token(T::LiteralStringOther),
        ]),
    ],
};
