//! Chroma's `rust.xml` lexer, converted to Rust (crate README, "Lexer and style files").

use crate::chroma::defs::prelude::*;

#[rustfmt::skip]
pub(crate) static LEXER: LexerDef = LexerDef {
    file: "rust",
    config: ConfigDef {
        name: "Rust",
        aliases: &["rust", "rs"],
        filenames: &["*.rs", "*.rs.in"],
        mime_types: &["text/rust", "text/x-rust"],
        ensure_nl: true,
        ..ConfigDef::EMPTY
    },
    states: &[
        ("modname", &[
            rule(r"\s+").token(T::Text),
            rule(r"[a-zA-Z_]\w*").token(T::NameNamespace).pop(1),
            rule("").pop(1),
        ]),
        ("lifetime", &[
            rule(r"[a-zA-Z_]+\w*").token(T::NameAttribute),
            rule("").pop(1),
        ]),
        ("number_lit", &[
            rule(r"[ui](8|16|32|64|size)").token(T::Keyword).pop(1),
            rule(r"f(32|64)").token(T::Keyword).pop(1),
            rule("").pop(1),
        ]),
        ("attribute_common", &[
            rule(r#"""#).token(T::LiteralString).push(&["string"]),
            rule(r"\[").token(T::CommentPreproc).push(&["attribute["]),
        ]),
        ("bytestring", &[
            rule(r"\\x[89a-fA-F][0-9a-fA-F]").token(T::LiteralStringEscape),
            include("string"),
        ]),
        ("comment", &[
            rule(r"[^*/]+").token(T::CommentMultiline),
            rule(r"/\*").token(T::CommentMultiline).push(&[]),
            rule(r"\*/").token(T::CommentMultiline).pop(1),
            rule(r"[*/]").token(T::CommentMultiline),
        ]),
        ("doccomment", &[
            rule(r"[^*/]+").token(T::LiteralStringDoc),
            rule(r"/\*").token(T::LiteralStringDoc).push(&[]),
            rule(r"\*/").token(T::LiteralStringDoc).pop(1),
            rule(r"[*/]").token(T::LiteralStringDoc),
        ]),
        ("funcname", &[
            rule(r"\s+").token(T::Text),
            rule(r"[a-zA-Z_]\w*").token(T::NameFunction).pop(1),
            rule("").pop(1),
        ]),
        ("formatted_string", &[
            rule(r#"""#).token(T::LiteralString).pop(1),
            rule(r#"\\['"\\nrt]|\\(?=\n)|\\x[0-7][0-9a-fA-F]|\\0|\\u\{[0-9a-fA-F]{1,6}\}|\{\{|\}\}"#).token(T::LiteralStringEscape),
            rule(r"\{[^}]*\}").token(T::LiteralStringInterpol),
            rule(r#"[^\\"\{\}]+"#).token(T::LiteralString),
            rule(r"\\").token(T::LiteralString),
        ]),
        ("string", &[
            rule(r#"""#).token(T::LiteralString).pop(1),
            rule(r#"\\['"\\nrt]|\\(?=\n)|\\x[0-7][0-9a-fA-F]|\\0|\\u\{[0-9a-fA-F]{1,6}\}"#).token(T::LiteralStringEscape),
            rule(r#"[^\\"]+"#).token(T::LiteralString),
            rule(r"\\").token(T::LiteralString),
        ]),
        ("root", &[
            rule(r"#![^[\r\n].*$").token(T::CommentPreproc),
            rule("").push(&["base"]),
        ]),
        ("attribute[", &[
            include("attribute_common"),
            rule(r"\]").token(T::CommentPreproc).pop(1),
            rule(r#"[^"\]\[]+"#).token(T::CommentPreproc),
        ]),
        ("base", &[
            rule(r"\n").token(T::TextWhitespace),
            rule(r"\s+").token(T::TextWhitespace),
            rule(r"//!.*?\n").token(T::LiteralStringDoc),
            rule(r"///(\n|[^/].*?\n)").token(T::LiteralStringDoc),
            rule(r"//(.*?)\n").token(T::CommentSingle),
            rule(r"/\*\*(\n|[^/*])").token(T::LiteralStringDoc).push(&["doccomment"]),
            rule(r"/\*!").token(T::LiteralStringDoc).push(&["doccomment"]),
            rule(r"/\*").token(T::CommentMultiline).push(&["comment"]),
            rule(r#"""#).token(T::LiteralString).push(&["string"]),
            rule(r"\$([a-zA-Z_]\w*|\(,?|\),?|,?)").token(T::CommentPreproc),
            rule(r"(unsafe|static|extern|return|const|crate|where|while|await|trait|super|async|match|impl|else|move|loop|pub|ref|mut|for|dyn|use|box|in|if|as)\b").token(T::Keyword),
            rule(r"(abstract|override|unsized|virtual|become|typeof|final|macro|yield|priv|try|do)\b").token(T::KeywordReserved),
            rule(r"(true|false)\b").token(T::KeywordConstant),
            rule(r"self\b").token(T::NameBuiltinPseudo),
            rule(r"mod\b").token(T::Keyword).push(&["modname"]),
            rule(r"let\b").token(T::KeywordDeclaration),
            rule(r"fn\b").token(T::Keyword).push(&["funcname"]),
            rule(r"(struct|enum|type|union)\b").token(T::Keyword).push(&["typename"]),
            rule(r"(default)(\s+)(type|fn)\b").groups(&[T::Keyword, T::Text, T::Keyword]),
            rule(r"(isize|usize|bool|char|u128|i128|i64|i32|i16|str|u64|u32|f32|f64|u16|i8|u8)\b").token(T::KeywordType),
            rule(r"[sS]elf\b").token(T::NameBuiltinPseudo),
            rule(r"(DoubleEndedIterator|ExactSizeIterator|IntoIterator|PartialOrd|PartialEq|ToString|Iterator|ToOwned|Default|Result|String|FnOnce|Extend|Option|FnMut|Unpin|Sized|AsRef|AsMut|Clone|None|From|Into|Sync|drop|Send|Drop|Copy|Some|Ord|Err|Box|Vec|Eq|Ok|Fn)\b").token(T::NameBuiltin),
            rule(r"::\b").token(T::Text),
            rule(r"(?::|->)").token(T::Text).push(&["typename"]),
            rule(r"(break|continue)(\b\s*)(\'[A-Za-z_]\w*)?").groups(&[T::Keyword, T::TextWhitespace, T::NameLabel]),
            rule(r#"'(\\['"\\nrt]|\\x[0-7][0-9a-fA-F]|\\0|\\u\{[0-9a-fA-F]{1,6}\}|.)'"#).token(T::LiteralStringChar),
            rule(r#"(b)('(?:\\['"\\nrt]|\\x[0-9a-fA-F]{2}|\\0|.)')"#).groups(&[T::LiteralStringAffix, T::LiteralStringChar]),
            rule(r"0b[01_]+").token(T::LiteralNumberBin).push(&["number_lit"]),
            rule(r"0o[0-7_]+").token(T::LiteralNumberOct).push(&["number_lit"]),
            rule(r"0[xX][0-9a-fA-F_]+").token(T::LiteralNumberHex).push(&["number_lit"]),
            rule(r"[0-9][0-9_]*(\.[0-9_]+[eE][+\-]?[0-9_]+|\.[0-9_]*(?!\.)|[eE][+\-]?[0-9_]+)").token(T::LiteralNumberFloat).push(&["number_lit"]),
            rule(r"[0-9][0-9_]*").token(T::LiteralNumberInteger).push(&["number_lit"]),
            rule(r#"(b)(")"#).groups(&[T::LiteralStringAffix, T::LiteralString]).push(&["bytestring"]),
            rule(r#"(?s)(b?r)(#*)(".*?"\2)"#).groups(&[T::LiteralStringAffix, T::LiteralString, T::LiteralString]),
            rule(r"'(static|_)").token(T::NameBuiltin),
            rule(r"'").token(T::NameAttribute).push(&["lifetime"]),
            rule(r"\.\.=?").token(T::Operator),
            rule(r"[{}()\[\],.;]").token(T::Punctuation),
            rule(r"[+\-*/%&|<>^!~@=:?]").token(T::Operator),
            rule(r"\b(r#)?_?([A-Z][A-Z0-9_]*){2,}\b").token(T::NameConstant),
            rule(r#"((?:e?print(?:ln)?|format(?:_args)?|panic|todo|un(?:reachable|implemented))!)(\s*)(\()(\s*)(")"#).groups(&[T::NameFunctionMagic, T::TextWhitespace, T::Punctuation, T::TextWhitespace, T::LiteralString]).push(&["formatted_string"]),
            rule(r"([a-zA-Z_]\w*!)(\s*)(\(|\[|\{)").groups(&[T::NameFunctionMagic, T::TextWhitespace, T::Punctuation]),
            rule(r"(r#)?[a-zA-Z_]\w*").token(T::Name),
            rule(r"r#[a-zA-Z_]\w*").token(T::Name),
            rule(r"#!?\[").token(T::CommentPreproc).push(&["attribute["]),
            rule(r"#").token(T::Text),
        ]),
        ("typename", &[
            rule(r"\s+").token(T::Text),
            rule(r"&").token(T::KeywordPseudo),
            rule(r"'(static|_)").token(T::NameBuiltin),
            rule(r"'").token(T::NameAttribute).push(&["lifetime"]),
            rule(r"(DoubleEndedIterator|ExactSizeIterator|IntoIterator|PartialOrd|PartialEq|ToString|Iterator|ToOwned|Default|Result|String|FnOnce|Extend|Option|FnMut|Unpin|Sized|AsRef|AsMut|Clone|None|From|Into|Sync|drop|Send|Drop|Copy|Some|Ord|Err|Box|Vec|Eq|Ok|Fn)\b").token(T::NameBuiltin),
            rule(r"(isize|usize|bool|char|u128|i128|i64|i32|i16|str|u64|u32|f32|f64|u16|i8|u8)\b").token(T::KeywordType),
            rule(r"[a-zA-Z_]\w*").token(T::NameClass).pop(1),
            rule("").pop(1),
        ]),
    ],
};
