//! Chroma's `standard_ml.xml` lexer, converted to Rust (crate README, "Lexer and style files").

use crate::chroma::defs::prelude::*;

#[rustfmt::skip]
pub(crate) static LEXER: LexerDef = LexerDef {
    file: "standard_ml",
    config: ConfigDef {
        name: "Standard ML",
        aliases: &["sml"],
        filenames: &["*.sml", "*.sig", "*.fun"],
        mime_types: &["text/x-standardml", "application/x-standardml"],
        ..ConfigDef::EMPTY
    },
    states: &[
        ("delimiters", &[
            rule(r"\(|\[|\{").token(T::Punctuation).push(&["main"]),
            rule(r"\)|\]|\}").token(T::Punctuation).pop(1),
            rule(r"\b(let|if|local)\b(?!\')").token(T::KeywordReserved).push(&["main", "main"]),
            rule(r"\b(struct|sig|while)\b(?!\')").token(T::KeywordReserved).push(&["main"]),
            rule(r"\b(do|else|end|in|then)\b(?!\')").token(T::KeywordReserved).pop(1),
        ]),
        ("root", &[
            rule("").push(&["main"]),
        ]),
        ("breakout", &[
            rule(r"(?=\b(where|do|handle|if|sig|op|while|case|as|else|signature|andalso|struct|infixr|functor|in|structure|then|local|rec|end|fun|of|orelse|val|include|fn|with|exception|let|and|infix|sharing|datatype|type|abstype|withtype|eqtype|nonfix|raise|open)\b(?!\'))").token(T::Text).pop(1),
        ]),
        ("tyvarseq", &[
            rule(r"\s").token(T::Text),
            rule(r"\(\*").token(T::CommentMultiline).push(&["comment"]),
            rule(r"\'[\w\']*").token(T::NameDecorator),
            rule(r"[a-zA-Z][\w']*").token(T::Name),
            rule(r",").token(T::Punctuation),
            rule(r"\)").token(T::Punctuation).pop(1),
            rule(r"[!%&$#+\-/:<=>?@\\~`^|*]+").token(T::Name),
        ]),
        ("char", &[
            rule(r#"[^"\\]"#).token(T::LiteralStringChar),
            rule(r#"\\[\\"abtnvfr]"#).token(T::LiteralStringEscape),
            rule(r"\\\^[\x40-\x5e]").token(T::LiteralStringEscape),
            rule(r"\\[0-9]{3}").token(T::LiteralStringEscape),
            rule(r"\\u[0-9a-fA-F]{4}").token(T::LiteralStringEscape),
            rule(r"\\\s+\\").token(T::LiteralStringInterpol),
            rule(r#"""#).token(T::LiteralStringChar).pop(1),
        ]),
        ("datbind", &[
            include("whitespace"),
            rule(r"\b(and)\b(?!\')").token(T::KeywordReserved).push(&["#pop", "dname"]),
            rule(r"\b(withtype)\b(?!\')").token(T::KeywordReserved).push(&["#pop", "tname"]),
            rule(r"\b(of)\b(?!\')").token(T::KeywordReserved),
            rule(r"(\|)(\s*)([a-zA-Z][\w']*)").groups(&[T::Punctuation, T::Text, T::NameClass]),
            rule(r"(\|)(\s+)([!%&$#+\-/:<=>?@\\~`^|*]+)").groups(&[T::Punctuation, T::Text, T::NameClass]),
            include("breakout"),
            include("core"),
            rule(r"\S+").token(T::Error),
        ]),
        ("string", &[
            rule(r#"[^"\\]"#).token(T::LiteralStringDouble),
            rule(r#"\\[\\"abtnvfr]"#).token(T::LiteralStringEscape),
            rule(r"\\\^[\x40-\x5e]").token(T::LiteralStringEscape),
            rule(r"\\[0-9]{3}").token(T::LiteralStringEscape),
            rule(r"\\u[0-9a-fA-F]{4}").token(T::LiteralStringEscape),
            rule(r"\\\s+\\").token(T::LiteralStringInterpol),
            rule(r#"""#).token(T::LiteralStringDouble).pop(1),
        ]),
        ("tname", &[
            include("whitespace"),
            include("breakout"),
            rule(r"\'[\w\']*").token(T::NameDecorator),
            rule(r"\(").token(T::Punctuation).push(&["tyvarseq"]),
            rule(r"=(?![!%&$#+\-/:<=>?@\\~`^|*]+)").token(T::Punctuation).push(&["#pop", "typbind"]),
            rule(r"([a-zA-Z][\w']*)").token(T::KeywordType),
            rule(r"([!%&$#+\-/:<=>?@\\~`^|*]+)").token(T::KeywordType),
            rule(r"\S+").token(T::Error).pop(1),
        ]),
        ("dname", &[
            include("whitespace"),
            include("breakout"),
            rule(r"\'[\w\']*").token(T::NameDecorator),
            rule(r"\(").token(T::Punctuation).push(&["tyvarseq"]),
            rule(r"(=)(\s*)(datatype)").groups(&[T::Punctuation, T::Text, T::KeywordReserved]).pop(1),
            rule(r"=(?![!%&$#+\-/:<=>?@\\~`^|*]+)").token(T::Punctuation).push(&["#pop", "datbind", "datcon"]),
            rule(r"([a-zA-Z][\w']*)").token(T::KeywordType),
            rule(r"([!%&$#+\-/:<=>?@\\~`^|*]+)").token(T::KeywordType),
            rule(r"\S+").token(T::Error).pop(1),
        ]),
        ("typbind", &[
            include("whitespace"),
            rule(r"\b(and)\b(?!\')").token(T::KeywordReserved).push(&["#pop", "tname"]),
            include("breakout"),
            include("core"),
            rule(r"\S+").token(T::Error).pop(1),
        ]),
        ("ename", &[
            include("whitespace"),
            rule(r"(exception|and)\b(\s+)([a-zA-Z][\w']*)").groups(&[T::KeywordReserved, T::Text, T::NameClass]),
            rule(r"(exception|and)\b(\s*)([!%&$#+\-/:<=>?@\\~`^|*]+)").groups(&[T::KeywordReserved, T::Text, T::NameClass]),
            rule(r"\b(of)\b(?!\')").token(T::KeywordReserved),
            include("breakout"),
            include("core"),
            rule(r"\S+").token(T::Error),
        ]),
        ("vname", &[
            include("whitespace"),
            rule(r"\'[\w\']*").token(T::NameDecorator),
            rule(r"\(").token(T::Punctuation).push(&["tyvarseq"]),
            rule(r"([a-zA-Z][\w']*)(\s*)(=(?![!%&$#+\-/:<=>?@\\~`^|*]+))").groups(&[T::NameVariable, T::Text, T::Punctuation]).pop(1),
            rule(r"([!%&$#+\-/:<=>?@\\~`^|*]+)(\s*)(=(?![!%&$#+\-/:<=>?@\\~`^|*]+))").groups(&[T::NameVariable, T::Text, T::Punctuation]).pop(1),
            rule(r"([a-zA-Z][\w']*)").token(T::NameVariable).pop(1),
            rule(r"([!%&$#+\-/:<=>?@\\~`^|*]+)").token(T::NameVariable).pop(1),
            rule("").pop(1),
        ]),
        ("sname", &[
            include("whitespace"),
            include("breakout"),
            rule(r"([a-zA-Z][\w']*)").token(T::NameNamespace),
            rule("").pop(1),
        ]),
        ("main-fun", &[
            include("whitespace"),
            rule(r"\s").token(T::Text),
            rule(r"\(\*").token(T::CommentMultiline).push(&["comment"]),
            rule(r"\b(fun|and)\b(?!\')").token(T::KeywordReserved).push(&["fname"]),
            rule(r"\b(val)\b(?!\')").token(T::KeywordReserved).push(&["#pop", "main", "vname"]),
            rule(r"\|").token(T::Punctuation).push(&["fname"]),
            rule(r"\b(case|handle)\b(?!\')").token(T::KeywordReserved).push(&["#pop", "main"]),
            include("delimiters"),
            include("core"),
            rule(r"\S+").token(T::Error),
        ]),
        ("datcon", &[
            include("whitespace"),
            rule(r"([a-zA-Z][\w']*)").token(T::NameClass).pop(1),
            rule(r"([!%&$#+\-/:<=>?@\\~`^|*]+)").token(T::NameClass).pop(1),
            rule(r"\S+").token(T::Error).pop(1),
        ]),
        ("dotted", &[
            rule(r"([a-zA-Z][\w']*)(\.)").token(T::NameNamespace),
            rule(r"([a-zA-Z][\w']*)").token(T::Name).pop(1),
            rule(r"([!%&$#+\-/:<=>?@\\~`^|*]+)").token(T::Name).pop(1),
            rule(r"\s+").token(T::Error),
            rule(r"\S+").token(T::Error),
        ]),
        ("main", &[
            include("whitespace"),
            rule(r"\b(val|and)\b(?!\')").token(T::KeywordReserved).push(&["vname"]),
            rule(r"\b(fun)\b(?!\')").token(T::KeywordReserved).push(&["#pop", "main-fun", "fname"]),
            include("delimiters"),
            include("core"),
            rule(r"\S+").token(T::Error),
        ]),
        ("comment", &[
            rule(r"[^(*)]").token(T::CommentMultiline),
            rule(r"\(\*").token(T::CommentMultiline).push(&[]),
            rule(r"\*\)").token(T::CommentMultiline).pop(1),
            rule(r"[(*)]").token(T::CommentMultiline),
        ]),
        ("whitespace", &[
            rule(r"\s+").token(T::Text),
            rule(r"\(\*").token(T::CommentMultiline).push(&["comment"]),
        ]),
        ("core", &[
            rule(r"(_|\}|\{|\)|;|,|\[|\(|\]|\.\.\.)").token(T::Punctuation),
            rule(r#"#""#).token(T::LiteralStringChar).push(&["char"]),
            rule(r#"""#).token(T::LiteralStringDouble).push(&["string"]),
            rule(r"~?0x[0-9a-fA-F]+").token(T::LiteralNumberHex),
            rule(r"0wx[0-9a-fA-F]+").token(T::LiteralNumberHex),
            rule(r"0w\d+").token(T::LiteralNumberInteger),
            rule(r"~?\d+\.\d+[eE]~?\d+").token(T::LiteralNumberFloat),
            rule(r"~?\d+\.\d+").token(T::LiteralNumberFloat),
            rule(r"~?\d+[eE]~?\d+").token(T::LiteralNumberFloat),
            rule(r"~?\d+").token(T::LiteralNumberInteger),
            rule(r"#\s*[1-9][0-9]*").token(T::NameLabel),
            rule(r"#\s*([a-zA-Z][\w']*)").token(T::NameLabel),
            rule(r"#\s+([!%&$#+\-/:<=>?@\\~`^|*]+)").token(T::NameLabel),
            rule(r"\b(datatype|abstype)\b(?!\')").token(T::KeywordReserved).push(&["dname"]),
            rule(r"(?=\b(exception)\b(?!\'))").token(T::Text).push(&["ename"]),
            rule(r"\b(functor|include|open|signature|structure)\b(?!\')").token(T::KeywordReserved).push(&["sname"]),
            rule(r"\b(type|eqtype)\b(?!\')").token(T::KeywordReserved).push(&["tname"]),
            rule(r"\'[\w\']*").token(T::NameDecorator),
            rule(r"([a-zA-Z][\w']*)(\.)").token(T::NameNamespace).push(&["dotted"]),
            rule(r"\b(abstype|and|andalso|as|case|datatype|do|else|end|exception|fn|fun|handle|if|in|infix|infixr|let|local|nonfix|of|op|open|orelse|raise|rec|then|type|val|with|withtype|while|eqtype|functor|include|sharing|sig|signature|struct|structure|where)\b").token(T::KeywordReserved),
            rule(r"([a-zA-Z][\w']*)").token(T::Name),
            rule(r"\b(:|\|,=|=>|->|#|:>)\b").token(T::KeywordReserved),
            rule(r"([!%&$#+\-/:<=>?@\\~`^|*]+)").token(T::Name),
        ]),
        ("fname", &[
            include("whitespace"),
            rule(r"\'[\w\']*").token(T::NameDecorator),
            rule(r"\(").token(T::Punctuation).push(&["tyvarseq"]),
            rule(r"([a-zA-Z][\w']*)").token(T::NameFunction).pop(1),
            rule(r"([!%&$#+\-/:<=>?@\\~`^|*]+)").token(T::NameFunction).pop(1),
            rule("").pop(1),
        ]),
    ],
};
