//! Chroma's `typst.xml` lexer, converted to Rust (crate README, "Lexer and style files").

use crate::chroma::defs::prelude::*;

#[rustfmt::skip]
pub(crate) static LEXER: LexerDef = LexerDef {
    file: "typst",
    config: ConfigDef {
        name: "Typst",
        aliases: &["typst"],
        filenames: &["*.typ"],
        mime_types: &["text/x-typst"],
        ..ConfigDef::EMPTY
    },
    states: &[
        ("root", &[
            include("markup"),
        ]),
        ("into_code", &[
            rule(r"(\#let|\#set|\#show)\b").token(T::KeywordDeclaration).push(&["inline_code"]),
            rule(r"(\#import|\#include)\b").token(T::KeywordNamespace).push(&["inline_code"]),
            rule(r"(\#if|\#for|\#while|\#export)\b").token(T::KeywordReserved).push(&["inline_code"]),
            rule(r"#\{").token(T::Punctuation).push(&["code"]),
            rule(r"#\(").token(T::Punctuation).push(&["code"]),
            rule(r"(#[a-zA-Z_][a-zA-Z0-9_-]*)(\[)").groups(&[T::NameFunction, T::Punctuation]).push(&["markup"]),
            rule(r"(#[a-zA-Z_][a-zA-Z0-9_-]*)(\()").groups(&[T::NameFunction, T::Punctuation]).push(&["code"]),
            rule(r"(\#true|\#false|\#none|\#auto)\b").token(T::KeywordConstant),
            rule(r"#[a-zA-Z_][a-zA-Z0-9_]*").token(T::NameVariable),
            rule(r"#0x[0-9a-fA-F]+").token(T::LiteralNumberHex),
            rule(r"#0b[01]+").token(T::LiteralNumberBin),
            rule(r"#0o[0-7]+").token(T::LiteralNumberOct),
            rule(r"#[0-9]+[\.e][0-9]+").token(T::LiteralNumberFloat),
            rule(r"#[0-9]+").token(T::LiteralNumberInteger),
        ]),
        ("markup", &[
            include("comment"),
            rule(r"^\s*=+.*$").token(T::GenericHeading),
            rule(r"[*][^*]*[*]").token(T::GenericStrong),
            rule(r"_[^_]*_").token(T::GenericEmph),
            rule(r"\$").token(T::Punctuation).push(&["math"]),
            rule(r"`[^`]*`").token(T::LiteralStringBacktick),
            rule(r"^(\s*)(-)(\s+)").groups(&[T::TextWhitespace, T::Punctuation, T::TextWhitespace]),
            rule(r"^(\s*)(\+)(\s+)").groups(&[T::TextWhitespace, T::Punctuation, T::TextWhitespace]),
            rule(r"^(\s*)([0-9]+\.)").groups(&[T::TextWhitespace, T::Punctuation]),
            rule(r"^(\s*)(/)(\s+)([^:]+)(:)").groups(&[T::TextWhitespace, T::Punctuation, T::TextWhitespace, T::NameVariable, T::Punctuation]),
            rule(r"<[a-zA-Z_][a-zA-Z0-9_-]*>").token(T::NameLabel),
            rule(r"@[a-zA-Z_][a-zA-Z0-9_-]*").token(T::NameLabel),
            rule(r"\\#").token(T::Text),
            include("into_code"),
            rule(r"```(?:.|\n)*?```").token(T::LiteralStringBacktick),
            rule(r"https?://[0-9a-zA-Z~/%#&=\',;.+?]*").token(T::GenericEmph),
            rule(r"(\-\-\-|\\|\~|\-\-|\.\.\.)\B").token(T::Punctuation),
            rule(r"\\\[").token(T::Punctuation),
            rule(r"\\\]").token(T::Punctuation),
            rule(r"\[").token(T::Punctuation).push(&[]),
            rule(r"\]").token(T::Punctuation).pop(1),
            rule(r"[ \t]+\n?|\n").token(T::TextWhitespace),
            rule(r"((?![*_$`<@\\#\] ]|https?://).)+").token(T::Text),
        ]),
        ("math", &[
            include("comment"),
            rule(r"(\\_|\\\^|\\\&)").token(T::Text),
            rule(r"(_|\^|\&|;)").token(T::Punctuation),
            rule(r"(\+|/|=|\[\||\|\]|\|\||\*|:=|::=|\.\.\.|'|\-|=:|!=|>>|>=|>>>|<<|<=|<<<|\->|\|\->|=>|\|=>|==>|\-\->|\~\~>|\~>|>\->|\->>|<\-|<==|<\-\-|<\~\~|<\~|<\-<|<<\-|<\->|<=>|<==>|<\-\->|>|<|\~|:|\|)").token(T::Operator),
            rule(r"\\").token(T::Punctuation),
            rule(r"\\\$").token(T::Punctuation),
            rule(r"\$").token(T::Punctuation).pop(1),
            include("into_code"),
            rule(r"([a-zA-Z][a-zA-Z0-9-]*)(\s*)(\()").groups(&[T::NameFunction, T::TextWhitespace, T::Punctuation]),
            rule(r"([a-zA-Z][a-zA-Z0-9-]*)(:)").groups(&[T::NameVariable, T::Punctuation]),
            rule(r"([a-zA-Z][a-zA-Z0-9-]*)").token(T::NameVariable),
            rule(r"[0-9]+(\.[0-9]+)?").token(T::LiteralNumber),
            rule(r"\.{1,3}|\(|\)|,|\{|\}").token(T::Punctuation),
            rule(r#""[^"]*""#).token(T::LiteralStringDouble),
            rule(r"[ \t\n]+").token(T::TextWhitespace),
        ]),
        ("comment", &[
            rule(r"//.*$").token(T::CommentSingle),
            rule(r"/[*](.|\n)*?[*]/").token(T::CommentMultiline),
        ]),
        ("code", &[
            include("comment"),
            rule(r"\[").token(T::Punctuation).push(&["markup"]),
            rule(r"\(|\{").token(T::Punctuation).push(&["code"]),
            rule(r"\)|\}").token(T::Punctuation).pop(1),
            rule(r#""[^"]*""#).token(T::LiteralStringDouble),
            rule(r",|\.{1,2}").token(T::Punctuation),
            rule(r"=").token(T::Operator),
            rule(r"(and|or|not)\b").token(T::OperatorWord),
            rule(r"=>|<=|==|!=|>|<|-=|\+=|\*=|/=|\+|-|\\|\*").token(T::Operator),
            rule(r"([a-zA-Z_][a-zA-Z0-9_-]*)(:)").groups(&[T::NameVariable, T::Punctuation]),
            rule(r"([a-zA-Z_][a-zA-Z0-9_-]*)(\()").groups(&[T::NameFunction, T::Punctuation]).push(&["code"]),
            rule(r"(as|break|export|continue|else|for|if|in|return|while)\b").token(T::KeywordReserved),
            rule(r"(import|include)\b").token(T::KeywordNamespace),
            rule(r"(auto|none|true|false)\b").token(T::KeywordConstant),
            rule(r"([0-9.]+)(mm|pt|cm|in|em|fr|%)").groups(&[T::LiteralNumber, T::KeywordReserved]),
            rule(r"0x[0-9a-fA-F]+").token(T::LiteralNumberHex),
            rule(r"0b[01]+").token(T::LiteralNumberBin),
            rule(r"0o[0-7]+").token(T::LiteralNumberOct),
            rule(r"[0-9]+[\.e][0-9]+").token(T::LiteralNumberFloat),
            rule(r"[0-9]+").token(T::LiteralNumberInteger),
            rule(r"(let|set|show)\b").token(T::KeywordDeclaration),
            rule(r"([a-zA-Z_][a-zA-Z0-9_-]*)").token(T::NameVariable),
            rule(r"[ \t\n]+").token(T::TextWhitespace),
            rule(r":").token(T::Punctuation),
        ]),
        ("inline_code", &[
            rule(r";\b").token(T::Punctuation).pop(1),
            rule(r"\n").token(T::TextWhitespace).pop(1),
            include("code"),
        ]),
    ],
};
