//! Chroma's `v.xml` lexer, converted to Rust (crate README, "Lexer and style files").

use crate::chroma::defs::prelude::*;

#[rustfmt::skip]
pub(crate) static LEXER: LexerDef = LexerDef {
    file: "v",
    config: ConfigDef {
        name: "V",
        aliases: &["v", "vlang"],
        filenames: &["*.v", "*.vv", "v.mod"],
        mime_types: &["text/x-v"],
        ensure_nl: true,
        ..ConfigDef::EMPTY
    },
    states: &[
        ("root", &[
            rule(r"\n").token(T::Text),
            rule(r"\s+").token(T::Text),
            rule(r"\\\n").token(T::Text),
            rule(r"(?<=module\s+\w[^\n]*\s+)(//[^\n]+\n)+(?=\n)").token(T::LiteralStringDoc),
            rule(r"(// *)(\w+)([^\n]+\n)(?=(?://[^\n]*\n)* *(?:pub +)?(?:fn|struct|union|type|interface|enum|const) +\2\b)").groups(&[T::LiteralStringDoc, T::GenericEmph, T::LiteralStringDoc]).push(&["string-doc"]),
            rule(r"//[^\n]*\n").token(T::CommentSingle),
            rule(r"/\*(?:(?:/\*(?:.|\n)*?\*/)*|.|\n)*\*/").token(T::CommentMultiline),
            rule(r"\b(import|module)\b").token(T::KeywordNamespace),
            rule(r"\b(fn|struct|union|map|chan|type|interface|enum|const|mut|shared|pub|__global)\b").token(T::KeywordDeclaration),
            rule(r"\?").token(T::KeywordDeclaration),
            rule(r"(?<=\)\s*)!").token(T::KeywordDeclaration),
            rule(r"[ \t]*#include[^\n]+").using("c"),
            rule(r"[ \t]*#\w[^\n]*").token(T::CommentPreproc),
            rule(r"(sql)(\s+)(\w+)(\s+)({)([^}]*?)(})").bygroups(&[E::Token(T::Keyword), E::Token(T::Text), E::Token(T::Name), E::Token(T::Text), E::Token(T::Punctuation), E::Using("sql"), E::Token(T::Punctuation)]),
            rule(r"\$(?=\w)").token(T::Operator),
            rule(r"(?<=\$)(?:embed_file|pkgconfig|tmpl|env|compile_error|compile_warn)").token(T::NameBuiltin),
            rule(r"(asm)(\s+)(\w+)(\s*)({)([^}]*?)(})").bygroups(&[E::Token(T::Keyword), E::Token(T::Text), E::Token(T::KeywordType), E::Token(T::Text), E::Token(T::Punctuation), E::Using("nasm"), E::Token(T::Punctuation)]),
            rule(r"\b_(?:un)?likely_(?=\()").token(T::NameFunctionMagic),
            rule(r"(?<=\$if.+?(?:&&|\|\|)?)((no_segfault_handler|no_bounds_checking|little_endian|freestanding|no_backtrace|big_endian|cplusplus|dragonfly|prealloc|android|windows|no_main|solaris|darwin|clang|tinyc|glibc|mingw|haiku|macos|amd64|arm64|debug|linux|prod|msvc|test|hpux|mach|x32|x64|gcc|qnx|gnu|ios|mac|js))+").token(T::NameBuiltin),
            rule(r"@(VMOD_FILE|VEXEROOT|VMODROOT|METHOD|STRUCT|COLUMN|VHASH|FILE|LINE|VEXE|MOD|FN)\b").token(T::NameVariableMagic),
            rule(r"\b(?<!@)(__offsetof|isreftype|continue|volatile|typeof|static|unsafe|return|assert|sizeof|atomic|select|match|break|defer|rlock|lock|else|goto|for|in|is|as|or|if|go)\b").token(T::Keyword),
            rule(r"\b(?<!@)(none|true|false|si_s_code|si_g32_code|si_g64_code)\b").token(T::KeywordConstant),
            rule(r"\b(?<!@)(vstring_literal_with_len|utf8_str_visible_length|get_str_intp_u64_format|get_str_intp_u32_format|utf32_decode_to_buffer|utf32_to_str_no_malloc|panic_optional_not_set|panic_result_not_set|contains_any_substr|strip_margin_custom|starts_with_capital|cstring_to_vstring|winapi_lasterr_str|c_error_number_str|panic_error_number|substr_with_check|string_from_wide2|sort_with_compare|trim_string_right|string_from_wide|sort_ignore_case|trim_string_left|reverse_in_place|split_into_lines|vstring_with_len|compare_strings|all_before_last|print_backtrace|repeat_to_depth|length_in_bytes|error_with_code|vstring_literal|gc_check_leaks|clone_to_depth|vcalloc_noscan|all_after_last|utf8_char_len|panic_lasterr|memdup_noscan|malloc_noscan|str_intp_rune|last_index_u8|utf8_to_utf32|flush_stderr|flush_stdout|str_intp_sub|replace_each|replace_once|vstrlen_char|utf8_getchar|str_intp_g64|contains_any|find_between|realloc_data|strip_margin|utf32_to_str|is_bin_digit|is_hex_digit|is_oct_digit|proc_pidpath|str_intp_g32|delete_many|delete_last|str_escaped|index_after|sort_by_len|str_intp_sq|starts_with|trim_space|last_index|parse_uint|is_capital|trim_right|join_lines|capitalize|all_before|after_char|match_glob|utf32_code|eq_epsilon|tos_clone|substr_ni|v_realloc|push_many|is_letter|split_nth|split_any|trim_left|index_any|ascii_str|parse_int|all_after|ends_with|is_title|contains|eprintln|is_space|index_u8|is_digit|vmemmove|byterune|is_alnum|pointers|grow_len|is_lower|grow_cap|str_intp|to_upper|hex_full|len_utf8|is_upper|try_push|to_lower|compare|vmemset|try_pop|vcalloc|reverse|vmemcmp|vstring|replace|ptr_str|strlong|to_wide|bytestr|f32_abs|f32_max|println|f32_min|f64_max|vmemcpy|vstrlen|prepend|vbytes|strsci|substr|string|insert|eprint|filter|delete|repeat|malloc|memdup|fields|before|reduce|string|isize|count|index|title|bytes|clone|usize|error|after|split|runes|print|panic|first|close|limit|isnil|bool|rune|tos3|u128|hex2|i128|hash|code|tos4|free|exit|keys|tos2|last|trim|strg|tos5|move|copy|drop|sort|dump|join|free|cap|int|any|all|any|len|map|pop|hex|f64|f32|u16|msg|i64|i16|u32|str|tos|u64|i8|u8)(?=\()").token(T::NameBuiltin),
            rule(r"\b(?<!@)(StrIntpCgenData|VAssertMetaInfo|StructAttribute|AttributeKind|FunctionData|StrIntpData|StrIntpType|MethodArgs|StrIntpMem|ArrayFlags|FieldData|SortedMap|ChanState|string|array|Error|map)\b").token(T::NameBuiltin),
            rule(r"\b(?<!@)(voidptr|string|error|isize|usize|i128|u128|bool|rune|int|f32|f64|i64|i16|u64|any|u32|u16|i8|u8)\b").token(T::KeywordType),
            rule(r"\bit\b").token(T::NameVariableMagic),
            rule(r"(?<!fn\s+)(?<=\w+\s+|^)\[(?=:if +)?(?=\w+)").token(T::Punctuation).push(&["attribute"]),
            rule(r"(<<=|>>=|>>>=|>>>|<<|>>|<=|>=|\^=|\+=|-=|\*=|/=|%=|&=|\|=|&&|\|\||<-|\+\+|--|==|!=|:=|\.\.\.|\.\.|[+\-*/%&|^~=#@!])").token(T::Operator),
            rule(r"[\d_]+(\.\d+e[+\-]?\d+|\.\d+|e[+\-]?\d+)").token(T::LiteralNumberFloat),
            rule(r"\.\d+(e[+\-]?\d+)?").token(T::LiteralNumberFloat),
            rule(r"0o[0-7_]+").token(T::LiteralNumberOct),
            rule(r"0x[0-9a-fA-F_]+").token(T::LiteralNumberHex),
            rule(r"0b[01_]+").token(T::LiteralNumberBin),
            rule(r"(0|[1-9][0-9_]*)").token(T::LiteralNumberInteger),
            rule(r"`").token(T::LiteralStringChar).push(&["char"]),
            include("strings"),
            rule(r"@?[A-Z]\w*").token(T::NameClass),
            rule(r"(?<=[^\W\d]\w*)(<)([A-Z]\w*)(>)").groups(&[T::Punctuation, T::NameClass, T::Punctuation]),
            rule(r"@?[^\W\d]\w*(?=\()").token(T::NameFunction),
            rule(r"(?<=fn\s+)@?[^\W\d]\w*(?=\s*\()").token(T::NameFunction),
            rule(r"(?<=(?:continue|break|goto)\s+)\w+").token(T::NameLabel),
            rule(r"\b[^\W\d]\w*(?=:(?:$|\s+for))").token(T::NameLabel),
            rule(r"[<>()\[\]{}.,;:]").token(T::Punctuation),
            rule(r"@?[^\W\d]\w*").token(T::NameVariable),
        ]),
        ("char", &[
            rule(r"`").token(T::LiteralStringChar).pop(1),
            include("char-escape"),
            rule(r"[^\\]").token(T::LiteralStringChar),
        ]),
        ("string-doc", &[
            rule(r"(// *)(#+ [^\n]+)(\n)").groups(&[T::LiteralStringDoc, T::GenericHeading, T::Text]),
            rule(r"// *([=_*~-])\1{2,}\n").token(T::LiteralStringDelimiter),
            rule(r"//[^\n]*\n").token(T::LiteralStringDoc),
            rule("").mutators(&[M::Pop(1)]),
        ]),
        ("string-curly-interpolation", &[
            rule(r"}").token(T::Punctuation).pop(1),
            include("strings"),
            rule(r"(:)( *?)([ 0'#+-])?(?:(\.)?([0-9]+))?([fFgeEGxXobsd])?").groups(&[T::Punctuation, T::Text, T::Operator, T::Punctuation, T::LiteralNumber, T::LiteralStringAffix]),
            rule(r#"[^}"':]+"#).using_self("root"),
        ]),
        ("attribute", &[
            rule(r"\]").token(T::Punctuation).pop(1),
            rule(r"'").token(T::Punctuation).push(&["string-single"]),
            rule(r#"""#).token(T::Punctuation).push(&["string-double"]),
            rule(r"[;:]").token(T::Punctuation),
            rule(r"(?<=\[)if\b").token(T::Keyword),
            rule(r"\s+").token(T::Text),
            rule(r"(?<=: *)\w+").token(T::LiteralString),
            rule(r"[^\W\d]\w*").token(T::NameAttribute),
        ]),
        ("strings", &[
            rule(r#"(c)?(")"#).groups(&[T::LiteralStringAffix, T::LiteralStringDouble]).push(&["string-double"]),
            rule(r"(c)?(')").groups(&[T::LiteralStringAffix, T::LiteralStringSingle]).push(&["string-single"]),
            rule(r#"(r)("[^"]+")"#).groups(&[T::LiteralStringAffix, T::LiteralString]),
            rule(r"(r)('[^']+')").groups(&[T::LiteralStringAffix, T::LiteralString]),
        ]),
        ("string-double", &[
            rule(r#"""#).token(T::LiteralStringDouble).pop(1),
            include("char-escape"),
            rule(r"(\$)((?!\\){)").groups(&[T::Operator, T::Punctuation]).push(&["string-curly-interpolation"]),
            rule(r"\$").token(T::Operator).push(&["string-interpolation"]),
            rule(r#"[^"]+?"#).token(T::LiteralStringDouble),
        ]),
        ("string-single", &[
            rule(r"'").token(T::LiteralStringSingle).pop(1),
            include("char-escape"),
            rule(r"(\$)((?!\\){)").groups(&[T::Operator, T::Punctuation]).push(&["string-curly-interpolation"]),
            rule(r"\$").token(T::Operator).push(&["string-interpolation"]),
            rule(r"[^']+?").token(T::LiteralStringSingle),
        ]),
        ("char-escape", &[
            rule(r#"\\[`'"\\abfnrtv$]|\\x[0-9a-fA-F]{2}|\\[0-7]{1,3}|\\u[0-9a-fA-F]{4}|\\U[0-9a-fA-F]{8}"#).token(T::LiteralStringEscape),
        ]),
        ("string-interpolation", &[
            rule(r"(\.)?(@)?(?:([^\W\d]\w*)(\()([^)]*)(\))|([^\W\d]\w*))").bygroups(&[E::Token(T::Punctuation), E::Token(T::Operator), E::Token(T::NameFunction), E::Token(T::Punctuation), E::UsingSelf("root"), E::Token(T::Punctuation), E::Token(T::NameVariable)]),
            rule("").mutators(&[M::Pop(1)]),
        ]),
    ],
};
