//! Port of gift v1.2.1 `gift_test.go:TestGolden`: 28 filters applied to
//! gift's `testdata/src.png` compared with `testdata/dst_<name>.png`.
//!
//! The golden PNGs were generated by upstream on amd64, and Go's own test
//! allows a difference of 1 per byte on every other architecture because of
//! FMA (`goldenEqual`). The port has the arm64 semantics, so it runs the test
//! with that tolerance and additionally checks the exact arm64 result: for
//! every filter the number of bytes that differ from the golden and the
//! SHA-256 of the result pixels, both taken from gift's TestGolden built with
//! go1.27.1 for linux/arm64 and run under qemu-aarch64 (4 of the 28 images
//! differ from the amd64 goldens there: contrast_increase, hue_rotate,
//! saturation_decrease, saturation_increase; on amd64 all 28 are identical).
//!
//! Fixtures: `fixtures/gotestdata/dst_*.gz` are raw dumps of the decoded
//! golden PNGs (`tools/go-oracle/gift gotestdata`; PNG decoding is
//! integer-only), `fixtures/real/giftsrc.gz` is the decoded `src.png`.

mod common;

use std::sync::Arc;

use common::{fixtures_dir, hex, load_dump};
use gift::{
    CUBIC_INTERPOLATION, Filter, LANCZOS_RESAMPLING, LEFT_ANCHOR, brightness, color_balance,
    color_func, colorize, contrast, convolution, crop_to_size, gamma, gaussian_blur, grayscale,
    hue, invert, maximum, mean, median, minimum, pixelate, resize, rotate, rotate180, saturation,
    sepia, sigmoid_filter, unsharp_mask,
};
use go_image::NRGBA;
use go_image::color::{self, Color};
use sha2::{Digest, Sha256};

/// Go: gift_test.go:loadImageNRGBA (the image is a checked-in dump).
fn load_image_nrgba(name: &str) -> NRGBA {
    let img = load_dump(&fixtures_dir().join("gotestdata").join(format!("{name}.gz")));
    let mut nrgba = NRGBA::new(img.bounds());
    gift::new(vec![]).draw(&mut nrgba, &*img);
    nrgba
}

/// Go: gift_test.go:goldenEqual with `runtime.GOARCH != "amd64"` (maxDiff 1).
fn golden_equal(img1: &NRGBA, img2: &NRGBA) -> bool {
    let max_diff = 1;
    if !img1.rect.eq(img2.rect) {
        return false;
    }
    if img1.pix.len() != img2.pix.len() {
        return false;
    }
    for i in 0..img1.pix.len() {
        let diff = (img1.pix[i] as i64 - img2.pix[i] as i64).abs();
        if diff > max_diff {
            return false;
        }
    }
    true
}

// Go: gift_test.go:TestGolden
#[test]
fn test_golden() {
    let filters: Vec<(&str, Arc<dyn Filter>)> = vec![
        ("resize", resize(100, 0, &LANCZOS_RESAMPLING)),
        ("crop_to_size", crop_to_size(100, 100, LEFT_ANCHOR)),
        ("rotate_180", rotate180()),
        (
            "rotate_30",
            rotate(
                30.0,
                Color::Alpha16(color::TRANSPARENT),
                CUBIC_INTERPOLATION,
            ),
        ),
        ("brightness_increase", brightness(30.0)),
        ("brightness_decrease", brightness(-30.0)),
        ("contrast_increase", contrast(30.0)),
        ("contrast_decrease", contrast(-30.0)),
        ("saturation_increase", saturation(50.0)),
        ("saturation_decrease", saturation(-50.0)),
        ("gamma_1.5", gamma(1.5)),
        ("gamma_0.5", gamma(0.5)),
        ("gaussian_blur", gaussian_blur(1.0)),
        ("unsharp_mask", unsharp_mask(1.0, 1.0, 0.0)),
        ("sigmoid", sigmoid_filter(0.5, 7.0)),
        ("pixelate", pixelate(5)),
        ("colorize", colorize(240.0, 50.0, 100.0)),
        ("grayscale", grayscale()),
        ("sepia", sepia(100.0)),
        ("invert", invert()),
        ("mean", mean(5, true)),
        ("median", median(5, true)),
        ("minimum", minimum(5, true)),
        ("maximum", maximum(5, true)),
        ("hue_rotate", hue(45.0)),
        ("color_balance", color_balance(10.0, -10.0, -10.0)),
        (
            "color_func",
            color_func(|r0, g0, _b0, a0| {
                let r = 1.0 - r0;
                let g = g0 + 0.1;
                let b = 0.0;
                let a = a0;
                (r, g, b, a)
            }),
        ),
        (
            "convolution_emboss",
            convolution(
                vec![-1.0, -1.0, 0.0, -1.0, 1.0, 1.0, 0.0, 1.0, 1.0],
                false,
                false,
                false,
                0.0,
            ),
        ),
    ];

    // (name, bytes differing from the amd64 golden, SHA-256 of dst.Pix) of
    // go1.27.1 linux/arm64 (qemu-aarch64); see the module comment.
    let arm64: [(&str, usize, &str); 28] = [
        (
            "brightness_decrease",
            0,
            "77d5d07af2a7449e4b289936e980e4341b61e2c0ce1fab4833de714677f2a90c",
        ),
        (
            "brightness_increase",
            0,
            "3489b7ec926ada1148e30fa82d0f8663e7eae5e1b465c0f976c74619dde77f94",
        ),
        (
            "color_balance",
            0,
            "08c61599c217b318e145a4974e56291a1b2fc42ad66f4fab8cc8b2d183f497af",
        ),
        (
            "color_func",
            0,
            "79009422d2a060da21ed18b3351e24e73115878e236a8b15e68613df6fe131c9",
        ),
        (
            "colorize",
            0,
            "0831285ecc3ca3857fbbee2dc7c258609ae8d942fd9c42ca554a099eb3f7fa26",
        ),
        (
            "contrast_decrease",
            0,
            "41074d453862b48ca64f8f3af6fc58884d26c807d47945398179951aa7897e7d",
        ),
        (
            "contrast_increase",
            234,
            "b6e33a5ccfd11d330530c58070a01c7c849501b25b596d40c48a469a3f607ae4",
        ),
        (
            "convolution_emboss",
            0,
            "15507bded193d4227942a5e95b99358c5e67d8d24a0fe883dc9f83bcab62cc15",
        ),
        (
            "crop_to_size",
            0,
            "68596fbac2fd3be7cbb5cce0e746ea9fd6242d7a0dc6c9645fc42b28dc65f259",
        ),
        (
            "gamma_0.5",
            0,
            "461edb23699f9ffde4bbcbb5a3c11179a3baf308ecb0c028804974974b0ba2fd",
        ),
        (
            "gamma_1.5",
            0,
            "97daf93b8f46d714e89de0f266a5c7ec01257f74d3a1a85a0f58d00547b163ce",
        ),
        (
            "gaussian_blur",
            0,
            "84ae3c8b65a028031895faa83c52ee66f3c90e6c2f15a4473831e597618bf6c7",
        ),
        (
            "grayscale",
            0,
            "17e590fe3f3a507e3b9c92a7c614a204a125e5a2b825c8867749b84e60977f1b",
        ),
        (
            "hue_rotate",
            34,
            "19e558f19fe501ea1f2152c2312ab5d14a0cd384a5fa030ce75ab0ecfcfef512",
        ),
        (
            "invert",
            0,
            "20aa995faff2a3fc488ed49120d77bb0e5ffa905aa1baabc287ad45f698162e5",
        ),
        (
            "maximum",
            0,
            "99947dea4f22e5bf668c1f18a6295f4d9434a312e256507c20645e0ad2d578c2",
        ),
        (
            "mean",
            0,
            "f76dd0bfce511ccaee20849f54cbf012fbe704703b849e75707eb692507f23d9",
        ),
        (
            "median",
            0,
            "9b9774125b521d2b1a0e2a63628dc3ee3da0008d4fd16517cf28cfa293d748c2",
        ),
        (
            "minimum",
            0,
            "3f3ae0e69d735b0734150518e5eafa872fa7147c1aaf346d0ebe86532d1a5e80",
        ),
        (
            "pixelate",
            0,
            "9f0d5ab9a72f25b97379e09e4fee120add5b248dcb04c3092b19c66e6c49f428",
        ),
        (
            "resize",
            0,
            "c35c7cd43bb2cafc37bf85565f9c3c646448a582ac204b594df0402b88950088",
        ),
        (
            "rotate_180",
            0,
            "05a479ad182484c9053c47a2b248ab768e94ff05cf6bb62dba84730b2a079120",
        ),
        (
            "rotate_30",
            0,
            "e5daec63c4430e5b0821507ba87fffeca0a67e1a1b269cc75ddebdebc67b064a",
        ),
        (
            "saturation_decrease",
            57,
            "ec692d18dcbb1e25262670ea515a3f748f35bb950fb9d87a69b1571940696cd5",
        ),
        (
            "saturation_increase",
            52,
            "64c50071799e05116798ff21fa62a554fc2ad4733b8ec8c2f455dc2065cc5b94",
        ),
        (
            "sepia",
            0,
            "38a140c4b42e44a524486f3cb19e3b9742faa13e05b81d4878243380cd6d745e",
        ),
        (
            "sigmoid",
            0,
            "b57b170396c7c67b72d623a1092b0983b9516f479f81774ca9cd7272612287b2",
        ),
        (
            "unsharp_mask",
            0,
            "de1de9c1a8f3b6d11f455c57f9a4fd90aedf005406e97c551370ab07de09dc20",
        ),
    ];

    let src = load_dump(&fixtures_dir().join("real").join("giftsrc.gz"));
    assert_eq!(filters.len(), arm64.len());
    for (name, filter) in filters {
        let g = gift::new(vec![filter]);
        let mut dst = NRGBA::new(g.bounds(src.bounds()));
        g.draw(&mut dst, &*src);
        let want = load_image_nrgba(&format!("dst_{name}"));
        assert!(
            golden_equal(&dst, &want),
            "resulting image differs from golden: {name}"
        );

        let ndiff = dst
            .pix
            .iter()
            .zip(&want.pix)
            .filter(|(a, b)| a != b)
            .count();
        let (_, want_ndiff, want_sha) = arm64.iter().find(|(n, _, _)| *n == name).copied().unwrap();
        assert_eq!(ndiff, want_ndiff, "{name}: bytes differing from the golden");
        assert_eq!(
            hex(&Sha256::digest(&dst.pix)),
            want_sha,
            "{name}: result differs from go1.27.1 linux/arm64"
        );
    }
}
