//! Differential tests against fixtures generated by tools/go-oracle/go-fmt
//! (Go 1.27.1 fmt).

mod common;

use common::*;
use go_value::Value;

fn parse_ranges(s: &str) -> Vec<(usize, usize)> {
    if s.is_empty() {
        return Vec::new();
    }
    s.split(',')
        .map(|p| match p.split_once('-') {
            Some((a, b)) => (a.parse().unwrap(), b.parse().unwrap()),
            None => {
                let a = p.parse().unwrap();
                (a, a)
            }
        })
        .collect()
}

fn formats() -> Vec<Vec<u8>> {
    read_fixture("formats.txt").lines().map(unquote).collect()
}

/// Every operand of values.txt formatted with every format of formats.txt,
/// hashed per operand (the nondeterministic formats listed by the oracle
/// are skipped). On a mismatch, GO_FMT_DUMP_DIR=<dir> writes the Rust
/// outputs as `<dir>/<index>.txt`, comparable with `oracle -mode dump -value <index>`.
#[test]
fn matrix_hashes() {
    let formats = formats();
    let matrix = read_fixture("matrix.txt");
    let dump_dir = std::env::var_os("GO_FMT_DUMP_DIR");
    let mut failures = Vec::new();
    let mut hashed = 0usize;
    let mut lines = 0usize;
    for (vi, line) in matrix.lines().enumerate() {
        lines += 1;
        let parts: Vec<&str> = line.split('\t').collect();
        assert_eq!(parts.len(), 3, "bad matrix line {line:?}");
        let v = spec_value(parts[0]);
        let want = u64::from_str_radix(parts[1], 16).unwrap();
        let skip = parse_ranges(parts[2]);
        let mut h = Fnv64::new();
        let mut outs = Vec::new();
        for (fi, f) in formats.iter().enumerate() {
            let out = go_fmt::sprintf(f, std::slice::from_ref(&v));
            if skip.iter().any(|&(a, b)| a <= fi && fi <= b) {
                if dump_dir.is_some() {
                    outs.push(q(&out));
                }
                continue;
            }
            h.write(&(out.len() as u64).to_le_bytes());
            h.write(&out);
            hashed += 1;
            if dump_dir.is_some() {
                outs.push(q(&out));
            }
        }
        if h.0 != want {
            failures.push(format!("#{vi} {}", parts[0]));
            if let Some(d) = &dump_dir {
                let mut s = outs.join("\n");
                s.push('\n');
                std::fs::write(std::path::Path::new(d).join(format!("{vi}.txt")), s).unwrap();
            }
        }
    }
    assert!(lines > 200, "matrix too small");
    eprintln!("matrix: {lines} operands, {hashed} outputs compared");
    assert!(
        failures.is_empty(),
        "{} operands differ:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

fn resolve_args(field: &str, values: &[String]) -> Vec<Value> {
    if field.is_empty() {
        return Vec::new();
    }
    field
        .split(' ')
        .map(|a| match a.strip_prefix('@') {
            Some(i) => spec_value(&values[i.parse::<usize>().unwrap()]),
            None => spec_value(a),
        })
        .collect()
}

/// Random Sprint/Sprintln/Sprintf/Errorf cases (multi-operand formats, star
/// widths/precisions, argument indexes, MISSING/EXTRA/BADINDEX...).
#[test]
fn cases() {
    let values: Vec<String> = read_fixture("values.txt")
        .lines()
        .map(String::from)
        .collect();
    let cases = read_fixture("cases.txt");
    let mut failures = Vec::new();
    let mut n = 0;
    for line in cases.lines() {
        let parts: Vec<&str> = line.split('\t').collect();
        let fname = parts[0];
        let format = unquote(parts[1]);
        let args = resolve_args(parts[2], &values);
        let want = unquote(parts[3]);
        let got = match fname {
            "sprint" => go_fmt::sprint(&args),
            "sprintln" => go_fmt::sprintln(&args),
            "sprintf" => go_fmt::sprintf(&format, &args),
            "errorf" => {
                let (msg, wrapped) = go_fmt::errorf(&format, &args);
                let want_wrapped: Vec<usize> = if parts[4].is_empty() {
                    vec![]
                } else {
                    parts[4].split(',').map(|x| x.parse().unwrap()).collect()
                };
                if wrapped != want_wrapped {
                    failures.push(format!(
                        "errorf {} {}: wrapped {:?} want {:?}",
                        parts[1], parts[2], wrapped, want_wrapped
                    ));
                }
                msg
            }
            other => panic!("unknown fn {other}"),
        };
        n += 1;
        if got != want {
            failures.push(format!(
                "{fname} {} [{}]:\n  got  {}\n  want {}",
                parts[1],
                parts[2],
                q(&got),
                q(&want)
            ));
        }
    }
    assert!(n > 5000, "too few cases");
    eprintln!("cases: {n}");
    assert!(
        failures.is_empty(),
        "{} cases differ:\n{}",
        failures.len(),
        failures
            .iter()
            .take(40)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n")
    );
}

/// The entries of Go's fmt_test.go tables (fmtTests, reorderTests,
/// startests) whose operands the value model can express.
#[test]
fn go_fmt_test_tables() {
    let lines = read_fixture("fmttests.txt");
    let mut failures = Vec::new();
    let mut n = 0;
    for line in lines.lines() {
        let parts: Vec<&str> = line.split('\t').collect();
        assert_eq!(parts.len(), 4, "bad line {line:?}");
        let format = unquote(parts[1]);
        let args = spec_args(parts[2]);
        let want = unquote(parts[3]);
        let got = go_fmt::sprintf(&format, &args);
        n += 1;
        if got != want {
            failures.push(format!(
                "{} {} {}:\n  got  {}\n  want {}",
                parts[0],
                parts[1],
                parts[2],
                q(&got),
                q(&want)
            ));
        }
    }
    assert!(n > 500, "too few table entries");
    eprintln!("fmt_test.go entries: {n}");
    assert!(
        failures.is_empty(),
        "{} entries differ:\n{}",
        failures.len(),
        failures.join("\n")
    );
}
