package main

import (
	"bufio"
	"bytes"
	"compress/gzip"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"hash/fnv"
	"math/rand"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"sort"
	"strconv"
	"strings"
)

// Record format of every *.rec.gz fixture (gzip, binary safe):
//
//	#rec N\n
//	then N fields, each: <decimal length>\n<bytes>\n
//
// A `min` record is [cfg, input, output, err, after]:
//   - the input is minified from a private copy buf := cp(input) (Go
//     append growth, so the capacity is Go's) through buffer.NewReader(buf);
//   - err is "" for nil, "PANIC" when Go panicked, else err.Error();
//   - after is "" when buf[:cap(buf)] is unchanged, else "A" + buf[:cap(buf)]
//     (the minifier rewrites its input in place and leaves the NUL sentinel
//     of parse.NewInput in the spare capacity).
//
// A `sub` record is [cfg, prefix, js, suffix, output, err, after]: the js is
// minified from buf[len(prefix):len(prefix)+len(js)] of buf := cp(prefix+js+
// suffix), like the HTML minifier does with a <script> token, and after is
// the whole buf[:cap(buf)] ("" when unchanged).
//
// In digest files (fuzz*) the output, err and after fields are replaced by
// their FNV-1a 64 hex digests.

type recWriter struct {
	f    *os.File
	gz   *gzip.Writer
	w    *bufio.Writer
	n    int
	name string
}

func newRecWriter(dir, name string) *recWriter {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		panic(err)
	}
	p := filepath.Join(dir, name+".rec.gz")
	f, err := os.Create(p)
	if err != nil {
		panic(err)
	}
	gz, _ := gzip.NewWriterLevel(f, gzip.BestCompression)
	w := &recWriter{f: f, gz: gz, w: bufio.NewWriter(gz), name: p}
	w.rec([]byte("# generated by tools/go-oracle/tdewolff-minify-js (" + runtime.Version() + "); DO NOT EDIT"))
	return w
}

func (r *recWriter) rec(fields ...[]byte) {
	_, _ = fmt.Fprintf(r.w, "#rec %d\n", len(fields))
	for _, f := range fields {
		_, _ = fmt.Fprintf(r.w, "%d\n", len(f))
		_, _ = r.w.Write(f)
		_ = r.w.WriteByte('\n')
	}
	r.n++
}

func (r *recWriter) close() {
	if err := r.w.Flush(); err != nil {
		panic(err)
	}
	if err := r.gz.Close(); err != nil {
		panic(err)
	}
	if err := r.f.Close(); err != nil {
		panic(err)
	}
	fmt.Fprintf(os.Stderr, "%s: %d records\n", r.name, r.n-1)
}

func digest(b []byte) []byte {
	h := fnv.New64a()
	h.Write(b)
	return []byte(fmt.Sprintf("%016x", h.Sum64()))
}

// cp is append([]byte(nil), s...) (Go size-class capacity).
func cp(s []byte) []byte { return append([]byte(nil), s...) }

func errField(err error) []byte {
	if err == nil {
		return nil
	}
	if strings.HasPrefix(err.Error(), "PANIC") {
		return []byte("PANIC")
	}
	return []byte(err.Error())
}

// runMin minifies a private copy of in and returns the record fields
// [output, err, after].
func runMin(cfg string, in []byte) [][]byte {
	buf := cp(in)
	pristine := append([]byte(nil), buf[:cap(buf)]...)
	out, err := minifyBuf(cfg, buf)
	var after []byte
	if !bytes.Equal(buf[:cap(buf)], pristine) {
		after = append([]byte("A"), buf[:cap(buf)]...)
	}
	return [][]byte{out, errField(err), after}
}

// runSub minifies the js embedded between prefix and suffix of one buffer
// and returns [output, err, after-of-the-whole-buffer].
func runSub(cfg string, prefix, src, suffix []byte) [][]byte {
	whole := append(append(append([]byte(nil), prefix...), src...), suffix...)
	buf := cp(whole)
	pristine := append([]byte(nil), buf[:cap(buf)]...)
	out, err := minifyBuf(cfg, buf[len(prefix):len(prefix)+len(src)])
	var after []byte
	if !bytes.Equal(buf[:cap(buf)], pristine) {
		after = append([]byte("A"), buf[:cap(buf)]...)
	}
	return [][]byte{out, errField(err), after}
}

func digests(fields [][]byte) [][]byte {
	var d [][]byte
	for _, f := range fields {
		d = append(d, digest(f))
	}
	return d
}

func modCache() string {
	out, err := exec.Command("go", "env", "GOMODCACHE").Output()
	if err != nil {
		panic(err)
	}
	return strings.TrimSpace(string(out))
}

func minifyJSDir() string {
	return filepath.Join(modCache(), "github.com/tdewolff/minify/v2@v2.23.8/js")
}

func parseJSDir() string {
	return filepath.Join(modCache(), "github.com/tdewolff/parse/v2@v2.8.1/js")
}

// testLiterals returns every string literal of the upstream minify/js and
// parse/js test files plus the hand-written cases, deduplicated in order.
func testLiterals() [][]byte {
	var files []string
	for _, dir := range []string{minifyJSDir(), parseJSDir()} {
		m, err := filepath.Glob(filepath.Join(dir, "*_test.go"))
		if err != nil {
			panic(err)
		}
		sort.Strings(m)
		files = append(files, m...)
	}
	seen := map[string]bool{}
	var lits [][]byte
	add := func(s string) {
		if !seen[s] {
			seen[s] = true
			lits = append(lits, []byte(s))
		}
	}
	for _, e := range extraCases {
		add(e)
	}
	for _, e := range notCases() {
		add(e)
	}
	for _, fn := range files {
		fset := token.NewFileSet()
		f, err := parser.ParseFile(fset, fn, nil, 0)
		if err != nil {
			panic(err)
		}
		ast.Inspect(f, func(n ast.Node) bool {
			if bl, ok := n.(*ast.BasicLit); ok && bl.Kind == token.STRING {
				s, err := strconv.Unquote(bl.Value)
				if err == nil {
					add(s)
				}
			}
			return true
		})
	}
	return lits
}

// extraCases are hand-written inputs: the seeksnack inline scripts and
// handlers (docs/rust-port/specs/minify.md §2.6), the embedded Hugo
// templates' scripts, and constructs that stress the in-place rewrites,
// the renamer, hoisting and the statement/expression optimizers.
var extraCases = []string{
	// seeksnack (recorded Go inputs)
	"window.dataLayer = window.dataLayer || [];\n function gtag(){dataLayer.push(arguments);}\n gtag('js', new Date());\n\n gtag('config', 'UA-149754145-1');",
	"(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':\nnew Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],\nj=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=\n'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);\n})(window,document,'script','dataLayer','G-8E03TCKZZV');",
	"(adsbygoogle = window.adsbygoogle || []).push({});",
	"socialMediaPopUp(this.href, '', 900, 500); return false;",
	"socialMediaPopUp(this.href, '', 500, 500); return false;",
	"location = this.value;",
	// Hugo's embedded google_analytics.html / disqus.html (rendered)
	"\n        var doNotTrack = false;\n        if (false) {\n          var dnt = (navigator.doNotTrack || window.doNotTrack || navigator.msDoNotTrack);\n          var doNotTrack = (dnt == \"1\" || dnt == \"yes\");\n        }\n        if (!doNotTrack) {\n          window.dataLayer = window.dataLayer || [];\n          function gtag(){dataLayer.push(arguments);}\n          gtag('js', new Date());\n          gtag('config', 'G-12345');\n        }\n      ",
	"\n        var doNotTrack = false;\n        if (true) {\n          var dnt = (navigator.doNotTrack || window.doNotTrack || navigator.msDoNotTrack);\n          var doNotTrack = (dnt == \"1\" || dnt == \"yes\");\n        }\n        if (!doNotTrack) {\n          window.dataLayer = window.dataLayer || [];\n          function gtag(){dataLayer.push(arguments);}\n          gtag('js', new Date());\n          gtag('config', 'G-12345');\n        }\n      ",
	"\n    window.disqus_config = function () {\n    this.page.identifier = 'id';this.page.title = 'T';\n    \n    };\n    (function() {\n        if ([\"localhost\", \"127.0.0.1\"].indexOf(window.location.hostname) != -1) {\n            document.getElementById('disqus_thread').innerHTML = 'Disqus comments not available by default when the website is previewed locally.';\n            return;\n        }\n        var d = document, s = d.createElement('script'); s.async = true;\n        s.src = '//' + \"shortname\" + '.disqus.com/embed.js';\n        s.setAttribute('data-timestamp', +new Date());\n        (d.head || d.body).appendChild(s);\n    })();\n",
	// in-place rewrites and aliasing
	"function f(){x={foo};var foo}",
	"function f(){x={foo:1,foo};var foo;return foo}",
	"function f(){var a;return{a}}",
	"function f(){let {aaa, bbb} = o; return [aaa, bbb]}",
	"function f(){var [aaa, ...bbb] = o; return bbb}",
	"x=function(){var name='a'+'b'+\"c\"+`d`;return name}",
	"a='x'+'y'+b+'z'+'w'",
	"a=\"'\"+'\"'+`$`",
	"a='\\x41\\u0042\\u{43}\\103\\n\\r\\t\\v\\f\\b\\0'",
	"a='</script>'+\"<\\/script>\"+`</script>`",
	"a=/<\\/script>/;b=/[\\]\\-\\^]/g",
	"a</script>/",
	"a=1e3+0x1F+0b101+0o17+1_000_000+.5e-3+5.0+0.0+1n+0xFFn",
	"a=(1).toString()+(1.5).toFixed()+(0x10).x+1..x",
	"!function(){var a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19,a20,a21,a22,a23,a24,a25,a26,a27,a28,a29,a30,a31,a32,a33,a34,a35,a36,a37,a38,a39,a40,a41,a42,a43,a44,a45,a46,a47,a48,a49,a50,a51,a52,a53,a54,a55,a56,a57,a58,a59,a60;a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19,a20,a21,a22,a23,a24,a25,a26,a27,a28,a29,a30,a31,a32,a33,a34,a35,a36,a37,a38,a39,a40,a41,a42,a43,a44,a45,a46,a47,a48,a49,a50,a51,a52,a53,a54,a55,a56,a57,a58,a59,a60,a1++,a60++}()",
	"!function(){var t,n,e,r,i,o,u,a,c,s,f,l,h,p,d,v,g,y,m,b,w,x,_,k,C,E,S,T,A,O,M,j,N,P,R,I,L,D,F,z,B,U,H,q,W,V,G,$,Y,K,X,J,Q,Z,tt,nt;t,n,e,r,i,o,u,a,c,s,f,l,h,p,d,v,g,y,m,b,w,x,_,k,C,E,S,T,A,O,M,j,N,P,R,I,L,D,F,z,B,U,H,q,W,V,G,$,Y,K,X,J,Q,Z,tt,nt}()",
	"function f(){var do_,if_,in_;do_=1;if_=2;in_=3;return do_+if_+in_+ab+ac}",
	// hoisting and var merging
	"function f(a){var b=1;if(a){var c=2;for(var d in a);}var e=[a,b]=a,{g,h}=a;return c+d+e}",
	"function f(){var a;a=1;var b;b=2;var c=3,d;for(var e=0;;)d=e;return a+b+c}",
	"function f(){for(var a=0;;);for(var a=0;;);var b;while(b)b--}",
	"var a=1;var b=2;let c=3;let d=4;const e=5;const f=6",
	"function f(){let a=1;let b=2;{let a=3;a++}return a+b}",
	// if/else, return/throw merging
	"function f(a){if(a)return 1;else return 2}",
	"function f(a){if(a){b();return}c();return}",
	"function f(a){if(!a)return;b();if(a)throw 1;else throw 2}",
	"function f(a){if(a)return b;return c}",
	"function f(a){if(a)throw b;throw c}",
	"for(;;){if(a)continue;b()}",
	"if(a){b()}else if(c){d()}else{e()}",
	"if(!a){b()}else{c()}",
	"if(a);else b()",
	"if(a){}else{}",
	"if(a)if(b)c();else d()",
	"if(a){if(b)c()}else d()",
	"a:for(;;){if(b)break a;continue a}",
	"switch(a){case 1:b();break;case 2:{let c=1;c++}default:d()}",
	"try{a()}catch(e){b()}finally{c()}",
	"try{a()}catch(e){b(e)}",
	"do{a()}while(b)",
	"while(a){b()}",
	"with(a){b()}",
	// expressions
	"a==null?b:a",
	"a!=null?a:b",
	"a===null||a===void 0?void 0:a.b",
	"a===undefined||a===null?void 0:a.b.c()",
	"a==null?void 0:a[b]`t`",
	"typeof a==='undefined';'x'!==typeof b",
	"a?b(c):b(d)",
	"a?!0:!1;a?!1:!0;a?b:!0;a?!1:b",
	"!(a&&b);!(a||b);!(a==b||c!=d);!!a;!!(a<b)",
	"a?b?c:d:d",
	"(a,b)?c:d",
	"(a,b)&&c",
	"x=(a,b)&&c",
	"isNaN(a);isNaN(abcdefgh);Number(1);Number(true);Number(null);Number(0x10n);Number(undefined);Number(a)",
	"Math.pow(a,b);Math.pow(a+1,b*2);Math.trunc(a);Math.abs(a);Math.abs(abcdef);x=Math.pow(a,b)**2",
	"void 0;void a();undefined;Infinity;-Infinity;x=undefined.x;y=Infinity*2",
	"a+ +b;a- -b;a+ ++b;a- --b;a/ /b/;a< !--b;a-->b",
	"a in b;for(var x=(a in b);;);for(var y=[a in b];;);",
	"new A;new A();(new A).b;new A.b;new (A())();new new A()()",
	"a?.b;a?.[b];a?.(b);(a?.b).c;(a?.b)()",
	"`a${b}c${`d${e}`}f`;tag`\\x41${a}\\u0042`;a=`\\``",
	"let[a]=b;x=let[0]",
	"({}).a;({a}=b);[a,b]=[b,a];({a:b,...c}=d)",
	"(function(){})();(function f(){f()})();!function(){}();(()=>{})()",
	"(class{});(class A{static a=1;static{b()}#c;get d(){}set d(v){}static async*e(){}})",
	"async function f(){await a;for await(const b of c);}",
	"function*g(){yield;yield a;yield*b;yield undefined}",
	"a=>({});a=>({}).b;(a,b)=>{return a,b};async a=>a;async(a)=>a;()=>{a();return b}",
	"import a from'm';import{b as c,'d'as e}from\"m\";import*as f from'm';import'm';export{a,c as default};export*from'm';export*as g from'm';export default 1;export const h=1;export function i(){}export class j{}",
	"\"use strict\";'use strict';function f(){'use asm';a}",
	"/*! bang */a;//! line\nb",
	"#!/usr/bin/env node\na",
	"a=1;/*! x */",
	"var a=\"\\u2028\\u2029\"",
	"a=\"\\\n\"+'\\\r\n'+`\\\n`",
	"\x00a",
	"a\x00",
	"",
	" ",
	";",
	"{}",
	"(",
	"a=",
	"'\\u{110000}';'\\u{10FFFF}';'\\uD800';'\\u{0}0';'\\x00\\x31'",
	"\"\\8\\9\\78\\378\\400\"",
	// rarely reached branches (found with coverage of the Rust port)
	"x=Number(1.5)+Number(.5e3)+Number(1_0.0)+Number('1')+Number(a,b)+Number()",
	"x=isNaN()+isNaN(a,b)+isNaN(1)+isNaN(a.b)+Math.trunc()+Math.trunc(a,b)+Math.abs()+Math.abs(a,b)+Math.abs(1)+Math.pow(a)+Math.pow(a,b,c)",
	"x=null==a||void 0===a?b:a;y=(void 0===a||null===a)?void 0:a.b;z=null!=a&&a!==void 0?a.c:void 0",
	"x=a*'b'+'c';y='a'+b*'c'+'d';z=a-'b'+'c'+'d'",
	"x=\"\\q</script>\";y='\\a\\b</script>\\c';z=`\\q</script>`",
	"function f(){var a=1,{a:x}=o;var [x]=p;var y=1,{y:z}=q,[w]=r;return a+x+y+z+w}",
	"function f(){var a=1,{a}=o,[b]=c;var d;return a+b+d}",
	"function f(){for(var a in o);for(var b of p);}",
	"function f(){if(x)if(a)return;else return;b()}",
	"function f(){if(x)if(a)throw b;else throw c}",
	"function f(){if(x)if(a)return 1;else return 2}",
	"function f(){if(x)if(a)return;else return 2}",
	"function f(){if(x)if(a)b();else c()}",
	"function f(){var a=1;var b=2;for(var c;;);}",
	"function f(){var a=1;for(var c;;);var b}",
	"function f(){var a;b();for(var c;;)c++;var d=1}",
	"function f(){var a=1;b();for(var [c]=d;;);var e=1}",
	"function f(){a=1;for(var a,b;;);var c=2}",
	"x=void(a,b);y=void[a];z=void{a:1};w=void`x`;v=void{a:b()};u=void{[a]:1};t=void{a,b:c=1}",
	"if([1,2]);if([a()]);if({a:1});if({a:b()});if(`t`);if(a`t`);if((a,b));if((1,2));",
	"{let a=[1]}{let b={c:d}}{let c=`t${d}`}{let d=(e,f)}{const e=[f()]}{let f={[g]:1}}",
	"function f(){{var a=1}if(b){var c}else{var d=2}return a+c+d}",
	"function f(){let a;if(a===void 0||a===null)return;b(a)}",
	"a=>{a();return b};async a=>{await a;return}",
	"for(;;){a();continue}l:for(;;){continue l}",
	"x=void 1`${a}`;y=void function(){}`t${b}`;if((()=>1)`${c()}`);",
}

// notCases returns `!(X op Y)` in several contexts for many X, Y shapes
// (optimizeUnaryExpr's De Morgan rewrite with its grouping score).
func notCases() []string {
	xs := []string{"a", "a==b", "a!==b", "a|b", "a&&b", "a||b", "(a||b)", "(a&&b)", "a?b:c", "a=b", "!a", "a<b", "a??b", "(a,b)"}
	var out []string
	for _, x := range xs {
		for _, y := range xs {
			for _, op := range []string{"&&", "||"} {
				e := "!(" + x + op + y + ")"
				out = append(out, "x="+e+";if("+e+")f();y="+e+"?1:2;z=a+"+e+";w="+e+"&&c")
			}
		}
	}
	return out
}

// genFixtures writes every fixture file into dir. scale multiplies the
// random case counts; seed selects the random streams.
func genFixtures(dir string, scale int, seed int64) {
	lits := testLiterals()
	cfgs := []string{"v2022", "v2022-inline", "0", "keep", "keep-alpha", "alpha", "keep-alpha-v2019", "keep-alpha-v2014", "p3-v2022"}

	// literals: every literal through every configuration
	w := newRecWriter(dir, "literals")
	for _, src := range lits {
		for _, cfg := range cfgs {
			w.rec(append([][]byte{[]byte("min"), []byte(cfg), src}, runMin(cfg, src)...)...)
		}
	}
	w.close()

	// embedded: scripts inside a larger buffer (NUL sentinel and in-place
	// writes land in the surrounding bytes, as with the HTML minifier)
	w = newRecWriter(dir, "embedded")
	rnd := rand.New(rand.NewSource(seed))
	for k, src := range lits {
		if k%3 != 0 || len(src) == 0 {
			continue
		}
		pre := []byte("<script>")
		suf := []byte("</script><p>tail</p>")
		if rnd.Intn(2) == 0 {
			pre = []byte("<a onclick=\"")
			suf = []byte("\">x</a>")
		}
		cfg := "v2022"
		if rnd.Intn(3) == 0 {
			cfg = "v2022-inline"
		}
		w.rec(append([][]byte{[]byte("sub"), []byte(cfg), pre, src, suf}, runSub(cfg, pre, src, suf)...)...)
	}
	w.close()

	// html: the JS minifier called by the HTML minifier (neohugo's M)
	genHTML(dir, lits, seed+4)

	// adversarial: sort orders, many locals, deep nesting, long chains
	w = newRecWriter(dir, "adversarial")
	for _, src := range adversarialInputs(seed + 5) {
		for _, cfg := range []string{"v2022", "keep-alpha"} {
			w.rec(append([][]byte{[]byte("min"), []byte(cfg), src}, runMin(cfg, src)...)...)
		}
	}
	w.close()

	// grammar: generated programs (hugo config, and a few other
	// configurations for a subset; digests)
	w = newRecWriter(dir, "grammar")
	rnd = rand.New(rand.NewSource(seed + 1))
	for k := 0; k < 2000*scale; k++ {
		src := genProgram(rnd)
		cfg := "v2022"
		switch rnd.Intn(8) {
		case 0:
			cfg = "0"
		case 1:
			cfg = "keep-v2022"
		case 2:
			cfg = "v2022-inline"
		case 3:
			cfg = "alpha-v2019"
		}
		w.rec(append([][]byte{[]byte("min"), []byte(cfg), src}, digests(runMin(cfg, src))...)...)
	}
	w.close()

	// fuzz: mutated literals and mutated generated programs (digests)
	var nonEmpty [][]byte
	for _, l := range lits {
		if 0 < len(l) {
			nonEmpty = append(nonEmpty, l)
		}
	}
	w = newRecWriter(dir, "fuzz")
	rnd = rand.New(rand.NewSource(seed + 2))
	for k := 0; k < 18000*scale; k++ {
		var src []byte
		if rnd.Intn(9) != 0 {
			src = mutate(rnd, nonEmpty)
		} else {
			src = mutateOps(rnd, genProgram(rnd), nonEmpty, 1+rnd.Intn(2))
		}
		cfg := "v2022"
		if rnd.Intn(4) == 0 {
			cfg = cfgs[rnd.Intn(len(cfgs))]
		}
		w.rec(append([][]byte{[]byte("min"), []byte(cfg), src}, digests(runMin(cfg, src))...)...)
	}
	w.close()

	// repo: the neohugo repository's own JS files; a `multi` record is
	// [name, input, (cfg, output, err, after)...] with digests
	repo := repoRoot()
	w = newRecWriter(dir, "repo")
	for _, p := range jsFiles([]string{repo}) {
		src, err := os.ReadFile(p)
		if err != nil {
			panic(err)
		}
		rel, _ := filepath.Rel(repo, p)
		fields := [][]byte{[]byte("multi"), []byte(filepath.ToSlash(rel)), src}
		for _, cfg := range []string{"v2022", "keep-v2022", "0", "v2022-inline"} {
			fields = append(fields, []byte(cfg))
			fields = append(fields, digests(runMin(cfg, src))...)
		}
		w.rec(fields...)
	}
	w.close()

	// corpuswin: random windows of the Go module cache's JS corpus, mutated
	// 0-2 times (digests)
	roots := []string{
		filepath.Join(modCache(), "github.com/tdewolff/minify/v2@v2.23.8"),
		filepath.Join(modCache(), "github.com/evanw/esbuild@v0.25.6"),
		filepath.Join(modCache(), "golang.org/x/tools@v0.34.0"),
		repo,
	}
	paths := jsFiles(roots)
	w = newRecWriter(dir, "corpuswin")
	rnd = rand.New(rand.NewSource(seed + 3))
	for k := 0; k < 3000*scale; k++ {
		src, err := os.ReadFile(paths[rnd.Intn(len(paths))])
		if err != nil {
			panic(err)
		}
		if len(src) == 0 {
			continue
		}
		l := 16
		for l < 16384 && rnd.Intn(4) != 0 {
			l *= 2
		}
		l = 1 + rnd.Intn(l)
		i := rnd.Intn(len(src))
		j := min(len(src), i+l)
		win := mutateOps(rnd, append([]byte(nil), src[i:j]...), nonEmpty, rnd.Intn(3))
		cfg := "v2022"
		if rnd.Intn(5) == 0 {
			cfg = "v2022-inline"
		}
		w.rec(append([][]byte{[]byte("min"), []byte(cfg), win}, digests(runMin(cfg, win))...)...)
	}
	w.close()

	// redteam: a sample of the red-team generators (redteam.go; digests)
	genRedTeamFixture(dir, scale, seed+6)
}

func repoRoot() string {
	out, err := exec.Command("go", "list", "-m", "-f", "{{.Dir}}").Output()
	if err != nil {
		panic(err)
	}
	return strings.TrimSpace(string(out))
}

var skipDir = regexp.MustCompile(`(^|/)(\.git|\.claude|node_modules|target)$`)

// jsFiles returns the sorted .js/.mjs/.cjs files under the roots.
func jsFiles(roots []string) []string {
	var paths []string
	for _, root := range roots {
		err := filepath.Walk(root, func(p string, info os.FileInfo, err error) error {
			if err != nil {
				return err
			}
			if info.IsDir() && skipDir.MatchString(filepath.ToSlash(p)) {
				return filepath.SkipDir
			}
			switch filepath.Ext(p) {
			case ".js", ".mjs", ".cjs":
				if info.Mode().IsRegular() {
					paths = append(paths, p)
				}
			}
			return nil
		})
		if err != nil {
			panic(err)
		}
	}
	sort.Strings(paths)
	return paths
}

// corpusDigests writes OUT (TSV): root base name, relative path, input
// digest and size, then for every configuration the digests of the output,
// the error and the buffer-after fields.
func corpusDigests(out string, cfgs, roots []string) {
	f, err := os.Create(out)
	if err != nil {
		panic(err)
	}
	w := bufio.NewWriter(f)
	_, _ = fmt.Fprintf(w, "# generated by tools/go-oracle/tdewolff-minify-js corpus (%s); DO NOT EDIT\n", runtime.Version())
	_, _ = fmt.Fprintf(w, "# root\tpath\tinput\tsize\t%s\n", strings.Join(cfgs, "\t"))
	n := 0
	mc := modCache()
	for _, root := range roots {
		// roots are relative to GOMODCACHE, or "repo" for the neohugo module
		dir := filepath.Join(mc, root)
		if root == "repo" {
			dir = repoRoot()
		}
		for _, p := range jsFiles([]string{dir}) {
			src, err := os.ReadFile(p)
			if err != nil {
				panic(err)
			}
			rel, _ := filepath.Rel(dir, p)
			_, _ = fmt.Fprintf(w, "%s\t%s\t%s\t%d", root, filepath.ToSlash(rel), digest(src), len(src))
			for _, cfg := range cfgs {
				d := digests(runMin(cfg, src))
				_, _ = fmt.Fprintf(w, "\t%s,%s,%s", d[0], d[1], d[2])
			}
			_, _ = fmt.Fprintln(w)
			n++
		}
	}
	if err := w.Flush(); err != nil {
		panic(err)
	}
	if err := f.Close(); err != nil {
		panic(err)
	}
	fmt.Fprintf(os.Stderr, "corpus: %d files\n", n)
}

var vocab = []string{
	" ", "\n", ";", ",", "(", ")", "{", "}", "[", "]", "=", "==", "===", "!", "!=", "!==", "?", ":", "?.", "??",
	"=>", "...", ".", "+", "-", "*", "/", "%", "**", "++", "--", "<", ">", "<=", ">=", "&&", "||", "&", "|", "^", "~",
	"'", "\"", "`", "${", "\\", "/*", "*/", "//", "\\u0061", "\\x41", "\\n", "0", "1", ".5", "1e3", "0x1", "1n",
	"a", "b", "var ", "let ", "const ", "function ", "return ", "if(", "else ", "for(", "while(", "do ", "in ", "of ",
	"new ", "class ", "extends ", "typeof ", "void ", "delete ", "await ", "yield ", "async ", "this", "null", "true",
	"false", "undefined", "Infinity", "NaN", "isNaN(", "Number(", "Math.pow(", "Math.abs(", "Math.trunc(", "import ",
	"export ", "default ", "try{", "catch(e)", "finally", "throw ", "break ", "continue ", "switch(", "case ",
	"/re/g", "</script>", "<!--", "-->", "é", " ", "\x00",
}

func mutate(rnd *rand.Rand, lits [][]byte) []byte {
	src := append([]byte(nil), lits[rnd.Intn(len(lits))]...)
	return mutateOps(rnd, src, lits, 1+rnd.Intn(3))
}

func mutateOps(rnd *rand.Rand, src []byte, lits [][]byte, ops int) []byte {
	for k := 0; k < ops; k++ {
		switch rnd.Intn(6) {
		case 0, 1: // insert a vocabulary token
			i := rnd.Intn(len(src) + 1)
			v := vocab[rnd.Intn(len(vocab))]
			src = append(src[:i:i], append([]byte(v), src[i:]...)...)
		case 2: // delete a range
			if 0 < len(src) {
				i := rnd.Intn(len(src))
				j := i + 1 + rnd.Intn(min(8, len(src)-i))
				src = append(src[:i:i], src[j:]...)
			}
		case 3: // splice with another literal
			o := lits[rnd.Intn(len(lits))]
			i := rnd.Intn(len(src) + 1)
			j := rnd.Intn(len(o) + 1)
			src = append(src[:i:i], o[j:]...)
		case 4: // duplicate a range
			if 0 < len(src) {
				i := rnd.Intn(len(src))
				j := i + 1 + rnd.Intn(min(16, len(src)-i))
				src = append(src[:j:j], append(append([]byte(nil), src[i:j]...), src[j:]...)...)
			}
		case 5: // truncate
			if 0 < len(src) {
				src = src[:rnd.Intn(len(src))]
			}
		}
	}
	return src
}
