package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strconv"
)

// litValue evaluates a string/int/bool literal expression of a test table
// (string concatenation included). ok is false for anything else.
func litValue(e ast.Expr) (any, bool) {
	switch v := e.(type) {
	case *ast.BasicLit:
		switch v.Kind {
		case token.STRING:
			s, err := strconv.Unquote(v.Value)
			if err != nil {
				return nil, false
			}
			return s, true
		case token.INT:
			n, err := strconv.ParseInt(v.Value, 0, 64)
			if err != nil {
				return nil, false
			}
			return n, true
		}
	case *ast.Ident:
		switch v.Name {
		case "true":
			return true, true
		case "false":
			return false, true
		}
	case *ast.ParenExpr:
		return litValue(v.X)
	case *ast.BinaryExpr:
		if v.Op == token.ADD {
			a, ok1 := litValue(v.X)
			b, ok2 := litValue(v.Y)
			if sa, ok := a.(string); ok && ok1 && ok2 {
				if sb, ok := b.(string); ok {
					return sa + sb, true
				}
			}
		}
	}
	return nil, false
}

// tableRows returns the rows of the first `[]struct{...}{...}` table in the
// test function `name` of the given file of the minify/js package.
func tableRows(file, name string) [][]any {
	fn := filepath.Join(minifyJSDir(), file)
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, fn, nil, 0)
	if err != nil {
		panic(err)
	}
	var rows [][]any
	for _, decl := range f.Decls {
		fd, ok := decl.(*ast.FuncDecl)
		if !ok || fd.Name.Name != name {
			continue
		}
		found := false
		ast.Inspect(fd, func(n ast.Node) bool {
			if found {
				return false
			}
			cl, ok := n.(*ast.CompositeLit)
			if !ok {
				return true
			}
			at, ok := cl.Type.(*ast.ArrayType)
			if !ok {
				return true
			}
			if _, ok := at.Elt.(*ast.StructType); !ok {
				return true
			}
			found = true
			for _, el := range cl.Elts {
				row := el.(*ast.CompositeLit)
				var vals []any
				for _, fe := range row.Elts {
					v, ok := litValue(fe)
					if !ok {
						panic("non-literal field in " + name)
					}
					vals = append(vals, v)
				}
				rows = append(rows, vals)
			}
			return false
		})
		if !found {
			panic("no table in " + name)
		}
	}
	if rows == nil {
		panic("no rows for " + name)
	}
	return rows
}

// rustBytes renders s as a Rust byte string literal.
func rustBytes(s string) string {
	var b bytes.Buffer
	b.WriteString("b\"")
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case c == '"':
			b.WriteString("\\\"")
		case c == '\\':
			b.WriteString("\\\\")
		case c == '\n':
			b.WriteString("\\n")
		case c == '\r':
			b.WriteString("\\r")
		case c == '\t':
			b.WriteString("\\t")
		case 0x20 <= c && c < 0x7f:
			b.WriteByte(c)
		default:
			fmt.Fprintf(&b, "\\x%02x", c)
		}
	}
	b.WriteString("\"")
	return b.String()
}

// checkRow runs one upstream row through Go and panics when Go's output is
// not the upstream expectation (the fixtures assume the upstream tests pass
// with go1.27.1).
func checkRow(cfg, in, expected string) {
	out, err := minifyBuf(cfg, cp([]byte(in)))
	if err != nil || string(out) != expected {
		panic(fmt.Sprintf("upstream row fails in Go: cfg=%s in=%q out=%q err=%v want=%q", cfg, in, out, err, expected))
	}
}

// genTables writes the upstream js_test.go / util_test.go tables as Rust
// source (tests/upstream_tables/mod.rs, also included by the crate's unit tests).
func genTables(out string) {
	var b bytes.Buffer
	b.WriteString("// Generated by tools/go-oracle/tdewolff-minify-js tables from\n")
	b.WriteString("// github.com/tdewolff/minify/v2@v2.23.8/js/{js,util}_test.go; DO NOT EDIT.\n\n")

	pairs := func(constName, file, fn, cfg string) {
		rows := tableRows(file, fn)
		fmt.Fprintf(&b, "/// Go: %s:%s (%d rows).\n#[allow(dead_code)]\npub const %s: &[(&[u8], &[u8])] = &[\n", file, fn, len(rows), constName)
		for _, r := range rows {
			in, exp := r[0].(string), r[1].(string)
			if cfg != "" {
				checkRow(cfg, in, exp)
			}
			fmt.Fprintf(&b, "    (%s, %s),\n", rustBytes(in), rustBytes(exp))
		}
		b.WriteString("];\n\n")
	}
	pairs("TEST_JS", "js_test.go", "TestJS", "keep-alpha")
	pairs("TEST_JS_VAR_RENAMING", "js_test.go", "TestJSVarRenaming", "alpha")

	rows := tableRows("js_test.go", "TestJSVersion")
	fmt.Fprintf(&b, "/// Go: js_test.go:TestJSVersion (%d rows: version, js, before, after).\n#[allow(dead_code, clippy::type_complexity)]\npub const TEST_JS_VERSION: &[(i64, &[u8], &[u8], &[u8])] = &[\n", len(rows))
	for _, r := range rows {
		v := r[0].(int64)
		for _, version := range []int64{2022, 2020, 2019, 2018, 2014} {
			exp := r[3].(string)
			if version < v {
				exp = r[2].(string)
			}
			checkRow(fmt.Sprintf("keep-alpha-v%d", version), r[1].(string), exp)
		}
		fmt.Fprintf(&b, "    (%d, %s, %s, %s),\n", v, rustBytes(r[1].(string)), rustBytes(r[2].(string)), rustBytes(r[3].(string)))
	}
	b.WriteString("];\n\n")

	rows = tableRows("../html/html_test.go", "TestHTMLCSSJS")
	fmt.Fprintf(&b, "/// Go: html/html_test.go:TestHTMLCSSJS (%d rows).\n#[allow(dead_code)]\npub const TEST_HTML_CSS_JS: &[(&[u8], &[u8])] = &[\n", len(rows))
	for _, r := range rows {
		in, exp := r[0].(string), r[1].(string)
		if f := runHTML("upstream", []byte(in)); string(f[0]) != exp || f[1] != nil {
			panic(fmt.Sprintf("upstream TestHTMLCSSJS row fails in Go: %q -> %q %q", in, f[0], f[1]))
		}
		fmt.Fprintf(&b, "    (%s, %s),\n", rustBytes(in), rustBytes(exp))
	}
	b.WriteString("];\n\n")

	pairs("TEST_STRING", "util_test.go", "TestString", "")

	rows = tableRows("util_test.go", "TestHasSideEffects")
	fmt.Fprintf(&b, "/// Go: util_test.go:TestHasSideEffects (%d rows).\n#[allow(dead_code)]\npub const TEST_HAS_SIDE_EFFECTS: &[(&[u8], bool)] = &[\n", len(rows))
	for _, r := range rows {
		fmt.Fprintf(&b, "    (%s, %v),\n", rustBytes(r[0].(string)), r[1].(bool))
	}
	b.WriteString("];\n")

	if err := os.WriteFile(out, b.Bytes(), 0o644); err != nil {
		panic(err)
	}
	fmt.Fprintf(os.Stderr, "tables: %s\n", out)
}
