[package]
name = "neohugo-site"
description = "Capture and assembly into the Model"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true
autotests = false

[lib]
doctest = false

[[test]]
name = "it"
path = "tests/it/main.rs"

[lints]
workspace = true

[dependencies]
neohugo-workspace-hack.workspace = true
neohugo-base.workspace = true
neohugo-config.workspace = true
neohugo-page.workspace = true
neohugo-pageparser.workspace = true
neohugo-vfs.workspace = true
neohugo-locale.workspace = true
csv.workspace = true
roxmltree.workspace = true
jiff.workspace = true
rayon.workspace = true
thiserror.workspace = true

[dev-dependencies]
neohugo-testkit.workspace = true
serde_json.workspace = true
tempfile.workspace = true
