//! Differential fuzzing against stream digests recorded by the Go oracle
//! (`tools/go-oracle/tdewolff-parse fuzz OUTDIR N SEED EXHAUST MAXWIN ROOT...`).
//! Each `<group>.fz` file starts with `#kinds K1 K2 ...` and holds one
//! `hex(input)\tfnv64(K1 stream)\t...` record per input.
//!
//! A small set is checked in (tests/fixtures/fuzz). Large sets live outside
//! the repository and run with
//!
//!   TDEWOLFF_PARSE_FUZZ=<OUTDIR> cargo test --release --test fuzz -- --ignored
//!
//! Failing inputs are written to `<OUTDIR>/fail/<kind>-<n>.bin` (the checked-in
//! set writes them to the system temp dir); diff them with
//! `cargo run --example dump -- KIND FILE` against the oracle's `dump` mode.

mod common;
use common::*;

use std::path::{Path, PathBuf};

/// Checks every `.fz` file of `dir`; returns (inputs × kinds, failures).
fn run_dir(dir: &Path, fail_dir: &Path) -> (usize, usize) {
    let mut files: Vec<PathBuf> = std::fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("{}: {}", dir.display(), e))
        .map(|e| e.unwrap().path())
        .filter(|p| p.extension().is_some_and(|e| e == "fz"))
        .collect();
    files.sort();
    assert!(!files.is_empty(), "no .fz files in {}", dir.display());
    let (mut total, mut failed) = (0usize, 0usize);
    for f in &files {
        let text = std::fs::read_to_string(f).unwrap();
        let mut lines = text.lines();
        let header = lines.next().expect("header");
        let kinds: Vec<String> = header
            .strip_prefix("#kinds ")
            .expect("#kinds header")
            .split(' ')
            .map(|s| s.to_string())
            .collect();
        let lines: Vec<&str> = lines.collect();
        let nthreads = std::thread::available_parallelism()
            .map(|n| n.get())
            .unwrap_or(4);
        let chunk = lines.len().div_ceil(nthreads).max(1);
        // per kind: failing inputs
        let fails: Vec<Vec<Vec<u8>>> = std::thread::scope(|sc| {
            let hs: Vec<_> = lines
                .chunks(chunk)
                .map(|ls| {
                    let kinds = &kinds;
                    sc.spawn(move || {
                        let mut fails = vec![Vec::new(); kinds.len()];
                        for l in ls {
                            let mut fields = l.split('\t');
                            let input = unhex_opt(fields.next().unwrap()).unwrap_or_default();
                            for (k, kind) in kinds.iter().enumerate() {
                                let want = u64::from_str_radix(fields.next().unwrap(), 16).unwrap();
                                let got = std::panic::catch_unwind(|| {
                                    fnv64a(stream_for(kind, &input).as_bytes())
                                });
                                if got.ok() != Some(want) {
                                    fails[k].push(input.clone());
                                }
                            }
                        }
                        fails
                    })
                })
                .collect();
            let mut all = vec![Vec::new(); kinds.len()];
            for h in hs {
                for (k, f) in h.join().unwrap().into_iter().enumerate() {
                    all[k].extend(f);
                }
            }
            all
        });
        for (k, kind) in kinds.iter().enumerate() {
            let fl = &fails[k];
            if !fl.is_empty() {
                std::fs::create_dir_all(fail_dir).unwrap();
                let mut sorted = fl.clone();
                sorted.sort_by_key(|b| b.len());
                for (i, b) in sorted.iter().take(50).enumerate() {
                    std::fs::write(fail_dir.join(format!("{}-{}.bin", kind, i)), b).unwrap();
                }
                for b in sorted.iter().take(5) {
                    eprintln!("FAIL {}: {:?}", kind, String::from_utf8_lossy(b));
                }
            }
            eprintln!(
                "{}: {}/{} identical",
                kind,
                lines.len() - fl.len(),
                lines.len()
            );
            total += lines.len();
            failed += fl.len();
        }
    }
    (total, failed)
}

#[test]
fn fuzz_checked_in() {
    let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/fuzz");
    let fail_dir = std::env::temp_dir().join("tdewolff-parse-fuzz-fail");
    let (total, failed) = run_dir(&dir, &fail_dir);
    eprintln!("fuzz (checked in): {} streams, {} failed", total, failed);
    assert_eq!(failed, 0);
}

#[test]
#[ignore = "needs a fuzz set generated by the Go oracle; run with --ignored"]
fn fuzz_digests() {
    let dir = PathBuf::from(std::env::var("TDEWOLFF_PARSE_FUZZ").expect("set TDEWOLFF_PARSE_FUZZ"));
    let (total, failed) = run_dir(&dir, &dir.join("fail"));
    eprintln!("fuzz total: {} streams, {} failed", total, failed);
    assert_eq!(failed, 0);
}
