name: Build
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

env:
  GO111MODULE: "on"
  GOPROXY: "https://proxy.golang.org"
  HUGO_BUILD_TAGS: "extended"

jobs:
  build:
    name: Build (${{ matrix.os }}, Go ${{ matrix.go }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: [1.15.x]
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Setup Go environment
        shell: bash
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      - name: Go info
        run: go env
      - name: Install gofumpt and mage
        run: |
          go get mvdan.cc/gofumpt
          go get github.com/magefile/mage
      - uses: actions/cache@v2
        id: cache
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install Go module
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          go mod download
          go mod verify
      - name: Run mage tests
        run: |
          mage -v test
      - name: Run mage check
        run: |
          mage -v check
      - name: Run mage neohugo
        run: |
          mage -v neohugo
