// Command minify is the Go oracle for minifiers/{config,minifiers}.go in
// crates/nh-transform (Wave B task T07): DecodeConfig and the minifier client
// (which media types get which tdewolff minifier with which options, the
// publish-chain Transformer and Client.Minify).
//
//	NH_T07_ORACLE_ARCH=arm64 go run ./tools/go-oracle/nh-transform/minify [-out crates/nh-transform/tests/fixtures/minify]
//
// The oracle runs itself again with `go build -overlay` (osupport.MinifiersPatch
// lets minifiers.New take the minify section from minifiers.OracleConf). The
// CSS/SVG colour conversions are FMA-sensitive (crates/tdewolff-minify
// PORTING.md), so the fixtures are generated by the linux/arm64 build under
// qemu (NH_T07_ORACLE_ARCH=arm64), like the golden darwin/arm64 build.
//
// Records (minify.jsonl.gz):
//
//   - "decode": DecodeConfig of typed config maps (lower-case keys as the
//     config loader delivers them, camelCase keys, the decimal/precision and
//     keepConditionalComments renames, map[string]string and maps.Params
//     nesting, weak conversions, bad values) → the decoded MinifyConfig or the
//     error;
//   - "min": for each config (default, customised, disabled types) and each
//     queried media type × input: whether Client.Transformer is nil, the
//     transformer's output (the publish chain) and Client.Minify's output, or
//     their errors. Inputs are the docs site's CSS/JS/SVG/JSON assets and
//     hand-written snippets per media type.
package main

import (
	"bytes"
	"flag"
	"io"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/neohugo/neohugo/common/maps"
	"github.com/neohugo/neohugo/media"
	"github.com/neohugo/neohugo/minifiers"
	"github.com/neohugo/neohugo/output"
	"github.com/neohugo/neohugo/tools/go-oracle/nh-publisher/osupport"
	"github.com/neohugo/neohugo/transform"
)

var setConf func(minifiers.MinifyConfig)

const hookFile = `package main

import "github.com/neohugo/neohugo/minifiers"

func init() {
	setConf = func(c minifiers.MinifyConfig) { minifiers.OracleConf = c }
}
`

// enc encodes a Go config value with its type.
func enc(v any) any {
	switch x := v.(type) {
	case nil:
		return nil
	case string:
		return map[string]any{"s": x}
	case int:
		return map[string]any{"i": x}
	case float64:
		return map[string]any{"f": x}
	case bool:
		return map[string]any{"b": x}
	case []any:
		l := make([]any, len(x))
		for i, e := range x {
			l[i] = enc(e)
		}
		return map[string]any{"l": l}
	case maps.Params:
		m := map[string]any{}
		for k, e := range x {
			m[k] = enc(e)
		}
		return map[string]any{"p": m}
	case map[string]string:
		m := map[string]any{}
		for k, e := range x {
			m[k] = e
		}
		return map[string]any{"ms": m}
	case map[string]any:
		m := map[string]any{}
		for k, e := range x {
			m[k] = enc(e)
		}
		return map[string]any{"m": m}
	}
	log.Fatalf("enc: unsupported %T", v)
	return nil
}

// dumpConf is the decoded config with Go's field names.
func dumpConf(c minifiers.MinifyConfig) map[string]any {
	t := c.Tdewolff
	return map[string]any{
		"MinifyOutput": c.MinifyOutput, "DisableHTML": c.DisableHTML, "DisableCSS": c.DisableCSS, "DisableJS": c.DisableJS,
		"DisableJSON": c.DisableJSON, "DisableSVG": c.DisableSVG, "DisableXML": c.DisableXML,
		"HTML": map[string]any{
			"KeepComments": t.HTML.KeepComments, "KeepConditionalComments": t.HTML.KeepConditionalComments,
			"KeepSpecialComments": t.HTML.KeepSpecialComments, "KeepDefaultAttrVals": t.HTML.KeepDefaultAttrVals,
			"KeepDocumentTags": t.HTML.KeepDocumentTags, "KeepEndTags": t.HTML.KeepEndTags, "KeepQuotes": t.HTML.KeepQuotes,
			"KeepWhitespace": t.HTML.KeepWhitespace, "TemplateDelims": []string{t.HTML.TemplateDelims[0], t.HTML.TemplateDelims[1]},
		},
		"CSS":  map[string]any{"KeepCSS2": t.CSS.KeepCSS2, "Precision": t.CSS.Precision, "Inline": t.CSS.Inline},
		"JS":   map[string]any{"Precision": t.JS.Precision, "KeepVarNames": t.JS.KeepVarNames, "Version": t.JS.Version},
		"JSON": map[string]any{"Precision": t.JSON.Precision, "KeepNumbers": t.JSON.KeepNumbers},
		"SVG":  map[string]any{"KeepComments": t.SVG.KeepComments, "Precision": t.SVG.Precision, "Inline": t.SVG.Inline},
		"XML":  map[string]any{"KeepWhitespace": t.XML.KeepWhitespace},
	}
}

type m = map[string]any

var decodeCases = []any{
	nil,
	m{},
	m{"minifyoutput": true},
	m{"minifyOutput": "true"},
	m{"minifyoutput": 1, "disablehtml": "1", "disablecss": "false", "disablejs": 0, "disablejson": true, "disablesvg": "t", "disablexml": "F"},
	m{"tdewolff": m{"html": m{"keepwhitespace": true, "keepcomments": true, "keepquotes": true, "keependtags": false, "keepdefaultattrvals": false, "keepdocumenttags": false, "templatedelims": []any{"{{", "}}"}}}},
	m{"tdewolff": m{"html": m{"keepconditionalcomments": true}}},
	m{"tdewolff": m{"html": m{"keepconditionalcomments": false}}},
	m{"tdewolff": m{"html": m{"keepconditionalcomments": true, "keepspecialcomments": false}}},
	m{"tdewolff": m{"html": m{"keepConditionalComments": true}}},
	m{"tdewolff": m{"html": map[string]string{"keepconditionalcomments": "true"}}},
	m{"tdewolff": maps.Params{"html": maps.Params{"keepconditionalcomments": "yes"}}},
	m{"tdewolff": m{"css": m{"decimal": 3}, "svg": m{"decimal": "4"}}},
	m{"tdewolff": m{"css": m{"decimal": 3, "precision": 5}, "svg": m{"decimal": -1}}},
	m{"tdewolff": m{"css": m{"decimal": 0}, "svg": m{"decimal": 2.9}}},
	m{"tdewolff": m{"css": map[string]string{"decimal": "3"}, "svg": maps.Params{"decimal": 7}}},
	m{"tdewolff": map[string]string{"css": "x"}},
	m{"tdewolff": m{"css": m{"precision": 3, "keepcss2": false, "inline": true, "newprecision": 9}}},
	m{"tdewolff": m{"js": m{"precision": 2, "keepvarnames": true, "version": 2019, "usealphabetvarnames": true}}},
	m{"tdewolff": m{"json": m{"precision": 1, "keepnumbers": true}, "xml": m{"keepwhitespace": true}}},
	m{"tdewolff": m{"svg": m{"keepcomments": true, "precision": 5, "inline": true}}},
	m{"tdewolff": m{"CSS": m{"Precision": "7"}, "Html": m{"KeepWhitespace": "true"}}},
	m{"tdewolff": m{"css": m{"precision": "abc"}}},
	m{"tdewolff": m{"html": m{"templatedelims": "x"}}},
	m{"tdewolff": m{"html": m{"templatedelims": []any{"a", "b", "c"}}}},
	m{"tdewolff": m{"js": m{"version": 3.7}}},
	m{"tdewolff": "notamap"},
	m{"unknown": 1, "tdewolff": m{"unknown": m{"x": 1}}},
	maps.Params{"minifyoutput": true, "tdewolff": maps.Params{"css": maps.Params{"decimal": 2}}},
}

// customConf is the non-default minify config of the "custom" variant.
var customConf = m{
	"minifyoutput": true,
	"tdewolff": m{
		"html": m{"keepwhitespace": true, "keepcomments": true, "keepquotes": true, "keependtags": false, "keepdefaultattrvals": false, "keepdocumenttags": false, "keepconditionalcomments": true},
		"css":  m{"precision": 3, "keepcss2": false},
		"js":   m{"precision": 3, "keepvarnames": true, "version": 2015},
		"json": m{"precision": 2, "keepnumbers": false},
		"svg":  m{"precision": 3, "keepcomments": true},
		"xml":  m{"keepwhitespace": true},
	},
}

var snippets = map[string][]string{
	"css": {
		"a { color : #ff0000 ; margin: 0px 0px 0px 0px }", "b{color:rgb(10%, 20%, 30%);background:hsl(120, 50%, 25%)}",
		"c{width:calc( 100% - 3.14159265px );opacity:0.50000}", "@media (min-width:100px){d{x:1.234567e+3px}}",
		"e{background:url( 'data:image/svg+xml;utf8,<svg xmlns=\"http://www.w3.org/2000/svg\"><rect width=\"1.00000\" height=\"2\"/></svg>' )}",
		"f{color:hsla(210.5, 33.3%, 66.6%, 0.333)}", "/*! keep */ g{}", "h{font:12px/1.5 \"Helvetica Neue\",Arial}", "i{", "",
	},
	"js": {
		"var a = 1 + 2; function f ( x ) { return x * 1.50000 }", "const x = { 'a': 1, b: [1,2,3] }; let y = x?.a ?? 3;",
		"if (a) { b() } else { c() }", "/* comment */ let s = `t ${1+1}`;", "class A { #p = 1; m() { return this.#p } }",
		"let n = 123456789.123456789; let m = 0.0000001;", "syntax error (", "",
	},
	"json": {
		`{ "a" : 1.50000 , "b" : [ 1 , 2 , 3 ] , "c" : "x" }`, `[1e10, 0.1234567, -0.0, 123456789012]`, `{"s": "é\n"}`, `{bad`, "",
	},
	"svg": {
		`<svg xmlns="http://www.w3.org/2000/svg" width="100.000" height="50"><!-- c --><path d="M 10.123456 20.654321 L 30 40 Z" fill="#FF0000"/></svg>`,
		`<svg viewBox="0 0 10.5 10"><rect x="0" y="0" width="10" height="10" style="fill: rgb(255, 0, 0)"/><circle r="1.23456789"/></svg>`,
		`<?xml version="1.0"?><svg><g><text>  a  b  </text></g></svg>`, `<svg><defs><style>.a{fill:#000000}</style></defs></svg>`, "",
	},
	"xml": {
		`<?xml version="1.0" encoding="utf-8"?>  <rss version="2.0">  <channel> <title> T </title> <item><description>&lt;p&gt;x&lt;/p&gt;</description></item> </channel></rss>`,
		"<urlset>\n  <url>\n    <loc>https://example.org/</loc>\n  </url>\n</urlset>", `<a b = "c"  d='e'/>`, "<x><![CDATA[ <y> ]]></x>", "",
	},
	"html": {
		"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title> T </title>\n<style> a { color : red } </style>\n<script> var a = 1 + 2; </script>\n</head>\n<body class=\"a  b\">\n<!-- comment -->\n<!--[if IE]><p>ie</p><![endif]-->\n<p id=\"x\"  style=\"color: #ff0000\"> Hello   <b>world</b> </p>\n<a href=\"https://example.org/\" onclick=\"f( 1 )\">link</a>\n<input type=\"text\" value=\"\" disabled=\"disabled\">\n<svg width=\"10.000\"><rect width=\"1.50\"/></svg>\n</body>\n</html>\n",
		"<p>a<p>b<ul><li>c<li>d</ul>", "<div   class = 'q' data-x = \"1\" >  x  </div>", "<pre>  keep   </pre><textarea> t </textarea>",
		"<script type=\"application/ld+json\">{ \"a\" : 1.0 }</script>", "{{ .Title }} <p>{{ if . }}x{{ end }}</p>", "",
	},
}

func readAssets(root string) map[string][]string {
	out := map[string][]string{}
	add := func(kind, pattern string) {
		files, err := filepath.Glob(filepath.Join(root, pattern))
		if err != nil {
			log.Fatal(err)
		}
		sort.Strings(files)
		for _, fn := range files {
			b, err := os.ReadFile(fn)
			if err != nil {
				log.Fatal(err)
			}
			if len(b) > 64*1024 {
				continue
			}
			out[kind] = append(out[kind], string(b))
		}
	}
	add("css", "docs/assets/css/*.css")
	add("css", "docs/assets/css/components/*.css")
	add("js", "docs/assets/js/*.js")
	add("js", "docs/assets/js/*/*.js")
	add("json", "docs/assets/jsconfig.json")
	add("svg", "docs/assets/images/sponsors/*.svg")
	return out
}

// queried is the media types asked of the client per input kind (their
// Transformer and Minify), including types that only the regexps match and
// types without a minifier.
var queried = map[string][]string{
	"css":  {"text/css", "text/x-custom-css", "text/plain"},
	"js":   {"text/javascript", "application/javascript", "text/x-javascript", "application/ecmascript", "text/jscript"},
	"json": {"application/json", "application/ld+json", "application/manifest+json", "text/x-json", "text/json", "application/geo+json"},
	"svg":  {"image/svg+xml", "image/svg"},
	"xml":  {"application/xml", "application/rss+xml", "text/xml", "application/x-custom+xml", "application/atom+xml"},
	"html": {"text/html", "text/html; charset=utf-8", "text/x-custom-html", "application/xhtml+xml", "text/calendar"},
}

// extraTypes are added to media.DefaultTypes (suffixes decide the
// registration of the css/js/json/svg/xml/html minifiers).
var extraTypes = []struct {
	typ  string
	exts []string
}{
	{"text/x-custom-css", []string{"css"}},
	{"application/x-custom+xml", []string{"xml"}},
	{"text/x-custom-html", []string{"xhtml"}},
}

// fromTo is a transform.FromTo over two buffers (the chain's fromToBuffer).
type fromTo struct {
	from *bytes.Buffer
	to   *bytes.Buffer
}

func (ft fromTo) From() transform.BytesReader { return ft.from }
func (ft fromTo) To() io.Writer               { return ft.to }

func main() {
	root := flag.String("root", ".", "neohugo module root")
	out := flag.String("out", "crates/nh-transform/tests/fixtures/minify", "output directory")
	flag.Parse()

	if !osupport.IsChild() {
		patches := []osupport.Patch{osupport.MinifiersPatch}
		if err := osupport.RunOverlaid(*root, "./tools/go-oracle/nh-transform/minify", patches,
			"hook_overlay.go", hookFile, []string{"-root", *root, "-out", *out}); err != nil {
			log.Fatal(err)
		}
		return
	}
	if setConf == nil {
		log.Fatal("minify: hooks not installed (not run through the overlay)")
	}

	w, err := osupport.Create(filepath.Join(*out, "minify.jsonl.gz"))
	if err != nil {
		log.Fatal(err)
	}
	write := func(rec map[string]any) {
		if err := w.Write(rec); err != nil {
			log.Fatal(err)
		}
	}

	for _, c := range decodeCases {
		conf, err := minifiers.DecodeConfig(c)
		rec := map[string]any{"t": "decode", "in": enc(c)}
		if err != nil {
			rec["err"] = err.Error()
		} else {
			rec["conf"] = dumpConf(conf)
		}
		write(rec)
	}

	types := append(media.Types{}, media.DefaultTypes...)
	var extra []any
	for _, e := range extraTypes {
		t, err := media.FromStringAndExt(e.typ, e.exts...)
		if err != nil {
			log.Fatal(err)
		}
		types = append(types, t)
		extra = append(extra, map[string]any{"type": e.typ, "exts": e.exts})
	}
	formats := append(output.Formats{}, output.DefaultFormats...)
	customHTML, _ := types.GetByType("text/x-custom-html")
	formats = append(formats, output.Format{Name: "customhtml", MediaType: customHTML, IsHTML: true})

	variants := []struct {
		name string
		conf any
	}{
		{"default", m{"minifyoutput": true}},
		{"custom", customConf},
		{"disabled", m{"minifyoutput": true, "disablecss": true, "disablejs": true, "disablejson": true, "disablesvg": true, "disablexml": true, "disablehtml": true}},
		{"nooutput", nil},
	}

	inputs := readAssets(*root)
	for k, v := range snippets {
		inputs[k] = append(inputs[k], v...)
	}
	kinds := []string{"css", "js", "json", "svg", "xml", "html"}

	for _, v := range variants {
		conf, err := minifiers.DecodeConfig(v.conf)
		if err != nil {
			log.Fatal(err)
		}
		setConf(conf)
		client, err := minifiers.New(types, formats, nil)
		if err != nil {
			log.Fatal(err)
		}
		write(map[string]any{"t": "client", "variant": v.name, "conf": enc(v.conf), "extraTypes": extra, "minifyOutput": client.MinifyOutput})
		for _, kind := range kinds {
			for _, mt := range queried[kind] {
				for _, in := range inputs[kind] {
					rec := map[string]any{"t": "min", "variant": v.name, "mt": mt, "in": osupport.S(in)}
					tr := client.Transformer(media.Type{Type: mt})
					if tr == nil {
						rec["nil"] = true
					} else {
						var b bytes.Buffer
						var terr error
						// Called directly (Chain.Apply would wrap an error with a random
						// temp file name).
						pm := osupport.PanicString(func() { terr = tr(fromTo{from: bytes.NewBufferString(in), to: &b}) })
						switch {
						case pm != "":
							rec["trPanic"] = pm
						case terr != nil:
							rec["trErr"] = terr.Error()
						default:
							rec["tr"] = osupport.B(b.Bytes())
						}
					}
					var b bytes.Buffer
					var merr error
					pm := osupport.PanicString(func() { merr = client.Minify(media.Type{Type: mt}, &b, strings.NewReader(in)) })
					switch {
					case pm != "":
						rec["minPanic"] = pm
					case merr != nil:
						rec["minErr"] = merr.Error()
					default:
						rec["min"] = osupport.B(b.Bytes())
					}
					write(rec)
				}
			}
		}
	}

	if err := w.Close(); err != nil {
		log.Fatal(err)
	}
	log.Printf("minify: %d records (%s)", w.N(), osupport.Arch())
}
